variables:
  rh_20_release: '2.0.6'
  rh_21_release: '2.1.1'
  namespace: rh.

#Global before script, determine if this is a tag and handle rpm release field accordingly
before_script:
    - safe_version=$(echo ${short_version} | tr -d -)
    - safe_ref=$(echo ${CI_COMMIT_REF_NAME} | tr -d /| tr '[:upper:]' '[:lower:]')
    - if [ -z "$CI_COMMIT_TAG" ]; then
        redhawk_version=${latest_version}
        rpm_release="0.$CI_PIPELINE_ID.rh${safe_version}";
      else
        redhawk_version=${release_version}
        rpm_release="`rpm --query --queryformat "%{release}\n" --specfile ${namespace}$CI_PROJECT_NAME.spec | head -n 1 | awk -F"." "{print $1}"`.rh${safe_version}";
      fi
    - redhawk_repo=$yum_repo_url/redhawk-core-framework/$redhawk_version/$dist/$arch

.package: &package
  image: ${docker_registry}${docker_rpm_repository}docker:latest-rpm
  stage: build
  tags:
    - dind
  script:
    # Ensure newest version of FROM image
    - docker pull ${docker_registry}${rpmbuild_repository}rpmbuild:${dist}-${arch}-onbuild
    - printf "FROM ${docker_registry}${rpmbuild_repository}rpmbuild:$dist-$arch-onbuild" > Dockerfile
    - name=$(echo $CI_PROJECT_NAME| tr '[:upper:]' '[:lower:]')
    - docker build -t $name:$safe_ref-$dist-$arch-rh${safe_version} --build-arg "project=$CI_PROJECT_NAME"
                                               --build-arg "rpm_release=$rpm_release"
                                               --build-arg "spec_file=${namespace}$CI_PROJECT_NAME.spec"
                                               --build-arg "arch=$arch"
                                               --build-arg "other_repos=$redhawk_repo" .
    - id=$(docker create $name:$safe_ref-$dist-$arch-rh${safe_version})
    - docker cp $id:/root/rpmbuild/RPMS/ output/
    - docker rm -f $id || true
  artifacts:
    paths:
      - output/*/*.rpm
    expire_in: 2 days
  #Skip on tag of following format
  except:
    - /^(\d+\.)?(\d+)?(\.\d+)$/

package:el6:rh2.0:
  variables:
    latest_version: 2.0-nightly
    release_version: $rh_20_release
    short_version: '2.0'
    dist: el6
    arch: x86_64
  <<: *package

package:el6-i386:rh2.0:
  variables:
    latest_version: 2.0-nightly
    release_version: $rh_20_release
    short_version: '2.0'
    dist: el6
    arch: i686
  <<: *package

package:el7:rh2.0:
  variables:
    latest_version: 2.0-nightly
    release_version: $rh_20_release
    short_version: '2.0'
    dist: el7
    arch: x86_64
  <<: *package

package:el6:rh2.1:
  variables:
    latest_version: 2.1-nightly
    release_version: $rh_21_release
    short_version: '2.1'
    dist: el6
    arch: x86_64
  <<: *package

package:el6-i386:rh2.1:
  variables:
    latest_version: 2.1-nightly
    release_version: $rh_21_release
    short_version: '2.1'
    dist: el6
    arch: i686
  <<: *package

package:el7:rh2.1:
  variables:
    latest_version: 2.1-nightly
    release_version: $rh_21_release
    short_version: '2.1'
    dist: el7
    arch: x86_64
  <<: *package

deploy:
  image: centos:7
  stage: deploy
  dependencies: []
  before_script:
    - echo "Deploying to $jenkins_url/job/$CI_PROJECT_NAMESPACE/job/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
  script:
    - if [ -n "$jenkins_url" ]; then
        curl --insecure -X POST $jenkins_url/job/$CI_PROJECT_NAMESPACE/job/$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME/buildWithParameters?pipeline_id=$CI_PIPELINE_ID --user $jenkins_user:$jenkins_api_token;
      fi
  #Skip on tag of following format
  except:
    - /^(\d+\.)?(\d+)?(\.\d+)$/
