VRT: vrt::ReferencePointPacket Class Reference
vrt::ReferencePointPacket Class Reference
A.6. Reference Point Packet.
#include <ReferencePointPacket.h>
Public Member Functions
ReferencePointPacket (const vector< char > &bbuf, bool readOnly)
Creates a new instance accessing the given data buffer.
ReferencePointPacket (const BasicVRTPacket &p)
Creates a new instance from the given packet.
ReferencePointPacket ()
Creates a new instance ready for the fields to be set.
wstring getDescription () const
Get A free-form description of the reference point.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
string getName () const
Get A free-form name of the reference point.
virtual string getPacketValid (bool strict, int32_t length) const
Checks to see if the packet is valid.
int32_t getRefPointID () const
Get the reference point identifier.
void setDescription (string val)
Set A free-form description of the reference point.
void setDescription (wstring val)
Set A free-form description of the reference point.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setName (string val)
Set A free-form name of the reference point.
void setRefPointID (int32_t val)
Set the reference point identifier.
Static Public Attributes
static const string CLASS_ID
The class identifier in string form (FF-FF-FA:2011.0006).
static const int64_t CLASS_IDENTIFIER
The class identifier in numeric form (0xFFFFFA20110006).
static const int32_t PACKET_LENGTH
The packet length (-40) excluding the header and trailer (if applicable).
static const PacketType PACKET_TYPE
The packet type (PacketType_ExtContext).
Protected Member Functions
ReferencePointPacket (const BasicVRTPacket &p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength)
Internal constructor, for use by subclasses.
virtual void toStringStream (ostringstream &str) const
Writes the packet content to a string stream in a user-friendly format.
Detailed Description
A.6. Reference Point Packet.
The "reference point packet" provides a free-form description of a reference point. This class of packet plays a major role in large-scale, run-time-configurable, installations where the exact processing path is not pre-determined.
Constructor & Destructor Documentation
vrt::ReferencePointPacket::ReferencePointPacket ()
Creates a new instance ready for the fields to be set.
The stream ID and timecode values will be initialized to 0.
vrt::ReferencePointPacket::ReferencePointPacket (const BasicVRTPacket & p)
Creates a new instance from the given packet.
Parameters:
p The packet.
Exceptions:
VRTException If the packet given does not match this type.
vrt::ReferencePointPacket::ReferencePointPacket (const BasicVRTPacket & p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength) [protected]
Internal constructor, for use by subclasses.
Parameters:
p The packet (already initialized).
type The expected packet type.
classID The expected classID.
minPayloadLength The minimum payload length.
maxPayloadLength The maximum payload length (<0 if not pre-defined).
Exceptions:
IllegalArgumentException If packet type or classID of the packet are invalid, or if the payload length is invalid.
vrt::ReferencePointPacket::ReferencePointPacket (const vector< char > & bbuf, bool readOnly)
Creates a new instance accessing the given data buffer.
Parameters:
bbuf The data buffer to use.
readOnly Should users of this instance be able to modify the underlying data buffer?
Member Function Documentation
wstring vrt::ReferencePointPacket::getDescription () const [inline]
Get A free-form description of the reference point.
Size: variable
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::getPayloadLength(), and vrt::BasicVRTPacket::unpackPayloadUTF8().
virtual Value* vrt::ReferencePointPacket::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::BasicVRTPacket.
virtual int32_t vrt::ReferencePointPacket::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::BasicVRTPacket.
virtual string vrt::ReferencePointPacket::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::BasicVRTPacket.
virtual ValueType vrt::ReferencePointPacket::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::BasicVRTPacket.
string vrt::ReferencePointPacket::getName () const [inline]
Get A free-form name of the reference point.
Size: 32
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadAscii().
virtual string vrt::ReferencePointPacket::getPacketValid (bool strict, int32_t length) const [virtual]
Checks to see if the packet is valid.
This is identical to isPacketValid(int32_t) except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No packet failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a packet.
length Verifies that the length of the packet matches this value.
Returns:
Empty string ("") if it is valid, a description of the error otherwise.
Reimplemented from vrt::BasicVRTPacket.
int32_t vrt::ReferencePointPacket::getRefPointID () const [inline]
Get the reference point identifier.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadInt().
void vrt::ReferencePointPacket::setDescription (string val) [inline]
Set A free-form description of the reference point.
Size: variable
Parameters:
val The new value to write to the packet.
References vrt::VRTMath::lengthUTF8(), vrt::BasicVRTPacket::MAX_PAYLOAD_LENGTH, vrt::BasicVRTPacket::packPayloadUTF8(), and vrt::BasicVRTPacket::setPayloadLength().
void vrt::ReferencePointPacket::setDescription (wstring val) [inline]
Set A free-form description of the reference point.
Size: variable
Parameters:
val The new value to write to the packet.
References vrt::VRTMath::lengthUTF8(), vrt::BasicVRTPacket::MAX_PAYLOAD_LENGTH, vrt::BasicVRTPacket::packPayloadUTF8(), and vrt::BasicVRTPacket::setPayloadLength().
virtual void vrt::ReferencePointPacket::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::BasicVRTPacket.
void vrt::ReferencePointPacket::setName (string val) [inline]
Set A free-form name of the reference point.
Size: 32
Parameters:
val The new value to write to the packet. Any non-ASCII characters in the string (numeric value >0x7F) or ASCII control characters (numeric value <0x20, 0x7F) will be replaced with '?'. If the string is longer than the size allotted, it will be truncated without warning.
References vrt::BasicVRTPacket::packPayloadAscii().
void vrt::ReferencePointPacket::setRefPointID (int32_t val) [inline]
Set the reference point identifier.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadInt().
virtual void vrt::ReferencePointPacket::toStringStream (ostringstream & str) const [protected, virtual]
Writes the packet content to a string stream in a user-friendly format.
Parameters:
str The string stream to write to.
Reimplemented from vrt::BasicVRTPacket.
Member Data Documentation
const string vrt::ReferencePointPacket::CLASS_ID [static]
The class identifier in string form (FF-FF-FA:2011.0006).
const int64_t vrt::ReferencePointPacket::CLASS_IDENTIFIER [static]
The class identifier in numeric form (0xFFFFFA20110006).
const int32_t vrt::ReferencePointPacket::PACKET_LENGTH [static]
The packet length (-40) excluding the header and trailer (if applicable).
A value of -40 indicates that the length is variable with a minimum length of 40 octets.
const PacketType vrt::ReferencePointPacket::PACKET_TYPE [static]
The packet type (PacketType_ExtContext).
The documentation for this class was generated from the following file:
cpp_src/vrt/libm/ReferencePointPacket.h