VRT: vrt::GeoSentences Class Reference
vrt::GeoSentences Class Reference
Represents GPS "sentences" describing a GPS geolocation fix.
#include <IndicatorFields.h>
Public Member Functions
GeoSentences (const GeoSentences &r)
Basic copy constructor.
GeoSentences ()
Creates a new instance.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
string getSentences () const
Gets the GPS "sentences".
TimeStamp getTimeStamp () const
Gets the time stamp for the geolocation fix.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setSentences (string s)
Sets the GPS "sentences".
virtual string toString () const
Gets a basic description of the object, useful for debugging.
virtual void writeBytes (const void *buffer)
Writes bytes to this record from the specified buffer.
Detailed Description
Represents GPS "sentences" describing a GPS geolocation fix.
Users are strongly encouraged to consider using the binary form when specifying a GPS geolocation fix (see Geolocation). There is no intention of adding any significant capabilities to this class.
See also:
Geolocation
Constructor & Destructor Documentation
vrt::GeoSentences::GeoSentences ()
Creates a new instance.
vrt::GeoSentences::GeoSentences (const GeoSentences & r)
Basic copy constructor.
Member Function Documentation
virtual Value* vrt::GeoSentences::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::AbstractGeolocation.
virtual int32_t vrt::GeoSentences::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::AbstractGeolocation.
virtual string vrt::GeoSentences::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::AbstractGeolocation.
virtual ValueType vrt::GeoSentences::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::AbstractGeolocation.
string vrt::GeoSentences::getSentences () const [inline]
Gets the GPS "sentences".
Returns:
The GPS "sentences".
References vrt::Record::getByteLength(), and vrt::Record::unpackAscii().
TimeStamp vrt::GeoSentences::getTimeStamp () const [inline]
Gets the time stamp for the geolocation fix.
Returns:
Since no standard time stamp exists for the sentences, this always returns a null value.
Reimplemented from vrt::AbstractGeolocation.
virtual void vrt::GeoSentences::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::AbstractGeolocation.
void vrt::GeoSentences::setSentences (string s) [inline]
Sets the GPS "sentences".
Parameters:
s The GPS "sentences" (should be ASCII).
References vrt::Record::packAscii(), vrt::Record::packInt(), and vrt::Record::setByteLength().
virtual string vrt::GeoSentences::toString () const [virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::AbstractGeolocation.
virtual void vrt::GeoSentences::writeBytes (const void * buffer) [inline, virtual]
Writes bytes to this record from the specified buffer.
Parameters:
buffer The buffer to read from.
Reimplemented from vrt::Record.
References vrt::Record::setByteLength(), and vrt::Record::unpackInt().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/IndicatorFields.h