VRT: vrt::BasicVRLFrame Class Reference
vrt::BasicVRLFrame Class Reference
Defines a VITA 49.1 VRL frame type.
#include <BasicVRLFrame.h>
Public Member Functions
BasicVRLFrame (const void *ptr, size_t size, bool readOnly=false)
Creates a new instance.
BasicVRLFrame (const vector< char > &buf, size_t size, bool readOnly=false)
Creates a new instance.
BasicVRLFrame (vector< char > *buf, bool readOnly=false)
Creates a new instance.
BasicVRLFrame (const vector< char > &buf, bool readOnly=false)
Creates a new instance.
BasicVRLFrame (const BasicVRLFrame &f)
Basic copy constructor for the class.
BasicVRLFrame (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
BasicVRLFrame ()
Creates a new instance with no packets in the frame.
~BasicVRLFrame ()
Basic destructor for the class.
BasicVRLFrame copy () const
Creates a copy of this frame that is independent of the original.
virtual bool equals (const VRTObject &o) const
Checks for equality with an unknown object.
bool equals (const BasicVRLFrame &o) const
Checks for equality with an unknown object.
int32_t getFrameCount () const
Gets the value of the 12-bit frame counter.
int32_t getFrameLength () const
Gets the total length of the frame in octets including the header and trailer.
void * getFramePointer ()
Gets a pointer to the frame's buffer.
string getFrameValid (bool strict, int32_t length) const
Checks to see if the frame is valid.
string getFrameValid (bool strict) const
Checks to see if the frame is valid.
int32_t getPacketCount () const
Gets the number of packets contained in this frame.
vector< BasicVRTPacket * > getVRTPackets () const
Gets all of the VRT packets contained in the VRL frame.
vector< void * > getVRTPacketsRW ()
Internal Use Only: Gets pointers to the start of all of the VRT packets contained in the VRL frame.
int32_t hashCode () const
Computes the hash code for a VRL frame.
bool isCRCValid () const
Checks to see if the CRC for the frame is valid.
bool isFrameValid (int32_t length) const
Checks to see if the frame is valid.
bool isFrameValid () const
Checks to see if the frame is valid.
void setFrameCount (int32_t count)
Optional functionality: Sets the value of the 12-bit frame counter.
void setFrameLength (int32_t length)
Optional functionality: Sets the total length of the frame in octets including the header and trailer.
int32_t setVRTPackets (int32_t maxFrameLength, const vector< BasicVRTPacket * > &packets)
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
int32_t setVRTPackets (int32_t maxFrameLength, const vector< BasicVRTPacket > &packets)
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
void setVRTPackets (const vector< BasicVRTPacket * > &packets)
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
void setVRTPackets (const vector< BasicVRTPacket > &packets)
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
int32_t setVRTPackets (int32_t maxFrameLength, const BasicVRTPacket *packet)
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
int32_t setVRTPackets (int32_t maxFrameLength, const BasicVRTPacket &packet)
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
void setVRTPackets (const BasicVRTPacket *packet)
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
void setVRTPackets (const BasicVRTPacket &packet)
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
void swap (vector< char > *buffer)
Internal Use Only: Does a buffer swap.
virtual string toString () const
Gets a free-form description of the frame.
void updateCRC ()
This will compute the CRC value for the frame and set it in the CRC field.
Static Public Member Functions
static int32_t getFrameLength (const void *ptr, int32_t off)
Internal Use Only: Get VRL frame length using a buffer input.
static int32_t getFrameLength (const vector< char > &buf, int32_t off)
Internal Use Only: Get VRL frame length using a buffer input.
static vector< vector< char > * > * getVRTPackets (const vector< char > &buffer, int32_t len)
Internal Use Only: Gets all of the VRT packets contained in the VRL frame.
static bool isVRL (const void *ptr, int32_t off)
Internal Use Only: Does the given buffer contain a VRL frame?
static bool isVRL (const vector< char > &buf, int32_t off)
Internal Use Only: Does the given buffer contain a VRL frame?
Public Attributes
vector< char > bbuf
Static Public Attributes
static const int32_t HEADER_LENGTH = 8
The length of the header in octets.
static const int32_t MAX_FRAME_LENGTH = 0x000FFFFF*4
The maximum length of the frame in octets (header + payload + trailer).
static const int32_t MAX_PAYLOAD_LENGTH = MAX_FRAME_LENGTH - HEADER_LENGTH - TRAILER_LENGTH
The maximum length of the payload in octets.
static const int32_t MIN_FRAME_LENGTH = HEADER_LENGTH + TRAILER_LENGTH
The minimum length of the frame in octets (header + no payload + trailer).
static const int32_t NO_CRC = 0x56454E44
This is the special code that can be used in place of the CRC32 in cases where a CRC is not considered unnecessary, and not included.
static const int8_t NO_CRC_0 = 0x56
This is the 1st transmitted int8_t of the 32-bit NO_CRC code.
static const int8_t NO_CRC_1 = 0x45
This is the 2nd transmitted int8_t of the 32-bit NO_CRC code.
static const int8_t NO_CRC_2 = 0x4E
This is the 3rd transmitted int8_t of the 32-bit NO_CRC code.
static const int8_t NO_CRC_3 = 0x44
This is the 4th transmitted int8_t of the 32-bit NO_CRC code.
static const int32_t TRAILER_LENGTH = 4
The length of the trailer in octets.
static const int32_t VRL_FAW = 0x56524C50
This is the 32-bit FWA (frame alignment word) marking the start of the frame.
static const int8_t VRL_FAW_0 = 0x56
This is the 1st transmitted int8_t of the 32-bit FWA (VRL_FAW).
static const int8_t VRL_FAW_1 = 0x52
This is the 2nd transmitted int8_t of the 32-bit FWA (VRL_FAW).
static const int8_t VRL_FAW_2 = 0x4C
This is the 3rd transmitted int8_t of the 32-bit FWA (VRL_FAW).
static const int8_t VRL_FAW_3 = 0x50
This is the 4th transmitted int8_t of the 32-bit FWA (VRL_FAW).
Detailed Description
Defines a VITA 49.1 VRL frame type.
Note that the numeric representation (byte order) used by all VRL frames is BIG_ENDIAN.
Constructor & Destructor Documentation
vrt::BasicVRLFrame::~BasicVRLFrame ()
Basic destructor for the class.
vrt::BasicVRLFrame::BasicVRLFrame ()
Creates a new instance with no packets in the frame.
vrt::BasicVRLFrame::BasicVRLFrame (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
Initially this will have no packets in the frame, but will have the underlying buffers pre-allocated as required.
Parameters:
bufsize The anticipated buffer size.
vrt::BasicVRLFrame::BasicVRLFrame (const BasicVRLFrame & f)
Basic copy constructor for the class.
Parameters:
f The frame to copy
vrt::BasicVRLFrame::BasicVRLFrame (const vector< char > & buf, bool readOnly = false)
Creates a new instance.
Parameters:
buf The data to initialize the frame with.
readOnly Should the frame be treated as read-only?
vrt::BasicVRLFrame::BasicVRLFrame (vector< char > * buf, bool readOnly = false)
Creates a new instance.
Parameters:
buf The data to initialize the frame with.
readOnly Should the frame be treated as read-only?
vrt::BasicVRLFrame::BasicVRLFrame (const vector< char > & buf, size_t size, bool readOnly = false)
Creates a new instance.
Parameters:
buf The data to initialize the frame with.
size The size of buffer to read in.
readOnly Should the frame be treated as read-only?
vrt::BasicVRLFrame::BasicVRLFrame (const void * ptr, size_t size, bool readOnly = false)
Creates a new instance.
Parameters:
ptr The pointer to the data to initialize the frame with.
size The size of buffer to read in.
readOnly Should the frame be treated as read-only?
Member Function Documentation
BasicVRLFrame vrt::BasicVRLFrame::copy () const
Creates a copy of this frame that is independent of the original.
The copy will not be read only and will not be "direct" (i.e. will not share data with the original). This method's behavior is undefined if the frame is invalid and may throw an exception in that event.
Returns:
A copy of this frame.
virtual bool vrt::BasicVRLFrame::equals (const VRTObject & o) const [virtual]
Checks for equality with an unknown object.
Two VRL frames are considered equal if the content of the frames is bit-for-bit identical. The actual implementation classes are not considered relevant for checking equality.
Parameters:
o The unknown object (can be null).
Returns:
true if they are identical, false otherwise. (This will always returns false if the object is null.)
bool vrt::BasicVRLFrame::equals (const BasicVRLFrame & o) const [virtual]
Checks for equality with an unknown object.
Two VRL frames are considered equal if the content of the frames is bit-for-bit identical. The actual implementation classes are not considered relevant for checking equality.
Parameters:
o The unknown object (can be null).
Returns:
true if they are identical, false otherwise. (This will always returns false if the object is null.)
Reimplemented from vrt::VRTObject.
int32_t vrt::BasicVRLFrame::getFrameCount () const
Gets the value of the 12-bit frame counter.
Returns:
The value of the frame counter.
static int32_t vrt::BasicVRLFrame::getFrameLength (const void * ptr, int32_t off) [inline, static]
Internal Use Only: Get VRL frame length using a buffer input.
References vrt::VRTMath::unpackInt().
static int32_t vrt::BasicVRLFrame::getFrameLength (const vector< char > & buf, int32_t off) [inline, static]
Internal Use Only: Get VRL frame length using a buffer input.
References getFrameLength().
int32_t vrt::BasicVRLFrame::getFrameLength () const [inline]
Gets the total length of the frame in octets including the header and trailer.
Returns:
The total length of the frame in octets.
Referenced by getFrameLength().
void* vrt::BasicVRLFrame::getFramePointer ()
Gets a pointer to the frame's buffer.
string vrt::BasicVRLFrame::getFrameValid (bool strict, int32_t length) const
Checks to see if the frame is valid.
This is identical to isFrameValid(..) except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No frame failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a frame.
length Verifies that the length of the frame matches this value.
Returns:
Empty string if it is valid, a description of the error otherwise.
string vrt::BasicVRLFrame::getFrameValid (bool strict) const [inline]
Checks to see if the frame is valid.
This is identical to isFrameValid() except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No frame failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a frame.
Returns:
Empty string if it is valid, a description of the error otherwise.
Referenced by isFrameValid().
int32_t vrt::BasicVRLFrame::getPacketCount () const
Gets the number of packets contained in this frame.
This will be equal to getVRTPackets().size() though will typically be implemented in a more efficient manner.
vector<BasicVRTPacket*> vrt::BasicVRLFrame::getVRTPackets () const
Gets all of the VRT packets contained in the VRL frame.
Returns:
The packets.
static vector<vector<char>*>* vrt::BasicVRLFrame::getVRTPackets (const vector< char > & buffer, int32_t len) [static]
Internal Use Only: Gets all of the VRT packets contained in the VRL frame.
Parameters:
buffer The frame buffer.
len The number of valid octets in the buffer.
Returns:
The packets (which will be writable copies of what is in the frame) or NULL on error.
vector<void*> vrt::BasicVRLFrame::getVRTPacketsRW ()
Internal Use Only: Gets pointers to the start of all of the VRT packets contained in the VRL frame.
Returns:
The pointers.
int32_t vrt::BasicVRLFrame::hashCode () const
Computes the hash code for a VRL frame.
For performance reasons, the hash code is based on up to 32 octets at the start of the frame.
Returns:
The hash code for the object.
bool vrt::BasicVRLFrame::isCRCValid () const
Checks to see if the CRC for the frame is valid.
This will always return true when the CRC is set to the special NO_CRC value.
Returns:
true if it is valid, false otherwise.
bool vrt::BasicVRLFrame::isFrameValid (int32_t length) const [inline]
Checks to see if the frame is valid.
This method adds an extra length check onto the basic checks performed by isFrameValid(). The most common use for this method is to verify that a frame read from a socket matches the length expected.
Parameters:
length Verifies that the length of the frame matches this value.
Returns:
true if it is valid, false otherwise.
References getFrameValid().
bool vrt::BasicVRLFrame::isFrameValid () const [inline]
Checks to see if the frame is valid.
This checks the overall structure of the frame and verifies the CRC (if specified). It also checks to see that the length of the frame as reported in the frame header is equal to the length of the header and trailer plus the length of each packet in the trailer. For the purposes of the packet length check, only the length of a packet is considered, no consideration is made to the validity of the packet.
Returns:
true if it is valid, false otherwise.
References getFrameValid().
static bool vrt::BasicVRLFrame::isVRL (const void * ptr, int32_t off) [inline, static]
Internal Use Only: Does the given buffer contain a VRL frame?
Parameters:
ptr The buffer to check. Note that the buffer can not be null and must have at least 4 octets following the offset given.
off The offset into the buffer.
Returns:
true if it is a VRL frame, false otherwise.
References VRL_FAW_0, VRL_FAW_1, VRL_FAW_2, and VRL_FAW_3.
static bool vrt::BasicVRLFrame::isVRL (const vector< char > & buf, int32_t off) [inline, static]
Internal Use Only: Does the given buffer contain a VRL frame?
Parameters:
buf The buffer to check. Note that the buffer can not be null and must have at least 4 octets following the offset given.
off The offset into the buffer.
Returns:
true if it is a VRL frame, false otherwise.
void vrt::BasicVRLFrame::setFrameCount (int32_t count)
Optional functionality: Sets the value of the 12-bit frame counter.
Parameters:
count The frame count.
Exceptions:
VRTException If this method is not supported, if the count is less than 0 or greater than 0x00000FFF.
void vrt::BasicVRLFrame::setFrameLength (int32_t length)
Optional functionality: Sets the total length of the frame in octets including the header and trailer.
In general the frame length should not be set directly; rather the setting of the packets in the frame should be used as the mechanism for setting the frame length.
Parameters:
length The total length of the frame in octets.
Exceptions:
VRTException If this method is not supported, if the length is less than 24 octets (the minimum length for a VRL frame) and/or not a multiple of 4-octets.
int32_t vrt::BasicVRLFrame::setVRTPackets (int32_t maxFrameLength, const vector< BasicVRTPacket * > & packets) [inline]
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
Of the packets given, this method will try to put as many as possible into the frame that will fit given the specified maximum frame length. If fewer fit, it will put fewer in.
Parameters:
maxFrameLength The maximum frame length in octets (inclusive of header and trailer).
packets The packets.
Returns:
The number of packets inserted into the frame (could be 0).
Exceptions:
VRTException If this method is not supported or if maxFrameLength is invalid or if any of the packets are invalid.
References MAX_FRAME_LENGTH, MIN_FRAME_LENGTH, and setVRTPackets().
int32_t vrt::BasicVRLFrame::setVRTPackets (int32_t maxFrameLength, const vector< BasicVRTPacket > & packets) [inline]
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
Of the packets given, this method will try to put as many as possible into the frame that will fit given the specified maximum frame length. If fewer fit, it will put fewer in.
Parameters:
maxFrameLength The maximum frame length in octets (inclusive of header and trailer).
packets The packets.
Returns:
The number of packets inserted into the frame (could be 0).
Exceptions:
VRTException If this method is not supported or if maxFrameLength is invalid or if any of the packets are invalid.
References MAX_FRAME_LENGTH, MIN_FRAME_LENGTH, and setVRTPackets().
void vrt::BasicVRLFrame::setVRTPackets (const vector< BasicVRTPacket * > & packets) [inline]
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
Strictly based on the maximum size of a VRT packet and the maximum size of a VRL frame, a minimum of 15 packets can be included. In normal use, only one or two tend to be included at a time.
Parameters:
packets The packets.
Exceptions:
VRTException If this method is not supported or if the total length of all packets exceeds the maximum that can be included in a single frame or if any of the packets are invalid.
References MAX_FRAME_LENGTH, and setVRTPackets().
void vrt::BasicVRLFrame::setVRTPackets (const vector< BasicVRTPacket > & packets) [inline]
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
Strictly based on the maximum size of a VRT packet and the maximum size of a VRL frame, a minimum of 15 packets can be included. In normal use, only one or two tend to be included at a time.
Parameters:
packets The packets.
Exceptions:
VRTException If this method is not supported or if the total length of all packets exceeds the maximum that can be included in a single frame or if any of the packets are invalid.
References MAX_FRAME_LENGTH, and setVRTPackets().
int32_t vrt::BasicVRLFrame::setVRTPackets (int32_t maxFrameLength, const BasicVRTPacket * packet) [inline]
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
Of the packets given, this method will try to put as many as possible into the frame that will fit given the specified maximum frame length. If fewer fit, it will put fewer in.
Parameters:
maxFrameLength The maximum frame length in octets (inclusive of header and trailer).
packet The packet.
Returns:
The number of packets inserted into the frame (could be 0).
Exceptions:
VRTException If this method is not supported or if maxFrameLength is invalid or if any of the packets are invalid.
References MAX_FRAME_LENGTH, MIN_FRAME_LENGTH, and setVRTPackets().
int32_t vrt::BasicVRLFrame::setVRTPackets (int32_t maxFrameLength, const BasicVRTPacket & packet) [inline]
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
Of the packets given, this method will try to put as many as possible into the frame that will fit given the specified maximum frame length. If fewer fit, it will put fewer in.
Parameters:
maxFrameLength The maximum frame length in octets (inclusive of header and trailer).
packet The packet.
Returns:
The number of packets inserted into the frame (could be 0).
Exceptions:
VRTException If this method is not supported or if maxFrameLength is invalid or if any of the packets are invalid.
References MAX_FRAME_LENGTH, MIN_FRAME_LENGTH, and setVRTPackets().
void vrt::BasicVRLFrame::setVRTPackets (const BasicVRTPacket * packet) [inline]
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
Strictly based on the maximum size of a VRT packet and the maximum size of a VRL frame, a minimum of 15 packets can be included. In normal use, only one or two tend to be included at a time.
Parameters:
packet The packet.
Exceptions:
VRTException If this method is not supported or if the total length of all packets exceeds the maximum that can be included in a single frame or if any of the packets are invalid.
References MAX_FRAME_LENGTH, and setVRTPackets().
void vrt::BasicVRLFrame::setVRTPackets (const BasicVRTPacket & packet) [inline]
Optional functionality: Sets all of the VRT packets contained in the VRL frame.
Strictly based on the maximum size of a VRT packet and the maximum size of a VRL frame, a minimum of 15 packets can be included. In normal use, only one or two tend to be included at a time.
Parameters:
packet The packet.
Exceptions:
VRTException If this method is not supported or if the total length of all packets exceeds the maximum that can be included in a single frame or if any of the packets are invalid.
References MAX_FRAME_LENGTH.
Referenced by setVRTPackets().
void vrt::BasicVRLFrame::swap (vector< char > * buffer) [inline]
Internal Use Only: Does a buffer swap.
virtual string vrt::BasicVRLFrame::toString () const [virtual]
Gets a free-form description of the frame.
Note that the content and structure of this string is implementation dependant and may change at any time.
Returns:
A free-form string describing the frame.
Reimplemented from vrt::VRTObject.
void vrt::BasicVRLFrame::updateCRC ()
This will compute the CRC value for the frame and set it in the CRC field.
All successful calls to one of the set methods on this packet will result in the CRC field being set, but that usually means that the CRC was merely set to the special NO_CRC value. This method must be called on the packet immediately before transmission (i.e. after the frame counter and frame length have been updated) if CRC protection is desired.
Most transmission options (UDP, UDP Multicast, TCP, etc.) provide their own CRC protection, which renders the CRC field in the VRL frame redundant and just wastes extra computational time on both the sender and receiver. As such, this method should only be called when absolutely necessary and such a call should usually be the responsibility of the frame sending routines.
Member Data Documentation
const int32_t vrt::BasicVRLFrame::HEADER_LENGTH = 8 [static]
The length of the header in octets.
    MAX_HEADER_LENGTH = 8
const int32_t vrt::BasicVRLFrame::MAX_FRAME_LENGTH = 0x000FFFFF*4 [static]
The maximum length of the frame in octets (header + payload + trailer).
Note that this is the absolute limit imposed by the VRL specification. The underlying transport protocols used (e.g. IP, UDP, TCP, etc.) may have limits lower than this.
    MAX_FRAME_LENGTH = 0x000FFFFF*4
See also:
getFrameLength()
Referenced by setVRTPackets().
const int32_t vrt::BasicVRLFrame::MAX_PAYLOAD_LENGTH = MAX_FRAME_LENGTH - HEADER_LENGTH - TRAILER_LENGTH [static]
The maximum length of the payload in octets.
Note that this is the absolute limit imposed by the VRL specification. The underlying transport protocols used (e.g. IP, UDP, TCP, etc.) may have limits lower than this.
    MAX_PAYLOAD_LENGTH = MAX_FRAME_LENGTH - MAX_HEADER_LENGTH - MAX_TRAILER_LENGTH
const int32_t vrt::BasicVRLFrame::MIN_FRAME_LENGTH = HEADER_LENGTH + TRAILER_LENGTH [static]
The minimum length of the frame in octets (header + no payload + trailer).
Note that this is the absolute limit imposed by the VRL specification and results in a near-useless frame with no payload packets.
    MIN_FRAME_LENGTH = HEADER_LENGTH + TRAILER_LENGTH
See also:
getFrameLength()
Referenced by setVRTPackets().
const int32_t vrt::BasicVRLFrame::NO_CRC = 0x56454E44 [static]
This is the special code that can be used in place of the CRC32 in cases where a CRC is not considered unnecessary, and not included.
    NO_CRC = 0x56454E44 = { 'V', 'E', 'N', 'D' }
Referenced by vrt::AbstractVRAFile::isCRCValid().
const int8_t vrt::BasicVRLFrame::NO_CRC_0 = 0x56 [static]
This is the 1st transmitted int8_t of the 32-bit NO_CRC code.
const int8_t vrt::BasicVRLFrame::NO_CRC_1 = 0x45 [static]
This is the 2nd transmitted int8_t of the 32-bit NO_CRC code.
const int8_t vrt::BasicVRLFrame::NO_CRC_2 = 0x4E [static]
This is the 3rd transmitted int8_t of the 32-bit NO_CRC code.
const int8_t vrt::BasicVRLFrame::NO_CRC_3 = 0x44 [static]
This is the 4th transmitted int8_t of the 32-bit NO_CRC code.
const int32_t vrt::BasicVRLFrame::TRAILER_LENGTH = 4 [static]
The length of the trailer in octets.
    MAX_TRAILER_LENGTH = 4
const int32_t vrt::BasicVRLFrame::VRL_FAW = 0x56524C50 [static]
This is the 32-bit FWA (frame alignment word) marking the start of the frame.
    VRL_FAW = 0x56524C50 = { 'V', 'R', 'L', 'P' }
const int8_t vrt::BasicVRLFrame::VRL_FAW_0 = 0x56 [static]
This is the 1st transmitted int8_t of the 32-bit FWA (VRL_FAW).
Referenced by isVRL().
const int8_t vrt::BasicVRLFrame::VRL_FAW_1 = 0x52 [static]
This is the 2nd transmitted int8_t of the 32-bit FWA (VRL_FAW).
Referenced by isVRL().
const int8_t vrt::BasicVRLFrame::VRL_FAW_2 = 0x4C [static]
This is the 3rd transmitted int8_t of the 32-bit FWA (VRL_FAW).
Referenced by isVRL().
const int8_t vrt::BasicVRLFrame::VRL_FAW_3 = 0x50 [static]
This is the 4th transmitted int8_t of the 32-bit FWA (VRL_FAW).
Referenced by isVRL().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/BasicVRLFrame.h