VRT: vrt::BasicAcknowledgePacket Class Reference
vrt::BasicAcknowledgePacket Class Reference
BasicAcknowledgePacket (AckV and AckX).
#include <BasicAcknowledgePacket.h>
Public Member Functions
BasicAcknowledgePacket (vector< char > *buf_ptr, bool readOnly=false)
BasicAcknowledgePacket (const vector< char > &buf, bool readOnly=false)
Creates a new instance accessing the given data buffer.
BasicAcknowledgePacket (const vector< char > &buf, ssize_t start, ssize_t end, bool readOnly=false)
BasicAcknowledgePacket (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
BasicAcknowledgePacket ()
Creates a new instance that can be written to.
BasicAcknowledgePacket (const void *buf, size_t len, bool readOnly=false)
Creates a new instance accessing the given data buffer.
BasicAcknowledgePacket (const BasicVRTPacket &p, int64_t classID)
Internal constructor, for use by subclasses.
BasicAcknowledgePacket (const BasicVRTPacket &p)
Basic copy constructor.
~BasicAcknowledgePacket ()
Basic destructor.
virtual void addCIF1 (bool add=true, bool occurrence=false)
Adds or removes a CIF Sets the Enable Indicator of CIF0 and adds or removes 4-bytes for the CIF.
virtual void addCIF2 (bool add=true, bool occurrence=false)
virtual void addCIF3 (bool add=true, bool occurrence=false)
virtual void addCIF7 (bool add=true, bool occurrence=false)
void addError (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Adds one or more errors to the error bit field for the specified indicator field.
void addWarning (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Adds one or more warnings to the warning bit field for the specified indicator field.
virtual ArrayOfRecords get3DPointingVectorStructured (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the 3D Pointing Vector (Structured) See V49.2 spec Section 9.4.1.
virtual ArrayOfRecords getCIFsArray (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the CIFs Array Array-of-Records type (See V49.2 spec Section 9.13.1).
virtual ContextAssocLists getContextAssocLists (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Context Association Lists.
virtual PayloadFormat getDataPayloadFormat (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Data Packet Payload Format.
int32_t getError (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the error bit field for the specified indicator field.
std::vector< WarningErrorField_t > getErrors () const
Gets all errors for all indicator fields.
FreeFormMessage_t getFreeFormMessage () const
Gets Free-form Warning/Error Message Field.
virtual GeoSentences getGeoSentences (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the GPS ASCII "sentences".
virtual IndexFieldList getIndexList (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Index Field List.
virtual ArrayOfRecords getSectorScanStep (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Sector Scan/Step Field.
virtual SpectrumField getSpectrumField (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Spectrum Field SpectrumField type (See V49.2 spec Section 9.6.1).
int32_t getWarning (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the warning bit field for the specified indicator field.
std::vector< WarningErrorField_t > getWarnings () const
Gets all warnings for all indicator fields.
bool hasFreeFormMessage () const
Is there a Free-form Warning/Error Message Field.
void removeError (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Removes one or more errors from the error bit field for the specified indicator field.
void removeWarning (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Removes one or more warnings from the warning bit field for the specified indicator field.
virtual void setDataPayloadFormat (const PayloadFormat &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Data Packet Payload Format.
void setError (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the error bit field for the specified indicator field.
virtual void setErrorsGenerated (bool set)
void setFreeFormMessage (const FreeFormMessage_t msg)
Sets Free-form Warning/Error Message Field.
virtual void setPacketType (PacketType t)
Optional functionality: Sets the packet type.
void setWarning (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the warning bit field for the specified indicator field.
virtual void setWarningsGenerated (bool set)
Protected Member Functions
BasicAcknowledgePacket (const BasicVRTPacket &p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength)
Internal constructor, for use by subclasses.
virtual int8_t getB (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const
Unpacks a 16-bit integer from the payload at the indicated position.
virtual int32_t getCIF7Offset (int32_t attr, int32_t len, bool occurrence=0) const
Gets the offset of the CIF7 attribute Offset is from the start of a field of size specified.
virtual int32_t getContextIndicatorField0 (bool occurrence=0) const
virtual int32_t getContextIndicatorField1 (bool occurrence=0) const
virtual int32_t getContextIndicatorField2 (bool occurrence=0) const
virtual int32_t getContextIndicatorField3 (bool occurrence=0) const
virtual int32_t getContextIndicatorField7 (bool occurrence=0) const
virtual Ephemeris getEphemeris (int8_t cifNum, int32_t field, int32_t cif7bit) const
Used for unpacking ephemeris records.
int32_t getErrorIndicatorField (IndicatorFieldEnum_t field) const
int32_t getErrorIndicatorField (int8_t eifNum) const
boolNull getErrorIndicatorFieldBit (IndicatorFieldEnum_t field) const
virtual int32_t getFieldLen (int8_t cifNum, int32_t field, int32_t parent=0) const
Gets the length of the given field when present (-1 if variable, -2 if not found).
virtual Geolocation getGeolocation (int8_t cifNum, int32_t field, int32_t cif7bit) const
Used for unpacking geolocation records.
virtual int16_t getI (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const
Unpacks a 16-bit integer from the payload at the indicated position.
virtual int32_t getL (int8_t cifNum, int32_t bit, int32_t cif7bit) const
Get 32-bits from buffer as a 32-bit integer.
virtual int32_t getL24 (int8_t cifNum, int32_t bit, int32_t offset, int32_t cif7bit) const
Unpacks a 32-bit integer from the payload at the indicated position.
virtual int32_t getOffset (int8_t cifNum, int32_t field) const
Prepares a packet for resend resetting any non-persistent values and clearing the context change flags.
virtual boolNull getStateEventBit (int32_t enable, int32_t indicator, int32_t cif7bit) const
Gets the specified bit from the State and Event Indicator field.
virtual TimeStamp getTimeStampField (int8_t cifNum, int32_t bit, int32_t cif7bit) const
Unpacks a TimeStamp from the payload at the indicated position.
virtual int32_t getTotalFieldSize (int32_t fieldLen, bool occurrence=0) const
Gets the total size of the field, including all CIF7 attributes.
virtual UUID getUUID (int8_t cifNum, int32_t bit, int32_t cif7bit) const
Unpacks a 128-bit UUID from the payload at the indicated position.
int32_t getWarningIndicatorField (IndicatorFieldEnum_t field) const
int32_t getWarningIndicatorField (int8_t wifNum) const
boolNull getWarningIndicatorFieldBit (IndicatorFieldEnum_t field) const
virtual int64_t getX (int8_t cifNum, int32_t bit, int32_t cif7bit) const
Unpacks a 64-bit integer from the payload at the indicated position.
bool isCIFEnable (int8_t cifNum) const
virtual void setB (int8_t cifNum, int32_t bit, int32_t xoff, int8_t val, int32_t cif7bit)
Packs a 16-bit integer from the payload at the indicated position.
virtual void setCIF7Bit (int32_t cif7bit, bool set, bool occurrence=false)
virtual void setContextIndicatorField0Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setContextIndicatorField1Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setContextIndicatorField2Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setContextIndicatorField3Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setContextIndicatorField7Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setI (int8_t cifNum, int32_t bit, int32_t xoff, int16_t val, int32_t cif7bit)
Packs a 16-bit integer from the payload at the indicated position.
virtual void setL (int8_t cifNum, int32_t bit, int32_t val, int32_t cif7bit)
Set 32-bits of buffer from a 32-bit integer.
virtual void setRecord (int8_t cifNum, int32_t bit, const Record *val, int32_t oldLen, int32_t cif7bit)
Gets a block of data.
virtual void setStateEventBit (int32_t enable, int32_t indicator, boolNull value, int32_t cif7bit)
Sets the specified bit of the State and Event Indicator field.
virtual void setTimeStampField (int8_t cifNum, int32_t bit, const TimeStamp &val, int32_t cif7bit)
Packs a TimeStamp from the payload at the indicated position.
virtual void setUUID (int8_t cifNum, int32_t bit, const UUID &val, int32_t cif7bit)
Packs a 128-bit UUID from the payload at the indicated position.
virtual void setX (int8_t cifNum, int32_t bit, int64_t val, int32_t cif7bit)
Packs a 64-bit integer from the payload at the indicated position.
virtual void toStringStream (ostringstream &str) const
Writes the packet content to a string stream in a user-friendly format.
Detailed Description
BasicAcknowledgePacket (AckV and AckX).
Constructor & Destructor Documentation
vrt::BasicAcknowledgePacket::~BasicAcknowledgePacket () [inline]
Basic destructor.
vrt::BasicAcknowledgePacket::BasicAcknowledgePacket (const BasicVRTPacket & p)
Basic copy constructor.
vrt::BasicAcknowledgePacket::BasicAcknowledgePacket (const BasicVRTPacket & p, int64_t classID)
Internal constructor, for use by subclasses.
Parameters:
p The packet (already initialized).
classID The expected classID.
Exceptions:
VRTException If packet type or classID of the packet are invalid.
vrt::BasicAcknowledgePacket::BasicAcknowledgePacket (const void * buf, size_t len, bool readOnly = false)
Creates a new instance accessing the given data buffer.
Parameters:
buf The pointer to the packet buffer.
len The length of the packet buffer.
readOnly Should users of this instance be able to modify the underlying data buffer?
vrt::BasicAcknowledgePacket::BasicAcknowledgePacket ()
Creates a new instance that can be written to.
Initially this will just be a simple context packet with no fields set (other than the required packet length of 8 and a default stream ID of 0).
vrt::BasicAcknowledgePacket::BasicAcknowledgePacket (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
Initially this will just be a simple context packet with no fields set (other than the required packet length of 8 and a default stream ID of 0), but will have the underlying buffers pre-allocated as required.
Parameters:
bufsize The anticipated buffer size.
vrt::BasicAcknowledgePacket::BasicAcknowledgePacket (const vector< char > & buf, bool readOnly = false)
Creates a new instance accessing the given data buffer.
Note that when the buffer lengths are given, only the most minimal of error checking is done. Users should call isPacketValid() to verify that the packet is valid. Invalid packets can result unpredictable behavior, but this is explicitly allowed (to the extent possible) so that applications creating packets can use this class even if the packet isn't yet "valid".
Parameters:
buf The data buffer to use.
readOnly Should users of this instance be able to modify the underlying data buffer?
Exceptions:
VRTException If the offset is negative or greater than the length of the buffer given. Also thrown if the buffer length is -1 and a copy can not be made because the sizes in the header of the packet are invalid.
vrt::BasicAcknowledgePacket::BasicAcknowledgePacket (const BasicVRTPacket & p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength) [protected]
Internal constructor, for use by subclasses.
Parameters:
p The packet (already initialized).
type The expected packet type.
classID The expected classID.
minPayloadLength The minimum payload length.
maxPayloadLength The maximum payload length (<0 if not pre-defined).
Exceptions:
VRTException If packet type or classID of the packet are invalid, or if the payload length is invalid.
Member Function Documentation
virtual void vrt::BasicAcknowledgePacket::addCIF1 (bool add = true, bool occurrence = false) [virtual]
Adds or removes a CIF Sets the Enable Indicator of CIF0 and adds or removes 4-bytes for the CIF.
Parameters:
add True = add CIF (default), False = remove CIF
occurrence False (0) if first occurrence (default, Warnings), True (1) if second occurrence (Errors)
Implements vrt::IndicatorFieldProvider.
void vrt::BasicAcknowledgePacket::addError (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Adds one or more errors to the error bit field for the specified indicator field.
Parameters:
field Indicator field
val Error bit field to add (set) to the error bit field.
cif7field (Optional) Indicator field for CIF7 attribute.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getL(), and setL().
void vrt::BasicAcknowledgePacket::addWarning (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Adds one or more warnings to the warning bit field for the specified indicator field.
Parameters:
field Indicator field
val Warning bit field to add (set) to the warning bit field.
cif7field (Optional) Indicator field for CIF7 attribute.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getL(), and setL().
virtual ArrayOfRecords vrt::BasicAcknowledgePacket::get3DPointingVectorStructured (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the 3D Pointing Vector (Structured) See V49.2 spec Section 9.4.1.
Array-of-Records format HeaderSize is either 0 or 1
Note: docs say 3 or 4, but that's inconsistent with definition of ArrayOfRecords, so ignoring that guidance 3 or 4 must include the required 3 words of every ArrayOfRecords, which is incorrect.
depends on whether optional App-Specific Header is included, which is a 32-bit word if so
optional App-Specific Header is a *Global* Index/Ref/Beam subfield NumWords/Record is either 1 or 2
depends on whether optional Index/Ref/Beam subfield is included in each record Bitmapped CIF subfield only uses bits 31 and 30
Bit 31: Set when each record includes the optional Index/Ref/Beam subfield
Bit 30: Always set; Indicates presence of 3D Pointing Vector subfield in each record, which is required App-Specific header is optional 32-bit word
as mentioned above, this is a *Global* Index/Ref/Beam subfield Each Record is at most 2 words
First 32-bit word is optional, and is the Index/Ref/Beam subfield
Second 32-bit word is required, and is the 3D Pointing Vector subfield Index/Ref/Beam subfield
Bits 31..16: Record Index (optional; 0 when global or unused in records)
Bits 15..4: Reserved
Bits 3..2: Reference (00 not specified; 01 ECEF; 10 Platform centered; 11 Array centered)
Bits 1..0: Beam (00 not specified; 01 Beam or signal direction; 10 Null; 11 reserved) 3D Pointing Vector subfield
Bits 31..16: Elevation angle in degrees; radix point to the right of bit 23; range [-90,90]
Bits 15..0: Azimuthal angle in degrees; radix point to the right of bit 7; range [0,512)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
3D Pointing Vector as an Array-of-Records (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
virtual int8_t vrt::BasicAcknowledgePacket::getB (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const [inline, protected, virtual]
Unpacks a 16-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual int32_t vrt::BasicAcknowledgePacket::getCIF7Offset (int32_t attr, int32_t len, bool occurrence = 0) const [protected, virtual]
Gets the offset of the CIF7 attribute Offset is from the start of a field of size specified.
Parameters:
attr CIF7 attribute bitmask
len Length of the field
occurrence False (0) if first occurrence (default; almost everything), True (1) if second occurrence (only Errors for BasicAcknowledgePacket)
Returns:
Offset from start of field
Reimplemented from vrt::IndicatorFieldProvider.
virtual ArrayOfRecords vrt::BasicAcknowledgePacket::getCIFsArray (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the CIFs Array Array-of-Records type (See V49.2 spec Section 9.13.1).
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The CIFs Array as an Array-of-Records (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
virtual ContextAssocLists vrt::BasicAcknowledgePacket::getContextAssocLists (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the Context Association Lists.
These lists indicate the other context/data streams associated with this one.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The context association lists (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
virtual PayloadFormat vrt::BasicAcknowledgePacket::getDataPayloadFormat (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the Data Packet Payload Format.
This specifies the format of the data in the paired data packet stream.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The payload format (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
virtual Ephemeris vrt::BasicAcknowledgePacket::getEphemeris (int8_t cifNum, int32_t field, int32_t cif7bit) const [inline, protected, virtual]
Used for unpacking ephemeris records.
Implements vrt::IndicatorFieldProvider.
int32_t vrt::BasicAcknowledgePacket::getError (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the error bit field for the specified indicator field.
Parameters:
field Indicator field
cif7field (Optional) Indicator field for CIF7 attribute.
cif7field (Optional) Indicator field for CIF7 attribute.
Returns:
Error bit field (0x0 or WEF_NULL or WEF_NO_WARNING_ERROR if no errors).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getL().
std::vector<WarningErrorField_t> vrt::BasicAcknowledgePacket::getErrors () const
Gets all errors for all indicator fields.
Returns:
Vector of errors.
virtual int32_t vrt::BasicAcknowledgePacket::getFieldLen (int8_t cifNum, int32_t field, int32_t parent = 0) const [protected, virtual]
Gets the length of the given field when present (-1 if variable, -2 if not found).
Parameters:
cifNum number of CIF that field belongs to.
field bitmask associated with field of interest.
parent length of parent field
Returns:
size of field of interest in bytes.
Exceptions:
VRTException If the CIF number is invalid.
Implements vrt::IndicatorFieldProvider.
FreeFormMessage_t vrt::BasicAcknowledgePacket::getFreeFormMessage () const
Gets Free-form Warning/Error Message Field.
Returns:
Free-form message
virtual Geolocation vrt::BasicAcknowledgePacket::getGeolocation (int8_t cifNum, int32_t field, int32_t cif7bit) const [inline, protected, virtual]
Used for unpacking geolocation records.
Implements vrt::IndicatorFieldProvider.
virtual GeoSentences vrt::BasicAcknowledgePacket::getGeoSentences (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the GPS ASCII "sentences".
These are ASCII "sentences" from a GPS (Global Positioning System) receiver, such as those conforming to NMEA-0183. Due to the great variety in GPS "sentences", this class makes little effort to do anything useful with them. Users are encouraged to use getGeolocationGPS() which essentially provides the same information, but in a consistent form.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The geolocation information (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
virtual int16_t vrt::BasicAcknowledgePacket::getI (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const [inline, protected, virtual]
Unpacks a 16-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual IndexFieldList vrt::BasicAcknowledgePacket::getIndexList (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the Index Field List.
IndexFieldList type (See V49.2 spec Section 9.3.2)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Index Field List (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
virtual int32_t vrt::BasicAcknowledgePacket::getL (int8_t cifNum, int32_t bit, int32_t cif7bit) const [protected, virtual]
Get 32-bits from buffer as a 32-bit integer.
Note: INT32_NULL is a valid value (0x80000000==FIELD_NOT_EXECUTED) in the context of Warning and Error fields. The value zero (0x0==WEF_NULL) has the same meaning as NULL in this context. This function returns 0x0 (which is WEF_NULL==WEF_NO_WARNING_ERROR==0x0) when the field does not exist. This function returns 0x80000000 (i.e. INT32_NULL) when the field contains that value.
Parameters:
cifNum Indicator field number
bit Bit mask of field.
cif7bit bitmask of CIF7 attribute
Returns:
32-bit integer from buffer.
Implements vrt::IndicatorFieldProvider.
Referenced by addError(), addWarning(), getError(), getWarning(), removeError(), and removeWarning().
virtual int32_t vrt::BasicAcknowledgePacket::getL24 (int8_t cifNum, int32_t bit, int32_t offset, int32_t cif7bit) const [inline, protected, virtual]
Unpacks a 32-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual int32_t vrt::BasicAcknowledgePacket::getOffset (int8_t cifNum, int32_t field) const [protected, virtual]
Prepares a packet for resend resetting any non-persistent values and clearing the context change flags.
This is implemented as follows: Gets the offset for the given context indicator field relative to the location of the first occurrence of CIF0. CIF7 is considered an invalid CIF number. For access to the second occurrence of CIFs (i.e. Error fields in Ack packets), add 8 to the CIF number, effectively setting the 4th bit (mod8 gives field, div8 gives occurrence). For the Free-form Warning/Error Message Field, set the CIF# to 0xFF (-1).
Parameters:
cifNum number of CIF that field belongs to; or -1 for Free-form message field.
field bitmask associated with field of interest; ignored for Free-form message field.
Returns:
offset in bytes from beginning of CIF payload.
Exceptions:
VRTException If the CIF number is invalid.
Implements vrt::IndicatorFieldProvider.
virtual ArrayOfRecords vrt::BasicAcknowledgePacket::getSectorScanStep (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the Sector Scan/Step Field.
Array-of-Records type (See V49.2 spec Section 9.6.2)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Sector Scan/Step Array-of-Records (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
virtual SpectrumField vrt::BasicAcknowledgePacket::getSpectrumField (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the Spectrum Field SpectrumField type (See V49.2 spec Section 9.6.1).
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Spectrum Field (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
virtual boolNull vrt::BasicAcknowledgePacket::getStateEventBit (int32_t enable, int32_t indicator, int32_t cif7bit) const [inline, protected, virtual]
Gets the specified bit from the State and Event Indicator field.
Parameters:
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
cif7bit Bit position of the CIF7 attribute indicator flag.
Returns:
null if field is not present, null if the enable bit is not set, true if the enable bit is set and the indicator bit is set, false if the enable bit is set but the indicator bit is not set.
Implements vrt::IndicatorFieldProvider.
virtual TimeStamp vrt::BasicAcknowledgePacket::getTimeStampField (int8_t cifNum, int32_t bit, int32_t cif7bit) const [inline, protected, virtual]
Unpacks a TimeStamp from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual int32_t vrt::BasicAcknowledgePacket::getTotalFieldSize (int32_t fieldLen, bool occurrence = 0) const [protected, virtual]
Gets the total size of the field, including all CIF7 attributes.
Parameters:
fieldLen Length of the field w/o including CIF7 attributes
occurrence False (0) if first occurrence (default; almost everything), True (1) if second occurrence (only Errors for BasicAcknowledgePacket)
Returns:
Length of the field including CIF7 attributes
Implements vrt::IndicatorFieldProvider.
virtual UUID vrt::BasicAcknowledgePacket::getUUID (int8_t cifNum, int32_t bit, int32_t cif7bit) const [inline, protected, virtual]
Unpacks a 128-bit UUID from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
int32_t vrt::BasicAcknowledgePacket::getWarning (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the warning bit field for the specified indicator field.
Parameters:
field Indicator field
cif7field (Optional) Indicator field for CIF7 attribute.
Returns:
Warning bit field (0x0 or WEF_NULL or WEF_NO_WARNING_ERROR if no warnings).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getL().
std::vector<WarningErrorField_t> vrt::BasicAcknowledgePacket::getWarnings () const
Gets all warnings for all indicator fields.
Returns:
Vector of warnings.
virtual int64_t vrt::BasicAcknowledgePacket::getX (int8_t cifNum, int32_t bit, int32_t cif7bit) const [inline, protected, virtual]
Unpacks a 64-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
bool vrt::BasicAcknowledgePacket::hasFreeFormMessage () const
Is there a Free-form Warning/Error Message Field.
Returns:
True if Free-form Message; False otherwise
void vrt::BasicAcknowledgePacket::removeError (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Removes one or more errors from the error bit field for the specified indicator field.
Parameters:
field Indicator field
val Error bit field to remove (unset) from the error bit field.
cif7field (Optional) Indicator field for CIF7 attribute.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getL(), and setL().
void vrt::BasicAcknowledgePacket::removeWarning (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Removes one or more warnings from the warning bit field for the specified indicator field.
Parameters:
field Indicator field
val Warning bit field to remove (unset) from the warning bit field.
cif7field (Optional) Indicator field for CIF7 attribute.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getL(), and setL().
virtual void vrt::BasicAcknowledgePacket::setB (int8_t cifNum, int32_t bit, int32_t xoff, int8_t val, int32_t cif7bit) [inline, protected, virtual]
Packs a 16-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicAcknowledgePacket::setDataPayloadFormat (const PayloadFormat & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline, virtual]
Sets the Data Packet Payload Format.
This specifies the format of the data in the paired data packet stream.
Parameters:
val The payload format (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
Implements vrt::IndicatorFieldProvider.
void vrt::BasicAcknowledgePacket::setError (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the error bit field for the specified indicator field.
Parameters:
field Indicator field
val Error bit field (0x0 or WEF_NULL or WEF_NO_WARNING_ERROR if no errors).
cif7field (Optional) Indicator field for CIF7 attribute.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setL().
void vrt::BasicAcknowledgePacket::setFreeFormMessage (const FreeFormMessage_t msg)
Sets Free-form Warning/Error Message Field.
Parameters:
msg Free-form message
virtual void vrt::BasicAcknowledgePacket::setI (int8_t cifNum, int32_t bit, int32_t xoff, int16_t val, int32_t cif7bit) [inline, protected, virtual]
Packs a 16-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicAcknowledgePacket::setL (int8_t cifNum, int32_t bit, int32_t val, int32_t cif7bit) [protected, virtual]
Set 32-bits of buffer from a 32-bit integer.
Note: INT32_NULL is a valid value (0x80000000==FIELD_NOT_EXECUTED) in the context of Warning and Error fields. The value zero (0x0==WEF_NULL) has the same meaning as NULL in this context. This function removes the field when set to 0x0 (which is WEF_NULL==WEF_NO_WARNING_ERROR==0x0). This function sets the value 0x80000000 (i.e. INT32_NULL) when the argument contains that value.
Parameters:
cifNum Indicator field number
bit Bit mask of field.
val 32-bit integer.
cif7bit bitmask of CIF7 attribute
Implements vrt::IndicatorFieldProvider.
Referenced by addError(), addWarning(), removeError(), removeWarning(), setError(), and setWarning().
virtual void vrt::BasicAcknowledgePacket::setPacketType (PacketType t) [inline, virtual]
Optional functionality: Sets the packet type.
Parameters:
t The packet type.
Exceptions:
VRTException If this method is not supported.
Reimplemented from vrt::BasicCommandPacket.
virtual void vrt::BasicAcknowledgePacket::setRecord (int8_t cifNum, int32_t bit, const Record * val, int32_t oldLen, int32_t cif7bit) [inline, protected, virtual]
Gets a block of data.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicAcknowledgePacket::setStateEventBit (int32_t enable, int32_t indicator, boolNull value, int32_t cif7bit) [inline, protected, virtual]
Sets the specified bit of the State and Event Indicator field.
Parameters:
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
value The value of the bits: null if the enable bit should not be set, true if the enable bit and the indicator bit should be set, false if the enable bit should be set but the indicator bit should not be set.
cif7bit Bit position of the CIF7 attribute indicator flag.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicAcknowledgePacket::setTimeStampField (int8_t cifNum, int32_t bit, const TimeStamp & val, int32_t cif7bit) [inline, protected, virtual]
Packs a TimeStamp from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicAcknowledgePacket::setUUID (int8_t cifNum, int32_t bit, const UUID & val, int32_t cif7bit) [inline, protected, virtual]
Packs a 128-bit UUID from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
void vrt::BasicAcknowledgePacket::setWarning (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the warning bit field for the specified indicator field.
Parameters:
field Indicator field
val Warning bit field (0x0 or WEF_NULL or WEF_NO_WARNING_ERROR if no warnings).
cif7field (Optional) Indicator field for CIF7 attribute.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setL().
virtual void vrt::BasicAcknowledgePacket::setX (int8_t cifNum, int32_t bit, int64_t val, int32_t cif7bit) [inline, protected, virtual]
Packs a 64-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicAcknowledgePacket::toStringStream (ostringstream & str) const [protected, virtual]
Writes the packet content to a string stream in a user-friendly format.
Parameters:
str The string stream to write to.
Reimplemented from vrt::BasicCommandPacket.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/BasicAcknowledgePacket.h