VRT: vrt::BasicDataPacket Class Reference
vrt::BasicDataPacket Class Reference
An basic but full-featured implementation of a VRT IF Data packet.
#include <BasicDataPacket.h>
Public Member Functions
BasicDataPacket (vector< char > *buf, bool readOnly=false)
Creates a new instance accessing the given data buffer pointer.
BasicDataPacket (const vector< char > &buf, bool readOnly=false)
Creates a new instance accessing the given data buffer.
BasicDataPacket (const vector< char > &buf, ssize_t start, ssize_t end, bool readOnly=false)
BasicDataPacket (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
BasicDataPacket ()
Creates a new instance that can be written to.
BasicDataPacket (const void *buf, size_t len, bool readOnly=false)
Creates a new instance accessing the given data buffer.
BasicDataPacket (const BasicVRTPacket &p)
Basic copy constructor for the class.
~BasicDataPacket ()
Basic destructor for the class.
int8_t getAssocPacketCount () const
Gets the associated packet count.
void * getData (void *array, bool convert=true) const
Unpacks the data and returns it in a native byte buffer.
void getData (vector< char > &array, size_t offset, bool convert=true) const
Unpacks the data and returns it in a native byte buffer.
void * getData (const PayloadFormat &pf, void *array, bool convert=true) const
Unpacks the data and returns it in a native byte buffer.
void getData (const PayloadFormat &pf, vector< char > &array, size_t offset, bool convert=true) const
Unpacks the data and returns it in a native byte buffer.
void * getData_normal (const PayloadFormat &pf, int position)
vector< int8_t > getDataByte () const
Unpacks the data and returns it as a byte array.
int8_t * getDataByte (int8_t *array) const
Unpacks the data and returns it as a byte array.
vector< int8_t > getDataByte (const PayloadFormat &pf) const
Unpacks the data and returns it as a byte array.
int8_t * getDataByte (const PayloadFormat &pf, int8_t *array) const
Unpacks the data and returns it as a byte array.
vector< double > getDataDouble () const
Unpacks the data and returns it as a double array.
double * getDataDouble (double *array) const
Unpacks the data and returns it as a double array.
vector< double > getDataDouble (const PayloadFormat &pf) const
Unpacks the data and returns it as a double array.
double * getDataDouble (const PayloadFormat &pf, double *array) const
Unpacks the data and returns it as a double array.
vector< float > getDataFloat () const
Unpacks the data and returns it as a float array.
float * getDataFloat (float *array) const
Unpacks the data and returns it as a float array.
vector< float > getDataFloat (const PayloadFormat &pf) const
Unpacks the data and returns it as a float array.
float * getDataFloat (const PayloadFormat &pf, float *array) const
Unpacks the data and returns it as a float array.
vector< int32_t > getDataInt () const
Unpacks the data and returns it as a int array.
int32_t * getDataInt (int32_t *array) const
Unpacks the data and returns it as a int array.
vector< int32_t > getDataInt (const PayloadFormat &pf) const
Unpacks the data and returns it as a int array.
int32_t * getDataInt (const PayloadFormat &pf, int32_t *array) const
Unpacks the data and returns it as a int array.
int32_t getDataLength (const PayloadFormat &pf) const
Gets the length of the data in number of elements.
int32_t getDataLength () const
Gets the length of the data in number of elements.
vector< int64_t > getDataLong () const
Unpacks the data and returns it as a long array.
int64_t * getDataLong (int64_t *array) const
Unpacks the data and returns it as a long array.
vector< int64_t > getDataLong (const PayloadFormat &pf) const
Unpacks the data and returns it as a long array.
int64_t * getDataLong (const PayloadFormat &pf, int64_t *array) const
Unpacks the data and returns it as a long array.
vector< int16_t > getDataShort () const
Unpacks the data and returns it as a byte array.
int16_t * getDataShort (int16_t *array) const
Unpacks the data and returns it as a short array.
vector< int16_t > getDataShort (const PayloadFormat &pf) const
Unpacks the data and returns it as a short array.
int16_t * getDataShort (const PayloadFormat &pf, int16_t *array) const
Unpacks the data and returns it as a short array.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
int32_t getLostBytes (const TimeStamp &expected, double sampleRate) const
Computes the number of bytes lost between two packets.
int32_t getLostBytes (const TimeStamp &expected, double sampleRate, const PayloadFormat &pf) const
Computes the number of bytes lost between two packets.
int32_t getLostSamples (const TimeStamp &expected, double sampleRate) const
Computes the number of samples lost between two packets.
TimeStamp getNextTimeStamp (double sampleRate) const
Gets the next expected time stamp for a data packet on this stream.
TimeStamp getNextTimeStamp (double sampleRate, const PayloadFormat &pf) const
Gets the next expected time stamp for a data packet on this stream.
virtual string getPacketValid (bool strict, int32_t length) const
Checks to see if the packet is valid.
virtual PayloadFormat getPayloadFormat () const
Gets the assumed payload format used when interacting with the data in this packet.
int32_t getScalarDataLength (const PayloadFormat &pf) const
Utility method: Gets the length of the data in number of scalar elements.
int32_t getScalarDataLength () const
Utility method: Gets the length of the data in number of scalar elements.
StartStopIndication getStartStopIndication () const
Gets the Sample Frame StartStopIndication value.
boolNull isAutomaticGainControl () const
Gets the AGC/MGC indicator flag.
boolNull isBit10 () const
Gets the #10 user-defined indicator flag.
boolNull isBit11 () const
Gets the #11 user-defined indicator flag.
boolNull isBit8 () const
Gets the #8 user-defined indicator flag.
boolNull isBit9 () const
Gets the #9 user-defined indicator flag.
boolNull isCalibratedTimeStamp () const
Gets the calibrated time indicator flag.
boolNull isDataValid () const
Gets the valid data indicator flag.
boolNull isDiscontinuious () const
Deprecated: Please change to using isDiscontinuous.
boolNull isDiscontinuous () const
Gets the sample loss indicator flag.
boolNull isInvertedSpectrum () const
Gets the spectral inversion indicator flag.
boolNull isOverRange () const
Gets the over-range indicator flag.
boolNull isReferenceLocked () const
Gets the reference lock indicator flag.
boolNull isSignalDetected () const
Gets the signal detected indicator flag.
void setAssocPacketCount (int8_t v)
Optional functionality: Gets the associated packet count.
void setAutomaticGainControl (boolNull v)
Optional functionality: Gets the AGC/MGC indicator flag.
void setBit10 (boolNull v)
Optional functionality: Gets the #10 user-defined indicator flag.
void setBit11 (boolNull v)
Optional functionality: Gets the #11 user-defined indicator flag.
void setBit8 (boolNull v)
Optional functionality: Gets the #8 user-defined indicator flag.
void setBit9 (boolNull v)
Optional functionality: Gets the #9 user-defined indicator flag.
void setCalibratedTimeStamp (boolNull v)
Optional functionality: Sets the calibrated time indicator flag.
void setData (const void *array, int32_t length, bool convert=true)
Packs the data from a native byte buffer.
void setData (const vector< char > &array, size_t offset, int32_t length, bool convert=true)
Packs the data from a native byte buffer.
void setData (const PayloadFormat &pf, const void *array, int32_t length, bool convert=true)
Packs the data from a native byte buffer.
void setData (const PayloadFormat &pf, const vector< char > &array, size_t offset, int32_t length, bool convert=true)
Packs the data from a native byte buffer.
void setDataByte (const vector< int8_t > &array)
Packs the data using the values from a byte array.
void setDataByte (const int8_t *array, size_t len)
Packs the data using the values from a byte array.
void setDataByte (const PayloadFormat &pf, const vector< int8_t > &array)
Packs the data using the values from a byte array.
void setDataByte (const PayloadFormat &pf, const int8_t *array, size_t len)
Packs the data using the values from a byte array.
void setDataDouble (const vector< double > &array)
Packs the data using the values from a double array.
void setDataDouble (const double *array, size_t len)
Packs the data using the values from a double array.
void setDataDouble (const PayloadFormat &pf, const vector< double > &array)
Packs the data using the values from a double array.
void setDataDouble (const PayloadFormat &pf, const double *array, size_t len)
Packs the data using the values from a double array.
void setDataFloat (const vector< float > &array)
Packs the data using the values from a float array.
void setDataFloat (const float *array, size_t len)
Packs the data using the values from a float array.
void setDataFloat (const PayloadFormat &pf, const vector< float > &array)
Packs the data using the values from a float array.
void setDataFloat (const PayloadFormat &pf, const float *array, size_t len)
Packs the data using the values from a float array.
void setDataInt (const vector< int32_t > &array)
Packs the data using the values from a int array.
void setDataInt (const int32_t *array, size_t len)
Packs the data using the values from a int array.
void setDataInt (const PayloadFormat &pf, const vector< int32_t > &array)
Packs the data using the values from a int array.
void setDataInt (const PayloadFormat &pf, const int32_t *array, size_t len)
Packs the data using the values from a int array.
void setDataLength (const PayloadFormat &pf, int32_t length)
Sets the length of the data in number of elements.
void setDataLength (int32_t length)
Sets the length of the data in number of elements.
void setDataLong (const vector< int64_t > &array)
Packs the data using the values from a long array.
void setDataLong (const int64_t *array, size_t len)
Packs the data using the values from a long array.
void setDataLong (const PayloadFormat &pf, const vector< int64_t > &array)
Packs the data using the values from a long array.
void setDataLong (const PayloadFormat &pf, const int64_t *array, size_t len)
Packs the data using the values from a long array.
void setDataShort (const vector< int16_t > &array)
Packs the data using the values from a short array.
void setDataShort (const int16_t *array, size_t len)
Packs the data using the values from a short array.
void setDataShort (const PayloadFormat &pf, const vector< int16_t > &array)
Packs the data using the values from a short array.
void setDataShort (const PayloadFormat &pf, const int16_t *array, size_t len)
Packs the data using the values from a short array.
void setDataValid (boolNull v)
Optional functionality: Gets the valid data indicator flag.
void setDiscontinuious (boolNull v)
Deprecated: Please change to using setDiscontinuous.
void setDiscontinuous (boolNull v)
Optional functionality: Gets the sample loss indicator flag.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setInvertedSpectrum (boolNull v)
Optional functionality: Gets the spectral inversion indicator flag.
void setOverRange (boolNull v)
Optional functionality: Gets the over-range indicator flag.
void setPacketType (PacketType t)
Optional functionality: Sets the packet type.
virtual void setPayloadFormat (const PayloadFormat &pf)
Optional Functionality: Sets the payload format to be assumed when interacting with the data in this packet.
void setReferenceLocked (boolNull v)
Optional functionality: Gets the reference lock indicator flag.
void setScalarDataLength (PayloadFormat pf, int32_t length)
Utility method: Sets the length of the data in number of scalar elements.
void setScalarDataLength (int32_t length)
Utility method: Sets the length of the data in number of scalar elements.
void setSignalDetected (boolNull v)
Optional functionality: Gets the signal detected indicator flag.
void setStartStopIndication (StartStopIndication v)
Optional functionality: Sets the Sample Frame Start Stop Indication value.
void swapPayloadBytes (const PayloadFormat &pf)
void unsetStartStopIndication ()
Optional functionality: Unsets the Sample Frame Start Stop Indication enable bits.
Protected Member Functions
BasicDataPacket (const BasicVRTPacket &p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength)
Internal constructor, for use by subclasses.
void dropTrailerIfEmpty ()
If the trailer is empty, delete it.
int32_t getDataLength (const PayloadFormat &pf, bool scalar) const
Gets the data length with option for scalar-only computation.
int32_t getTrailer () const
Gets the trailer as an integer.
boolNull getTrailerBit (int32_t enable, int32_t indicator) const
Gets the specified bit from the trailer.
void setDataLength (const PayloadFormat &pf, int32_t length, bool scalar)
Sets the data length with option for scalar-only computation.
virtual void setTrailerBit (int32_t enable, int32_t indicator, boolNull value)
Optional functionality: Sets the specified bit from the trailer.
virtual void toStringStream (ostringstream &str) const
Writes the packet content to a string stream in a user-friendly format.
Detailed Description
An basic but full-featured implementation of a VRT IF Data packet.
The following implementation is used for the HasFields methods:
     ID | Name                 | Type
    ----+----------------------+---------------
    N+0 | CalibratedTimeStamp  | BoolNull
    N+1 | DataValid            | BoolNull
    N+2 | ReferenceLocked      | BoolNull
    N+3 | AGC                  | BoolNull
    N+4 | SignalDetected       | BoolNull
    N+5 | InvertedSpectrum     | BoolNull
    N+6 | OverRange            | BoolNull
    N+7 | Discontinuous        | BoolNull
    N+8 | Bit11                | BoolNull
    N+9 | Bit10                | BoolNull
    N+10| Bit9                 | BoolNull
    N+11| Bit8                 | BoolNull
    N+12| AssocPacketCount     | Int8
    N+13| PayloadFormat        | PayloadFormat
    ----+----------------------+---------------
    (N = number of fields in BasicVRTPacket)
Constructor & Destructor Documentation
vrt::BasicDataPacket::~BasicDataPacket () [inline]
Basic destructor for the class.
vrt::BasicDataPacket::BasicDataPacket (const BasicVRTPacket & p)
Basic copy constructor for the class.
vrt::BasicDataPacket::BasicDataPacket (const void * buf, size_t len, bool readOnly = false)
Creates a new instance accessing the given data buffer.
Parameters:
buf The pointer to the packet buffer.
len The length of the packet buffer.
readOnly Should users of this instance be able to modify the underlying data buffer?
vrt::BasicDataPacket::BasicDataPacket ()
Creates a new instance that can be written to.
Initially this will just be a simple data packet with no fields set (other than the required packet length of 4).
vrt::BasicDataPacket::BasicDataPacket (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
Initially this will just be a simple data packet with no fields set (other than the required packet length of 4), but will have the underlying buffers pre-allocated as required.
Parameters:
bufsize The anticipated buffer size.
vrt::BasicDataPacket::BasicDataPacket (const vector< char > & buf, bool readOnly = false)
Creates a new instance accessing the given data buffer.
Note that when the buffer lengths are given, only the most minimal of error checking is done. Users should call isPacketValid() to verify that the packet is valid. Invalid packets can result unpredictable behavior, but this is explicitly allowed (to the extent possible) so that applications creating packets can use this class even if the packet isn't yet "valid".
Parameters:
buf The data buffer to use.
readOnly Should users of this instance be able to modify the underlying data buffer?
vrt::BasicDataPacket::BasicDataPacket (vector< char > * buf, bool readOnly = false)
Creates a new instance accessing the given data buffer pointer.
Note that when the buffer lengths are given, only the most minimal of error checking is done. Users should call isPacketValid() to verify that the packet is valid. Invalid packets can result unpredictable behavior, but this is explicitly allowed (to the extent possible) so that applications creating packets can use this class even if the packet isn't yet "valid".
Parameters:
buf The data buffer pointer to use.
readOnly Should users of this instance be able to modify the underlying data buffer?
vrt::BasicDataPacket::BasicDataPacket (const BasicVRTPacket & p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength) [protected]
Internal constructor, for use by subclasses.
Parameters:
p The packet (already initialized).
type The expected packet type.
classID The expected classID.
minPayloadLength The minimum payload length.
maxPayloadLength The maximum payload length (<0 if not pre-defined).
Exceptions:
VRTException If packet type or classID of the packet are invalid, or if the payload length is invalid.
Member Function Documentation
void vrt::BasicDataPacket::dropTrailerIfEmpty () [protected]
If the trailer is empty, delete it.
int8_t vrt::BasicDataPacket::getAssocPacketCount () const
Gets the associated packet count.
This indicates the number of context packets with context change or event information relevant to this data packet.
Returns:
The associated packet count (0..127), or null if not specified (null is returned for all context packets).
void* vrt::BasicDataPacket::getData (void * array, bool convert = true) const [inline]
Unpacks the data and returns it in a native byte buffer.
This is basically a byte-for-byte copy of the payload, except that a conversion is done from BIG_ENDIAN to the native byte ordering. This method is intended for use within existing programming frameworks that already provide type conversions. This method does not convert the values to byte data, only copies the data to what is effectively a void* buffer in the native byte order.
For 8-bit, 4-bit and 1-bit types, this is implemented as a fast array copy with no translation being done with regards to byte order. Further, with 4-bit and 1-bit types an assumption is made that the number of entries is an even multiple of one octet (i.e. 4-bit values must be in multiples of 2 and 1-bit values in multiples of 8).
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getData(p.getPayloadFormat(),array)
Parameters:
array The array to insert the data into.
convert Convert byte order to match native representation? Set this to false if it is necessary to keep the data in big-endian format.
Returns:
array
Exceptions:
VRTException If the payload format is null or if the array is null.
VRTException If the payload format is anything other than PayloadFormat_INT4, PayloadFormat_INT8, PayloadFormat_INT16, PayloadFormat_INT32, PayloadFormat_INT64, PayloadFormat_FLOAT32, PayloadFormat_DOUBLE64 PayloadFormat_UINT1, PayloadFormat_UINT4, PayloadFormat_UINT8, PayloadFormat_UINT16, PayloadFormat_UINT32, PayloadFormat_UINT64.
References getData(), and getPayloadFormat().
void vrt::BasicDataPacket::getData (vector< char > & array, size_t offset, bool convert = true) const [inline]
Unpacks the data and returns it in a native byte buffer.
This is basically a byte-for-byte copy of the payload, except that a conversion is done from BIG_ENDIAN to the native byte ordering. This method is intended for use within existing programming frameworks that already provide type conversions. This method does not convert the values to byte data, only copies the data to what is effectively a void* buffer in the native byte order.
For 8-bit, 4-bit and 1-bit types, this is implemented as a fast array copy with no translation being done with regards to byte order. Further, with 4-bit and 1-bit types an assumption is made that the number of entries is an even multiple of one octet (i.e. 4-bit values must be in multiples of 2 and 1-bit values in multiples of 8).
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getData(p.getPayloadFormat(),array,offset)
Parameters:
array The array to insert the data into.
offset The array offset.
convert Convert byte order to match native representation? Set this to false if it is necessary to keep the data in big-endian format.
Returns:
array
Exceptions:
VRTException If the payload format is null or if the array is null.
VRTException If the payload format is anything other than PayloadFormat_INT4, PayloadFormat_INT8, PayloadFormat_INT16, PayloadFormat_INT32, PayloadFormat_INT64, PayloadFormat_FLOAT32, PayloadFormat_DOUBLE64 PayloadFormat_UINT1, PayloadFormat_UINT4, PayloadFormat_UINT8, PayloadFormat_UINT16, PayloadFormat_UINT32, PayloadFormat_UINT64.
VRTException If the array length is shorter than offset+getPayloadLength().
References getData(), and getPayloadFormat().
void* vrt::BasicDataPacket::getData (const PayloadFormat & pf, void * array, bool convert = true) const
Unpacks the data and returns it in a native byte buffer.
This is basically a byte-for-byte copy of the payload, except that a conversion is done from BIG_ENDIAN to the native byte ordering. This method is intended for use within existing programming frameworks that already provide type conversions. This method does not convert the values to byte data, only copies the data to what is effectively a void* buffer in the native byte order.
For 8-bit, 4-bit and 1-bit types, this is implemented as a fast array copy with no translation being done with regards to byte order. Further, with 4-bit and 1-bit types an assumption is made that the number of entries is an even multiple of one octet (i.e. 4-bit values must be in multiples of 2 and 1-bit values in multiples of 8).
Parameters:
pf The payload format to assume.
array The array to insert the data into.
convert Convert byte order to match native representation? Set this to false if it is necessary to keep the data in big-endian format.
Returns:
array
Exceptions:
VRTException If the payload format is null or if the array is null.
VRTException If the payload format is anything other than PayloadFormat_INT4, PayloadFormat_INT8, PayloadFormat_INT16, PayloadFormat_INT32, PayloadFormat_INT64, PayloadFormat_FLOAT32, PayloadFormat_DOUBLE64 PayloadFormat_UINT1, PayloadFormat_UINT4, PayloadFormat_UINT8, PayloadFormat_UINT16, PayloadFormat_UINT32, PayloadFormat_UINT64.
VRTException If the array length is shorter than offset+getPayloadLength().
void vrt::BasicDataPacket::getData (const PayloadFormat & pf, vector< char > & array, size_t offset, bool convert = true) const [inline]
Unpacks the data and returns it in a native byte buffer.
This is basically a byte-for-byte copy of the payload, except that a conversion is done from BIG_ENDIAN to the native byte ordering. This method is intended for use within existing programming frameworks that already provide type conversions. This method does not convert the values to byte data, only copies the data to what is effectively a void* buffer in the native byte order.
For 8-bit, 4-bit and 1-bit types, this is implemented as a fast array copy with no translation being done with regards to byte order. Further, with 4-bit and 1-bit types an assumption is made that the number of entries is an even multiple of one octet (i.e. 4-bit values must be in multiples of 2 and 1-bit values in multiples of 8).
Parameters:
pf The payload format to assume.
array The array to insert the data into.
offset The array offset.
convert Convert byte order to match native representation? Set this to false if it is necessary to keep the data in big-endian format.
Exceptions:
VRTException If the payload format is null or if the array is null.
VRTException If the payload format is anything other than PayloadFormat_INT4, PayloadFormat_INT8, PayloadFormat_INT16, PayloadFormat_INT32, PayloadFormat_INT64, PayloadFormat_FLOAT32, PayloadFormat_DOUBLE64 PayloadFormat_UINT1, PayloadFormat_UINT4, PayloadFormat_UINT8, PayloadFormat_UINT16, PayloadFormat_UINT32, PayloadFormat_UINT64.
VRTException If the array length is shorter than offset+getPayloadLength().
References vrt::BasicVRTPacket::getPayloadLength().
Referenced by getData().
vector<int8_t> vrt::BasicDataPacket::getDataByte () const [inline]
Unpacks the data and returns it as a byte array.
If the underlying data is not double, it will be converted to byte and any values that fall outside of the range of a byte will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataByte(p.getPayloadFormat())
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat().
Referenced by getDataByte().
int8_t* vrt::BasicDataPacket::getDataByte (int8_t * array) const [inline]
Unpacks the data and returns it as a byte array.
If the underlying data is not byte, it will be converted to byte and any values that fall outside of the range of a byte will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataDouble(p.getPayloadFormat())
Parameters:
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References getDataByte(), and getPayloadFormat().
vector<int8_t> vrt::BasicDataPacket::getDataByte (const PayloadFormat & pf) const [inline]
Unpacks the data and returns it as a byte array.
If the underlying data is not byte, it will be converted to byte and any values that fall outside of the range of a byte will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsByte().
int8_t* vrt::BasicDataPacket::getDataByte (const PayloadFormat & pf, int8_t * array) const [inline]
Unpacks the data and returns it as a byte array.
If the underlying data is not byte, it will be converted to byte and any values that fall outside of the range of a byte will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsByte().
vector<double> vrt::BasicDataPacket::getDataDouble () const [inline]
Unpacks the data and returns it as a double array.
If the underlying data is not double, it will be converted to double and any values that fall outside of the range of a double will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataDouble(p.getPayloadFormat())
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat().
Referenced by getDataDouble().
double* vrt::BasicDataPacket::getDataDouble (double * array) const [inline]
Unpacks the data and returns it as a double array.
If the underlying data is not double, it will be converted to double and any values that fall outside of the range of a double will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataDouble(p.getPayloadFormat())
Parameters:
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References getDataDouble(), and getPayloadFormat().
vector<double> vrt::BasicDataPacket::getDataDouble (const PayloadFormat & pf) const [inline]
Unpacks the data and returns it as a double array.
If the underlying data is not double, it will be converted to double and any values that fall outside of the range of a double will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsDouble().
double* vrt::BasicDataPacket::getDataDouble (const PayloadFormat & pf, double * array) const [inline]
Unpacks the data and returns it as a double array.
If the underlying data is not double, it will be converted to double and any values that fall outside of the range of a double will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
pf The payload format to assume.
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsDouble().
vector<float> vrt::BasicDataPacket::getDataFloat () const [inline]
Unpacks the data and returns it as a float array.
If the underlying data is not double, it will be converted to float and any values that fall outside of the range of a float will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataFloat(p.getPayloadFormat())
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat().
Referenced by getDataFloat().
float* vrt::BasicDataPacket::getDataFloat (float * array) const [inline]
Unpacks the data and returns it as a float array.
If the underlying data is not float, it will be converted to float and any values that fall outside of the range of a float will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataDouble(p.getPayloadFormat())
Parameters:
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References getDataFloat(), and getPayloadFormat().
vector<float> vrt::BasicDataPacket::getDataFloat (const PayloadFormat & pf) const [inline]
Unpacks the data and returns it as a float array.
If the underlying data is not float, it will be converted to float and any values that fall outside of the range of a float will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsFloat().
float* vrt::BasicDataPacket::getDataFloat (const PayloadFormat & pf, float * array) const [inline]
Unpacks the data and returns it as a float array.
If the underlying data is not float, it will be converted to float and any values that fall outside of the range of a float will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsFloat().
vector<int32_t> vrt::BasicDataPacket::getDataInt () const [inline]
Unpacks the data and returns it as a int array.
If the underlying data is not double, it will be converted to int and any values that fall outside of the range of a int will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataInt(p.getPayloadFormat())
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat().
Referenced by getDataInt().
int32_t* vrt::BasicDataPacket::getDataInt (int32_t * array) const [inline]
Unpacks the data and returns it as a int array.
If the underlying data is not int, it will be converted to int and any values that fall outside of the range of a int will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataDouble(p.getPayloadFormat())
Parameters:
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References getDataInt(), and getPayloadFormat().
vector<int32_t> vrt::BasicDataPacket::getDataInt (const PayloadFormat & pf) const [inline]
Unpacks the data and returns it as a int array.
If the underlying data is not int, it will be converted to int and any values that fall outside of the range of a int will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsInt().
int32_t* vrt::BasicDataPacket::getDataInt (const PayloadFormat & pf, int32_t * array) const [inline]
Unpacks the data and returns it as a int array.
If the underlying data is not int, it will be converted to int and any values that fall outside of the range of a int will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsInt().
int32_t vrt::BasicDataPacket::getDataLength (const PayloadFormat & pf, bool scalar) const [protected]
Gets the data length with option for scalar-only computation.
int32_t vrt::BasicDataPacket::getDataLength (const PayloadFormat & pf) const [inline]
Gets the length of the data in number of elements.
Unlike getPayloadLength() this returns the number of data elements, not bytes. For complex data the real and imaginary components of a single value count as a single element (see getScalarDataLength()).
Parameters:
pf The payload format to assume.
Returns:
The number of elements in the payload.
Exceptions:
VRTException If the payload format is null.
References getDataLength().
int32_t vrt::BasicDataPacket::getDataLength () const [inline]
Gets the length of the data in number of elements.
Unlike getPayloadLength() this returns the number of data elements, not bytes. For complex data the real and imaginary components of a single value count as a single element (see getScalarDataLength()).
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataLength(p.getPayloadFormat())
Returns:
The number of elements in the payload.
References getPayloadFormat().
Referenced by getDataLength(), and getScalarDataLength().
vector<int64_t> vrt::BasicDataPacket::getDataLong () const [inline]
Unpacks the data and returns it as a long array.
If the underlying data is not double, it will be converted to long and any values that fall outside of the range of a long will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataLong(p.getPayloadFormat())
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat().
Referenced by getDataLong().
int64_t* vrt::BasicDataPacket::getDataLong (int64_t * array) const [inline]
Unpacks the data and returns it as a long array.
If the underlying data is not long, it will be converted to long and any values that fall outside of the range of a long will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataDouble(p.getPayloadFormat())
Parameters:
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References getDataLong(), and getPayloadFormat().
vector<int64_t> vrt::BasicDataPacket::getDataLong (const PayloadFormat & pf) const [inline]
Unpacks the data and returns it as a long array.
If the underlying data is not long, it will be converted to long and any values that fall outside of the range of a long will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsLong().
int64_t* vrt::BasicDataPacket::getDataLong (const PayloadFormat & pf, int64_t * array) const [inline]
Unpacks the data and returns it as a long array.
If the underlying data is not long, it will be converted to long and any values that fall outside of the range of a long will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsLong().
vector<int16_t> vrt::BasicDataPacket::getDataShort () const [inline]
Unpacks the data and returns it as a byte array.
If the underlying data is not double, it will be converted to byte and any values that fall outside of the range of a byte will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataShort(p.getPayloadFormat())
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat().
Referenced by getDataShort().
int16_t* vrt::BasicDataPacket::getDataShort (int16_t * array) const [inline]
Unpacks the data and returns it as a short array.
If the underlying data is not short, it will be converted to short and any values that fall outside of the range of a short will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataDouble(p.getPayloadFormat())
Parameters:
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References getDataShort(), and getPayloadFormat().
vector<int16_t> vrt::BasicDataPacket::getDataShort (const PayloadFormat & pf) const [inline]
Unpacks the data and returns it as a short array.
If the underlying data is not short, it will be converted to short and any values that fall outside of the range of a short will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
Returns:
The data elements.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsShort().
int16_t* vrt::BasicDataPacket::getDataShort (const PayloadFormat & pf, int16_t * array) const [inline]
Unpacks the data and returns it as a short array.
If the underlying data is not short, it will be converted to short and any values that fall outside of the range of a short will will have unpredictable output. If the payload format is incorrectly specified, the output of this method will be useless.
Parameters:
pf The payload format to assume.
array The array to insert the data into (not null). The array must be sufficiently long for the number of elements in the packet (see getScalarDataLength(pf)).
Returns:
Pointer to 'buf'.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), getScalarDataLength(), and vrt::PackUnpack::unpackAsShort().
virtual Value* vrt::BasicDataPacket::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::NoDataPacket.
virtual int32_t vrt::BasicDataPacket::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::NoDataPacket.
virtual string vrt::BasicDataPacket::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::NoDataPacket.
virtual ValueType vrt::BasicDataPacket::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::NoDataPacket.
int32_t vrt::BasicDataPacket::getLostBytes (const TimeStamp & expected, double sampleRate) const [inline]
Computes the number of bytes lost between two packets.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataLength(p.getPayloadFormat())
Parameters:
expected The expected time stamp (predicted from by calling getNextTimeStamp(..) on the previous packet).
sampleRate The applicable sample rate.
Returns:
The number of lost bytes. This will be 0 if no bytes were lost and -N if there is an N byte overlap (i.e. extra data). The -N case is usually the result of an incorrect sample rate and/or incorrect payload format.
References getLostBytes(), and getPayloadFormat().
int32_t vrt::BasicDataPacket::getLostBytes (const TimeStamp & expected, double sampleRate, const PayloadFormat & pf) const [inline]
Computes the number of bytes lost between two packets.
Parameters:
expected The expected time stamp (predicted from by calling getNextTimeStamp(..) on the previous packet).
sampleRate The applicable sample rate.
pf The payload format to assume.
Returns:
The number of lost bytes. This will be 0 if no bytes were lost and -N if there is an N byte overlap (i.e. extra data). The -N case is usually the result of an incorrect sample rate and/or incorrect payload format.
References vrt::PayloadFormat::getDataItemSize(), and getLostSamples().
Referenced by getLostBytes().
int32_t vrt::BasicDataPacket::getLostSamples (const TimeStamp & expected, double sampleRate) const
Computes the number of samples lost between two packets.
Parameters:
expected The expected time stamp (predicted from by calling getNextTimeStamp(..) on the previous packet).
sampleRate The applicable sample rate.
Returns:
The number of lost samples. This will be 0 if no samples were lost and -N if there is an N sample overlap (i.e. extra data). The -N case is usually the result of an incorrect sample rate and/or incorrect payload format.
Referenced by getLostBytes().
TimeStamp vrt::BasicDataPacket::getNextTimeStamp (double sampleRate) const [inline]
Gets the next expected time stamp for a data packet on this stream.
This is computed as the following:
    nextTimeStamp = currentTimeStamp + (dataLength * sampleRate)
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataLength(p.getPayloadFormat())
Parameters:
sampleRate The applicable sample rate.
Returns:
The time stamp to expect for the next data packet.
References getNextTimeStamp(), and getPayloadFormat().
TimeStamp vrt::BasicDataPacket::getNextTimeStamp (double sampleRate, const PayloadFormat & pf) const
Gets the next expected time stamp for a data packet on this stream.
This is computed as the following:
    nextTimeStamp = currentTimeStamp + (dataLength * sampleRate)
Parameters:
sampleRate The applicable sample rate.
pf The payload format to assume.
Returns:
The time stamp to expect for the next data packet.
Exceptions:
VRTException If the payload format is null.
Referenced by getNextTimeStamp().
virtual string vrt::BasicDataPacket::getPacketValid (bool strict, int32_t length) const [virtual]
Checks to see if the packet is valid.
This is identical to isPacketValid(int32_t) except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No packet failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a packet.
length Verifies that the length of the packet matches this value.
Returns:
Empty string ("") if it is valid, a description of the error otherwise.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::StandardDataPacket, and vrt::NoDataPacket.
virtual PayloadFormat vrt::BasicDataPacket::getPayloadFormat () const [inline, virtual]
Gets the assumed payload format used when interacting with the data in this packet.
This setting can either be fixed based on the packet class or set via setPayloadFormat.
Returns:
The payload format to assume when interacting with this packet. This will return null if the payload format appears unspecified for this packet class and no call to setPayloadFormat has been made.
Reimplemented in vrt::StandardDataPacket.
Referenced by getData(), getDataByte(), getDataDouble(), getDataFloat(), getDataInt(), getDataLength(), getDataLong(), getDataShort(), getLostBytes(), getNextTimeStamp(), getScalarDataLength(), setData(), setDataByte(), setDataDouble(), setDataFloat(), setDataInt(), setDataLength(), setDataLong(), setDataShort(), and setScalarDataLength().
int32_t vrt::BasicDataPacket::getScalarDataLength (const PayloadFormat & pf) const [inline]
Utility method: Gets the length of the data in number of scalar elements.
Unlike getPayloadLength() this returns the number of data elements, not bytes. For complex data the real and imaginary components of a single value count as a two elements (see getDataLength()).
Parameters:
pf The payload format to assume.
Returns:
The number of elements in the payload.
Exceptions:
VRTException If the payload format is null.
References getDataLength().
int32_t vrt::BasicDataPacket::getScalarDataLength () const [inline]
Utility method: Gets the length of the data in number of scalar elements.
Unlike getPayloadLength() this returns the number of data elements, not bytes. For complex data the real and imaginary components of a single value count as a two elements (see getDataLength()).
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getScalarDataLength(p.getPayloadFormat())
Returns:
The number of elements in the payload.
References getDataLength(), and getPayloadFormat().
Referenced by getDataByte(), getDataDouble(), getDataFloat(), getDataInt(), getDataLong(), and getDataShort().
StartStopIndication vrt::BasicDataPacket::getStartStopIndication () const [inline]
Gets the Sample Frame StartStopIndication value.
Bits 11..10 and accompanying enable bits 23..22 are used together as the two-bit StartStopIndication for Data Packets using Sample Frames. The following values are possible: 00 StartStopIndication_NA 01 StartStopIndication_First 10 StartStopIndication_Middle 11 StartStopIndication_Final When either trailer is not present or enable bits are not set, StartStopIndication_NA is returned.
Returns:
StartStopIndication value if the enable bits are set, or StartStopIndication_NA if not.
References isBit10(), and isBit11().
int32_t vrt::BasicDataPacket::getTrailer () const [protected]
Gets the trailer as an integer.
Returns:
null if there is no trailer, an integer representing the trailer if there is.
boolNull vrt::BasicDataPacket::getTrailerBit (int32_t enable, int32_t indicator) const [protected]
Gets the specified bit from the trailer.
Parameters:
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
Returns:
null if there is no trailer, null if the enable bit is not set, true if the enable bit is set and the indicator bit is set, false if the enable bit is set but the indicator bit is not set.
Referenced by isAutomaticGainControl(), isBit10(), isBit11(), isBit8(), isBit9(), isCalibratedTimeStamp(), isDataValid(), isDiscontinuous(), isInvertedSpectrum(), isOverRange(), isReferenceLocked(), and isSignalDetected().
boolNull vrt::BasicDataPacket::isAutomaticGainControl () const [inline]
Gets the AGC/MGC indicator flag.
    true  = AGC (automatic gain control) is being used
    false = MGC (manual gain control) is being used
    null  = This information is not available
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References getTrailerBit().
boolNull vrt::BasicDataPacket::isBit10 () const [inline]
Gets the #10 user-defined indicator flag.
The definition of this flag should be included in the documentation for the relevant packet class (this flag should be identified there as "Enable Bit Position 22" and/or "Indicator Bit Position 10").
Returns:
true if the flag is set, false if it is not set, null if the flag isn't specified.
References getTrailerBit().
Referenced by getStartStopIndication().
boolNull vrt::BasicDataPacket::isBit11 () const [inline]
Gets the #11 user-defined indicator flag.
The definition of this flag should be included in the documentation for the relevant packet class (this flag should be identified there as "Enable Bit Position 23" and/or "Indicator Bit Position 11").
Returns:
true if the flag is set, false if it is not set, null if the flag isn't specified.
References getTrailerBit().
Referenced by getStartStopIndication().
boolNull vrt::BasicDataPacket::isBit8 () const [inline]
Gets the #8 user-defined indicator flag.
The definition of this flag should be included in the documentation for the relevant packet class (this flag should be identified there as "Enable Bit Position 20" and/or "Indicator Bit Position 8").
Returns:
true if the flag is set, false if it is not set, null if the flag isn't specified.
References getTrailerBit().
boolNull vrt::BasicDataPacket::isBit9 () const [inline]
Gets the #9 user-defined indicator flag.
The definition of this flag should be included in the documentation for the relevant packet class (this flag should be identified there as "Enable Bit Position 21" and/or "Indicator Bit Position 9").
Returns:
true if the flag is set, false if it is not set, null if the flag isn't specified.
References getTrailerBit().
boolNull vrt::BasicDataPacket::isCalibratedTimeStamp () const [inline]
Gets the calibrated time indicator flag.
    true  = The time stamp in this packet is calibrated to an external reference (e.g. atomic clock)
    false = The time stamp in this packet is *not* calibrated to an external reference
            and may be inaccurate
    null  = This information is not available
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References getTrailerBit().
boolNull vrt::BasicDataPacket::isDataValid () const [inline]
Gets the valid data indicator flag.
    true  = The data in the packet is valid
    false = A condition exists that *may* invalidate some or all of the data in the packet
    null  = This information is not available
Note that the definition of "valid" and "invalid" data is application specific, so it is important to consult the documentation for the relevant packet class before using this field.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References getTrailerBit().
boolNull vrt::BasicDataPacket::isDiscontinuious () const [inline]
Deprecated: Please change to using isDiscontinuous.
References isDiscontinuous().
boolNull vrt::BasicDataPacket::isDiscontinuous () const [inline]
Gets the sample loss indicator flag.
    true  = One or more sample discontinuities present in the data due to processing errors
            and/or data overflow
    false = No discontinuities present
    null  = This information is not available
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References getTrailerBit().
Referenced by isDiscontinuious().
boolNull vrt::BasicDataPacket::isInvertedSpectrum () const [inline]
Gets the spectral inversion indicator flag.
    true  = Signal conveyed in the payload has an inverted spectrum w.r.t. an up-stream
            reference point
    false = Spectrum is not inverted
    null  = This information is not available
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References getTrailerBit().
boolNull vrt::BasicDataPacket::isOverRange () const [inline]
Gets the over-range indicator flag.
    true  = The data in the payload is invalid since one or more data samples exceeded the
            range of the data item
    false = No samples over range
    null  = This information is not available
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References getTrailerBit().
boolNull vrt::BasicDataPacket::isReferenceLocked () const [inline]
Gets the reference lock indicator flag.
    true  = All of the phase-locked loops affecting the data are locked and stable
    false = At least one of the phase-locked loops affecting the data is not locked and stable
    null  = This information is not available
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References getTrailerBit().
boolNull vrt::BasicDataPacket::isSignalDetected () const [inline]
Gets the signal detected indicator flag.
    true  = Some signal detected in this packet
    false = No signal detected in this packet
    null  = This information is not available
Note that the definition of what constitutes a detected signal application specific, so it is important to conslut the documentation for the relevant packet class before using this field.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References getTrailerBit().
void vrt::BasicDataPacket::setAssocPacketCount (int8_t v)
Optional functionality: Gets the associated packet count.
This indicates the number of context packets with context change or event information relevant to this data packet.
Parameters:
v The associated packet count (0..127), or null if not specified.
Exceptions:
VRTException If this method is not supported.
void vrt::BasicDataPacket::setAutomaticGainControl (boolNull v) [inline]
Optional functionality: Gets the AGC/MGC indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
void vrt::BasicDataPacket::setBit10 (boolNull v) [inline]
Optional functionality: Gets the #10 user-defined indicator flag.
Parameters:
v true if the flag is set, false if not set, null if the flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
Referenced by setStartStopIndication(), and unsetStartStopIndication().
void vrt::BasicDataPacket::setBit11 (boolNull v) [inline]
Optional functionality: Gets the #11 user-defined indicator flag.
Parameters:
v true if the flag is set, false if not set, null if the flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
Referenced by setStartStopIndication(), and unsetStartStopIndication().
void vrt::BasicDataPacket::setBit8 (boolNull v) [inline]
Optional functionality: Gets the #8 user-defined indicator flag.
Parameters:
v true if the flag is set, false if not set, null if the flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
void vrt::BasicDataPacket::setBit9 (boolNull v) [inline]
Optional functionality: Gets the #9 user-defined indicator flag.
Parameters:
v true if the flag is set, false if not set, null if the flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
void vrt::BasicDataPacket::setCalibratedTimeStamp (boolNull v) [inline]
Optional functionality: Sets the calibrated time indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
void vrt::BasicDataPacket::setData (const void * array, int32_t length, bool convert = true) [inline]
Packs the data from a native byte buffer.
This is basically a byte-for-byte copy of the payload, except that a conversion is done from the native to BIG_ENDIAN byte ordering. This method is intended for use within existing programming frameworks that already provide type conversions. This method does not convert the values from byte data, only copies the data from what is effectively a void* buffer in the native byte order.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setData(p.getPayloadFormat(),array,offset,length)
Parameters:
array The array to insert the data into.
length The number of bytes to pack (must be a multiple of 8 for PayloadFormat_INT64 or PayloadFormat_DOUBLE64 or a multiple of 4 for all others).
convert Convert byte order to match native representation? Set this to false if it is necessary to keep the data in big-endian format.
Exceptions:
VRTException If the payload format is null or if the array is null.
VRTException If the payload format is anything other than
VRTException If the payload format is anything other than PayloadFormat_INT4, PayloadFormat_INT8, PayloadFormat_INT16, PayloadFormat_INT32, PayloadFormat_INT64, PayloadFormat_FLOAT32, PayloadFormat_DOUBLE64 PayloadFormat_UINT1, PayloadFormat_UINT4, PayloadFormat_UINT8, PayloadFormat_UINT16, PayloadFormat_UINT32, PayloadFormat_UINT64.
VRTException If the array length is shorter than offset+getPayloadLength().
VRTException If the length is invalid.
References getPayloadFormat(), and setData().
void vrt::BasicDataPacket::setData (const vector< char > & array, size_t offset, int32_t length, bool convert = true) [inline]
Packs the data from a native byte buffer.
This is basically a byte-for-byte copy of the payload, except that a conversion is done from the native to BIG_ENDIAN byte ordering. This method is intended for use within existing programming frameworks that already provide type conversions. This method does not convert the values from byte data, only copies the data from what is effectively a void* buffer in the native byte order.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setData(p.getPayloadFormat(),array,offset,length)
Parameters:
array The array to insert the data into.
offset The array offset.
length The number of bytes to pack (must be a multiple of 8 for PayloadFormat_INT64 or PayloadFormat_DOUBLE64 or a multiple of 4 for all others).
convert Convert byte order to match native representation? Set this to false if it is necessary to keep the data in big-endian format.
Exceptions:
VRTException If the payload format is null or if the array is null.
VRTException If the payload format is anything other than PayloadFormat_INT4, PayloadFormat_INT8, PayloadFormat_INT16, PayloadFormat_INT32, PayloadFormat_INT64, PayloadFormat_FLOAT32, PayloadFormat_DOUBLE64 PayloadFormat_UINT1, PayloadFormat_UINT4, PayloadFormat_UINT8, PayloadFormat_UINT16, PayloadFormat_UINT32, PayloadFormat_UINT64.
VRTException If the array length is shorter than offset+getPayloadLength().
VRTException If the length is invalid.
References getPayloadFormat(), and setData().
void vrt::BasicDataPacket::setData (const PayloadFormat & pf, const void * array, int32_t length, bool convert = true)
Packs the data from a native byte buffer.
This is basically a byte-for-byte copy of the payload, except that a conversion is done from the native to BIG_ENDIAN byte ordering. This method is intended for use within existing programming frameworks that already provide type conversions. This method does not convert the values from byte data, only copies the data from what is effectively a void* buffer in the native byte order.
Parameters:
pf The payload format to assume.
array The array to insert the data into.
length The number of bytes to pack (must be a multiple of 8 for PayloadFormat_INT64 or PayloadFormat_DOUBLE64 or a multiple of 4 for all others).
convert Convert byte order to match native representation? Set this to false if it is necessary to keep the data in big-endian format.
Exceptions:
VRTException If the payload format is null or if the array is null.
VRTException If the payload format is anything other than PayloadFormat_INT4, PayloadFormat_INT8, PayloadFormat_INT16, PayloadFormat_INT32, PayloadFormat_INT64, PayloadFormat_FLOAT32, PayloadFormat_DOUBLE64 PayloadFormat_UINT1, PayloadFormat_UINT4, PayloadFormat_UINT8, PayloadFormat_UINT16, PayloadFormat_UINT32, PayloadFormat_UINT64.
VRTException If the length is invalid.
void vrt::BasicDataPacket::setData (const PayloadFormat & pf, const vector< char > & array, size_t offset, int32_t length, bool convert = true) [inline]
Packs the data from a native byte buffer.
This is basically a byte-for-byte copy of the payload, except that a conversion is done from the native to BIG_ENDIAN byte ordering. This method is intended for use within existing programming frameworks that already provide type conversions. This method does not convert the values from byte data, only copies the data from what is effectively a void* buffer in the native byte order.
Parameters:
pf The payload format to assume.
array The array to insert the data into.
offset The array offset.
length The number of bytes to pack (must be a multiple of 8 for PayloadFormat_INT64 or PayloadFormat_DOUBLE64 or a multiple of 4 for all others).
convert Convert byte order to match native representation? Set this to false if it is necessary to keep the data in big-endian format.
Exceptions:
VRTException If the payload format is null or if the array is null.
VRTException If the payload format is anything other than PayloadFormat_INT4, PayloadFormat_INT8, PayloadFormat_INT16, PayloadFormat_INT32, PayloadFormat_INT64, PayloadFormat_FLOAT32, PayloadFormat_DOUBLE64 PayloadFormat_UINT1, PayloadFormat_UINT4, PayloadFormat_UINT8, PayloadFormat_UINT16, PayloadFormat_UINT32, PayloadFormat_UINT64.
VRTException If the array length is shorter than offset+getPayloadLength().
VRTException If the length is invalid.
References vrt::BasicVRTPacket::getPayloadLength().
Referenced by setData().
void vrt::BasicDataPacket::setDataByte (const vector< int8_t > & array) [inline]
Packs the data using the values from a byte array.
If the underlying data is not byte, it will be converted from byte and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataByte(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataByte().
void vrt::BasicDataPacket::setDataByte (const int8_t * array, size_t len) [inline]
Packs the data using the values from a byte array.
If the underlying data is not byte, it will be converted from byte and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataByte(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataByte().
void vrt::BasicDataPacket::setDataByte (const PayloadFormat & pf, const vector< int8_t > & array) [inline]
Packs the data using the values from a byte array.
If the underlying data is not byte, it will be converted from byte and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsByte(), and setScalarDataLength().
void vrt::BasicDataPacket::setDataByte (const PayloadFormat & pf, const int8_t * array, size_t len) [inline]
Packs the data using the values from a byte array.
If the underlying data is not byte, it will be converted from byte and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsByte(), and setScalarDataLength().
Referenced by setDataByte().
void vrt::BasicDataPacket::setDataDouble (const vector< double > & array) [inline]
Packs the data using the values from a double array.
If the underlying data is not double, it will be converted from double and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataDouble(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataDouble().
void vrt::BasicDataPacket::setDataDouble (const double * array, size_t len) [inline]
Packs the data using the values from a double array.
If the underlying data is not double, it will be converted from double and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataByte(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataDouble().
void vrt::BasicDataPacket::setDataDouble (const PayloadFormat & pf, const vector< double > & array) [inline]
Packs the data using the values from a double array.
If the underlying data is not double, it will be converted from double and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsDouble(), and setScalarDataLength().
void vrt::BasicDataPacket::setDataDouble (const PayloadFormat & pf, const double * array, size_t len) [inline]
Packs the data using the values from a double array.
If the underlying data is not double, it will be converted from double and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsDouble(), and setScalarDataLength().
Referenced by setDataDouble().
void vrt::BasicDataPacket::setDataFloat (const vector< float > & array) [inline]
Packs the data using the values from a float array.
If the underlying data is not float, it will be converted from float and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataFloat(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataFloat().
void vrt::BasicDataPacket::setDataFloat (const float * array, size_t len) [inline]
Packs the data using the values from a float array.
If the underlying data is not float, it will be converted from float and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataByte(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataFloat().
void vrt::BasicDataPacket::setDataFloat (const PayloadFormat & pf, const vector< float > & array) [inline]
Packs the data using the values from a float array.
If the underlying data is not float, it will be converted from float and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsFloat(), and setScalarDataLength().
void vrt::BasicDataPacket::setDataFloat (const PayloadFormat & pf, const float * array, size_t len) [inline]
Packs the data using the values from a float array.
If the underlying data is not float, it will be converted from float and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsFloat(), and setScalarDataLength().
Referenced by setDataFloat().
void vrt::BasicDataPacket::setDataInt (const vector< int32_t > & array) [inline]
Packs the data using the values from a int array.
If the underlying data is not int, it will be converted from int and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataInt(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataInt().
void vrt::BasicDataPacket::setDataInt (const int32_t * array, size_t len) [inline]
Packs the data using the values from a int array.
If the underlying data is not int, it will be converted from int and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataByte(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataInt().
void vrt::BasicDataPacket::setDataInt (const PayloadFormat & pf, const vector< int32_t > & array) [inline]
Packs the data using the values from a int array.
If the underlying data is not int, it will be converted from int and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsInt(), and setScalarDataLength().
void vrt::BasicDataPacket::setDataInt (const PayloadFormat & pf, const int32_t * array, size_t len) [inline]
Packs the data using the values from a int array.
If the underlying data is not int, it will be converted from int and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsInt(), and setScalarDataLength().
Referenced by setDataInt().
void vrt::BasicDataPacket::setDataLength (const PayloadFormat & pf, int32_t length, bool scalar) [protected]
Sets the data length with option for scalar-only computation.
void vrt::BasicDataPacket::setDataLength (const PayloadFormat & pf, int32_t length) [inline]
Sets the length of the data in number of elements.
Unlike setPayloadLength(..) this sets the number of data elements, not bytes. For complex data the real and imaginary components of a single value count as a single element (see getScalarDataLength()).
Parameters:
pf The payload format to assume.
length The number of elements in the payload.
Exceptions:
VRTException If the payload format is null.
References setDataLength().
void vrt::BasicDataPacket::setDataLength (int32_t length) [inline]
Sets the length of the data in number of elements.
Unlike setPayloadLength(..) this sets the number of data elements, not bytes. For complex data the real and imaginary components of a single value count as a single element (see getScalarDataLength()).
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getDataLength(p.getPayloadFormat())
Parameters:
length The number of elements in the payload.
References getPayloadFormat().
Referenced by setDataLength(), and setScalarDataLength().
void vrt::BasicDataPacket::setDataLong (const vector< int64_t > & array) [inline]
Packs the data using the values from a long array.
If the underlying data is not long, it will be converted from long and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataLong(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataLong().
void vrt::BasicDataPacket::setDataLong (const int64_t * array, size_t len) [inline]
Packs the data using the values from a long array.
If the underlying data is not long, it will be converted from long and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataByte(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataLong().
void vrt::BasicDataPacket::setDataLong (const PayloadFormat & pf, const vector< int64_t > & array) [inline]
Packs the data using the values from a long array.
If the underlying data is not long, it will be converted from long and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsLong(), and setScalarDataLength().
void vrt::BasicDataPacket::setDataLong (const PayloadFormat & pf, const int64_t * array, size_t len) [inline]
Packs the data using the values from a long array.
If the underlying data is not long, it will be converted from long and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsLong(), and setScalarDataLength().
Referenced by setDataLong().
void vrt::BasicDataPacket::setDataShort (const vector< int16_t > & array) [inline]
Packs the data using the values from a short array.
If the underlying data is not short, it will be converted from short and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataShort(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataShort().
void vrt::BasicDataPacket::setDataShort (const int16_t * array, size_t len) [inline]
Packs the data using the values from a short array.
If the underlying data is not short, it will be converted from short and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.setDataByte(p.getPayloadFormat(),array)
Parameters:
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References getPayloadFormat(), and setDataShort().
void vrt::BasicDataPacket::setDataShort (const PayloadFormat & pf, const vector< int16_t > & array) [inline]
Packs the data using the values from a short array.
If the underlying data is not short, it will be converted from short and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsShort(), and setScalarDataLength().
void vrt::BasicDataPacket::setDataShort (const PayloadFormat & pf, const int16_t * array, size_t len) [inline]
Packs the data using the values from a short array.
If the underlying data is not short, it will be converted from short and any values that fall outside of the range of a of the payload format will have unpredictable output. This method also has the effect of setting the size of the data (see setDataLength) and indirectly the payload and packet.
Parameters:
pf The payload format to assume.
array The values to insert.
len The length of the array (in number of scalar values).
Exceptions:
VRTException If the payload format is null.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), vrt::PackUnpack::packAsShort(), and setScalarDataLength().
Referenced by setDataShort().
void vrt::BasicDataPacket::setDataValid (boolNull v) [inline]
Optional functionality: Gets the valid data indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
void vrt::BasicDataPacket::setDiscontinuious (boolNull v) [inline]
Deprecated: Please change to using setDiscontinuous.
References setDiscontinuous().
void vrt::BasicDataPacket::setDiscontinuous (boolNull v) [inline]
Optional functionality: Gets the sample loss indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
Referenced by setDiscontinuious().
virtual void vrt::BasicDataPacket::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::NoDataPacket.
void vrt::BasicDataPacket::setInvertedSpectrum (boolNull v) [inline]
Optional functionality: Gets the spectral inversion indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
void vrt::BasicDataPacket::setOverRange (boolNull v) [inline]
Optional functionality: Gets the over-range indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
void vrt::BasicDataPacket::setPacketType (PacketType t) [inline, virtual]
Optional functionality: Sets the packet type.
Parameters:
t The packet type.
Exceptions:
VRTException If this method is not supported.
Reimplemented from vrt::BasicVRTPacket.
virtual void vrt::BasicDataPacket::setPayloadFormat (const PayloadFormat & pf) [inline, virtual]
Optional Functionality: Sets the payload format to be assumed when interacting with the data in this packet.
Note that this setting exists only for the lifetime of this object and is not directly stored within the data packet.
Many data packet classes use a fixed payload format (see getPayloadFormat()) and will throw an exception if this method is called.
Parameters:
pf The payload format to assume.
Exceptions:
VRTException If setting the payload format is unsupported.
Reimplemented in vrt::StandardDataPacket.
void vrt::BasicDataPacket::setReferenceLocked (boolNull v) [inline]
Optional functionality: Gets the reference lock indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
void vrt::BasicDataPacket::setScalarDataLength (PayloadFormat pf, int32_t length) [inline]
Utility method: Sets the length of the data in number of scalar elements.
Unlike setPayloadLength(..) this sets the number of data elements, not bytes. For complex data the real and imaginary components of a single value count as a two elements (see setDataLength(..).
Parameters:
pf The payload format to assume.
length The number of elements in the payload.
Exceptions:
NullPointerException If the payload format is null.
References setDataLength().
void vrt::BasicDataPacket::setScalarDataLength (int32_t length) [inline]
Utility method: Sets the length of the data in number of scalar elements.
Unlike setPayloadLength(..) this sets the number of data elements, not bytes. For complex data the real and imaginary components of a single value count as a two elements (see setDataLength(..).
This method can only be used AFTER a payload format for the packet has been specified (see getPayloadFormat(). This method is identical to calling p.getScalarDataLength(p.getPayloadFormat())
Parameters:
length The number of elements in the payload.
References getPayloadFormat(), and setDataLength().
Referenced by setDataByte(), setDataDouble(), setDataFloat(), setDataInt(), setDataLong(), and setDataShort().
void vrt::BasicDataPacket::setSignalDetected (boolNull v) [inline]
Optional functionality: Gets the signal detected indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
Exceptions:
VRTException If this method is not supported.
References setTrailerBit().
void vrt::BasicDataPacket::setStartStopIndication (StartStopIndication v) [inline]
Optional functionality: Sets the Sample Frame Start Stop Indication value.
Bits 11..10 and accompanying enable bits 23..22 are used together as the two-bit StartStopIndication for Data Packets using Sample Frames. The following values are possible: 00 StartStopIndication_NA 01 StartStopIndication_First 10 StartStopIndication_Middle 11 StartStopIndication_Final
Parameters:
v StartStopIndication value to set.
Exceptions:
VRTException If this method is not supported.
References setBit10(), and setBit11().
virtual void vrt::BasicDataPacket::setTrailerBit (int32_t enable, int32_t indicator, boolNull value) [protected, virtual]
Optional functionality: Sets the specified bit from the trailer.
Parameters:
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
value The value of the bits: null if the enable bit should not be set, true if the enable bit and the indicator bit should be set, false if the enable bit should be set but the indicator bit should not be set.
Referenced by setAutomaticGainControl(), setBit10(), setBit11(), setBit8(), setBit9(), setCalibratedTimeStamp(), setDataValid(), setDiscontinuous(), setInvertedSpectrum(), setOverRange(), setReferenceLocked(), and setSignalDetected().
virtual void vrt::BasicDataPacket::toStringStream (ostringstream & str) const [protected, virtual]
Writes the packet content to a string stream in a user-friendly format.
Parameters:
str The string stream to write to.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::StandardDataPacket, and vrt::NoDataPacket.
void vrt::BasicDataPacket::unsetStartStopIndication () [inline]
Optional functionality: Unsets the Sample Frame Start Stop Indication enable bits.
See setStartStopIndication.
Exceptions:
VRTException If this method is not supported.
References setBit10(), and setBit11().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/BasicDataPacket.h