VRT: vrt::Ephemeris Class Reference
vrt::Ephemeris Class Reference
Represents an ECEF ephemeris fix.
#include <IndicatorFields.h>
Public Member Functions
Ephemeris (const Ephemeris &r)
Basic copy constructor.
Ephemeris ()
Creates a new instance.
double getAttitudeAlpha () const
Gets the attitude about the Z-axis in degrees.
double getAttitudeBeta () const
Gets the attitude about the Y-axis in degrees.
double getAttitudePhi () const
Gets the attitude about the X-axis in degrees.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
double getPositionX () const
Gets the position along the X-axis in meters.
double getPositionY () const
Gets the position along the Y-axis in meters.
double getPositionZ () const
Gets the position along the Z-axis in meters.
double getVelocityX () const
Gets the velocity along the X-axis in meters per second.
double getVelocityY () const
Gets the velocity along the Y-axis in meters per second.
double getVelocityZ () const
Gets the velocity along the Z-axis in meters per second.
void setAttitudeAlpha (double val)
Sets the attitude about the Z-axis in degrees.
void setAttitudeBeta (double val)
Sets the attitude about the Y-axis in degrees.
void setAttitudePhi (double val)
Sets the attitude about the X-axis in degrees.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setPositionX (double val)
Sets the position along the X-axis in meters.
void setPositionY (double val)
Sets the position along the Y-axis in meters.
void setPositionZ (double val)
Sets the position along the Z-axis in meters.
void setTimeStamp (const TimeStamp &ts)
Sets the time stamp for the geolocation fix.
void setVelocityX (double val)
Sets the velocity along the X-axis in meters per second.
void setVelocityY (double val)
Sets the velocity along the Y-axis in meters per second.
void setVelocityZ (double val)
Sets the velocity along the Z-axis in meters per second.
virtual string toString () const
Gets a basic description of the object, useful for debugging.
Detailed Description
Represents an ECEF ephemeris fix.
See also:
Geolocation
Constructor & Destructor Documentation
vrt::Ephemeris::Ephemeris ()
Creates a new instance.
vrt::Ephemeris::Ephemeris (const Ephemeris & r)
Basic copy constructor.
Member Function Documentation
double vrt::Ephemeris::getAttitudeAlpha () const [inline]
Gets the attitude about the Z-axis in degrees.
Returns:
The value of null if not specified.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Ephemeris::getAttitudeBeta () const [inline]
Gets the attitude about the Y-axis in degrees.
Returns:
The value of null if not specified.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Ephemeris::getAttitudePhi () const [inline]
Gets the attitude about the X-axis in degrees.
Returns:
The value of null if not specified.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
virtual Value* vrt::Ephemeris::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::AbstractGeolocation.
virtual int32_t vrt::Ephemeris::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::AbstractGeolocation.
virtual string vrt::Ephemeris::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::AbstractGeolocation.
virtual ValueType vrt::Ephemeris::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::AbstractGeolocation.
double vrt::Ephemeris::getPositionX () const [inline]
Gets the position along the X-axis in meters.
Returns:
The value of null if not specified.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Ephemeris::getPositionY () const [inline]
Gets the position along the Y-axis in meters.
Returns:
The value of null if not specified.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Ephemeris::getPositionZ () const [inline]
Gets the position along the Z-axis in meters.
Returns:
The value of null if not specified.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Ephemeris::getVelocityX () const [inline]
Gets the velocity along the X-axis in meters per second.
Returns:
The value of null if not specified.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Ephemeris::getVelocityY () const [inline]
Gets the velocity along the Y-axis in meters per second.
Returns:
The value of null if not specified.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Ephemeris::getVelocityZ () const [inline]
Gets the velocity along the Z-axis in meters per second.
Returns:
The value of null if not specified.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
void vrt::Ephemeris::setAttitudeAlpha (double val) [inline]
Sets the attitude about the Z-axis in degrees.
Parameters:
val The value or null if not specified.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Ephemeris::setAttitudeBeta (double val) [inline]
Sets the attitude about the Y-axis in degrees.
Parameters:
val The value or null if not specified.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Ephemeris::setAttitudePhi (double val) [inline]
Sets the attitude about the X-axis in degrees.
Parameters:
val The value or null if not specified.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
virtual void vrt::Ephemeris::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::AbstractGeolocation.
void vrt::Ephemeris::setPositionX (double val) [inline]
Sets the position along the X-axis in meters.
Parameters:
val The value or null if not specified.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Ephemeris::setPositionY (double val) [inline]
Sets the position along the Y-axis in meters.
Parameters:
val The value or null if not specified.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Ephemeris::setPositionZ (double val) [inline]
Sets the position along the Z-axis in meters.
Parameters:
val The value or null if not specified.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Ephemeris::setTimeStamp (const TimeStamp & ts) [inline, virtual]
Sets the time stamp for the geolocation fix.
Parameters:
ts The time stamp for the geolocation fix.
Reimplemented from vrt::AbstractGeolocation.
void vrt::Ephemeris::setVelocityX (double val) [inline]
Sets the velocity along the X-axis in meters per second.
Parameters:
val The value or null if not specified.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Ephemeris::setVelocityY (double val) [inline]
Sets the velocity along the Y-axis in meters per second.
Parameters:
val The value or null if not specified.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Ephemeris::setVelocityZ (double val) [inline]
Sets the velocity along the Z-axis in meters per second.
Parameters:
val The value or null if not specified.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
virtual string vrt::Ephemeris::toString () const [virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::AbstractGeolocation.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/IndicatorFields.h