VRT: vrt::StandardDataPacket Class Reference
vrt::StandardDataPacket Class Reference
Represents a standard data packet.
#include <StandardDataPacket.h>
Public Member Functions
StandardDataPacket (const PayloadFormat &format)
Creates a new instance that can be written to.
StandardDataPacket (DataType type=DataType_Int8, RealComplexType realComplex=RealComplexType_Real, int32_t frameSize=0)
Creates a new instance that can be written to.
StandardDataPacket (const vector< char > &buf, bool readonly)
Creates a new instance accessing the given data buffer.
StandardDataPacket (const BasicDataPacket &p)
Basic copy constructor for the class.
StandardDataPacket (const int32_t pktsize)
~StandardDataPacket ()
Basic destructor for the class.
DataType getDataType () const
Gets the data type used.
int32_t getFrameSize () const
Gets the frame size used.
virtual string getPacketValid (bool strict, int32_t length) const
Checks to see if the packet is valid.
virtual PayloadFormat getPayloadFormat () const
Gets the assumed payload format used when interacting with the data in this packet.
RealComplexType getRealComplexType () const
Gets the real/complex type used.
virtual void setPayloadFormat (DataType type, RealComplexType realComplex, int32_t frameSize)
Sets the payload format and class ID.
virtual void setPayloadFormat (const PayloadFormat &pf)
Optional Functionality: Sets the payload format to be assumed when interacting with the data in this packet.
Static Public Member Functions
static bool isStandardDataPacket (int64_t id)
Does the ID match that of a StandardDataPacket?
Static Public Attributes
static const int64_t CLASS_ID_CHECK = __INT64_C(0xFFFFFA00000000)
See CLASS_ID_MASK
static const int64_t CLASS_ID_MASK = __INT64_C(0xFFFFFFFF000000)
Mask and check value used for determining if a given class ID matches one used for a StandardDataPacket.
Protected Member Functions
virtual void toStringStream (ostringstream &str) const
Writes the packet content to a string stream in a user-friendly format.
Detailed Description
Represents a standard data packet.
Overview
The "standard data packet" defines a specific set of Class Identifiers that can be used with IF Data and Extension Data packets. Rather than enumerate all possible Class Identifiers that can be used, an algorithmic approach is taken to assign them (this algorithm should be apparent from the diagrams shown below). All of the Class Identifiers will be in the range of FF-FF-FA:0000.0000 to FF-FF-FA:00FF.FFFF.
Note that although much of the information in the algorithm derives from information contained in the paired IF Context packet (especially the Data Packet Payload Field), this is not intended to be a substitute for the proper use of the fields in the paired IF Context packet.
The StandardDataPacket shall only be used with data packets that meet all of the following criteria (see VRT section 7.1.5.18):
Contain "Real" or "Complex, Cartesian" values;
Contain 4-/8-/16-/32-/64-bit Signed Fixed Point, 1-/4-/8-/16-/32-/64-bit Unsigned Fixed Point, 32-bit IEEE-754 Single-Precision Floating-Point, or 64-bit IEEE-754 Double-Precision Floating-Point values;
Have an Event-Tag Size of zero;
Have an Channel-Tag Size of zero;
Have an Item Packing Field Size equal to the Data Item Size; and
Have a Repeat Count of 1.
  +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
  |31|30|29|28|27|26|25|24|23|22|21|20|19|18|17|16|15|14|13|12|11|10| 9| 8| 7| 6| 5| 4| 3| 2| 1| 0|
  +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
  |        Reserved       |                         FF-FF-FA                                      |
  +-----------------------+-----+-----+-----------+-----------------------------------------------+
  | 0  0  0  0  0  0  0  0| Res | R/C | Data Type |               Vector Size                     |
  +-----------------------+-----+-----+-----------+-----------------------------------------------+
                   Organization of the StandardDataPacket Class Identifier
              +--------+-------------------------------------------+-----------+
              |  Bit   |               Field                       |Field Width|
              |Position|            Description                    |  (bits)   |
              +--------+-------------------------------------------+-----------+
              | 24..31 | Fixed Value (binary 0000 0000)            |     8     |
              +--------+-------------------------------------------+-----------+
              | 22..23 | Reserved    (binary 00)                   |     2     |
              +--------+-------------------------------------------+-----------+
              | 20..21 | Real/Complex Indicator:                   |     1     |
              |        |     00 = Real                             |           |
              |        |     01 = Complex, Cartesian               |           |
              |        |     10 = Reserved                         |           |
              |        |     11 = Reserved                         |           |
              |        |   (This mirrors VRT Rule 7.1.5.18-3.)     |           |
              +--------+-------------------------------------------+-----------+
              | 16..19 | Data Type:                                |     4     |
              |        |   0000 = Reserved                         |           |
              |        |   0001 =  4-bit Signed Fixed Point        |           |
              |        |   0010 =  8-bit Signed Fixed Point        |           |
              |        |   0011 = 16-bit Signed Fixed Point        |           |
              |        |   0100 = 32-bit Signed Fixed Point        |           |
              |        |   0101 = 64-bit Signed Fixed Point        |           |
              |        |   0110 = 32-bit IEEE-754 Single-Precision |           |
              |        |   0111 = 64-bit IEEE-754 Double-Precision |           |
              |        |   1000 =  1-bit Unsigned Fixed Point      |           |
              |        |   1001 =  4-bit Unsigned Fixed Point      |           |
              |        |   1010 =  8-bit Unsigned Fixed Point      |           |
              |        |   1011 = 16-bit Unsigned Fixed Point      |           |
              |        |   1100 = 32-bit Unsigned Fixed Point      |           |
              |        |   1101 = 64-bit Unsigned Fixed Point      |           |
              |        |   1110 = Reserved                         |           |
              |        |   1111 = Reserved                         |           |
              +--------+-------------------------------------------+-----------+
              |  0..15 | Vector Size:                              |    16     |
              |        |    An unsigned number that is one less    |           |
              |        |    than the actual Vector size. (This     |           |
              |        |    mirrors VRT Rule 7.1.5.18-11.)         |           |
              +--------+-------------------------------------------+-----------+
              Location of Parameter Fields in the Second Class Identifier Word
Permission
The authors of this library give permission for the above text and diagrams to be incorporated into other standards and documentation, provided that no substantive changes are made thereto and the authors are clearly identified.
History
The idea of the "standard data packet" originated with this library in early 2011. At the time the OUI of "FF-FF-00" the was used (this was arbitrarily chosen based on suggestions from the VITA-49.0b suggestions) and the exact layout of the bits differed slightly from what is used today. There was also a notion for using the user-defined bits in the trailer to indicate the number of pad bits (this concept later worked its way into the VITA-49.0b suggestions).
After some "beta testing" and discussions with a number of users it was decided to make some changes, with the agreement that other users would then adopt the "StandardDataPacket" as a (pseudo-)standard. The change from "FF-FF-00" to "FF-FF-FA" was done to avoid conflict with other users. Some users have given special meaning to the "A" in at the end of the "FF-FF-FA" OUI; the authors of this library is aware of this and views it as "convenient" but neither endorses nor denounces this use.
Future
Although there are no plans to make changes at this time, there are two bits ("Res" in the top diagram) that could be used and a number of additional data types and real/complex indicators available. However, the "Fixed Value" bits are permanently fixed at zero as some users have already been using other parts of the "FF-FF-FA" for other uses.
Constructor & Destructor Documentation
vrt::StandardDataPacket::~StandardDataPacket () [inline]
Basic destructor for the class.
vrt::StandardDataPacket::StandardDataPacket (const BasicDataPacket & p) [inline]
Basic copy constructor for the class.
vrt::StandardDataPacket::StandardDataPacket (const vector< char > & buf, bool readonly) [inline]
Creates a new instance accessing the given data buffer.
Note that when the buffer lengths are given, only the most minimal of error checking is done. Users should call isPacketValid() to verify that the packet is valid. Invalid packets can result unpredictable behavior, but this is explicitly allowed (to the extent possible) so that applications creating packets can use this class even if the packet isn't yet "valid".
Parameters:
buf The data buffer to use.
readonly Should users of this instance be able to modify the underlying data buffer?
vrt::StandardDataPacket::StandardDataPacket (DataType type = DataType_Int8, RealComplexType realComplex = RealComplexType_Real, int32_t frameSize = 0) [inline]
Creates a new instance that can be written to.
Parameters:
type The numeric type (one of: Int4, Int8, Int16, Int32, Int64, Float, Double, etc.).
realComplex Real/Complex mode (one of: Real, ComplexCartesian).
frameSize Frame size, must be a multiple of 256 or 0/1 to indicate that the data is not framed.
Exceptions:
VRTException if an invalid value is passed in.
References setPayloadFormat().
vrt::StandardDataPacket::StandardDataPacket (const PayloadFormat & format) [inline]
Creates a new instance that can be written to.
Parameters:
format The payload format to use.
Exceptions:
VRTException if the payload format is unsupported.
References setPayloadFormat().
Member Function Documentation
DataType vrt::StandardDataPacket::getDataType () const [inline]
Gets the data type used.
Returns:
The data type.
See also:
setPayloadFormat
References vrt::PayloadFormat::getDataType(), and getPayloadFormat().
int32_t vrt::StandardDataPacket::getFrameSize () const [inline]
Gets the frame size used.
Returns:
The frame size.
See also:
setPayloadFormat
References getPayloadFormat(), and vrt::PayloadFormat::getVectorSize().
virtual string vrt::StandardDataPacket::getPacketValid (bool strict, int32_t length) const [virtual]
Checks to see if the packet is valid.
This is identical to isPacketValid(int32_t) except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No packet failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a packet.
length Verifies that the length of the packet matches this value.
Returns:
Empty string ("") if it is valid, a description of the error otherwise.
Reimplemented from vrt::BasicDataPacket.
virtual PayloadFormat vrt::StandardDataPacket::getPayloadFormat () const [inline, virtual]
Gets the assumed payload format used when interacting with the data in this packet.
This setting can either be fixed based on the packet class or set via setPayloadFormat.
Returns:
The payload format to assume when interacting with this packet. This will return null if the payload format appears unspecified for this packet class and no call to setPayloadFormat has been made.
Reimplemented from vrt::BasicDataPacket.
References vrt::BasicVRTPacket::getClassIdentifier().
Referenced by getDataType(), getFrameSize(), and getRealComplexType().
RealComplexType vrt::StandardDataPacket::getRealComplexType () const [inline]
Gets the real/complex type used.
Returns:
The data type.
See also:
setPayloadFormat
References getPayloadFormat(), and vrt::PayloadFormat::getRealComplexType().
static bool vrt::StandardDataPacket::isStandardDataPacket (int64_t id) [inline, static]
Does the ID match that of a StandardDataPacket?
References CLASS_ID_CHECK, and CLASS_ID_MASK.
virtual void vrt::StandardDataPacket::setPayloadFormat (DataType type, RealComplexType realComplex, int32_t frameSize) [virtual]
Sets the payload format and class ID.
Parameters:
type The numeric type (one of: Int4, Int8, Int16, Int32, Int64, Float, Double, etc.).
realComplex Real/Complex mode (one of: Real, ComplexCartesian).
frameSize Frame size, must be a multiple of 256 or 0/1 to indicate that the data is not framed.
Exceptions:
VRTException if an invalid value is passed in.
virtual void vrt::StandardDataPacket::setPayloadFormat (const PayloadFormat & pf) [virtual]
Optional Functionality: Sets the payload format to be assumed when interacting with the data in this packet.
Note that this setting exists only for the lifetime of this object and is not directly stored within the data packet.
Many data packet classes use a fixed payload format (see getPayloadFormat()) and will throw an exception if this method is called.
Parameters:
pf The payload format to assume.
Exceptions:
VRTException If setting the payload format is unsupported.
Reimplemented from vrt::BasicDataPacket.
Referenced by StandardDataPacket().
virtual void vrt::StandardDataPacket::toStringStream (ostringstream & str) const [protected, virtual]
Writes the packet content to a string stream in a user-friendly format.
Parameters:
str The string stream to write to.
Reimplemented from vrt::BasicDataPacket.
Member Data Documentation
const int64_t vrt::StandardDataPacket::CLASS_ID_CHECK = __INT64_C(0xFFFFFA00000000) [static]
See CLASS_ID_MASK
Referenced by isStandardDataPacket().
const int64_t vrt::StandardDataPacket::CLASS_ID_MASK = __INT64_C(0xFFFFFFFF000000) [static]
Mask and check value used for determining if a given class ID matches one used for a StandardDataPacket.
This is intended to be used as follows:
    if ((classID & CLASS_ID_MASK) == CLASS_ID_CHECK) {
      // Found a StandardDataPacket
      ...
    }
Note that this is not a guarantee that the class ID is valid, but it says that the class ID matches that expected for a StandardDataPacket.
Referenced by isStandardDataPacket().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/StandardDataPacket.h