VRT: vrt::LeapSeconds Class Reference
vrt::LeapSeconds Class Reference
Class to deal with leap seconds.
#include <LeapSeconds.h>
Public Member Functions
LeapSeconds (const LeapSeconds &ls)
Creates a new instance.
~LeapSeconds ()
Basic destructor.
virtual bool equals (const VRTObject &o) const
double getLeapSeconds (double wsec, double fsec) const
Calculate and return the difference between TAI (International Atomic Time) and UTC (Universal Coordinated Time) for the given time.
int32_t getLeapSecondsPOSIX (int64_t posix) const
Gets the number of leap seconds elapsed prior to the given time.
int32_t getLeapSecondsUTC (int64_t utc) const
Gets the number of leap seconds elapsed prior to the given time.
int32_t getMonth (int32_t year, int64_t utc) const
Internal use only: Gets month number based on UTC year (1970..N) and UTC time (from 1970).
int64_t getStartOfMonth (int32_t year, int32_t mon) const
Internal use only: Gets UTC start-of-month based on year (1970..N) and month (1..12).
int64_t getStartOfYearPOSIX (int32_t year) const
Internal use only: Gets the start of the POSIX year in seconds-since-1970.
int64_t getStartOfYearUTC (int32_t year) const
Internal use only: Gets the start of the UTC year in seconds-since-1970.
int32_t getYear (int64_t utc) const
Internal use only: Converts UTC time to a year number (1970..N).
int64_t getYiS (int64_t utc) const
Internal use only: Converts UTC time to the UTC time at 1 Jan of the given year.
bool isLeapSecond (int64_t utc) const
Internal use only: Is the identified UTC time equal to an inserted leap second? That is, is the time equal to the 86401th second of the day (23:59:60)?
virtual bool isNullValue () const
Is this object equal to null.
string toStringUTC (int64_t seconds, int64_t picoseconds=__INT64_C(-1)) const
Internal Use Only: Converts a UTC time to Year-Month-Day Hour:Min:Sec.
Static Public Member Functions
static LeapSeconds * getDefaultInstance ()
Gets the default instance.
static LeapSeconds * getInstance (string fname)
Gets an instance with the given tai-utc.dat file.
static int32_t isLeapYear (int32_t year)
Internal Use Only: Indicates if the given year is a leap year.
static void setDefaultInstance (string fname)
Sets the default instance to use.
static void setDefaultInstance (LeapSeconds *def)
Sets the default instance to use.
static string toPicosecondString (int64_t psec)
Internal Use Only: Converts a set of picoseconds to a string in the form "0.00000000000".
static string toStringGPS (int64_t seconds, int64_t picoseconds=__INT64_C(-1))
Internal Use Only: Converts a GPS time to Year-Month-Day Hour:Min:Sec.
static int32_t ymdToGpsDay (int32_t year, int32_t month, int32_t day)
Internal Use Only: Calculate the number of days (sonce 6-Jan-1980) for the supplied date.
static int32_t ymdToPosixDay (int32_t year, int32_t month, int32_t day)
Internal Use Only: Calculate the number of days (since 1-Jan-1970) for the supplied date.
Static Public Attributes
static const int32_t GPS2TAI_LS_1980 = 19
Internal use only: Number of leap seconds between GPS and TAI on 6 JAN 1980.
static const int32_t GPS2UTC = 315964811
static const int32_t J1970TOJ1950 = 631152000
static const int32_t UTC2TAI_LS_1970 = 8
Internal use only: Number of leap seconds between UTC and TAI on 1 JAN 1970, rounded to the nearest second.
Detailed Description
Class to deal with leap seconds.
See also:
vrt::TimeStamp
Constructor & Destructor Documentation
vrt::LeapSeconds::~LeapSeconds () [inline]
Basic destructor.
vrt::LeapSeconds::LeapSeconds (const LeapSeconds & ls)
Creates a new instance.
Member Function Documentation
static LeapSeconds* vrt::LeapSeconds::getDefaultInstance () [static]
Gets the default instance.
This will return the instance previously set with setDefaultInstance(..); if no default instance has yet been set, the VRTConfig#getLeapSecondsFile() will be used as the default.
Returns:
An using the give file.
Referenced by vrt::TimeStamp::forNoradTime(), vrt::TimeStamp::forTime(), vrt::TimeStamp::forTimeIRIG(), vrt::TimeStamp::forTimeNORAD(), vrt::TimeStamp::forTimePOSIX(), vrt::TimeStamp::forTimePTP(), vrt::TimeStamp::getSystemTime(), and vrt::TimeStamp::parseTime().
static LeapSeconds* vrt::LeapSeconds::getInstance (string fname) [static]
Gets an instance with the given tai-utc.dat file.
On the first call to this method the file will be opened and read. Subsequent calls may either re-open the file or return the an existing open copy.
Parameters:
fname Name of the file to read from.
Returns:
An using the give file.
Referenced by setDefaultInstance().
double vrt::LeapSeconds::getLeapSeconds (double wsec, double fsec) const
Calculate and return the difference between TAI (International Atomic Time) and UTC (Universal Coordinated Time) for the given time.
Generally, this will be the number of leap seconds in effect at that time. Between 1961/01/01 and 1972/01/01 this was a sliding value with fractional offset; since 1972/01/01 this is an integral number of seconds.
The functionality of this method matches the m_get_leap_seconds(..) method in X-Midas's leap_seconds.cc class, but uses an optimized algorithm for the most common cases.
Parameters:
wsec The number of whole seconds in Midas time referenced to UTC.
fsec The number of fractional seconds (ignored after 1972/01/01).
Returns:
The difference between TAI and UTC (i.e. TAI - UTC) in seconds.
Exceptions:
VRTException If the date is before 1961/01/01.
int32_t vrt::LeapSeconds::getLeapSecondsPOSIX (int64_t posix) const
Gets the number of leap seconds elapsed prior to the given time.
Parameters:
posix Number of days elapsed since 1970/01/01 multiplied by 86400, plus the number of seconds in the current day.
Returns:
Leap seconds elapsed during prior to the given time.
Exceptions:
VRTException if the input time is before 1972/01/01. (Between 1970 and 1972, the number of leap seconds is non-integral.)
int32_t vrt::LeapSeconds::getLeapSecondsUTC (int64_t utc) const
Gets the number of leap seconds elapsed prior to the given time.
Parameters:
utc 1-second time tics since 1970/01/01.
Returns:
Leap seconds elapsed during prior to the given time.
Exceptions:
VRTException if the input time is before 1972/01/01. (Between 1970 and 1972, the number of leap seconds is not-integral.)
int32_t vrt::LeapSeconds::getMonth (int32_t year, int64_t utc) const
Internal use only: Gets month number based on UTC year (1970..N) and UTC time (from 1970).
In this form 'year' is technically redundant (since it can be computed from 'utc'), but it is here to skip that computation.
int64_t vrt::LeapSeconds::getStartOfMonth (int32_t year, int32_t mon) const
Internal use only: Gets UTC start-of-month based on year (1970..N) and month (1..12).
int64_t vrt::LeapSeconds::getStartOfYearPOSIX (int32_t year) const
Internal use only: Gets the start of the POSIX year in seconds-since-1970.
int64_t vrt::LeapSeconds::getStartOfYearUTC (int32_t year) const
Internal use only: Gets the start of the UTC year in seconds-since-1970.
Referenced by getYiS().
int32_t vrt::LeapSeconds::getYear (int64_t utc) const
Internal use only: Converts UTC time to a year number (1970..N).
Referenced by getYiS().
int64_t vrt::LeapSeconds::getYiS (int64_t utc) const [inline]
Internal use only: Converts UTC time to the UTC time at 1 Jan of the given year.
References getStartOfYearUTC(), and getYear().
bool vrt::LeapSeconds::isLeapSecond (int64_t utc) const
Internal use only: Is the identified UTC time equal to an inserted leap second? That is, is the time equal to the 86401th second of the day (23:59:60)?
Parameters:
utc 1-second time tics since 1970/01/01.
Returns:
true if the time is 23:59:60, false otherwise.
Exceptions:
VRTException if the input time is before 1972/01/01.
static int32_t vrt::LeapSeconds::isLeapYear (int32_t year) [inline, static]
Internal Use Only: Indicates if the given year is a leap year.
The code for this method was copied from RFC 3339.
    Source: Klyne, et.al. "RFC 3339 / Date and Time on the Internet: Timestamps."
            ITEF, July 2002. http://tools.ietf.org/html/rfc3339 (Retrieved 2007-06-15)
Parameters:
year The year number.
Returns:
true if it is a leap year, false otherwise.
virtual bool vrt::LeapSeconds::isNullValue () const [inline, virtual]
Is this object equal to null.
Reimplemented from vrt::VRTObject.
static void vrt::LeapSeconds::setDefaultInstance (string fname) [inline, static]
Sets the default instance to use.
Parameters:
fname Name of the file to read from.
Exceptions:
VRTException if there is an error while reading and parsing the file.
References getInstance(), and setDefaultInstance().
static void vrt::LeapSeconds::setDefaultInstance (LeapSeconds * def) [static]
Sets the default instance to use.
Parameters:
def The default instance to use.
Referenced by setDefaultInstance().
static string vrt::LeapSeconds::toPicosecondString (int64_t psec) [static]
Internal Use Only: Converts a set of picoseconds to a string in the form "0.00000000000".
static string vrt::LeapSeconds::toStringGPS (int64_t seconds, int64_t picoseconds = __INT64_C(-1)) [static]
Internal Use Only: Converts a GPS time to Year-Month-Day Hour:Min:Sec.
Parameters:
seconds Whole seconds.
picoseconds Picoseconds (-1 to ignore).
Returns:
Year-Month-Day Hour:Min:Sec.
string vrt::LeapSeconds::toStringUTC (int64_t seconds, int64_t picoseconds = __INT64_C(-1)) const
Internal Use Only: Converts a UTC time to Year-Month-Day Hour:Min:Sec.
Parameters:
seconds Whole seconds.
picoseconds Picoseconds (-1 to ignore).
Returns:
Year-Month-Day Hour:Min:Sec.
static int32_t vrt::LeapSeconds::ymdToGpsDay (int32_t year, int32_t month, int32_t day) [static]
Internal Use Only: Calculate the number of days (sonce 6-Jan-1980) for the supplied date.
Parameters:
year The year (e.g. 2002).
month The month (1 = Jan)
day The day.
Returns:
The Modified Julian Day.
static int32_t vrt::LeapSeconds::ymdToPosixDay (int32_t year, int32_t month, int32_t day) [static]
Internal Use Only: Calculate the number of days (since 1-Jan-1970) for the supplied date.
Parameters:
year The year (e.g. 2002).
month The month (1 = Jan)
day The day.
Returns:
The Modified Julian Day.
Member Data Documentation
const int32_t vrt::LeapSeconds::GPS2TAI_LS_1980 = 19 [static]
Internal use only: Number of leap seconds between GPS and TAI on 6 JAN 1980.
See vrt::TimeStamp for details.
const int32_t vrt::LeapSeconds::GPS2UTC = 315964811 [static]
Deprecated:
This constant has moved to the vrt::TimeStamp class.
const int32_t vrt::LeapSeconds::J1970TOJ1950 = 631152000 [static]
Deprecated:
This constant has moved to VRTIO in the accompanying Midas option tree.
const int32_t vrt::LeapSeconds::UTC2TAI_LS_1970 = 8 [static]
Internal use only: Number of leap seconds between UTC and TAI on 1 JAN 1970, rounded to the nearest second.
See vrt::TimeStamp for details.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/LeapSeconds.h