VRT: vrt::UUID Class Reference
vrt::UUID Class Reference
A 128-bit universally unique identifier (UUID).
#include <UUID.h>
Public Member Functions
UUID (const uuid_t uuid)
Copy constructor.
UUID (const UUID &uuid)
Copy constructor.
UUID ()
Basic no-argument constructor.
~UUID ()
Destructor.
virtual bool equals (const UUID &uuid) const
Checks to see if two UUIDs are equal.
virtual bool equals (const VRTObject &o) const
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
string getUUID () const
Gets the 16-byte UUID value into the given buffer.
uuid_t & getUUIDPointer ()
Gets a pointer to the UUID value.
void getValue (void *buf) const
Gets the 16-byte UUID value into the given buffer.
virtual bool isNullValue () const
A UUID is considered null if all bits are set to 0 (this is not a valid UUID).
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setUUID (const char *uuid)
Sets the 16-byte UUID value from the given buffer.
void setUUID (const string &uuid)
Sets the 16-byte UUID value from the given buffer.
void setValue (const void *buf)
Sets the 16-byte UUID value from the given buffer.
virtual string toString () const
Converts the UUID to a string.
Static Public Member Functions
static UUID randomUUID ()
Generates a random UUID.
Detailed Description
A 128-bit universally unique identifier (UUID).
This provides an OO wrapper for the uuid_t value defined in the uuid/uuid.h library that allows its inclusion in VRT packets similar to other values.
    By default the standard UUID library (-luuid) will be used when working with
    UUIDs in the C++ code. Since some platforms do not have this library installed,
    there is a mini UUID library internal to the VRT C++ code. (The internal library
    supports the minimum set of functions required here and is not intended for use
    by external users.) The internal library has two versions: the second version
    supports generation of RFC 4122-compliant UUIDs using gcrypt as a source of
    secure-random numbers; the first version does not depend on gcrypt but does
    not support generation of UUIDs (use the first version only as a last resort).
      Standard UUID library:            setenv INTERNAL_UUID_LIB 0
      Internal UUID library (no gen):   setenv INTERNAL_UUID_LIB 1
      Internal UUID library (random):   setenv INTERNAL_UUID_LIB 2
Constructor & Destructor Documentation
vrt::UUID::~UUID () [inline]
Destructor.
vrt::UUID::UUID ()
Basic no-argument constructor.
vrt::UUID::UUID (const UUID & uuid)
Copy constructor.
vrt::UUID::UUID (const uuid_t uuid)
Copy constructor.
Member Function Documentation
virtual bool vrt::UUID::equals (const UUID & uuid) const [virtual]
Checks to see if two UUIDs are equal.
Reimplemented from vrt::VRTObject.
virtual Value* vrt::UUID::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::HasFields.
virtual int32_t vrt::UUID::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::HasFields.
virtual string vrt::UUID::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::HasFields.
virtual ValueType vrt::UUID::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::HasFields.
string vrt::UUID::getUUID () const
Gets the 16-byte UUID value into the given buffer.
Referenced by toString().
uuid_t& vrt::UUID::getUUIDPointer () [inline]
Gets a pointer to the UUID value.
void vrt::UUID::getValue (void * buf) const [inline]
Gets the 16-byte UUID value into the given buffer.
Referenced by vrt::VRTMath::packUUID().
virtual bool vrt::UUID::isNullValue () const [virtual]
A UUID is considered null if all bits are set to 0 (this is not a valid UUID).
Reimplemented from vrt::VRTObject.
static UUID vrt::UUID::randomUUID () [static]
Generates a random UUID.
virtual void vrt::UUID::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::HasFields.
void vrt::UUID::setUUID (const char * uuid)
Sets the 16-byte UUID value from the given buffer.
void vrt::UUID::setUUID (const string & uuid)
Sets the 16-byte UUID value from the given buffer.
void vrt::UUID::setValue (const void * buf) [inline]
Sets the 16-byte UUID value from the given buffer.
Referenced by vrt::VRTMath::unpackUUID().
virtual string vrt::UUID::toString () const [inline, virtual]
Converts the UUID to a string.
Reimplemented from vrt::VRTObject.
References getUUID().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/UUID.h