VRT: vrt::Point Class Reference
vrt::Point Class Reference
Point Definition.
#include <EphemerisPacket.h>
Public Member Functions
Point ()
Creates a new instance ready for the fields to be set.
float getAccelerationX () const
Get ECEF acceleration X.
float getAccelerationY () const
Get ECEF acceleration Y.
float getAccelerationZ () const
Get ECEF acceleration Z.
float getAttitudeAlpha () const
Get attitude Alpha.
float getAttitudeBeta () const
Get attitude Beta.
float getAttitudePhi () const
Get attitude Phi.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
double getPositionX () const
Get ECEF position X.
double getPositionY () const
Get ECEF position Y.
double getPositionZ () const
Get ECEF position Z.
double getVelocityX () const
Get ECEF velocity X.
double getVelocityY () const
Get ECEF velocity Y.
double getVelocityZ () const
Get ECEF velocity Z.
void setAccelerationX (float val)
Set ECEF acceleration X.
void setAccelerationY (float val)
Set ECEF acceleration Y.
void setAccelerationZ (float val)
Set ECEF acceleration Z.
void setAttitudeAlpha (float val)
Set attitude Alpha.
void setAttitudeBeta (float val)
Set attitude Beta.
void setAttitudePhi (float val)
Set attitude Phi.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setPositionX (double val)
Set ECEF position X.
void setPositionY (double val)
Set ECEF position Y.
void setPositionZ (double val)
Set ECEF position Z.
void setVelocityX (double val)
Set ECEF velocity X.
void setVelocityY (double val)
Set ECEF velocity Y.
void setVelocityZ (double val)
Set ECEF velocity Z.
virtual string toString () const
Gets a basic description of the object, useful for debugging.
Static Public Attributes
static const int32_t RECORD_LENGTH
The length of the record in octets (72).
Protected Member Functions
Point (const Record &r)
Basic copy constructor.
Detailed Description
Point Definition.
Note: Any changes made to this record will not be reflected in the packet. This maintains the CONOP that anything read from the packet can be used independent of the packet and that the packet can only be modified by calling a set method on the packet its self.
Constructor & Destructor Documentation
vrt::Point::Point (const Record & r) [protected]
Basic copy constructor.
vrt::Point::Point ()
Creates a new instance ready for the fields to be set.
All of the bytes that make up the record will be initialized to 0.
Member Function Documentation
float vrt::Point::getAccelerationX () const [inline]
Get ECEF acceleration X.
Units: m/s^2
Returns:
The value read from the packet.
References vrt::Record::unpackFloat().
float vrt::Point::getAccelerationY () const [inline]
Get ECEF acceleration Y.
Units: m/s^2
Returns:
The value read from the packet.
References vrt::Record::unpackFloat().
float vrt::Point::getAccelerationZ () const [inline]
Get ECEF acceleration Z.
Units: m/s^2
Returns:
The value read from the packet.
References vrt::Record::unpackFloat().
float vrt::Point::getAttitudeAlpha () const [inline]
Get attitude Alpha.
Units: deg
Range: [0,360)
Returns:
The value read from the packet.
References vrt::Record::unpackFloat().
float vrt::Point::getAttitudeBeta () const [inline]
Get attitude Beta.
Units: deg
Range: [0,360)
Returns:
The value read from the packet.
References vrt::Record::unpackFloat().
float vrt::Point::getAttitudePhi () const [inline]
Get attitude Phi.
Units: deg
Range: [0,360)
Returns:
The value read from the packet.
References vrt::Record::unpackFloat().
virtual Value* vrt::Point::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::Record.
virtual int32_t vrt::Point::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::Record.
virtual string vrt::Point::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::Record.
virtual ValueType vrt::Point::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::Record.
double vrt::Point::getPositionX () const [inline]
Get ECEF position X.
Units: m
Returns:
The value read from the packet.
References vrt::Record::unpackDouble().
double vrt::Point::getPositionY () const [inline]
Get ECEF position Y.
Units: m
Returns:
The value read from the packet.
References vrt::Record::unpackDouble().
double vrt::Point::getPositionZ () const [inline]
Get ECEF position Z.
Units: m
Returns:
The value read from the packet.
References vrt::Record::unpackDouble().
double vrt::Point::getVelocityX () const [inline]
Get ECEF velocity X.
Units: m/s
Returns:
The value read from the packet.
References vrt::Record::unpackDouble().
double vrt::Point::getVelocityY () const [inline]
Get ECEF velocity Y.
Units: m/s
Returns:
The value read from the packet.
References vrt::Record::unpackDouble().
double vrt::Point::getVelocityZ () const [inline]
Get ECEF velocity Z.
Units: m/s
Returns:
The value read from the packet.
References vrt::Record::unpackDouble().
void vrt::Point::setAccelerationX (float val) [inline]
Set ECEF acceleration X.
Units: m/s^2
Parameters:
val The new value to write to the packet.
References vrt::Record::packFloat().
void vrt::Point::setAccelerationY (float val) [inline]
Set ECEF acceleration Y.
Units: m/s^2
Parameters:
val The new value to write to the packet.
References vrt::Record::packFloat().
void vrt::Point::setAccelerationZ (float val) [inline]
Set ECEF acceleration Z.
Units: m/s^2
Parameters:
val The new value to write to the packet.
References vrt::Record::packFloat().
void vrt::Point::setAttitudeAlpha (float val) [inline]
Set attitude Alpha.
Units: deg
Range: [0,360)
Parameters:
val The new value to write to the packet.
References vrt::Record::packFloat().
void vrt::Point::setAttitudeBeta (float val) [inline]
Set attitude Beta.
Units: deg
Range: [0,360)
Parameters:
val The new value to write to the packet.
References vrt::Record::packFloat().
void vrt::Point::setAttitudePhi (float val) [inline]
Set attitude Phi.
Units: deg
Range: [0,360)
Parameters:
val The new value to write to the packet.
References vrt::Record::packFloat().
virtual void vrt::Point::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::Record.
void vrt::Point::setPositionX (double val) [inline]
Set ECEF position X.
Units: m
Parameters:
val The new value to write to the packet.
References vrt::Record::packDouble().
void vrt::Point::setPositionY (double val) [inline]
Set ECEF position Y.
Units: m
Parameters:
val The new value to write to the packet.
References vrt::Record::packDouble().
void vrt::Point::setPositionZ (double val) [inline]
Set ECEF position Z.
Units: m
Parameters:
val The new value to write to the packet.
References vrt::Record::packDouble().
void vrt::Point::setVelocityX (double val) [inline]
Set ECEF velocity X.
Units: m/s
Parameters:
val The new value to write to the packet.
References vrt::Record::packDouble().
void vrt::Point::setVelocityY (double val) [inline]
Set ECEF velocity Y.
Units: m/s
Parameters:
val The new value to write to the packet.
References vrt::Record::packDouble().
void vrt::Point::setVelocityZ (double val) [inline]
Set ECEF velocity Z.
Units: m/s
Parameters:
val The new value to write to the packet.
References vrt::Record::packDouble().
virtual string vrt::Point::toString () const [virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::Record.
Member Data Documentation
const int32_t vrt::Point::RECORD_LENGTH [static]
The length of the record in octets (72).
The documentation for this class was generated from the following file:
cpp_src/vrt/libm/EphemerisPacket.h