VRT: vrt::PayloadFormat Class Reference
vrt::PayloadFormat Class Reference
Specifies the payload format.
#include <PayloadFormat.h>
Public Member Functions
PayloadFormat (int64_t bits)
Internal Use Only: Creates new instance.
PayloadFormat (bool procEfficient, RealComplexType type, DataItemFormat format, bool repeating, int32_t eventTagSize, int32_t chanTagSize, int32_t fieldSize, int32_t itemSize, int32_t repeatCount, int32_t vectorSize, int32_t fracSize=0)
Creates new instance.
PayloadFormat (DataType dataType, RealComplexType realComplex=RealComplexType_Real)
Creates new instance.
PayloadFormat (RealComplexType type, DataItemFormat format, int32_t size, int32_t fracSize)
Creates new instance.
PayloadFormat (DataItemFormat format, int32_t size, int32_t fracSize)
Creates new instance.
PayloadFormat (RealComplexType type, DataItemFormat format, int32_t size)
Creates new instance.
PayloadFormat (DataItemFormat format, int32_t size)
Creates new instance.
PayloadFormat (const PayloadFormat &pf)
Creates new instance.
PayloadFormat ()
Creates new instance.
virtual bool equals (const VRTObject &o) const
int64_t getBits () const
Internal Use Only: Gets the bits.
int getChannelTagSize () const
Gets the channel tag size.
DataItemFormat getDataItemFormat () const
Gets the data format used.
int32_t getDataItemFracSize () const
Gets the data item fractional size.
int32_t getDataItemSize () const
Gets the data item size.
DataType getDataType () const
Utility method: If this payload format matches one of the pre-defined data types, and is stored without any "extra bits", return that type.
int32_t getEventTagSize () const
Gets the event tag size.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
int32_t getItemPackingFieldSize () const
Gets the item packing field size.
RealComplexType getRealComplexType () const
Gets the real/complex type used.
int32_t getRepeatCount () const
Gets the repeat count.
virtual string getValid () const
Checks to see if the payload format is valid.
int32_t getVectorSize () const
Gets the vector size.
bool isComplex () const
Utility method: Indicates if the payload format is complex.
virtual bool isNullValue () const
Is this object equal to null? Since the values 0x0000000000000000 and 0x8000000000000000 are both valid and 0xFFFFFFFFFFFFFFFF is invalid, this object uses -1 as the indicator for a null payload format.
bool isProcessingEfficient () const
Indicates if the processing efficient packing method used.
bool isRepeating () const
Indicates if the sample-component repeat is used.
bool isSigned () const
Utility method: Indicates if the payload format is signed.
bool isValid () const
Checks to see if the payload format is valid.
void setBits (int64_t bits)
Internal Use Only: Sets the bits.
void setChannelTagSize (int32_t val)
Sets the channel tag size.
void setDataItemFormat (DataItemFormat val)
Sets the data format used.
void setDataItemFracSize (int32_t val)
Sets the data item fractional size.
void setDataItemSize (int32_t val)
Sets the data item size.
void setDataType (DataType type)
Utility method: Sets the payload format to match one of the pre-defined data types.
void setEventTagSize (int32_t val)
Sets the event tag size.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setItemPackingFieldSize (int32_t val)
Sets the item packing field size.
void setProcessingEfficient (bool val)
Indicates if the processing efficient packing method used.
void setRealComplexType (RealComplexType val)
Sets the real/complex type used.
void setRepeatCount (int32_t val)
Sets the repeat count.
void setRepeating (bool val)
Indicates if the sample-component repeat is used.
void setVectorSize (int32_t val)
Sets the vector size.
virtual string toString () const
Converts this class its string form.
Detailed Description
Specifies the payload format.
The following implementation is used for the HasFields methods:
     ID | Name                 | Type
    ----+----------------------+---------------
     0  | ProcessingEfficient  | Bool
     1  | RealComplexType      | Int8
     2  | DataItemFormat       | Int8
     3  | Repeating            | Bool
     4  | EventTagSize         | Int32
     5  | ChannelTagSize       | Int32
     6  | DataItemFracSize     | Int32 - NEW in V49.2 and used only for Non-Normalized
     7  | ItemPackingFieldSize | Int32
     8  | DataItemSize         | Int32
     9  | RepeatCount          | Int32
     10 | VectorSize           | Int32
     11 | DataType             | Int64
    ----+----------------------+---------------
Constructor & Destructor Documentation
vrt::PayloadFormat::PayloadFormat ()
Creates new instance.
vrt::PayloadFormat::PayloadFormat (const PayloadFormat & pf)
Creates new instance.
vrt::PayloadFormat::PayloadFormat (DataItemFormat format, int32_t size)
Creates new instance.
This is identical to new PayloadFormat(true,RealComplexType.Real,format,false,0,0,size,size,1,1).
Parameters:
format The data format used.
size The data item size.
vrt::PayloadFormat::PayloadFormat (RealComplexType type, DataItemFormat format, int32_t size)
Creates new instance.
This is identical to new PayloadFormat(true,type,format,false,0,0,size,size,1,1).
Parameters:
type The real/complex type used.
format The data format used.
size The data item size.
vrt::PayloadFormat::PayloadFormat (DataItemFormat format, int32_t size, int32_t fracSize)
Creates new instance.
This is identical to new PayloadFormat(true,RealComplexType.Real,format,false,0,0,size,size,1,1,fracSize).
Parameters:
format The data format used.
size The data item size.
fracSize The data item fraction size.
vrt::PayloadFormat::PayloadFormat (RealComplexType type, DataItemFormat format, int32_t size, int32_t fracSize)
Creates new instance.
This is identical to new PayloadFormat(true,type,format,false,0,0,size,size,1,1,fracSize).
Parameters:
type The real/complex type used.
format The data format used.
size The data item size.
fracSize The data item fraction size.
vrt::PayloadFormat::PayloadFormat (DataType dataType, RealComplexType realComplex = RealComplexType_Real)
Creates new instance.
Parameters:
dataType The data format used.
realComplex The real/complex type used.
vrt::PayloadFormat::PayloadFormat (bool procEfficient, RealComplexType type, DataItemFormat format, bool repeating, int32_t eventTagSize, int32_t chanTagSize, int32_t fieldSize, int32_t itemSize, int32_t repeatCount, int32_t vectorSize, int32_t fracSize = 0)
Creates new instance.
Parameters:
procEfficient true if Processing Efficient or false if Link Efficient.
type The real/complex type used.
format The data format used.
repeating Indicates if the sample-component repeat is used.
eventTagSize the event tag size.
chanTagSize the channel tag size.
fieldSize The item packing field size.
itemSize The data item size.
repeatCount The repeat count.
vectorSize The vector size.
fracSize The data item fraction size (default=0).
vrt::PayloadFormat::PayloadFormat (int64_t bits)
Internal Use Only: Creates new instance.
Member Function Documentation
int64_t vrt::PayloadFormat::getBits () const [inline]
Internal Use Only: Gets the bits.
int vrt::PayloadFormat::getChannelTagSize () const [inline]
Gets the channel tag size.
Returns:
The channel tag size (0..15).
DataItemFormat vrt::PayloadFormat::getDataItemFormat () const [inline]
Gets the data format used.
Returns:
The format used.
Referenced by isSigned().
int32_t vrt::PayloadFormat::getDataItemFracSize () const [inline]
Gets the data item fractional size.
Returns:
The data item fractional size (0..15).
int32_t vrt::PayloadFormat::getDataItemSize () const [inline]
Gets the data item size.
Returns:
The data item size (0..63).
Referenced by vrt::BasicDataPacket::getLostBytes().
DataType vrt::PayloadFormat::getDataType () const
Utility method: If this payload format matches one of the pre-defined data types, and is stored without any "extra bits", return that type.
Although technically "unsigned" this method will recognize any 1-bit integer data as DataType_UInt1. Note: Considers all non-normalized data types as not pre-defined.
Returns:
The data type or null if not a pre-defined type.
Referenced by vrt::StandardDataPacket::getDataType().
int32_t vrt::PayloadFormat::getEventTagSize () const [inline]
Gets the event tag size.
Returns:
The event tag size (0..7).
virtual Value* vrt::PayloadFormat::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::HasFields.
virtual int32_t vrt::PayloadFormat::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::HasFields.
virtual string vrt::PayloadFormat::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::HasFields.
virtual ValueType vrt::PayloadFormat::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::HasFields.
int32_t vrt::PayloadFormat::getItemPackingFieldSize () const [inline]
Gets the item packing field size.
Returns:
The field size (0..63).
RealComplexType vrt::PayloadFormat::getRealComplexType () const [inline]
Gets the real/complex type used.
Returns:
The type used.
Referenced by vrt::StandardDataPacket::getRealComplexType(), and isComplex().
int32_t vrt::PayloadFormat::getRepeatCount () const [inline]
Gets the repeat count.
Returns:
The repeat count (1..65536).
virtual string vrt::PayloadFormat::getValid () const [virtual]
Checks to see if the payload format is valid.
This is identical to isValid() except that a description of the error is returned.
Returns:
"" if it is valid, a description of the error otherwise.
Referenced by isValid().
int32_t vrt::PayloadFormat::getVectorSize () const [inline]
Gets the vector size.
Returns:
The vector size (1..65536).
Referenced by vrt::StandardDataPacket::getFrameSize().
bool vrt::PayloadFormat::isComplex () const [inline]
Utility method: Indicates if the payload format is complex.
Returns:
true if the data format is complex, false if it is real.
References getRealComplexType().
virtual bool vrt::PayloadFormat::isNullValue () const [inline, virtual]
Is this object equal to null? Since the values 0x0000000000000000 and 0x8000000000000000 are both valid and 0xFFFFFFFFFFFFFFFF is invalid, this object uses -1 as the indicator for a null payload format.
Reimplemented from vrt::VRTObject.
bool vrt::PayloadFormat::isProcessingEfficient () const [inline]
Indicates if the processing efficient packing method used.
Returns:
true if Processing Efficient (byte-aligned) or false if Link Efficient (fewest bytes used).
bool vrt::PayloadFormat::isRepeating () const [inline]
Indicates if the sample-component repeat is used.
Returns:
true if it is being used, false if not.
bool vrt::PayloadFormat::isSigned () const [inline]
Utility method: Indicates if the payload format is signed.
Returns:
true if the data format is signed, false if it is unsigned.
References getDataItemFormat().
bool vrt::PayloadFormat::isValid () const [inline]
Checks to see if the payload format is valid.
Returns:
true if it is valid, false otherwise.
References getValid().
void vrt::PayloadFormat::setBits (int64_t bits) [inline]
Internal Use Only: Sets the bits.
void vrt::PayloadFormat::setChannelTagSize (int32_t val) [inline]
Sets the channel tag size.
Parameters:
val The channel tag size (0..15).
Exceptions:
VRTException If the specified value is not in the allowable range.
void vrt::PayloadFormat::setDataItemFormat (DataItemFormat val) [inline]
Sets the data format used.
Parameters:
val The format used.
Exceptions:
VRTException If the specified value is unsupported.
void vrt::PayloadFormat::setDataItemFracSize (int32_t val) [inline]
Sets the data item fractional size.
Parameters:
val The data item fractional size (0..15).
Exceptions:
VRTException If the specified value is not in the allowable range.
void vrt::PayloadFormat::setDataItemSize (int32_t val) [inline]
Sets the data item size.
Parameters:
val The data item size (0..63).
Exceptions:
VRTException If the specified value is not in the allowable range.
void vrt::PayloadFormat::setDataType (DataType type)
Utility method: Sets the payload format to match one of the pre-defined data types.
Note: Considers all non-normalized data types as not pre-defined.
Parameters:
type The data type.
Exceptions:
NullPointerException if type is null.
void vrt::PayloadFormat::setEventTagSize (int32_t val) [inline]
Sets the event tag size.
Parameters:
val The event tag size (0..7).
Exceptions:
VRTException If the specified value is not in the allowable range.
virtual void vrt::PayloadFormat::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::HasFields.
void vrt::PayloadFormat::setItemPackingFieldSize (int32_t val) [inline]
Sets the item packing field size.
Parameters:
val The field size (0..63).
Exceptions:
VRTException If the specified value is not in the allowable range.
void vrt::PayloadFormat::setProcessingEfficient (bool val) [inline]
Indicates if the processing efficient packing method used.
Parameters:
val true if Processing Efficient (byte-aligned) or false if Link Efficient (fewest bytes used).
void vrt::PayloadFormat::setRealComplexType (RealComplexType val) [inline]
Sets the real/complex type used.
Parameters:
val The type used.
Exceptions:
VRTException If the specified value is unsupported.
void vrt::PayloadFormat::setRepeatCount (int32_t val) [inline]
Sets the repeat count.
Parameters:
val The repeat count (1..65536).
Exceptions:
VRTException If the specified value is not in the allowable range.
void vrt::PayloadFormat::setRepeating (bool val) [inline]
Indicates if the sample-component repeat is used.
Parameters:
val true if it is being used, false if not.
void vrt::PayloadFormat::setVectorSize (int32_t val) [inline]
Sets the vector size.
Parameters:
val The vector size (1..65536).
Exceptions:
VRTException If the specified value is not in the allowable range.
virtual string vrt::PayloadFormat::toString () const [virtual]
Converts this class its string form.
Reimplemented from vrt::VRTObject.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/PayloadFormat.h