VRT: vrt::EphemerisPacket Class Reference
vrt::EphemerisPacket Class Reference
A.7. ECEF Ephemeris.
#include <EphemerisPacket.h>
Public Member Functions
EphemerisPacket (const vector< char > &bbuf, bool readOnly)
Creates a new instance accessing the given data buffer.
EphemerisPacket (const BasicVRTPacket &p)
Creates a new instance from the given packet.
EphemerisPacket ()
Creates a new instance ready for the fields to be set.
FixType getAccFixType () const
Get the acceleration fix type.
vector< Point > getAllPoints () const
Get ECEF fix points (1+).
FixType getAttFixType () const
Get the attitude fix type.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
int64_t getFixDelta () const
Get time delta between each set of points (seconds + picoseconds) max is one day (0 if only one point).
TimeStamp getFixTime () const
Get time stamp of the first point.
virtual string getPacketValid (bool strict, int32_t length) const
Checks to see if the packet is valid.
Point getPoint (int32_t i) const
Get item in ECEF fix points (1+).
int32_t getPointCount () const
Get length of ECEF fix points (1+).
FixType getPosFixType () const
Get the position fix type.
string getProducedBy () const
Get ephemeris produced by.
FixType getVelFixType () const
Get the velocity fix type.
void setAccFixType (FixType val)
Set the acceleration fix type.
void setAllPoints (const vector< Point > &val)
Set ECEF fix points (1+).
void setAttFixType (FixType val)
Set the attitude fix type.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setFixDelta (int64_t val)
Set time delta between each set of points (seconds + picoseconds) max is one day (0 if only one point).
void setFixTime (TimeStamp val)
Set time stamp of the first point.
void setPoint (int32_t i, const Point &val)
Set item in ECEF fix points (1+).
void setPointCount (int32_t length)
Set length of ECEF fix points (1+).
void setPosFixType (FixType val)
Set the position fix type.
void setProducedBy (string val)
Set ephemeris produced by.
void setVelFixType (FixType val)
Set the velocity fix type.
Static Public Attributes
static const string CLASS_ID
The class identifier in string form (FF-FF-FA:2011.ECEF).
static const int64_t CLASS_IDENTIFIER
The class identifier in numeric form (0xFFFFFA2011ECEF).
static const int32_t PACKET_LENGTH
The packet length (-56) excluding the header and trailer (if applicable).
static const PacketType PACKET_TYPE
The packet type (PacketType_ExtContext).
Protected Member Functions
EphemerisPacket (const BasicVRTPacket &p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength)
Internal constructor, for use by subclasses.
virtual void toStringStream (ostringstream &str) const
Writes the packet content to a string stream in a user-friendly format.
Detailed Description
A.7. ECEF Ephemeris.
Describes the position of a vehicle in ECEF (ECR) coordinates. This augments the standard IF Context packet which includes basic ephemeris information for a single point in time, but lacks the ability to convey a description of the actual and anticipated movements of a vehicle. A good example would be that of a ballistic projectile that lacks a GPS or INS system, but has an extremely predictable path of travel.
The ECEF and Attitude shall be defined using the same coordinate system described in VITA 49.0 rules 7.1.5.21-1 and 7.1.5.21-2.
If the associated IF Context packet includes ECEF ephemeris values, they shall be consistent with the values provided here (excepting rounding errors). Note that "consistent" differs from "equal" in that the fixes in the IF Context packet may be sampled at a different time interval resulting in values that are "consistent" but "unequal". Also note that the ECEF values may differ significantly from the GPS and/or INS values that are (optionally) included in the IF Context packet in cases where there are measurement inconsistencies between the devices used.
The enumerated Fix Type enumeration provides extra detail to processing systems that assign different "accuracy tolerances" based on the fix type. All fix types less than zero indicates a predicted/estimated value is given, fix types greater than zero indicates an actual/measured value is given. If both Predicted and Actual values are included, the Fix Types shall report all points as Predicted or shall not specify the Fix Type.
The Fix Time field specifies the time of the first fix. Where multiple fix points are provided the Fix Delta gives the delta between each pair of fixes (e.g. between points(7) and points(8)), all points must be evenly spaced. A fix at the current time will have the fix time match that of the packet; though it need not be the first point listed.
This approach allows for old fixes to be re-sent as necessary and allows use of predicted values for interpolation. In the case of orbiting spacecraft, future positions of vehicles can be predicted with some accuracy so the inclusion of points in the past and future allows consumers to interpolate the positions at any arbitrary time.
Stationary objects are identified by velocity and acceleration values of zero (but a non-zero fix type for both) and will typically have 1+ past and 1+ future points specified (with the same values). Any interpolation algorithms should always resolve to the stationary position.
Constructor & Destructor Documentation
vrt::EphemerisPacket::EphemerisPacket ()
Creates a new instance ready for the fields to be set.
The stream ID and timecode values will be initialized to 0.
vrt::EphemerisPacket::EphemerisPacket (const BasicVRTPacket & p)
Creates a new instance from the given packet.
Parameters:
p The packet.
Exceptions:
VRTException If the packet given does not match this type.
vrt::EphemerisPacket::EphemerisPacket (const BasicVRTPacket & p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength) [protected]
Internal constructor, for use by subclasses.
Parameters:
p The packet (already initialized).
type The expected packet type.
classID The expected classID.
minPayloadLength The minimum payload length.
maxPayloadLength The maximum payload length (<0 if not pre-defined).
Exceptions:
IllegalArgumentException If packet type or classID of the packet are invalid, or if the payload length is invalid.
vrt::EphemerisPacket::EphemerisPacket (const vector< char > & bbuf, bool readOnly)
Creates a new instance accessing the given data buffer.
Parameters:
bbuf The data buffer to use.
readOnly Should users of this instance be able to modify the underlying data buffer?
Member Function Documentation
FixType vrt::EphemerisPacket::getAccFixType () const [inline]
Get the acceleration fix type.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadByte().
vector<Point> vrt::EphemerisPacket::getAllPoints () const
Get ECEF fix points (1+).
Size: variable
Returns:
The value read from the packet.
FixType vrt::EphemerisPacket::getAttFixType () const [inline]
Get the attitude fix type.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadByte().
virtual Value* vrt::EphemerisPacket::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::BasicVRTPacket.
virtual int32_t vrt::EphemerisPacket::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::BasicVRTPacket.
virtual string vrt::EphemerisPacket::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::BasicVRTPacket.
virtual ValueType vrt::EphemerisPacket::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::BasicVRTPacket.
int64_t vrt::EphemerisPacket::getFixDelta () const [inline]
Get time delta between each set of points (seconds + picoseconds) max is one day (0 if only one point).
Units: ps
Range: [0,86401e12]
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadLong().
TimeStamp vrt::EphemerisPacket::getFixTime () const [inline]
Get time stamp of the first point.
Units: sec
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadTimeStamp().
virtual string vrt::EphemerisPacket::getPacketValid (bool strict, int32_t length) const [virtual]
Checks to see if the packet is valid.
This is identical to isPacketValid(int32_t) except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No packet failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a packet.
length Verifies that the length of the packet matches this value.
Returns:
Empty string ("") if it is valid, a description of the error otherwise.
Reimplemented from vrt::BasicVRTPacket.
Point vrt::EphemerisPacket::getPoint (int32_t i) const
Get item in ECEF fix points (1+).
Parameters:
i The index.
Returns:
The value read from the packet.
Exceptions:
VRTException if i is greater than or equal to getPointCount()
int32_t vrt::EphemerisPacket::getPointCount () const [inline]
Get length of ECEF fix points (1+).
Returns:
The number of entries.
References vrt::BasicVRTPacket::getPayloadLength().
FixType vrt::EphemerisPacket::getPosFixType () const [inline]
Get the position fix type.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadByte().
string vrt::EphemerisPacket::getProducedBy () const [inline]
Get ephemeris produced by.
Size: 32
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadAscii().
FixType vrt::EphemerisPacket::getVelFixType () const [inline]
Get the velocity fix type.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadByte().
void vrt::EphemerisPacket::setAccFixType (FixType val) [inline]
Set the acceleration fix type.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadByte().
void vrt::EphemerisPacket::setAllPoints (const vector< Point > & val)
Set ECEF fix points (1+).
Size: variable
Parameters:
val The new value to write to the packet.
Exceptions:
VRTException If the length of val is invalid
void vrt::EphemerisPacket::setAttFixType (FixType val) [inline]
Set the attitude fix type.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadByte().
virtual void vrt::EphemerisPacket::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::BasicVRTPacket.
void vrt::EphemerisPacket::setFixDelta (int64_t val) [inline]
Set time delta between each set of points (seconds + picoseconds) max is one day (0 if only one point).
Units: ps
Range: [0,86401e12]
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadLong().
void vrt::EphemerisPacket::setFixTime (TimeStamp val) [inline]
Set time stamp of the first point.
Units: sec
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadTimeStamp().
void vrt::EphemerisPacket::setPoint (int32_t i, const Point & val)
Set item in ECEF fix points (1+).
Parameters:
i The index.
val The new value.
Exceptions:
VRTException if i is greater than or equal to getPointCount()
void vrt::EphemerisPacket::setPointCount (int32_t length)
Set length of ECEF fix points (1+).
Parameters:
length The number of entries.
Exceptions:
VRTException if length is negative
void vrt::EphemerisPacket::setPosFixType (FixType val) [inline]
Set the position fix type.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadByte().
void vrt::EphemerisPacket::setProducedBy (string val) [inline]
Set ephemeris produced by.
Size: 32
Parameters:
val The new value to write to the packet. Any non-ASCII characters in the string (numeric value >0x7F) or ASCII control characters (numeric value <0x20, 0x7F) will be replaced with '?'. If the string is longer than the size allotted, it will be truncated without warning.
References vrt::BasicVRTPacket::packPayloadAscii().
void vrt::EphemerisPacket::setVelFixType (FixType val) [inline]
Set the velocity fix type.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadByte().
virtual void vrt::EphemerisPacket::toStringStream (ostringstream & str) const [protected, virtual]
Writes the packet content to a string stream in a user-friendly format.
Parameters:
str The string stream to write to.
Reimplemented from vrt::BasicVRTPacket.
Member Data Documentation
const string vrt::EphemerisPacket::CLASS_ID [static]
The class identifier in string form (FF-FF-FA:2011.ECEF).
const int64_t vrt::EphemerisPacket::CLASS_IDENTIFIER [static]
The class identifier in numeric form (0xFFFFFA2011ECEF).
const int32_t vrt::EphemerisPacket::PACKET_LENGTH [static]
The packet length (-56) excluding the header and trailer (if applicable).
A value of -56 indicates that the length is variable with a minimum length of 56 octets.
const PacketType vrt::EphemerisPacket::PACKET_TYPE [static]
The packet type (PacketType_ExtContext).
The documentation for this class was generated from the following file:
cpp_src/vrt/libm/EphemerisPacket.h