VRT: vrt::IndicatorFieldProvider Class Reference
vrt::IndicatorFieldProvider Class Reference
XXX Interface for working with Context/Command Indicator Fields (CIFs) XXX.
#include <IndicatorFields.h>
Public Member Functions
virtual void addCIF1 (bool add=true, bool occurrence=false)=0
Adds or removes a CIF Sets the Enable Indicator of CIF0 and adds or removes 4-bytes for the CIF.
virtual void addCIF2 (bool add=true, bool occurrence=false)=0
virtual void addCIF3 (bool add=true, bool occurrence=false)=0
virtual void addCIF7 (bool add=true, bool occurrence=false)=0
float get3DPointingVectorAzimuth (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Azimuthal Angle subfield of the Single-word 3D Pointing Vector.
float get3DPointingVectorElevation (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Elevation Angle subfield of the Single-word 3D Pointing Vector.
virtual ArrayOfRecords get3DPointingVectorStructured (IndicatorFieldEnum_t cif7field=CIF_NULL) const =0
Gets the 3D Pointing Vector (Structured) See V49.2 spec Section 9.4.1.
TimeStamp getAge (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Age The Age value and format depends on the packet timestamp format indicated by TSI and TSF fields of the Packet Prologue.
float getAirTemperature (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Air Temperature.
double getAuxBandwidth (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Auxiliary Bandwidth of the signal in Hz.
double getAuxFrequency (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Auxiliary Frequency of the signal in Hz.
float getAuxGain (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Total Auxiliary Gain of the device in dB.
float getAuxGain1 (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Stage 1 Auxiliary Gain of the device in dB.
float getAuxGain2 (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Stage 2 Auxiliary Gain of the device in dB.
double getBandOffsetIF (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the IF Band Offset of the signal in Hz.
double getBandwidth (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Bandwidth of the signal in Hz.
int32_t getBarometricPressure (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Barometric Pressure Atmospheric pressure measured in the units of Pascal.
int32_t getBindField (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Bind Indicator Field See V49.2 spec Section 9.8.1 for Bind Indicator Field.
float getBitErrorRate (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Bit Error Rate (BER).
int64_t getBufferStatus (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Buffer Size, Level, and Status (See V49.2 spec Section 9.10.7) Bits 63-32 | Buffer Sz | Size in bytes (assume 32-bit integer) Bits 31-16 | Reserved | Fixed value of 0x0 Bits 15-8 | Level | Indicates buffer utilization: empty <=> 0x0; full <=> (either 0x80 if one-hot, or 0xFF; user-defined) Bits 7-0 | Status | Used to indicate buffer underrun/overrun/etc.
int32_t getBuildVersion (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Build Version Information (See V49.2 spec Section 9.10.4) bits 31-25 | Year | Year compiled; Values map linearly such that 0 => year 2000, up to 127 => year 2127 bits 24-16 | Day | Day of year compiled; Valid values are 1..366, where 1 => Jan 1 (? 366 is for leap year/seconds?) bits 15-10 | Revision | Used to distinguish between versions made on the same day, allowing up to 64 revisions per day bits 9-0 | User Def | User defined info associated with the build.
int32_t getChildrenSID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Children SID See V49.2 spec Section 9.8.2 for Children SID.
string getChildrenSIDString (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Children SID as a string See V49.2 spec Section 9.8.2 for Children SID.
boolNull getCIF7Attribute (IndicatorFieldEnum_t cif7field, bool occurrence=false) const
int32_t getCIF7Belief (IndicatorFieldEnum_t field) const
Get CIF7 BELIEF Attribute of a field Conveys a factor conveying the degree of confidence that the probability is accurate.
int32_t getCIF7Probability (IndicatorFieldEnum_t field) const
Get CIF7 PROBABILITY Attribute of a field Conveys the probability of the selected field of being accurate or true.
virtual ArrayOfRecords getCIFsArray (IndicatorFieldEnum_t cif7field=CIF_NULL) const =0
Gets the CIFs Array Array-of-Records type (See V49.2 spec Section 9.13.1).
int32_t getCitedMessageID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Cited Message ID Used to relay, repeat or recall the information that was conveyed in a packet with the same Message ID for a Cited SID.
int32_t getCitedSID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Cited SID See V49.2 spec Section 9.8.2 for Cited SID.
string getCitedSIDString (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Cited SID as a string See V49.2 spec Section 9.8.2 for Cited SID.
int32_t getCommunicationPriorityID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Communication Priority ID Communication Priority ID is used to set a priority level to the information to be conveyed over a communication channel.
virtual ContextAssocLists getContextAssocLists (IndicatorFieldEnum_t cif7field=CIF_NULL) const =0
Gets the Context Association Lists.
int32_t getControlleeIDField (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Controllee ID Indicator Field See V49.2 spec Section 9.8.3 for Controllee ID.
UUID getControlleeUUIDField (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Controllee UUID Indicator Field See V49.2 spec Section 9.8.3 for Controllee UUID.
int32_t getControllerIDField (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Controller ID Indicator Field See V49.2 spec Section 9.8.3 for Controller ID.
UUID getControllerUUIDField (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Controller UUID Indicator Field See V49.2 spec Section 9.8.3 for Controller UUID.
int16_t getCountryCode (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Country Code The ISO 3166 Numeric code or user-defined code for a country.
virtual PayloadFormat getDataPayloadFormat (IndicatorFieldEnum_t cif7field=CIF_NULL) const =0
Gets the Data Packet Payload Format.
string getDeviceID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Device Identifier specifying the manufacturer and model of the device producing this context packet stream.
int64_t getDeviceIdentifier (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Device Identifier specifying the manufacturer and model of the device producing this context packet stream.
int32_t getDiscreteIO32 (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Discrete IO 32-bit Field (See V49.2 spec Section 9.11) All bits are user-defined.
int64_t getDiscreteIO64 (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Discrete IO 64-bit Field (See V49.2 spec Section 9.11) All bits are user-defined.
int64_t getDuration (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Duration Duration expresses the length of time that a pattern in a signal existed (Context Packets) or should exist (Command Packets).
int64_t getDwell (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Dwell Dwell expresses the length of time that a signal existed (Context Packets) or should exist (Command Packets).
float getEbN0 (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Energy per Bit to Noise Density ratio (Eb/N0).
int16_t getEmsDeviceClass (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets EMS Device Class Conveys the general type of sensor used to generate the signal such as radar, communications, beacon.
int32_t getEmsDeviceInstance (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets EMS Device Instance Unique identifier for the specific device emitting the RF signal The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
int32_t getEmsDeviceType (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets EMS Device Type Identifies the specific type of EMS device such as a WSR-88D (weather radar), EASAT Primary Surveillanec radar (air traffic control), Motorola MOTOTRBO radio (business radio) or Verizon LTE.
Ephemeris getEphemerisECEF (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the ECEF (Earth-Centered, Earth-Fixed) Ephemeris for the collector.
int32_t getEphemerisReference (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Ephemeris Reference Identifier.
Ephemeris getEphemerisRelative (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Relative Ephemeris for the collector.
int16_t getEventID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Event ID Used to enumerate the different events that impact the interpretation of information or operations.
int64_t getFallTime (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Fall Time Fall Time is the delta time from 90% of maximum deviation to 10% of maximum deviation.
double getFrequencyIF (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the IF Reference Frequency of the signal in Hz.
double getFrequencyOffsetRF (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the RF Reference Frequency Offset of the signal in Hz.
double getFrequencyRF (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the RF Reference Frequency of the signal in Hz.
int16_t getFunctionID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Function ID Used to enumerate different analog, digital and other processes performed by SID it is associated with.
int16_t getFunctionPriorityID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Function Priority ID Function Priority ID enables a prioritization schema to be expressed for using V49.2 Command Packets, such as in receiver, exciter, DSP and other device.
float getGain (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Total Gain of the device in dB.
float getGain1 (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Stage 1 Gain of the device in dB.
float getGain2 (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Stage 2 Gain of the device in dB.
Geolocation getGeolocationGPS (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Formatted GPS (Global Positioning System) Geolocation for the collector.
Geolocation getGeolocationINS (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Formatted INS (Inertial Navigation System) Geolocation for the collector.
virtual GeoSentences getGeoSentences (IndicatorFieldEnum_t cif7field=CIF_NULL) const =0
Gets the GPS ASCII "sentences".
int16_t getHealthStatus (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Health Status (See V49.2 spec Section 9.10.2) uses lower 16 bits of 32 bit word values are user defined and mapped to a defined health state.
float getHorizontalBeamwidth (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Horizontal Beamwidth in degrees.
int32_t getHumidity (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Humidity Percent humidity.
virtual IndexFieldList getIndexList (IndicatorFieldEnum_t cif7field=CIF_NULL) const =0
Gets the Index Field List.
int32_t getInformationSource (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Information Source A tag to represent different types of information sources.
int64_t getJitter (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Jitter Jitter expresses the uncertainty of the timing attribute.
int16_t getModeID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Mode ID Used to enumerate the different modes or states a node associated of the SID it is bonded to.
int16_t getModulationClass (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Modulation Class Conveys the general type of waveform used to generate a signal such as pulsed radar, pulsed linear FM radar, CW FM radar, n-ary QAM, n-ary PSK, LTE.
int16_t getModulationType (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Modulation Type Conveys more detailed modulation attributes that can be used to uniquely identify a waveform association to an EMS device and/or object.
int32_t getNetworkID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Network ID Used to associate information to be on the same network.
float getNoiseFigure (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Noise Figure of the receiver, expressed in decibels.
int64_t getOffsetTime (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Offset Time Offset Time is used to measure latency between the timestamp in the V49 Packet Prologue and the timing edge when the information in the Context Packet or Command Packet became valid.
float getOneDecibelCompressionPoint (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets 1-dB Compression Point.
int16_t getOperator (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Operator ID Provides linkage to operator enumerations Operator ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.7 for Operator ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field.
int64_t getOverRangeCount (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Over-Range Count.
int32_t getParentsSID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Parents SID See V49.2 spec Section 9.8.2 for Parents SID.
string getParentsSIDString (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Parents SID as a string See V49.2 spec Section 9.8.2 for Parents SID.
int64_t getPeriod (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Period Period expresses the time between cyclical phenomena of a signal.
float getPhaseOffset (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Phase Offset.
int32_t getPlatformClass (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Platform Class Platform ID is used to link to a generic class of the object such as ship, commercial airliner, mountain or building The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
int32_t getPlatformDisplay (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Platform Display Used to link to a graphical display item The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
int32_t getPlatformInstance (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Platform Instance Used to link to specific objects such as the United Airlines Flight 7301, Mount Shasta, or Empire State Building The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
float getPolarizationEllipticityAngle (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Polarization Ellipticity Angle in units of Radians.
float getPolarizationTiltAngle (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Polarization Tilt Angle in units of Radians.
int64_t getPulseWidth (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Pulse Width Pulse Width measures the delta time between two timing edges of a signal.
double getRange (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Range.
float getReferenceLevel (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Reference Level of the signal in dBm.
int32_t getReferencePointIdentifier (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Reference Point Identifier.
int32_t getRFFootprint (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets RF Footprint.
int32_t getRFFootprintRange (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets RF Footprint Range.
int64_t getRiseTime (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Rise Time Rise Time is the delta time from 10% of maximum deviation to 90% of maximum deviation.
double getSamplePeriod (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Sample Period (inverse of Sample Rate) in sec.
double getSampleRate (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Sample Rate in Hz.
int16_t getSeaAndSwellState (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Sea and Swell State Sea and Swell States use the Douglas sea and swell scale as officially defined by the United Kingdom MetOffice in "Fact Sheet No. 6".
float getSeaGroundTemperature (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Sea/Ground Temperature.
float getSecondOrderInputInterceptPoint (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Second-order Input Intercept Point (IIP2).
virtual ArrayOfRecords getSectorScanStep (IndicatorFieldEnum_t cif7field=CIF_NULL) const =0
Gets the Sector Scan/Step Field.
TimeStamp getShelfLife (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Shelf Life The Shelf Life value and format depends on the packet timestamp format indicated by TSI and TSF fields of the Packet Prologue.
int32_t getSiblingsSID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Siblings SID See V49.2 spec Section 9.8.2 for Siblings SID.
string getSiblingsSIDString (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Siblings SID as a string See V49.2 spec Section 9.8.2 for Siblings SID.
float getSNR (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Signal-to-Noise Ratio, expressed in decibels.
int32_t getSpatialReferenceType (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Spatial Reference Type.
int16_t getSpatialScanType (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Spatial Scan Type.
virtual SpectrumField getSpectrumField (IndicatorFieldEnum_t cif7field=CIF_NULL) const =0
Gets the Spectrum Field SpectrumField type (See V49.2 spec Section 9.6.1).
float getTemperature (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Temperature in degrees Celsius.
float getThirdOrderInputInterceptPoint (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Third-order Input Intercept Point (IIP3).
float getThreshold1 (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Stage 1 Threshold.
float getThreshold2 (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Stage 2 Threshold.
int64_t getTimeStampAdjustment (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Timestamp Adjustment in picoseconds.
int32_t getTimeStampCalibration (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Timestamp Calibration Time in seconds.
int64_t getTimestampDetails (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Timestamp Details Timestamp Details describes the timestamps used in the Context Stream and the paired Data Stream (if present).
int64_t getTimestampSkew (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Timestamp Skew Timestamp Skew conveys a time offset between channels in a system or between systems in a distributed system-of-systems architecture.
int32_t getTrackID (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Track ID A dynamic number that is generated during operations used to indicate that information from a specrum observation or a set of spectrum observations over time is associated.
int16_t getTroposphericState (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets Tropospheric State Used to enumerate the state of the troposphere.
int32_t getUserDefinedBits (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the User-Defined Bits from the State and Event Indicator Bits.
int32_t getV49SpecVersion (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets V49 Standard and Spec Compliance Number (See V49.2 spec Section 9.10.3) 0x00000001 => V49.0 0x00000002 => V49.1 0x00000003 => V49A (which implies V49.0 and V49.1) 0x00000004 => V49.2.
float getVerticalBeamwidth (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Vertical Beamwidth in degrees.
boolNull isAutomaticGainControl (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the AGC/MGC indicator flag.
boolNull isCalibratedTimeStamp (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the calibrated time indicator flag.
bool isChangePacket () const
Gets the Context Field Change Indicator.
bool isCIF1Enable (bool occurrence=0) const
Gets the CIF1 Enable Indicator.
bool isCIF2Enable (bool occurrence=0) const
Gets the CIF2 Enable Indicator.
bool isCIF3Enable (bool occurrence=0) const
Gets the CIF3 Enable Indicator.
bool isCIF7Enable (bool occurrence=0) const
Gets the CIF7 Enable Indicator.
boolNull isDataValid (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the valid data indicator flag.
boolNull isDiscontinuous (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the sample loss indicator flag.
boolNull isInvertedSpectrum (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the spectral inversion indicator flag.
boolNull isOverRange (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the over-range indicator flag.
boolNull isReferenceLocked (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the reference lock indicator flag.
boolNull isSignalDetected (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the signal detected indicator flag.
void set3DPointingVectorAzimuth (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Azimuthal Angle subfield of the Single-word 3D Pointing Vector.
void set3DPointingVectorElevation (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Elevation Angle subfield of the Single-word 3D Pointing Vector.
void set3DPointingVectorStructured (const ArrayOfRecords &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the 3D Pointing Vector (Structured) See V49.2 spec Section 9.4.1.
void setAge (const TimeStamp &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Age The Age value and format depends on the packet timestamp format indicated by TSI and TSF fields of the Packet Prologue.
void setAirTemperature (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Air Temperature.
void setAutomaticGainControl (boolNull v, IndicatorFieldEnum_t cif7field=CIF_NULL)
Optional functionality: Gets the AGC/MGC indicator flag.
void setAuxBandwidth (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Auxiliary Bandwidth of the signal in Hz.
void setAuxFrequency (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Auxiliary Frequency of the signal in Hz.
void setAuxGain (float gain1, float gain2, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Total Auxiliary Gain of the device in dB.
void setAuxGain (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Total Auxiliary Gain of the device in dB.
void setAuxGain1 (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Stage 1 Auxiliary Gain of the device in dB.
void setAuxGain2 (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Stage 2 Auxiliary Gain of the device in dB.
void setBandOffsetIF (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the IF Band Offset of the signal in Hz.
void setBandwidth (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Bandwidth of the signal in Hz.
void setBarometricPressure (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Barometric Pressure Atmospheric pressure measured in the units of Pascal.
void setBeamwidth (float hval, float vval, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Horizontal and Vertical Beamwidth in degrees.
void setBindField (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Bind Indicator Field See V49.2 spec Section 9.8.1 for Bind Indicator Field.
void setBitErrorRate (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Bit Error Rate (BER).
void setBufferStatus (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Buffer Size, Level, and Status (See V49.2 spec Section 9.10.7) Bits 63-32 | Buffer Sz | Size in bytes (assume 32-bit integer) Bits 31-16 | Reserved | Fixed value of 0x0 Bits 15-8 | Level | Indicates buffer utilization: empty <=> 0x0; full <=> (either 0x80 if one-hot, or 0xFF; user-defined) Bits 7-0 | Status | Used to indicate buffer underrun/overrun/etc.
void setBuildVersion (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Build Version Information (See V49.2 spec Section 9.10.4) bits 31-25 | Year | Year compiled; Values map linearly such that 0 => year 2000, up to 127 => year 2127 bits 24-16 | Day | Day of year compiled; Valid values are 1..366, where 1 => Jan 1 (? 366 is for leap year/seconds?) bits 15-10 | Revision | Used to distinguish between versions made on the same day, allowing up to 64 revisions per day bits 9-0 | User Def | User defined info associated with the build.
void setCalibratedTimeStamp (boolNull v, IndicatorFieldEnum_t cif7field=CIF_NULL)
Optional functionality: Sets the calibrated time indicator flag.
void setChangePacket (bool change)
Sets the Context Field Change Indicator.
void setChildrenSID (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Children SID See V49.2 spec Section 9.8.2 for Children SID.
void setChildrenSIDString (string val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Children SID from a string See V49.2 spec Section 9.8.2 for Children SID.
void setCIF7Attribute (IndicatorFieldEnum_t cif7field, bool set, bool occurrence=false)
void setCIF7Belief (IndicatorFieldEnum_t field, int32_t val)
Set CIF7 BELIEF Attribute of a field Conveys a factor conveying the degree of confidence that the probability is accurate.
void setCIF7Probability (IndicatorFieldEnum_t field, int32_t val)
Set CIF7 PROBABILITY Attribute of a field Conveys the probability of the selected field of being accurate or true.
void setCIFsArray (const ArrayOfRecords &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the CIFs Array Array-of-Records type (See V49.2 spec Section 9.13.1).
void setCitedMessageID (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Cited Message ID Used to relay, repeat or recall the information that was conveyed in a packet with the same Message ID for a Cited SID.
void setCitedSID (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Cited SID See V49.2 spec Section 9.8.2 for Cited SID.
void setCitedSIDString (string val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Cited SID from a string See V49.2 spec Section 9.8.2 for Cited SID.
void setCommunicationPriorityID (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Communication Priority ID Communication Priority ID is used to set a priority level to the information to be conveyed over a communication channel.
void setContextAssocLists (const ContextAssocLists &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Context Association Lists.
void setControlleeIDField (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Controllee ID Indicator Field See V49.2 spec Section 9.8.3 for Controllee ID.
void setControlleeUUIDField (const UUID &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Controllee UUID Indicator Field See V49.2 spec Section 9.8.3 for Controllee UUID.
void setControllerIDField (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Controller ID Indicator Field See V49.2 spec Section 9.8.3 for Controller ID.
void setControllerUUIDField (const UUID &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Controller UUID Indicator Field See V49.2 spec Section 9.8.3 for Controller UUID.
void setCountryCode (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Country Code The ISO 3166 Numeric code or user-defined code for a country.
virtual void setDataPayloadFormat (const PayloadFormat &val, IndicatorFieldEnum_t cif7field=CIF_NULL)=0
Sets the Data Packet Payload Format.
void setDataValid (boolNull v, IndicatorFieldEnum_t cif7field=CIF_NULL)
Optional functionality: Gets the valid data indicator flag.
void setDeviceID (const string &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Device Identifier specifying the manufacturer and model of the device producing this context packet stream.
void setDeviceIdentifier (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Device Identifier specifying the manufacturer and model of the device producing this context packet stream.
void setDiscontinuous (boolNull v, IndicatorFieldEnum_t cif7field=CIF_NULL)
Optional functionality: Gets the sample loss indicator flag.
void setDiscreteIO32 (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Discrete IO 32-bit Field (See V49.2 spec Section 9.11) All bits are user-defined.
void setDiscreteIO64 (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Discrete IO 64-bit Field (See V49.2 spec Section 9.11) All bits are user-defined.
void setDuration (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Duration Duration expresses the length of time that a pattern in a signal existed (Context Packets) or should exist (Command Packets).
void setDwell (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Dwell Dwell expresses the length of time that a signal existed (Context Packets) or should exist (Command Packets).
void setEbN0 (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Energy per Bit to Noise Density ratio (Eb/N0).
void setEmsDeviceClass (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets EMS Device Class Conveys the general type of sensor used to generate the signal such as radar, communications, beacon.
void setEmsDeviceInstance (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets EMS Device Instance Unique identifier for the specific device emitting the RF signal The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
void setEmsDeviceType (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets EMS Device Type Identifies the specific type of EMS device such as a WSR-88D (weather radar), EASAT Primary Surveillanec radar (air traffic control), Motorola MOTOTRBO radio (business radio) or Verizon LTE.
void setEphemerisECEF (const Ephemeris &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the ECEF (Earth-Centered, Earth-Fixed) Ephemeris for the collector.
void setEphemerisReference (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Ephemeris Reference Identifier.
void setEphemerisRelative (const Ephemeris &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Relative Ephemeris for the collector.
void setEventID (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Event ID Used to enumerate the different events that impact the interpretation of information or operations.
void setFallTime (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Fall Time Fall Time is the delta time from 90% of maximum deviation to 10% of maximum deviation.
void setFrequencyIF (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the IF Reference Frequency of the signal in Hz.
void setFrequencyOffsetRF (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the RF Reference Frequency Offset of the signal in Hz.
void setFrequencyRF (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the RF Reference Frequency of the signal in Hz.
void setFunctionID (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Function ID Used to enumerate different analog, digital and other processes performed by SID it is associated with.
void setFunctionPriorityID (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Function Priority ID Function Priority ID enables a prioritization schema to be expressed for using V49.2 Command Packets, such as in receiver, exciter, DSP and other device.
void setGain (float gain1, float gain2, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Total Gain of the device in dB.
void setGain (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Total Gain of the device in dB.
void setGain1 (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Stage 1 Gain of the device in dB.
void setGain2 (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Stage 2 Gain of the device in dB.
void setGeolocationGPS (const Geolocation &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Formatted GPS (Global Positioning System) Geolocation for the collector.
void setGeolocationINS (const Geolocation &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Formatted INS (Inertial Navigation System) Geolocation for the collector.
void setGeoSentences (const GeoSentences &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the GPS ASCII "sentences".
void setHealthStatus (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Health Status (See V49.2 spec Section 9.10.2) uses lower 16 bits of 32 bit word values are user defined and mapped to a defined health state.
void setHorizontalBeamwidth (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Horizontal Beamwidth in degrees.
void setHumidity (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Humidity Percent humidity.
void setIndexList (const IndexFieldList &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Index Field List.
void setInformationSource (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Information Source A tag to represent different types of information sources.
void setInvertedSpectrum (boolNull v, IndicatorFieldEnum_t cif7field=CIF_NULL)
Optional functionality: Gets the spectral inversion indicator flag.
void setJitter (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Jitter Jitter expresses the uncertainty of the timing attribute.
void setModeID (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Mode ID Used to enumerate the different modes or states a node associated of the SID it is bonded to.
void setModulationClass (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Modulation Class Conveys the general type of waveform used to generate a signal such as pulsed radar, pulsed linear FM radar, CW FM radar, n-ary QAM, n-ary PSK, LTE.
void setModulationType (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Modulation Type Conveys more detailed modulation attributes that can be used to uniquely identify a waveform association to an EMS device and/or object.
void setNetworkID (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Network ID Used to associate information to be on the same network.
void setNoiseFigure (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Noise Figure of the receiver, expressed in decibels.
void setOffsetTime (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Offset Time Offset Time is used to measure latency between the timestamp in the V49 Packet Prologue and the timing edge when the information in the Context Packet or Command Packet became valid.
void setOneDecibelCompressionPoint (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the 1-dB Compression Point.
void setOperator (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Operator ID Provides linkage to operator enumerations Operator ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.7 for Operator ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field.
void setOverRange (boolNull v, IndicatorFieldEnum_t cif7field=CIF_NULL)
Optional functionality: Gets the over-range indicator flag.
void setOverRangeCount (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Over-Range Count.
void setParentsSID (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Parents SID See V49.2 spec Section 9.8.2 for Parents SID.
void setParentsSIDString (string val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Parents SID from a string See V49.2 spec Section 9.8.2 for Parents SID.
void setPeriod (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Period Period expresses the time between cyclical phenomena of a signal.
void setPhaseOffset (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Phase Offset.
void setPlatformClass (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Platform Class Platform ID is used to link to a generic class of the object such as ship, commercial airliner, mountain or building The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
void setPlatformDisplay (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Platform Display Used to link to a graphical display item The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
void setPlatformInstance (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Platform Instance Used to link to specific objects such as the United Airlines Flight 7301, Mount Shasta, or Empire State Building The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
void setPolarizationEllipticityAngle (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Polarization Ellipticity Angle in units of Radians.
void setPolarizationTiltAngle (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Polarization Tilt Angle in units of Radians.
void setPulseWidth (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Pulse Width Pulse Width measures the delta time between two timing edges of a signal.
void setRange (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Range.
void setReferenceLevel (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Reference Level of the signal in dBm.
void setReferenceLocked (boolNull v, IndicatorFieldEnum_t cif7field=CIF_NULL)
Optional functionality: Gets the reference lock indicator flag.
void setReferencePointIdentifier (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Reference Point Identifier.
void setRFFootprint (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets RF Footprint.
void setRFFootprintRange (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets RF Footprint Range.
void setRiseTime (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Rise Time Rise Time is the delta time from 10% of maximum deviation to 90% of maximum deviation.
void setSamplePeriod (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Sample Period (inverse of Sample Rate) in sec.
void setSampleRate (double val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Sample Rate in Hz.
void setSeaAndSwellState (int8_t sea, int8_t swell, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Sea and Swell State Sea and Swell States use the Douglas sea and swell scale as officially defined by the United Kingdom MetOffice in "Fact Sheet No. 6".
void setSeaAndSwellState (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Sea and Swell State Sea and Swell States use the Douglas sea and swell scale as officially defined by the United Kingdom MetOffice in "Fact Sheet No. 6".
void setSeaGroundTemperature (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Sea/Ground Temperature.
void setSecondOrderInputInterceptPoint (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Second-order Input Intercept Point (IIP2).
void setSectorScanStep (const ArrayOfRecords &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Sector Scan/Step Field.
void setShelfLife (const TimeStamp &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Shelf Life The Shelf Life value and format depends on the packet timestamp format indicated by TSI and TSF fields of the Packet Prologue.
void setSiblingsSID (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Siblings SID See V49.2 spec Section 9.8.2 for Siblings SID.
void setSiblingsSIDString (string val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Siblings SID from a string See V49.2 spec Section 9.8.2 for Siblings SID.
void setSignalDetected (boolNull v, IndicatorFieldEnum_t cif7field=CIF_NULL)
Optional functionality: Gets the signal detected indicator flag.
void setSNR (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Signal-to-Noise Ratio, expressed in decibels.
void setSpatialReferenceType (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Spatial Reference Type.
void setSpatialScanType (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Spatial Scan Type.
void setSpectrumField (const SpectrumField &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Spectrum Field SpectrumField type (See V49.2 spec Section 9.6.1).
void setTemperature (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Temperature in degrees Celsius.
void setThirdOrderInputInterceptPoint (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Third-order Input Intercept Point (IIP3).
void setThreshold (float threshold1, float threshold2, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Stage 1 and Stage 2 Threshold subfields.
void setThreshold (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Stage 1 Threshold.
void setThreshold1 (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Stage 1 Threshold.
void setThreshold2 (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Stage 2 Threshold.
void setTimeStampAdjustment (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Timestamp Adjustment in picoseconds.
void setTimeStampCalibration (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Timestamp Calibration Time in seconds.
void setTimestampDetails (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Timestamp Details Timestamp Details describes the timestamps used in the Context Stream and the paired Data Stream (if present).
void setTimestampSkew (int64_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Timestamp Skew Timestamp Skew conveys a time offset between channels in a system or between systems in a distributed system-of-systems architecture.
void setTrackID (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Track ID A dynamic number that is generated during operations used to indicate that information from a specrum observation or a set of spectrum observations over time is associated.
void setTroposphericState (int16_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets Tropospheric State Used to enumerate the state of the troposphere.
void setUserDefinedBits (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the User-Defined Bits from the State and Event Indicator Bits.
void setV49SpecVersion (int32_t val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets V49 Standard and Spec Compliance Number (See V49.2 spec Section 9.10.3) 0x00000001 => V49.0 0x00000002 => V49.1 0x00000003 => V49A (which implies V49.0 and V49.1) 0x00000004 => V49.2.
void setVerticalBeamwidth (float val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Vertical Beamwidth in degrees.
Protected Member Functions
virtual int8_t getB (IndicatorFieldEnum_t field, int32_t xoff, IndicatorFieldEnum_t cif7field) const
virtual int8_t getB (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const =0
Unpacks a 16-bit integer from the payload at the indicated position.
boolNull getCIF7Bit (int32_t cif7bit, bool occurrence=false) const
virtual int32_t getCIF7Offset (int32_t attr, int32_t len, bool occurrence=0) const
Gets the offset of the CIF7 attribute, INCLUDING the attribute This offset needs to be calculated differently because a value of 0 is permitted, and we can't return -0 to indicate not present.
virtual int32_t getContextIndicatorField (IndicatorFieldEnum_t field, bool occurrence=0) const
virtual int32_t getContextIndicatorField (int8_t cifNum) const
Gets the CIF for the CIF number specified.
virtual int32_t getContextIndicatorField0 (bool occurrence=0) const =0
virtual int32_t getContextIndicatorField1 (bool occurrence=0) const =0
virtual int32_t getContextIndicatorField2 (bool occurrence=0) const =0
virtual int32_t getContextIndicatorField3 (bool occurrence=0) const =0
virtual int32_t getContextIndicatorField7 (bool occurrence=0) const =0
virtual boolNull getContextIndicatorFieldBit (int8_t cifNum, int32_t bit) const
virtual boolNull getContextIndicatorFieldBit (IndicatorFieldEnum_t field, bool occurrence=0) const
Gets a CIF bit value.
virtual Ephemeris getEphemeris (int8_t cifNum, int32_t field, int32_t cif7bit) const =0
Used for unpacking ephemeris records.
virtual int32_t getFieldLen (IndicatorFieldEnum_t field, int32_t parent=0) const
virtual int32_t getFieldLen (int8_t cifNum, int32_t field, int32_t parent=0) const =0
Gets the length of the given field when present.
virtual Geolocation getGeolocation (int8_t cifNum, int32_t field, int32_t cif7bit) const =0
Used for unpacking geolocation records.
virtual int16_t getI (IndicatorFieldEnum_t field, int32_t xoff, IndicatorFieldEnum_t cif7field) const
virtual int16_t getI (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const =0
Unpacks a 16-bit integer from the payload at the indicated position.
virtual int32_t getL (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field) const
virtual int32_t getL (int8_t cifNum, int32_t bit, int32_t cif7bit) const =0
Unpacks a 32-bit integer from the payload at the indicated position.
virtual int32_t getL24 (IndicatorFieldEnum_t field, int32_t offset, IndicatorFieldEnum_t cif7field) const
virtual int32_t getL24 (int8_t cifNum, int32_t bit, int32_t offset, int32_t cif7bit) const =0
Unpacks a 32-bit integer from the payload at the indicated position.
virtual int32_t getOffset (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field, bool occurrence) const
virtual int32_t getOffset (IndicatorFieldEnum_t field, bool occurrence) const
virtual int32_t getOffset (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field) const
virtual int32_t getOffset (int8_t cifNum, int32_t field, int32_t cif7bit) const
virtual int32_t getOffset (IndicatorFieldEnum_t field) const
virtual int32_t getOffset (int8_t cifNum, int32_t field) const =0
Gets the offset for the given context indicator field relative to the location of the first occurrence of CIF0.
virtual boolNull getStateEventBit (int32_t enable, int32_t indicator, int32_t cif7bit) const =0
Gets the specified bit from the State and Event Indicator field.
virtual TimeStamp getTimeStampField (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field) const
virtual TimeStamp getTimeStampField (int8_t cifNum, int32_t bit, int32_t cif7bit) const =0
Unpacks a TimeStamp from the payload at the indicated position.
virtual int32_t getTotalFieldSize (int32_t fieldLen, bool occurrence=0) const =0
Gets the total size of the field, including all CIF7 attributes.
virtual UUID getUUID (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field) const
virtual UUID getUUID (int8_t cifNum, int32_t bit, int32_t cif7bit) const =0
Unpacks a 128-bit UUID from the payload at the indicated position.
virtual int64_t getX (IndicatorFieldEnum_t field, IndicatorFieldEnum_t cif7field) const
virtual int64_t getX (int8_t cifNum, int32_t bit, int32_t cif7bit) const =0
Unpacks a 64-bit integer from the payload at the indicated position.
bool isCIFEnable (int8_t cifNum) const
virtual void setB (IndicatorFieldEnum_t field, int32_t xoff, int8_t val, IndicatorFieldEnum_t cif7field)
virtual void setB (int8_t cifNum, int32_t bit, int32_t xoff, int8_t val, int32_t cif7bit)=0
Packs a 16-bit integer from the payload at the indicated position.
virtual void setCIF7Bit (int32_t cif7bit, bool set, bool occurrence=false)=0
virtual void setContextIndicatorField0Bit (int32_t bit, bool set, bool occurrence=0)=0
virtual void setContextIndicatorField1Bit (int32_t bit, bool set, bool occurrence=0)=0
virtual void setContextIndicatorField2Bit (int32_t bit, bool set, bool occurrence=0)=0
virtual void setContextIndicatorField3Bit (int32_t bit, bool set, bool occurrence=0)=0
virtual void setContextIndicatorField7Bit (int32_t bit, bool set, bool occurrence=0)=0
virtual void setContextIndicatorFieldBit (int8_t cifNum, int32_t bit, bool set)
virtual void setContextIndicatorFieldBit (IndicatorFieldEnum_t field, bool set, bool occurrence=0)
Sets the header type, used with getOffset(.
virtual void setI (IndicatorFieldEnum_t field, int32_t xoff, int16_t val, IndicatorFieldEnum_t cif7field)
virtual void setI (int8_t cifNum, int32_t bit, int32_t xoff, int16_t val, int32_t cif7bit)=0
Packs a 16-bit integer from the payload at the indicated position.
virtual void setL (IndicatorFieldEnum_t field, int32_t val, IndicatorFieldEnum_t cif7field)
virtual void setL (int8_t cifNum, int32_t bit, int32_t val, int32_t cif7bit)=0
Packs a 32-bit integer from the payload at the indicated position.
void setRecord (IndicatorFieldEnum_t field, const Record *val, int32_t oldLen, IndicatorFieldEnum_t cif7field)
virtual void setRecord (int8_t cifNum, int32_t bit, const Record *val, int32_t oldLen, int32_t cif7bit)=0
Gets a block of data.
void setRecord (IndicatorFieldEnum_t field, const Record &val, int32_t oldLen, IndicatorFieldEnum_t cif7field)
void setRecord (int8_t cifNum, int32_t bit, const Record &val, int32_t oldLen, int32_t cif7bit)
Sets a block of data.
void setRecord (IndicatorFieldEnum_t field, const Record *val, IndicatorFieldEnum_t cif7field)
void setRecord (int8_t cifNum, int32_t bit, const Record *val, int32_t cif7bit)
Sets a block of data.
void setRecord (IndicatorFieldEnum_t field, const Record &val, IndicatorFieldEnum_t cif7field)
void setRecord (int8_t cifNum, int32_t bit, const Record &val, int32_t cif7bit)
Sets a block of data.
void setRecord (IndicatorFieldEnum_t field, const Record &val, const Record &old, IndicatorFieldEnum_t cif7field)
void setRecord (int8_t cifNum, int32_t bit, const Record &val, const Record &old, int32_t cif7bit)
Sets a block of data.
virtual void setStateEventBit (int32_t enable, int32_t indicator, boolNull value, int32_t cif7bit)=0
Sets the specified bit of the State and Event Indicator field.
virtual void setTimeStampField (IndicatorFieldEnum_t field, const TimeStamp &val, IndicatorFieldEnum_t cif7field)
virtual void setTimeStampField (int8_t cifNum, int32_t bit, const TimeStamp &val, int32_t cif7bit)=0
Packs a TimeStamp from the payload at the indicated position.
virtual void setUUID (IndicatorFieldEnum_t field, const UUID &val, IndicatorFieldEnum_t cif7field)
virtual void setUUID (int8_t cifNum, int32_t bit, const UUID &val, int32_t cif7bit)=0
Packs a 128-bit UUID from the payload at the indicated position.
virtual void setX (IndicatorFieldEnum_t field, int64_t val, IndicatorFieldEnum_t cif7field)
virtual void setX (int8_t cifNum, int32_t bit, int64_t val, int32_t cif7bit)=0
Packs a 64-bit integer from the payload at the indicated position.
Detailed Description
XXX Interface for working with Context/Command Indicator Fields (CIFs) XXX.
Member Function Documentation
virtual void vrt::IndicatorFieldProvider::addCIF1 (bool add = true, bool occurrence = false) [pure virtual]
Adds or removes a CIF Sets the Enable Indicator of CIF0 and adds or removes 4-bytes for the CIF.
Parameters:
add True = add CIF (default), False = remove CIF
occurrence False (0) if first occurrence (default; almost everything), True (1) if second occurrence (only Errors for BasicAcknowledgePacket)
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
float vrt::IndicatorFieldProvider::get3DPointingVectorAzimuth (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Azimuthal Angle subfield of the Single-word 3D Pointing Vector.
(See V49.2 spec Section 9.4.1)
Bits 31..16: Elevation angle in degrees; radix point to the right of bit 23; range [-90,90]
Bits 15..0: Azimuthal angle in degrees; radix point to the right of bit 7; range [0,512)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Azimuthal Angle (null if not specified).
References getI(), vrt::IndicatorFields::PNT_VECT_3D_SI, and vrt::VRTMath::toFloat16().
float vrt::IndicatorFieldProvider::get3DPointingVectorElevation (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Elevation Angle subfield of the Single-word 3D Pointing Vector.
(See V49.2 spec Section 9.4.1)
Bits 31..16: Elevation angle in degrees; radix point to the right of bit 23; range [-90,90]
Bits 15..0: Azimuthal angle in degrees; radix point to the right of bit 7; range [0,512)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Elevation Angle (null if not specified).
References getI(), vrt::IndicatorFields::PNT_VECT_3D_SI, and vrt::VRTMath::toFloat16().
virtual ArrayOfRecords vrt::IndicatorFieldProvider::get3DPointingVectorStructured (IndicatorFieldEnum_t cif7field = CIF_NULL) const [pure virtual]
Gets the 3D Pointing Vector (Structured) See V49.2 spec Section 9.4.1.
Array-of-Records format HeaderSize is either 0 or 1
Note: docs say 3 or 4, but that's inconsistent with definition of ArrayOfRecords, so ignoring that guidance 3 or 4 must include the required 3 words of every ArrayOfRecords, which is incorrect.
depends on whether optional App-Specific Header is included, which is a 32-bit word if so
optional App-Specific Header is a *Global* Index/Ref/Beam subfield NumWords/Record is either 1 or 2
depends on whether optional Index/Ref/Beam subfield is included in each record Bitmapped CIF subfield only uses bits 31 and 30
Bit 31: Set when each record includes the optional Index/Ref/Beam subfield
Bit 30: Always set; Indicates presence of 3D Pointing Vector subfield in each record, which is required App-Specific header is optional 32-bit word
as mentioned above, this is a *Global* Index/Ref/Beam subfield Each Record is at most 2 words
First 32-bit word is optional, and is the Index/Ref/Beam subfield
Second 32-bit word is required, and is the 3D Pointing Vector subfield Index/Ref/Beam subfield
Bits 31..16: Record Index (optional; 0 when global or unused in records)
Bits 15..4: Reserved
Bits 3..2: Reference (00 not specified; 01 ECEF; 10 Platform centered; 11 Array centered)
Bits 1..0: Beam (00 not specified; 01 Beam or signal direction; 10 Null; 11 reserved) 3D Pointing Vector subfield
Bits 31..16: Elevation angle in degrees; radix point to the right of bit 23; range [-90,90]
Bits 15..0: Azimuthal angle in degrees; radix point to the right of bit 7; range [0,512)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
3D Pointing Vector as an Array-of-Records (null if not specified). Note that changes to the returned object do not alter the packet.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by set3DPointingVectorStructured().
TimeStamp vrt::IndicatorFieldProvider::getAge (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Age The Age value and format depends on the packet timestamp format indicated by TSI and TSF fields of the Packet Prologue.
See V49.2 spec Section 9.7.2 for Age
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Age (null if not specified)
References vrt::IndicatorFields::AGE, and getTimeStampField().
float vrt::IndicatorFieldProvider::getAirTemperature (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Air Temperature.
Air temperature in degrees Celcius. The valid range of values is from -273.15 to +511.984375 degrees Celcius. Bits 31..16: Reserved; 0x0 Bits 15..0: 16-bit floating point value with radix point to the right of bit 6. See V49.2 spec Section 9.9.2 for Air Temperature
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Air Temperature (null if not specified).
References vrt::IndicatorFields::AIR_TEMP, getI(), and vrt::VRTMath::toFloat16().
double vrt::IndicatorFieldProvider::getAuxBandwidth (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Auxiliary Bandwidth of the signal in Hz.
(See V49.2 spec Section 9.5.16)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The aux bandwidth (null if not specified).
References vrt::IndicatorFields::AUX_BANDWIDTH, getX(), and vrt::VRTMath::toDouble64().
double vrt::IndicatorFieldProvider::getAuxFrequency (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Auxiliary Frequency of the signal in Hz.
(See V49.2 spec Section 9.5.14)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The aux frequency (null if not specified).
References vrt::IndicatorFields::AUX_FREQUENCY, getX(), and vrt::VRTMath::toDouble64().
float vrt::IndicatorFieldProvider::getAuxGain (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Total Auxiliary Gain of the device in dB.
The total aux gain is the sum of getAuxGain1() and getAuxGain2(). (See V49.2 spec Section 9.5.15)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The total aux gain (null if not specified).
References getAuxGain1(), and getAuxGain2().
float vrt::IndicatorFieldProvider::getAuxGain1 (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Stage 1 Auxiliary Gain of the device in dB.
This is a second front-end gain control/metadata field for control and reporting on anciliary hardware or processing in a single chain described by a single Stream ID. In cases where a separate Stage 1 and Stage 2 gain is not necessary, this holds the total aux gain of the system and Stage 2 Auxiliary Gain is set to zero. (See V49.2 spec Section 9.5.15)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The stage 1 aux gain (null if not specified).
References vrt::IndicatorFields::AUX_GAIN, getI(), and vrt::VRTMath::toFloat16().
Referenced by getAuxGain().
float vrt::IndicatorFieldProvider::getAuxGain2 (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Stage 2 Auxiliary Gain of the device in dB.
This is a second back-end gain control/metadata field for control and reporting on anciliary hardware or processing in a single chain described by a single Stream ID. In cases where a separate Stage 1 and Stage 2 gain is not necessary, Stage 1 Auxiliary Gain holds the total aux gain of the system and this is set to zero. (See V49.2 spec Section 9.5.15)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The stage 2 aux gain (null if not specified).
References vrt::IndicatorFields::AUX_GAIN, getI(), and vrt::VRTMath::toFloat16().
Referenced by getAuxGain().
virtual int8_t vrt::IndicatorFieldProvider::getB (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const [protected, pure virtual]
Unpacks a 16-bit integer from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by getUserDefinedBits().
double vrt::IndicatorFieldProvider::getBandOffsetIF (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the IF Band Offset of the signal in Hz.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The band offset (null if not specified).
References getX(), vrt::IndicatorFields::IF_OFFSET, and vrt::VRTMath::toDouble64().
double vrt::IndicatorFieldProvider::getBandwidth (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Bandwidth of the signal in Hz.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The bandwidth (null if not specified).
References vrt::IndicatorFields::BANDWIDTH, getX(), and vrt::VRTMath::toDouble64().
int32_t vrt::IndicatorFieldProvider::getBarometricPressure (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Barometric Pressure Atmospheric pressure measured in the units of Pascal.
Bits 31..17: Reserved; 0x0 Bits 16..0: 0x1FFFF=131071 Pascals; 0x00001=1/131071 Pascals See V49.2 spec Section 9.9.2 for Barometric Pressure
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Barometric Pressure (null if not specified)
References vrt::IndicatorFields::BAROMETRIC_PRESSURE, and getL().
int32_t vrt::IndicatorFieldProvider::getBindField (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Bind Indicator Field See V49.2 spec Section 9.8.1 for Bind Indicator Field.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Bind field (null if not specified)
References vrt::IndicatorFields::BIND, and getL().
float vrt::IndicatorFieldProvider::getBitErrorRate (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Bit Error Rate (BER).
Valid range is from -256dB to +255.984375dB (= 0x7FFE), with the maximum positive value (0x7FFF) designating the "BER not used" case. (See V49.2 spec Section 9.5.17)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The BER (null if not specified).
References vrt::IndicatorFields::EB_NO_BER, getI(), and vrt::VRTMath::toFloat16().
int64_t vrt::IndicatorFieldProvider::getBufferStatus (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Buffer Size, Level, and Status (See V49.2 spec Section 9.10.7) Bits 63-32 | Buffer Sz | Size in bytes (assume 32-bit integer) Bits 31-16 | Reserved | Fixed value of 0x0 Bits 15-8 | Level | Indicates buffer utilization: empty <=> 0x0; full <=> (either 0x80 if one-hot, or 0xFF; user-defined) Bits 7-0 | Status | Used to indicate buffer underrun/overrun/etc.
; user-defined
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Buffer Status (null if not specified)
References vrt::IndicatorFields::BUFFER_SZ, and getX().
int32_t vrt::IndicatorFieldProvider::getBuildVersion (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Build Version Information (See V49.2 spec Section 9.10.4) bits 31-25 | Year | Year compiled; Values map linearly such that 0 => year 2000, up to 127 => year 2127 bits 24-16 | Day | Day of year compiled; Valid values are 1..366, where 1 => Jan 1 (? 366 is for leap year/seconds?) bits 15-10 | Revision | Used to distinguish between versions made on the same day, allowing up to 64 revisions per day bits 9-0 | User Def | User defined info associated with the build.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Build Version code (null if not specified)
References getL(), and vrt::IndicatorFields::VER_BLD_CODE.
int32_t vrt::IndicatorFieldProvider::getChildrenSID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Children SID See V49.2 spec Section 9.8.2 for Children SID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Children SID (null if not specified)
References vrt::IndicatorFields::CHILDREN_SID, and getL().
string vrt::IndicatorFieldProvider::getChildrenSIDString (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Children SID as a string See V49.2 spec Section 9.8.2 for Children SID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Children SID (null if not specified)
References vrt::IndicatorFields::CHILDREN_SID, vrt::Utilities::format(), and getL().
int32_t vrt::IndicatorFieldProvider::getCIF7Belief (IndicatorFieldEnum_t field) const [inline]
Get CIF7 BELIEF Attribute of a field Conveys a factor conveying the degree of confidence that the probability is accurate.
Bits 31..8: Reserved (0x0) Bits 7..0: Belief % 0xFF = 100% 0x00 = 0% 0x01 = 1/255 of 100%
Parameters:
field IndicatorFieldEnum of target field
Returns:
val BELIEF value
References vrt::IndicatorFields::BELIEF, and getL().
virtual int32_t vrt::IndicatorFieldProvider::getCIF7Offset (int32_t attr, int32_t len, bool occurrence = 0) const [inline, protected, virtual]
Gets the offset of the CIF7 attribute, INCLUDING the attribute This offset needs to be calculated differently because a value of 0 is permitted, and we can't return -0 to indicate not present.
Instead, offset is from the start of the parent non-CIF7 field and includes the entire CIF7 attribute indicated. This is essentially an offset to the end of the field instead of the beginning. It can be easily adjusted by the calling function by reducing the magnitude by the length of the CIF7 attribute (i.e. getFieldLen(7,attr,len)).
Parameters:
attr CIF7 attribute bitmask
len Length of the parent field
occurrence False (0) if first occurrence (default; almost everything), True (1) if second occurrence (only Errors for BasicAcknowledgePacket)
Returns:
Offset from start of the parent field to the end of CIF7 attribute
Exceptions:
VRTException for classes that do not support CIF7.
Reimplemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
int32_t vrt::IndicatorFieldProvider::getCIF7Probability (IndicatorFieldEnum_t field) const [inline]
Get CIF7 PROBABILITY Attribute of a field Conveys the probability of the selected field of being accurate or true.
Bits 31..16: Reserved (0x0) Bits 15..8: Probability Function 0x00 = Uniformed Distribution 0x01 = Normal Distribution 0x02 to 0xFF = User Defined Bits 7..0: Probability % 0xFF = 100% 0x00 = 0% 0x01 = 1/255 of 100%
Parameters:
field IndicatorFieldEnum of target field
Returns:
val PROBABILITY value
References getL(), and vrt::IndicatorFields::PROBABILITY.
virtual ArrayOfRecords vrt::IndicatorFieldProvider::getCIFsArray (IndicatorFieldEnum_t cif7field = CIF_NULL) const [pure virtual]
Gets the CIFs Array Array-of-Records type (See V49.2 spec Section 9.13.1).
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The CIFs Array as an Array-of-Records (null if not specified). Note that changes to the returned object do not alter the packet.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setCIFsArray().
int32_t vrt::IndicatorFieldProvider::getCitedMessageID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Cited Message ID Used to relay, repeat or recall the information that was conveyed in a packet with the same Message ID for a Cited SID.
The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field. XXX See V49.2 spec Section 9.8.4 for Cited Message ID See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Cited Message ID (null if not specified)
References vrt::IndicatorFields::CITED_MESSAGE_ID, and getL().
int32_t vrt::IndicatorFieldProvider::getCitedSID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Cited SID See V49.2 spec Section 9.8.2 for Cited SID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Cited SID (null if not specified)
References vrt::IndicatorFields::CITED_SID, and getL().
string vrt::IndicatorFieldProvider::getCitedSIDString (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Cited SID as a string See V49.2 spec Section 9.8.2 for Cited SID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Cited SID (null if not specified)
References vrt::IndicatorFields::CITED_SID, vrt::Utilities::format(), and getL().
int32_t vrt::IndicatorFieldProvider::getCommunicationPriorityID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Communication Priority ID Communication Priority ID is used to set a priority level to the information to be conveyed over a communication channel.
The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field. XXX See V49.2 spec Section 9.8.10.5 for Communication Priority ID See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Communication Priority ID (null if not specified)
References vrt::IndicatorFields::COMM_PRIORITY_ID, and getL().
virtual ContextAssocLists vrt::IndicatorFieldProvider::getContextAssocLists (IndicatorFieldEnum_t cif7field = CIF_NULL) const [pure virtual]
Gets the Context Association Lists.
These lists indicate the other context/data streams associated with this one.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The context association lists (null if not specified). Note that changes to the returned object do not alter the packet.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setContextAssocLists().
virtual int32_t vrt::IndicatorFieldProvider::getContextIndicatorField (int8_t cifNum) const [inline, protected, virtual]
Gets the CIF for the CIF number specified.
May return NULL To access second occurrence of CIF, add 8 to cifNum.
Parameters:
cifNum Integer number of CIF
Returns:
Value of CIF specified if present; NULL otherwise.
Exceptions:
VRTException If the CIF number is invalid.
virtual boolNull vrt::IndicatorFieldProvider::getContextIndicatorFieldBit (IndicatorFieldEnum_t field, bool occurrence = 0) const [inline, protected, virtual]
Gets a CIF bit value.
Parameters:
field Indicator field enumeration value for field of interest
occurrence False if first occurrence (almost everything), true if second occurrence (only Errors)
Returns:
true if bit is set, false otherwise.
References vrt::IndicatorFields::getCIFBitMask(), and vrt::IndicatorFields::getCIFNumber().
int32_t vrt::IndicatorFieldProvider::getControlleeIDField (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Controllee ID Indicator Field See V49.2 spec Section 9.8.3 for Controllee ID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Controllee ID (null if not specified)
References vrt::IndicatorFields::CONTROLLEE_ID, and getL().
UUID vrt::IndicatorFieldProvider::getControlleeUUIDField (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Controllee UUID Indicator Field See V49.2 spec Section 9.8.3 for Controllee UUID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Controllee UUID (null if not specified)
References vrt::IndicatorFields::CONTROLLEE_UUID, and getUUID().
int32_t vrt::IndicatorFieldProvider::getControllerIDField (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Controller ID Indicator Field See V49.2 spec Section 9.8.3 for Controller ID.
Returns:
The Controller ID (null if not specified)
References vrt::IndicatorFields::CONTROLLER_ID, and getL().
UUID vrt::IndicatorFieldProvider::getControllerUUIDField (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Controller UUID Indicator Field See V49.2 spec Section 9.8.3 for Controller UUID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Controller UUID (null if not specified)
References vrt::IndicatorFields::CONTROLLER_UUID, and getUUID().
int16_t vrt::IndicatorFieldProvider::getCountryCode (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Country Code The ISO 3166 Numeric code or user-defined code for a country.
Bit 15: Set if user-defined country/entity code Bits 14..12: Reserved Bits 11..0: ISO 3166 or user-defined country/entity code Country Code uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.7 for Country Code See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Country Code (null if not specified)
References vrt::IndicatorFields::COUNTRY_CODE, and getI().
virtual PayloadFormat vrt::IndicatorFieldProvider::getDataPayloadFormat (IndicatorFieldEnum_t cif7field = CIF_NULL) const [pure virtual]
Gets the Data Packet Payload Format.
This specifies the format of the data in the paired data packet stream.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The payload format (null if not specified). Note that changes to the returned object do not alter the packet.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
string vrt::IndicatorFieldProvider::getDeviceID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Device Identifier specifying the manufacturer and model of the device producing this context packet stream.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The device identifier as a string (null if not specified).
References getDeviceIdentifier(), and vrt::Utilities::toStringDeviceID().
int64_t vrt::IndicatorFieldProvider::getDeviceIdentifier (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Device Identifier specifying the manufacturer and model of the device producing this context packet stream.
Returns:
The device identifier (null if not specified).
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::DEVICE_ID, and getX().
Referenced by getDeviceID().
int32_t vrt::IndicatorFieldProvider::getDiscreteIO32 (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Discrete IO 32-bit Field (See V49.2 spec Section 9.11) All bits are user-defined.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Discrete IO 32-bit field (null if not specified)
References vrt::IndicatorFields::DISCRETE_IO32, and getL().
int64_t vrt::IndicatorFieldProvider::getDiscreteIO64 (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Discrete IO 64-bit Field (See V49.2 spec Section 9.11) All bits are user-defined.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Discrete IO 64-bit field (null if not specified)
References vrt::IndicatorFields::DISCRETE_IO64, and getX().
int64_t vrt::IndicatorFieldProvider::getDuration (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Duration Duration expresses the length of time that a pattern in a signal existed (Context Packets) or should exist (Command Packets).
Duration uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Duration See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Duration (null if not specified)
References vrt::IndicatorFields::DURATION, and getX().
int64_t vrt::IndicatorFieldProvider::getDwell (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Dwell Dwell expresses the length of time that a signal existed (Context Packets) or should exist (Command Packets).
Dwell uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Dwell See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Dwell (null if not specified)
References vrt::IndicatorFields::DWELL, and getX().
float vrt::IndicatorFieldProvider::getEbN0 (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Energy per Bit to Noise Density ratio (Eb/N0).
Valid range is from -256dB to +255.984375dB (= 0x7FFE), with the maximum positive value (0x7FFF) designating the "Eb/N0 not used" case. (See V49.2 spec Section 9.5.17)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Eb/N0 (null if not specified).
References vrt::IndicatorFields::EB_NO_BER, getI(), and vrt::VRTMath::toFloat16().
int16_t vrt::IndicatorFieldProvider::getEmsDeviceClass (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets EMS Device Class Conveys the general type of sensor used to generate the signal such as radar, communications, beacon.
The enumeration may also represent sub- classes such as search radar, navigation radar, broadcast commercial FM station, SATCOM, cellular, public safety radio or military radio. EMS Device Class uses the Generic16 bit Identifier field Bits 15..14: General organization relationship {00: Coalition, 01: Known, 10: Unknown, 11: Reserved} Bit 13: Set if device is exciter Bit 12: Set if device is receiver Bits 11..0: enumeration of general type of EMS device See V49.2 spec Section 9.8.9 for EMS Device Class See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The EMS Device Class (null if not specified)
References vrt::IndicatorFields::EMS_DEVICE_CLASS, and getI().
int32_t vrt::IndicatorFieldProvider::getEmsDeviceInstance (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets EMS Device Instance Unique identifier for the specific device emitting the RF signal The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
XXX See V49.2 spec Section 9.8.9 for EMS Device Instance See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The EMS Device Instance (null if not specified)
References vrt::IndicatorFields::EMS_DEVICE_INSTANCE, and getL().
int32_t vrt::IndicatorFieldProvider::getEmsDeviceType (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets EMS Device Type Identifies the specific type of EMS device such as a WSR-88D (weather radar), EASAT Primary Surveillanec radar (air traffic control), Motorola MOTOTRBO radio (business radio) or Verizon LTE.
The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field. XXX See V49.2 spec Section 9.8.9 for EMS Device Type See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The EMS Device Type (null if not specified)
References vrt::IndicatorFields::EMS_DEVICE_TYPE, and getL().
virtual Ephemeris vrt::IndicatorFieldProvider::getEphemeris (int8_t cifNum, int32_t field, int32_t cif7bit) const [protected, pure virtual]
Used for unpacking ephemeris records.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by getEphemerisECEF(), and getEphemerisRelative().
Ephemeris vrt::IndicatorFieldProvider::getEphemerisECEF (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the ECEF (Earth-Centered, Earth-Fixed) Ephemeris for the collector.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The ephemeris information (null if not specified). Note that changes to the returned object do not alter the packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getEphemeris().
int32_t vrt::IndicatorFieldProvider::getEphemerisReference (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Ephemeris Reference Identifier.
This is used specifies the process whose origin applies to the ephemeris returned by getEphemerisRelative().
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The ephemeris information (null if not specified). Note that changes to the returned object do not alter the packet.
References vrt::IndicatorFields::EPHEM_REF, and getL().
Ephemeris vrt::IndicatorFieldProvider::getEphemerisRelative (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Relative Ephemeris for the collector.
Unlike getEphemerisECEF() which uses the ECEF coordinate system, this ephemeris is relative to a user-defined system specified by getEphemerisReference().
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The ephemeris information (null if not specified). Note that changes to the returned object do not alter the packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getEphemeris().
int16_t vrt::IndicatorFieldProvider::getEventID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Event ID Used to enumerate the different events that impact the interpretation of information or operations.
Enumerated events can represent simple or complex relationships such as signal crossing threshold or signal crossing threshold while aperture pointing at a specific location. Event ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.10.3 for Event ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Event ID (null if not specified)
References vrt::IndicatorFields::EVENT_ID, and getI().
int64_t vrt::IndicatorFieldProvider::getFallTime (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Fall Time Fall Time is the delta time from 90% of maximum deviation to 10% of maximum deviation.
Deviation is referenced to the noise floor of the signal. Fall Time uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Fall Time See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Fall Time (null if not specified)
References vrt::IndicatorFields::FALL_TIME, and getX().
virtual int32_t vrt::IndicatorFieldProvider::getFieldLen (int8_t cifNum, int32_t field, int32_t parent = 0) const [protected, pure virtual]
Gets the length of the given field when present.
Parameters:
cifNum CIF number
field CIF field bitmask
parent Length of parent CIF field (only applicable for CIF7 fields)
Returns:
length of the field. -1 if not found
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setRecord().
double vrt::IndicatorFieldProvider::getFrequencyIF (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the IF Reference Frequency of the signal in Hz.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The frequency (null if not specified).
References getX(), vrt::IndicatorFields::IF_FREQ, and vrt::VRTMath::toDouble64().
double vrt::IndicatorFieldProvider::getFrequencyOffsetRF (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the RF Reference Frequency Offset of the signal in Hz.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The frequency offset (null if not specified).
References getX(), vrt::IndicatorFields::RF_OFFSET, and vrt::VRTMath::toDouble64().
double vrt::IndicatorFieldProvider::getFrequencyRF (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the RF Reference Frequency of the signal in Hz.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The frequency (null if not specified).
References getX(), vrt::IndicatorFields::RF_FREQ, and vrt::VRTMath::toDouble64().
int16_t vrt::IndicatorFieldProvider::getFunctionID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Function ID Used to enumerate different analog, digital and other processes performed by SID it is associated with.
For example, an enumeration of the field values can convey if it is an antenna, RF receiver, ADC, channelizer, DDC, DUC, DAC, RF upconverter or other attribute. Function ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.10.1 for Function ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Function ID (null if not specified)
References vrt::IndicatorFields::FUNCTION_ID, and getI().
int16_t vrt::IndicatorFieldProvider::getFunctionPriorityID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Function Priority ID Function Priority ID enables a prioritization schema to be expressed for using V49.2 Command Packets, such as in receiver, exciter, DSP and other device.
Function Priority ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.10.4 for Function Priority ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Function Priority ID (null if not specified)
References vrt::IndicatorFields::FUNCT_PRIORITY_ID, and getI().
float vrt::IndicatorFieldProvider::getGain (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Total Gain of the device in dB.
The total gain is the sum of getGain1() and getGain2().
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The gain (null if not specified).
References getGain1(), and getGain2().
float vrt::IndicatorFieldProvider::getGain1 (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Stage 1 Gain of the device in dB.
This is the front-end gain of the system. In cases where a separate Stage 1 and Stage 2 gain is not necessary, this holds the total gain of the system and Gain 2 is set to zero.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The gain (null if not specified).
References vrt::IndicatorFields::GAIN, getI(), and vrt::VRTMath::toFloat16().
Referenced by getGain().
float vrt::IndicatorFieldProvider::getGain2 (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Stage 2 Gain of the device in dB.
This is the back-end gain of the system. In cases where a separate Stage 1 and Stage 2 gain is not necessary, the Stage 1 gain holds the total gain of the system and this is set to zero.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The gain (null if not specified).
References vrt::IndicatorFields::GAIN, getI(), and vrt::VRTMath::toFloat16().
Referenced by getGain().
virtual Geolocation vrt::IndicatorFieldProvider::getGeolocation (int8_t cifNum, int32_t field, int32_t cif7bit) const [protected, pure virtual]
Used for unpacking geolocation records.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by getGeolocationGPS(), and getGeolocationINS().
Geolocation vrt::IndicatorFieldProvider::getGeolocationGPS (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Formatted GPS (Global Positioning System) Geolocation for the collector.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The geolocation information (null if not specified). Note that changes to the returned object do not alter the packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getGeolocation().
Geolocation vrt::IndicatorFieldProvider::getGeolocationINS (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Formatted INS (Inertial Navigation System) Geolocation for the collector.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The geolocation information (null if not specified). Note that changes to the returned object do not alter the packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getGeolocation().
virtual GeoSentences vrt::IndicatorFieldProvider::getGeoSentences (IndicatorFieldEnum_t cif7field = CIF_NULL) const [pure virtual]
Gets the GPS ASCII "sentences".
These are ASCII "sentences" from a GPS (Global Positioning System) receiver, such as those conforming to NMEA-0183. Due to the great variety in GPS "sentences", this class makes little effort to do anything useful with them. Users are encouraged to use getGeolocationGPS() which essentially provides the same information, but in a consistent form.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The geolocation information (null if not specified). Note that changes to the returned object do not alter the packet.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setGeoSentences().
int16_t vrt::IndicatorFieldProvider::getHealthStatus (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Health Status (See V49.2 spec Section 9.10.2) uses lower 16 bits of 32 bit word values are user defined and mapped to a defined health state.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Health Status value (null if not specified)
References getI(), and vrt::IndicatorFields::HEALTH_STATUS.
float vrt::IndicatorFieldProvider::getHorizontalBeamwidth (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Horizontal Beamwidth in degrees.
Valid range is from 0 to 360 degrees. (See V49.2 spec Section 9.4.2)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Horizontal Beamwidth (null if not specified).
References vrt::IndicatorFields::BEAMWIDTH, getL(), and vrt::VRTMath::toFloat32().
int32_t vrt::IndicatorFieldProvider::getHumidity (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Humidity Percent humidity.
Bits 31..16: Reserved; 0x0 Bits 15..0: Percent humidity. 0xFFFF=100%; 0x0001=(1/65535)*100% See V49.2 spec Section 9.9.2 for Humidity
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Humidity (null if not specified)
References getL(), and vrt::IndicatorFields::HUMIDITY.
virtual int16_t vrt::IndicatorFieldProvider::getI (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const [protected, pure virtual]
Unpacks a 16-bit integer from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by get3DPointingVectorAzimuth(), get3DPointingVectorElevation(), getAirTemperature(), getAuxGain1(), getAuxGain2(), getBitErrorRate(), getCountryCode(), getEbN0(), getEmsDeviceClass(), getEventID(), getFunctionID(), getFunctionPriorityID(), getGain1(), getGain2(), getHealthStatus(), getModeID(), getModulationClass(), getModulationType(), getNoiseFigure(), getOneDecibelCompressionPoint(), getOperator(), getPhaseOffset(), getPolarizationEllipticityAngle(), getPolarizationTiltAngle(), getReferenceLevel(), getSeaAndSwellState(), getSeaGroundTemperature(), getSecondOrderInputInterceptPoint(), getSNR(), getSpatialScanType(), getTemperature(), getThirdOrderInputInterceptPoint(), getThreshold1(), getThreshold2(), and getTroposphericState().
virtual IndexFieldList vrt::IndicatorFieldProvider::getIndexList (IndicatorFieldEnum_t cif7field = CIF_NULL) const [pure virtual]
Gets the Index Field List.
IndexFieldList type (See V49.2 spec Section 9.3.2)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Index Field List (null if not specified). Note that changes to the returned object do not alter the packet.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setIndexList().
int32_t vrt::IndicatorFieldProvider::getInformationSource (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Information Source A tag to represent different types of information sources.
The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field. XXX See V49.2 spec Section 9.8.5 for Information Source See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Information Source (null if not specified)
References getL(), and vrt::IndicatorFields::INFORMATION_SOURCE.
int64_t vrt::IndicatorFieldProvider::getJitter (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Jitter Jitter expresses the uncertainty of the timing attribute.
The Jitter range is +/- the value expressed in the Jitter field. Jitter uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Jitter See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Jitter (null if not specified)
References getX(), and vrt::IndicatorFields::JITTER.
virtual int32_t vrt::IndicatorFieldProvider::getL (int8_t cifNum, int32_t bit, int32_t cif7bit) const [protected, pure virtual]
Unpacks a 32-bit integer from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by getBarometricPressure(), getBindField(), getBuildVersion(), getChildrenSID(), getChildrenSIDString(), getCIF7Belief(), getCIF7Probability(), getCitedMessageID(), getCitedSID(), getCitedSIDString(), getCommunicationPriorityID(), getControlleeIDField(), getControllerIDField(), getDiscreteIO32(), getEmsDeviceInstance(), getEmsDeviceType(), getEphemerisReference(), getHorizontalBeamwidth(), getHumidity(), getInformationSource(), getNetworkID(), getOverRangeCount(), getParentsSID(), getParentsSIDString(), getPlatformClass(), getPlatformDisplay(), getPlatformInstance(), getRange(), getReferencePointIdentifier(), getRFFootprint(), getRFFootprintRange(), getSiblingsSID(), getSiblingsSIDString(), getSpatialReferenceType(), getTimeStampCalibration(), getTrackID(), getV49SpecVersion(), and getVerticalBeamwidth().
virtual int32_t vrt::IndicatorFieldProvider::getL24 (int8_t cifNum, int32_t bit, int32_t offset, int32_t cif7bit) const [protected, pure virtual]
Unpacks a 32-bit integer from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
int16_t vrt::IndicatorFieldProvider::getModeID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Mode ID Used to enumerate the different modes or states a node associated of the SID it is bonded to.
For example, an enumeration of the field may convey Start, Stop, Reset, Pause, Restart, Load, Wait for Event, Zeroize information. Mode ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.10.2 for Mode ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Mode ID (null if not specified)
References getI(), and vrt::IndicatorFields::MODE_ID.
int16_t vrt::IndicatorFieldProvider::getModulationClass (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Modulation Class Conveys the general type of waveform used to generate a signal such as pulsed radar, pulsed linear FM radar, CW FM radar, n-ary QAM, n-ary PSK, LTE.
Modulation Class uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.9 for Modulation Class See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Modulation Class (null if not specified)
References getI(), and vrt::IndicatorFields::MODULATION_CLASS.
int16_t vrt::IndicatorFieldProvider::getModulationType (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Modulation Type Conveys more detailed modulation attributes that can be used to uniquely identify a waveform association to an EMS device and/or object.
Modulation Type uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.9 for Modulation Type See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Returns:
The Modulation Type (null if not specified)
References getI(), and vrt::IndicatorFields::MODULATION_TYPE.
int32_t vrt::IndicatorFieldProvider::getNetworkID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Network ID Used to associate information to be on the same network.
Network ID uses the Generic32 bit Identifier field See V49.2 spec Section 9.8.13 for Network ID See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Network ID (null if not specified)
References getL(), and vrt::IndicatorFields::NETWORK_ID.
float vrt::IndicatorFieldProvider::getNoiseFigure (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Noise Figure of the receiver, expressed in decibels.
The Noise Figure of a receiver is a measure of the reduction in the SNR between the input of the receiver (the antenna) to the output of the RF processing chain. (See V49.2 spec Section 9.5.7)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Noise Figure (null if not specified).
References getI(), vrt::IndicatorFields::SNR_NOISE, and vrt::VRTMath::toFloat16().
virtual int32_t vrt::IndicatorFieldProvider::getOffset (int8_t cifNum, int32_t field) const [protected, pure virtual]
Gets the offset for the given context indicator field relative to the location of the first occurrence of CIF0.
For access to the second occurrence of CIFs (i.e. Error fields in Ack packets), add 8 to the CIF number, effectively setting the 4th bit (mod8 gives field, div8 gives occurrence).
Parameters:
cifNum number of CIF that field belongs to.
field bitmask associated with field of interest.
Returns:
offset in bytes from beginning of CIF payload, or CIF7 as described above.
Exceptions:
VRTException If the CIF number is invalid.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by getRange(), and setUserDefinedBits().
int64_t vrt::IndicatorFieldProvider::getOffsetTime (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Offset Time Offset Time is used to measure latency between the timestamp in the V49 Packet Prologue and the timing edge when the information in the Context Packet or Command Packet became valid.
Offset Time uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Offset Time See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Offset Time (null if not specified)
References getX(), and vrt::IndicatorFields::OFFSET_TIME.
float vrt::IndicatorFieldProvider::getOneDecibelCompressionPoint (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets 1-dB Compression Point.
(See V49.2 spec Section 9.5.2)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The 1-dB Compression Point (null if not specified).
References vrt::IndicatorFields::COMPRESS_PT, getI(), and vrt::VRTMath::toFloat16().
int16_t vrt::IndicatorFieldProvider::getOperator (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Operator ID Provides linkage to operator enumerations Operator ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.7 for Operator ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Operator ID (null if not specified)
References getI(), and vrt::IndicatorFields::OPERATOR.
int64_t vrt::IndicatorFieldProvider::getOverRangeCount (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Over-Range Count.
This is the count of the number of over-range data samples in the single paired data packet.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The count (null if not specified).
References getL(), and vrt::IndicatorFields::OVER_RANGE.
int32_t vrt::IndicatorFieldProvider::getParentsSID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Parents SID See V49.2 spec Section 9.8.2 for Parents SID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Parents SID (null if not specified)
References getL(), and vrt::IndicatorFields::PARENTS_SID.
string vrt::IndicatorFieldProvider::getParentsSIDString (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Parents SID as a string See V49.2 spec Section 9.8.2 for Parents SID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Parents SID (null if not specified)
References vrt::Utilities::format(), getL(), and vrt::IndicatorFields::PARENTS_SID.
int64_t vrt::IndicatorFieldProvider::getPeriod (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Period Period expresses the time between cyclical phenomena of a signal.
Period uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Period See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Period (null if not specified)
References getX(), and vrt::IndicatorFields::PERIOD.
float vrt::IndicatorFieldProvider::getPhaseOffset (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Phase Offset.
Phase Offset is measured from the Reference Point to the Described Signal. The unit of measure for the reference level is the angle measure in units of radians. This is sometimes called Phase Difference. (See V49.2 spec Section 9.5.8)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Phase Offset (null if not specified).
References getI(), vrt::IndicatorFields::PHASE, and vrt::VRTMath::toFloat16().
int32_t vrt::IndicatorFieldProvider::getPlatformClass (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Platform Class Platform ID is used to link to a generic class of the object such as ship, commercial airliner, mountain or building The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
XXX See V49.2 spec Section 9.8.8 for Platform Class See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Platform Class (null if not specified)
References getL(), and vrt::IndicatorFields::PLATFORM_CLASS.
int32_t vrt::IndicatorFieldProvider::getPlatformDisplay (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Platform Display Used to link to a graphical display item The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
XXX See V49.2 spec Section 9.8.8 for Platform Display See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Platform Display (null if not specified)
References getL(), and vrt::IndicatorFields::PLATFORM_DISPLAY.
int32_t vrt::IndicatorFieldProvider::getPlatformInstance (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Platform Instance Used to link to specific objects such as the United Airlines Flight 7301, Mount Shasta, or Empire State Building The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
XXX See V49.2 spec Section 9.8.8 for Platform Instance See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Platform Instance (null if not specified)
References getL(), and vrt::IndicatorFields::PLATFORM_INSTANCE.
float vrt::IndicatorFieldProvider::getPolarizationEllipticityAngle (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Polarization Ellipticity Angle in units of Radians.
(See V49.2 spec Section 9.4.8)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Ellipticity Angle (null if not specified).
References getI(), vrt::IndicatorFields::POLARIZATION, and vrt::VRTMath::toFloat16().
float vrt::IndicatorFieldProvider::getPolarizationTiltAngle (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Polarization Tilt Angle in units of Radians.
(See V49.2 spec Section 9.4.8)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Tilt Angle (null if not specified).
References getI(), vrt::IndicatorFields::POLARIZATION, and vrt::VRTMath::toFloat16().
int64_t vrt::IndicatorFieldProvider::getPulseWidth (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Pulse Width Pulse Width measures the delta time between two timing edges of a signal.
It measures the time between the rising edge and falling edge of a signal or vice versa. Pulse Width uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Pulse Width See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Pulse Width (null if not specified)
References getX(), and vrt::IndicatorFields::PULSE_WIDTH.
double vrt::IndicatorFieldProvider::getRange (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Range.
(See V49.2 spec Section 9.4.10)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The range (null if not specified)
References getL(), getOffset(), vrt::IndicatorFields::RANGE, and vrt::VRTMath::toDouble32().
float vrt::IndicatorFieldProvider::getReferenceLevel (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Reference Level of the signal in dBm.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The reference level (null if not specified).
References getI(), vrt::IndicatorFields::REF_LEVEL, and vrt::VRTMath::toFloat16().
int32_t vrt::IndicatorFieldProvider::getReferencePointIdentifier (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Reference Point Identifier.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The point in the system where this context applies (null if not specified).
References getL(), and vrt::IndicatorFields::REF_POINT.
int32_t vrt::IndicatorFieldProvider::getRFFootprint (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets RF Footprint.
RF Footprint is used to portray antenna geographical footprint on Earth via a Generic32 bit Identifier field linked to a KML Class Code in a Data Extension Packet. See V49.2 spec Section 9.8.12 for RF Footprint See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The RF Footprint (null if not specified)
References getL(), and vrt::IndicatorFields::RF_FOOTPRINT.
int32_t vrt::IndicatorFieldProvider::getRFFootprintRange (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets RF Footprint Range.
RF Footprint Range is used to portray antenna geographical footprint on Earth via a Generic32 bit Identifier field linked to a KML in a Data Extension Packet. See V49.2 spec Section 9.8.12 for RF Footprint Range See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The RF Footprint Range (null if not specified)
References getL(), and vrt::IndicatorFields::RF_FOOTPRINT_RANGE.
int64_t vrt::IndicatorFieldProvider::getRiseTime (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Rise Time Rise Time is the delta time from 10% of maximum deviation to 90% of maximum deviation.
Deviation is referenced to the noise floor of the signal. Rise Time uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Rise Time See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Rise Time (null if not specified)
References getX(), and vrt::IndicatorFields::RISE_TIME.
double vrt::IndicatorFieldProvider::getSamplePeriod (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Sample Period (inverse of Sample Rate) in sec.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The sample period (null if not specified).
References getSampleRate().
double vrt::IndicatorFieldProvider::getSampleRate (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Sample Rate in Hz.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The sample rate (null if not specified).
References getX(), vrt::IndicatorFields::SAMPLE_RATE, and vrt::VRTMath::toDouble64().
Referenced by getSamplePeriod().
int16_t vrt::IndicatorFieldProvider::getSeaAndSwellState (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Sea and Swell State Sea and Swell States use the Douglas sea and swell scale as officially defined by the United Kingdom MetOffice in "Fact Sheet No. 6".
Sea and Swell States are each a number between 0 and 9. Bits 31..16: Reserved (property of all Generic16 bit Identifier fields) Bits 15..10: User Defined Bits 9..5: Swell State Bits 4..0: Sea State Sea and Swell State uses the Generic16 bit Identifier field See V49.2 spec Section 9.9.1 for Sea and Swell State See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Sea and Swell State (null if not specified)
References getI(), and vrt::IndicatorFields::SEA_AND_SWELL_STATE.
float vrt::IndicatorFieldProvider::getSeaGroundTemperature (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Sea/Ground Temperature.
Sea or ground temperature in degrees Celcius. The valid range of values is from -273.15 to +511.984375 degrees Celcius. Bits 31..16: Reserved; 0x0 Bits 15..0: 16-bit floating point value with radix point to the right of bit 6. See V49.2 spec Section 9.9.2 for Sea/Ground Temperature
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Sea/Ground Temperature (null if not specified).
References getI(), vrt::IndicatorFields::SEA_GROUND_TEMP, and vrt::VRTMath::toFloat16().
float vrt::IndicatorFieldProvider::getSecondOrderInputInterceptPoint (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Second-order Input Intercept Point (IIP2).
(See V49.2 spec Section 9.5.6)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The IIP2 (null if not specified).
References getI(), vrt::IndicatorFields::ICPT_PTS_2_3, and vrt::VRTMath::toFloat16().
virtual ArrayOfRecords vrt::IndicatorFieldProvider::getSectorScanStep (IndicatorFieldEnum_t cif7field = CIF_NULL) const [pure virtual]
Gets the Sector Scan/Step Field.
Array-of-Records type (See V49.2 spec Section 9.6.2)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Sector Scan/Step Array-of-Records (null if not specified). Note that changes to the returned object do not alter the packet.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setSectorScanStep().
TimeStamp vrt::IndicatorFieldProvider::getShelfLife (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Shelf Life The Shelf Life value and format depends on the packet timestamp format indicated by TSI and TSF fields of the Packet Prologue.
See V49.2 spec Section 9.7.2 for Shelf Life
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Shelf Life (null if not specified)
References getTimeStampField(), and vrt::IndicatorFields::SHELF_LIFE.
int32_t vrt::IndicatorFieldProvider::getSiblingsSID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Siblings SID See V49.2 spec Section 9.8.2 for Siblings SID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Siblings SID (null if not specified)
References getL(), and vrt::IndicatorFields::SIBLINGS_SID.
string vrt::IndicatorFieldProvider::getSiblingsSIDString (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Siblings SID as a string See V49.2 spec Section 9.8.2 for Siblings SID.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Siblings SID (null if not specified)
References vrt::Utilities::format(), getL(), and vrt::IndicatorFields::SIBLINGS_SID.
float vrt::IndicatorFieldProvider::getSNR (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Signal-to-Noise Ratio, expressed in decibels.
(See V49.2 spec Section 9.5.7)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The SNR (null if not specified).
References getI(), vrt::IndicatorFields::SNR_NOISE, and vrt::VRTMath::toFloat16().
int32_t vrt::IndicatorFieldProvider::getSpatialReferenceType (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Spatial Reference Type.
Spatial Reference Type uses the Generic32 bit Identifier field See V49.2 spec Section 9.8.11 for Spatial Reference Type See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Spatial Reference Type (null if not specified)
References getL(), and vrt::IndicatorFields::SPATIAL_REF_TYPE.
int16_t vrt::IndicatorFieldProvider::getSpatialScanType (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Spatial Scan Type.
Spatial Scan Type uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.11 for Spatial Scan Type See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Spatial Scan Type (null if not specified)
References getI(), and vrt::IndicatorFields::SPATIAL_SCAN_TYPE.
virtual SpectrumField vrt::IndicatorFieldProvider::getSpectrumField (IndicatorFieldEnum_t cif7field = CIF_NULL) const [pure virtual]
Gets the Spectrum Field SpectrumField type (See V49.2 spec Section 9.6.1).
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Spectrum Field (null if not specified). Note that changes to the returned object do not alter the packet.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setSpectrumField().
virtual boolNull vrt::IndicatorFieldProvider::getStateEventBit (int32_t enable, int32_t indicator, int32_t cif7bit) const [protected, pure virtual]
Gets the specified bit from the State and Event Indicator field.
Parameters:
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
cif7bit Bit position of the CIF7 attribute indicator flag.
Returns:
null if field is not present, null if the enable bit is not set, true if the enable bit is set and the indicator bit is set, false if the enable bit is set but the indicator bit is not set.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by isAutomaticGainControl(), isCalibratedTimeStamp(), isDataValid(), isDiscontinuous(), isInvertedSpectrum(), isOverRange(), isReferenceLocked(), and isSignalDetected().
float vrt::IndicatorFieldProvider::getTemperature (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Temperature in degrees Celsius.
This is used to convey the temperature of any component that may affect the described signal.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The temperature (null if not specified).
References getI(), vrt::IndicatorFields::TEMPERATURE, and vrt::VRTMath::toFloat16().
float vrt::IndicatorFieldProvider::getThirdOrderInputInterceptPoint (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Third-order Input Intercept Point (IIP3).
(See V49.2 spec Section 9.5.6)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The IIP3 (null if not specified).
References getI(), vrt::IndicatorFields::ICPT_PTS_2_3, and vrt::VRTMath::toFloat16().
float vrt::IndicatorFieldProvider::getThreshold1 (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Stage 1 Threshold.
In cases where Stage 1 and Stage 2 thresholds are not necessary, this holds the single threshold value and Stage 2 Threshold is set to zero. (See V49.2 spec Section 9.5.13)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The stage 1 threshold (null if not specified).
References getI(), vrt::IndicatorFields::THRESHOLD, and vrt::VRTMath::toFloat16().
float vrt::IndicatorFieldProvider::getThreshold2 (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Stage 2 Threshold.
In cases where Stage 1 and Stage 2 thresholds are not necessary, this shall be set to zero and Stage 1 Threshold holds the single threshold value. (See V49.2 spec Section 9.5.13)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The stage 2 threshold (null if not specified).
References getI(), vrt::IndicatorFields::THRESHOLD, and vrt::VRTMath::toFloat16().
int64_t vrt::IndicatorFieldProvider::getTimeStampAdjustment (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Timestamp Adjustment in picoseconds.
This is the required time adjustment between the time the signal was digitized (i.e. the timestamp) and the time at the reference point.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The timestamp adjustment (null if not specified).
References getX(), and vrt::IndicatorFields::TIME_ADJUST.
Referenced by vrt::BasicContextPacket::getAdjustedTimeStamp().
int32_t vrt::IndicatorFieldProvider::getTimeStampCalibration (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Timestamp Calibration Time in seconds.
This is the most recent date and time when the timestamp in the Data and Context packets was known to be correct.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The calibration time (null if not specified).
References getL(), and vrt::IndicatorFields::TIME_CALIB.
int64_t vrt::IndicatorFieldProvider::getTimestampDetails (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Timestamp Details Timestamp Details describes the timestamps used in the Context Stream and the paired Data Stream (if present).
First Word: Bits 31..24: User Defined Bits 23..19: Reserved; 0x0 Bit 18: (G) Globally applicable? Bits 17..16: (TSE Code) Type of Timestamp Epoch provided Bits 15..14: (LSH Code) Indicates the means by which leap seconds are handled in the packet timestamps Bits 13..12: (LSP Code) Indicates the number of seconds in the current day denoted by the packet timestamps Bits 11..9: (Time Source) Indicates time reference source being used Bit 8: (E) If 0, Current POSIX Time Offset is undefined. If 1, Current POSIX Time Offset conveys the difference in seconds between UTC time and POSIX time, as a signed twos-complement number, and it represents the total leap seconds count. Bits 7..0: (Current POSIX Time Offset) See Bit 8 (E) Second Word: Bits 31..0: (Timestamp Epoch) Unsigned integer value specifying the number of whole seconds, in the epoch denoted by the TSE Code, describing the start of the epoch used for timestamps in all packets to which the Timestamp Details field applies. When the TSE Code is set to Unspecified, the value in the Timestamp Epoch field has no meaning. See V49.2 spec Section 9.7.3.4 for Timestamp Details
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Timestamp Details (null if not specified)
References getX(), and vrt::IndicatorFields::TIMESTAMP_DETAILS.
virtual TimeStamp vrt::IndicatorFieldProvider::getTimeStampField (int8_t cifNum, int32_t bit, int32_t cif7bit) const [protected, pure virtual]
Unpacks a TimeStamp from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by getAge(), and getShelfLife().
int64_t vrt::IndicatorFieldProvider::getTimestampSkew (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Timestamp Skew Timestamp Skew conveys a time offset between channels in a system or between systems in a distributed system-of-systems architecture.
Timestamp Skew uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.3.2 for Timestamp Skew See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Timestamp Skew (null if not specified)
References getX(), and vrt::IndicatorFields::TIMESTAMP_SKEW.
virtual int32_t vrt::IndicatorFieldProvider::getTotalFieldSize (int32_t fieldLen, bool occurrence = 0) const [protected, pure virtual]
Gets the total size of the field, including all CIF7 attributes.
Parameters:
fieldLen Length of the field w/o including CIF7 attributes
occurrence False (0) if first occurrence (default; almost everything), True (1) if second occurrence (only Errors for BasicAcknowledgePacket)
Returns:
Length of the field including CIF7 attributes
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
int32_t vrt::IndicatorFieldProvider::getTrackID (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Track ID A dynamic number that is generated during operations used to indicate that information from a specrum observation or a set of spectrum observations over time is associated.
Track ID uses the Generic32 bit Identifier field See V49.2 spec Section 9.8.6 for Track ID See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Track ID (null if not specified)
References getL(), and vrt::IndicatorFields::TRACK_ID.
int16_t vrt::IndicatorFieldProvider::getTroposphericState (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets Tropospheric State Used to enumerate the state of the troposphere.
Tropospheric State uses the Generic16 bit Identifier field See V49.2 spec Section 9.1.1 for Tropospheric State See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Tropospheric State (null if not specified)
References getI(), and vrt::IndicatorFields::TROPOSPHERIC_STATE.
int32_t vrt::IndicatorFieldProvider::getUserDefinedBits (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the User-Defined Bits from the State and Event Indicator Bits.
The definition of these bits should be included in the documentation for the relevent packet class. Unlike other bits of the State and Event Indicator Field, there is no concept of an undefined-value for user bits if the State and Event Indicator Field is present to support some other bits. As such, zero will be returned if the State and Event Indicator Field is absent.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
true if the flag is set, false if it is not set, zero if the State and Event Indicator Field is absent.
References getB(), and vrt::IndicatorFields::STATE_EVENT.
virtual UUID vrt::IndicatorFieldProvider::getUUID (int8_t cifNum, int32_t bit, int32_t cif7bit) const [protected, pure virtual]
Unpacks a 128-bit UUID from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by getControlleeUUIDField(), and getControllerUUIDField().
int32_t vrt::IndicatorFieldProvider::getV49SpecVersion (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets V49 Standard and Spec Compliance Number (See V49.2 spec Section 9.10.3) 0x00000001 => V49.0 0x00000002 => V49.1 0x00000003 => V49A (which implies V49.0 and V49.1) 0x00000004 => V49.2.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The V49 spec version (null if not specified)
References getL(), and vrt::IndicatorFields::V49_COMPL.
float vrt::IndicatorFieldProvider::getVerticalBeamwidth (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the Vertical Beamwidth in degrees.
Valid range is from 0 to 360 degrees. (See V49.2 spec Section 9.4.2)
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Vertical Beamwidth (null if not specified).
References vrt::IndicatorFields::BEAMWIDTH, getL(), and vrt::VRTMath::toFloat32().
virtual int64_t vrt::IndicatorFieldProvider::getX (int8_t cifNum, int32_t bit, int32_t cif7bit) const [protected, pure virtual]
Unpacks a 64-bit integer from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by getAuxBandwidth(), getAuxFrequency(), getBandOffsetIF(), getBandwidth(), getBufferStatus(), getDeviceIdentifier(), getDiscreteIO64(), getDuration(), getDwell(), getFallTime(), getFrequencyIF(), getFrequencyOffsetRF(), getFrequencyRF(), getJitter(), getOffsetTime(), getPeriod(), getPulseWidth(), getRiseTime(), getSampleRate(), getTimeStampAdjustment(), getTimestampDetails(), and getTimestampSkew().
boolNull vrt::IndicatorFieldProvider::isAutomaticGainControl (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the AGC/MGC indicator flag.
    true  = AGC (automatic gain control) is being used
    false = MGC (manual gain control) is being used
    null  = This information is not available
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getStateEventBit().
boolNull vrt::IndicatorFieldProvider::isCalibratedTimeStamp (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the calibrated time indicator flag.
    true  = The time stamp in this packet is calibrated to an external reference (e.g. atomic clock)
    false = The time stamp in this packet is *not* calibrated to an external reference
            and may be inaccurate
    null  = This information is not available
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getStateEventBit().
bool vrt::IndicatorFieldProvider::isChangePacket () const [inline]
Gets the Context Field Change Indicator.
Returns:
true if anything in the packet has changed since the last context packet, false if nothing has changed since the last context packet.
Reimplemented in vrt::BasicContextPacket, and vrt::BasicControlPacket.
bool vrt::IndicatorFieldProvider::isCIF1Enable (bool occurrence = 0) const [inline]
Gets the CIF1 Enable Indicator.
Returns:
true if bit is set, false otherwise.
bool vrt::IndicatorFieldProvider::isCIF2Enable (bool occurrence = 0) const [inline]
Gets the CIF2 Enable Indicator.
Returns:
true if bit is set, false otherwise.
bool vrt::IndicatorFieldProvider::isCIF3Enable (bool occurrence = 0) const [inline]
Gets the CIF3 Enable Indicator.
Returns:
true if bit is set, false otherwise.
bool vrt::IndicatorFieldProvider::isCIF7Enable (bool occurrence = 0) const [inline]
Gets the CIF7 Enable Indicator.
Returns:
true if bit is set, false otherwise.
boolNull vrt::IndicatorFieldProvider::isDataValid (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the valid data indicator flag.
    true  = The data in the packet is valid
    false = A condition exists that *may* invalidate some or all of the data in the packet
    null  = This information is not available
Note that the definition of "valid" and "invalid" data is application specific, so it is important to conslut the documentation for the relevent packet class before using this field.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getStateEventBit().
boolNull vrt::IndicatorFieldProvider::isDiscontinuous (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the sample loss indicator flag.
    true  = One or more sample discontinuities present in the data due to processing errors
            and/or data overflow
    false = No discontinuities present
    null  = This information is not available
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getStateEventBit().
boolNull vrt::IndicatorFieldProvider::isInvertedSpectrum (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the spectral inversion indicator flag.
    true  = Signal conveyed in the payload has an inverted spectrum w.r.t. an up-stream
            reference point
    false = Spectrum is not inverted
    null  = This information is not available
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getStateEventBit().
boolNull vrt::IndicatorFieldProvider::isOverRange (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the over-range indicator flag.
    true  = The data in the payload is invalid since one or more data samples exceeded the
            range of the data item
    false = No samples over range
    null  = This information is not available
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getStateEventBit().
boolNull vrt::IndicatorFieldProvider::isReferenceLocked (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the reference lock indicator flag.
    true  = All of the phase-locked loops affecting the data are locked and stable
    false = At least one of the phase-locked loops affecting the data is not locked and stable
    null  = This information is not available
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getStateEventBit().
boolNull vrt::IndicatorFieldProvider::isSignalDetected (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline]
Gets the signal detected indicator flag.
    true  = Some signal detected in this packet
    false = No signal detected in this packet
    null  = This information is not available
Note that the definition of what constitutes a detected signal application specific, so it is important to conslut the documentation for the relevent packet class before using this field.
Parameters:
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
true if the flag is set, false if it is not set, null if this optional flag isn't specified (null is returned for all context packets).
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and getStateEventBit().
void vrt::IndicatorFieldProvider::set3DPointingVectorAzimuth (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Azimuthal Angle subfield of the Single-word 3D Pointing Vector.
If no Elevation Angle has been specified, it will be set to zero following the call to this method. If set to null, both Elevation and Azimuthal Angles will be set to null. (See V49.2 spec Section 9.4.1)
Bits 31..16: Elevation angle in degrees; radix point to the right of bit 23; range [-90,90]
Bits 15..0: Azimuthal angle in degrees; radix point to the right of bit 7; range [0,512)
Parameters:
val The Azimuthal Angle (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::PNT_VECT_3D_SI, setI(), and setL().
void vrt::IndicatorFieldProvider::set3DPointingVectorElevation (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Elevation Angle subfield of the Single-word 3D Pointing Vector.
If no Azimuthal Angle has been specified, it will be set to zero following the call to this method. If set to null, both Elevation and Azimuthal Angles will be set to null. (See V49.2 spec Section 9.4.1)
Bits 31..16: Elevation angle in degrees; radix point to the right of bit 23; range [-90,90]
Bits 15..0: Azimuthal angle in degrees; radix point to the right of bit 7; range [0,512)
Parameters:
val The Elevation Angle (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::PNT_VECT_3D_SI, setI(), and setL().
void vrt::IndicatorFieldProvider::set3DPointingVectorStructured (const ArrayOfRecords & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the 3D Pointing Vector (Structured) See V49.2 spec Section 9.4.1.
Array-of-Records format HeaderSize is either 0 or 1
Note: docs say 3 or 4, but that's inconsistent with definition of ArrayOfRecords, so ignoring that guidance 3 or 4 must include the required 3 words of every ArrayOfRecords, which is incorrect.
depends on whether optional App-Specific Header is included, which is a 32-bit word if so
optional App-Specific Header is a *Global* Index/Ref/Beam subfield NumWords/Record is either 1 or 2
depends on whether optional Index/Ref/Beam subfield is included in each record Bitmapped CIF subfield only uses bits 31 and 30
Bit 31: Set when each record includes the optional Index/Ref/Beam subfield
Bit 30: Always set; Indicates presence of 3D Pointing Vector subfield in each record, which is required App-Specific header is optional 32-bit word
as mentioned above, this is a *Global* Index/Ref/Beam subfield Each Record is at most 2 words
First 32-bit word is optional, and is the Index/Ref/Beam subfield
Second 32-bit word is required, and is the 3D Pointing Vector subfield Index/Ref/Beam subfield
Bits 31..16: Record Index (optional; 0 when global or unused in records)
Bits 15..4: Reserved
Bits 3..2: Reference (00 not specified; 01 ECEF; 10 Platform centered; 11 Array centered)
Bits 1..0: Beam (00 not specified; 01 Beam or signal direction; 10 Null; 11 reserved) 3D Pointing Vector subfield
Bits 31..16: Elevation angle in degrees; radix point to the right of bit 23; range [-90,90]
Bits 15..0: Azimuthal angle in degrees; radix point to the right of bit 7; range [0,512)
Parameters:
val The 3D Pointing Vector as an Array-of-Records (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References get3DPointingVectorStructured(), vrt::IndicatorFields::PNT_VECT_3D_ST, and setRecord().
void vrt::IndicatorFieldProvider::setAge (const TimeStamp & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Age The Age value and format depends on the packet timestamp format indicated by TSI and TSF fields of the Packet Prologue.
See V49.2 spec Section 9.7.2 for Age
Parameters:
val The Age (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::AGE, and setTimeStampField().
void vrt::IndicatorFieldProvider::setAirTemperature (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Air Temperature.
Air temperature in degrees Celcius. The valid range of values is from -273.15 to +511.984375 degrees Celcius. Bits 31..16: Reserved; 0x0 Bits 15..0: 16-bit floating point value with radix point to the right of bit 6. See V49.2 spec Section 9.9.2 for Air Temperature
Parameters:
val The Air Temperature (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::AIR_TEMP, vrt::VRTMath::fromFloat16(), and setI().
void vrt::IndicatorFieldProvider::setAutomaticGainControl (boolNull v, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Optional functionality: Gets the AGC/MGC indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException If this method is not supported or if called on a context packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setStateEventBit().
void vrt::IndicatorFieldProvider::setAuxBandwidth (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Auxiliary Bandwidth of the signal in Hz.
(See V49.2 spec Section 9.5.16)
Parameters:
val The aux bandwidth (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::AUX_BANDWIDTH, vrt::VRTMath::fromDouble64(), and setX().
void vrt::IndicatorFieldProvider::setAuxFrequency (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Auxiliary Frequency of the signal in Hz.
(See V49.2 spec Section 9.5.14)
Parameters:
val The aux frequency (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::AUX_FREQUENCY, vrt::VRTMath::fromDouble64(), and setX().
void vrt::IndicatorFieldProvider::setAuxGain (float gain1, float gain2, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Total Auxiliary Gain of the device in dB.
(See V49.2 spec Section 9.5.15)
Parameters:
gain1 The stage 1 aux gain.
gain2 The stage 2 aux gain.
cif7field (Optional) Indicator field for the CIF7 attribute.
References setAuxGain1(), and setAuxGain2().
void vrt::IndicatorFieldProvider::setAuxGain (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Total Auxiliary Gain of the device in dB.
This is effectively the same as setAuxGain(val,0) except that setAuxGain(null) will mark both aux gain values as unspecified. (Note that it is not possible to specify one of the aux gain values and leave the other as unspecified.) (See V49.2 spec Section 9.5.15)
Parameters:
val The total aux gain (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::AUX_GAIN, and setI().
void vrt::IndicatorFieldProvider::setAuxGain1 (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Stage 1 Auxiliary Gain of the device in dB.
This is a second front-end gain control/metadata field for control and reporting on anciliary hardware or processing in a single chain described by a single Stream ID. In cases where a separate Stage 1 and Stage 2 gain is not necessary, this holds the total aux gain of the system and Stage 2 Auxiliary Gain is set to zero. If no Stage 2 Auxiliary Gain has been specified, it will be set to 0 following the call to this method. (See V49.2 spec Section 9.5.15)
Parameters:
val The stage 1 aux gain (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::AUX_GAIN, vrt::VRTMath::fromFloat16(), and setI().
Referenced by setAuxGain().
void vrt::IndicatorFieldProvider::setAuxGain2 (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Stage 2 Auxiliary Gain of the device in dB.
This is a second back-end gain control/metadata field for control and reporting on anciliary hardware or processing in a single chain described by a single Stream ID. In cases where a separate Stage 1 and Stage 2 gain is not necessary, Stage 1 Auxiliary Gain holds the total aux gain of the system and this is set to zero. If no Stage 1 Auxiliary Gain has been specified, it will be set to 0 following the call to this method. (See V49.2 spec Section 9.5.15)
Parameters:
val The stage 2 aux gain (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::AUX_GAIN, vrt::VRTMath::fromFloat16(), and setI().
Referenced by setAuxGain().
virtual void vrt::IndicatorFieldProvider::setB (int8_t cifNum, int32_t bit, int32_t xoff, int8_t val, int32_t cif7bit) [protected, pure virtual]
Packs a 16-bit integer from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setUserDefinedBits().
void vrt::IndicatorFieldProvider::setBandOffsetIF (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the IF Band Offset of the signal in Hz.
Parameters:
val The band offset (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromDouble64(), vrt::IndicatorFields::IF_OFFSET, and setX().
void vrt::IndicatorFieldProvider::setBandwidth (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Bandwidth of the signal in Hz.
Parameters:
val The bandwidth (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::BANDWIDTH, vrt::VRTMath::fromDouble64(), and setX().
void vrt::IndicatorFieldProvider::setBarometricPressure (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Barometric Pressure Atmospheric pressure measured in the units of Pascal.
Bits 31..17: Reserved; 0x0 Bits 16..0: 0x1FFFF=131071 Pascals; 0x00001=1/131071 Pascals See V49.2 spec Section 9.9.2 for Barometric Pressure
Parameters:
val The Barometric Pressure (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::BAROMETRIC_PRESSURE, and setL().
void vrt::IndicatorFieldProvider::setBeamwidth (float hval, float vval, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Horizontal and Vertical Beamwidth in degrees.
Valid range is from 0 to 360 degrees. Radix point to the right of bit 7 for each 16-bit number fractional resolution: 0.0078125 (1/128) degrees Bits 31..16: Horizontal Degrees Bits 15..0: Vertical Degrees (See V49.2 spec Section 9.4.2)
Parameters:
hval The Horizontal Beamwidth (null will override vval).
vval The Vertical Beamwidth (null will override hval).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::BEAMWIDTH, vrt::VRTMath::fromFloat32(), and setL().
void vrt::IndicatorFieldProvider::setBindField (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Bind Indicator Field See V49.2 spec Section 9.8.1 for Bind Indicator Field.
Parameters:
val The Bind field (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::BIND, and setL().
void vrt::IndicatorFieldProvider::setBitErrorRate (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Bit Error Rate (BER).
Valid range is from -256dB to +255.984375dB (= 0x7FFE), with the maximum positive value (0x7FFF) designating the "BER not used" case. If no Eb/N0 has been specified, it will be set to zero following the call to this method. If set to null, both Eb/N0 and BER will be set to null. (See V49.2 spec Section 9.5.17)
Parameters:
val The BER (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::EB_NO_BER, vrt::VRTMath::fromFloat16(), setI(), and setL().
void vrt::IndicatorFieldProvider::setBufferStatus (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Buffer Size, Level, and Status (See V49.2 spec Section 9.10.7) Bits 63-32 | Buffer Sz | Size in bytes (assume 32-bit integer) Bits 31-16 | Reserved | Fixed value of 0x0 Bits 15-8 | Level | Indicates buffer utilization: empty <=> 0x0; full <=> (either 0x80 if one-hot, or 0xFF; user-defined) Bits 7-0 | Status | Used to indicate buffer underrun/overrun/etc.
; user-defined
Parameters:
val The Buffer Status (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::BUFFER_SZ, and setX().
void vrt::IndicatorFieldProvider::setBuildVersion (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Build Version Information (See V49.2 spec Section 9.10.4) bits 31-25 | Year | Year compiled; Values map linearly such that 0 => year 2000, up to 127 => year 2127 bits 24-16 | Day | Day of year compiled; Valid values are 1..366, where 1 => Jan 1 (? 366 is for leap year/seconds?) bits 15-10 | Revision | Used to distinguish between versions made on the same day, allowing up to 64 revisions per day bits 9-0 | User Def | User defined info associated with the build.
Parameters:
val The Build Version (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
Returns:
The Build Version code (null if not specified)
References setL(), and vrt::IndicatorFields::VER_BLD_CODE.
void vrt::IndicatorFieldProvider::setCalibratedTimeStamp (boolNull v, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Optional functionality: Sets the calibrated time indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException If this method is not supported or if called on a context packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setStateEventBit().
void vrt::IndicatorFieldProvider::setChangePacket (bool change) [inline]
Sets the Context Field Change Indicator.
Parameters:
change true if anything in the packet has changed since the last context packet, false if nothing has changed since the last context packet.
References vrt::IndicatorFields::CHANGE_IND, and setContextIndicatorFieldBit().
void vrt::IndicatorFieldProvider::setChildrenSID (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Children SID See V49.2 spec Section 9.8.2 for Children SID.
Parameters:
val The Children SID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::CHILDREN_SID, and setL().
Referenced by setChildrenSIDString().
void vrt::IndicatorFieldProvider::setChildrenSIDString (string val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Children SID from a string See V49.2 spec Section 9.8.2 for Children SID.
Parameters:
val The Children SID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setChildrenSID().
void vrt::IndicatorFieldProvider::setCIF7Belief (IndicatorFieldEnum_t field, int32_t val) [inline]
Set CIF7 BELIEF Attribute of a field Conveys a factor conveying the degree of confidence that the probability is accurate.
Bits 31..8: Reserved (0x0) Bits 7..0: Belief % 0xFF = 100% 0x00 = 0% 0x01 = 1/255 of 100%
Parameters:
field IndicatorFieldEnum of target field
val BELIEF value
References vrt::IndicatorFields::BELIEF, and setL().
void vrt::IndicatorFieldProvider::setCIF7Probability (IndicatorFieldEnum_t field, int32_t val) [inline]
Set CIF7 PROBABILITY Attribute of a field Conveys the probability of the selected field of being accurate or true.
Bits 31..16: Reserved (0x0) Bits 15..8: Probability Function 0x00 = Uniformed Distribution 0x01 = Normal Distribution 0x02 to 0xFF = User Defined Bits 7..0: Probability % 0xFF = 100% 0x00 = 0% 0x01 = 1/255 of 100%
Parameters:
field IndicatorFieldEnum of target field
val PROBABILITY value
References vrt::IndicatorFields::PROBABILITY, and setL().
void vrt::IndicatorFieldProvider::setCIFsArray (const ArrayOfRecords & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the CIFs Array Array-of-Records type (See V49.2 spec Section 9.13.1).
Parameters:
val The CIFs Array as an Array-of-Records (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::CIFS_ARRAY, getCIFsArray(), and setRecord().
void vrt::IndicatorFieldProvider::setCitedMessageID (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Cited Message ID Used to relay, repeat or recall the information that was conveyed in a packet with the same Message ID for a Cited SID.
The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field. XXX See V49.2 spec Section 9.8.4 for Cited Message ID See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The Cited Message ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::CITED_MESSAGE_ID, and setL().
void vrt::IndicatorFieldProvider::setCitedSID (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Cited SID See V49.2 spec Section 9.8.2 for Cited SID.
Parameters:
val The Cited SID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::CITED_SID, and setL().
Referenced by setCitedSIDString().
void vrt::IndicatorFieldProvider::setCitedSIDString (string val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Cited SID from a string See V49.2 spec Section 9.8.2 for Cited SID.
Parameters:
val The Cited SID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setCitedSID().
void vrt::IndicatorFieldProvider::setCommunicationPriorityID (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Communication Priority ID Communication Priority ID is used to set a priority level to the information to be conveyed over a communication channel.
The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field. XXX See V49.2 spec Section 9.8.10.5 for Communication Priority ID See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The Communication Priority ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::COMM_PRIORITY_ID, and setL().
void vrt::IndicatorFieldProvider::setContextAssocLists (const ContextAssocLists & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Context Association Lists.
These lists indicate the other context/data streams associated with this one.
Parameters:
val The context association lists (null if not specified). Note that changes to the
cif7field (Optional) Indicator field for the CIF7 attribute. returned object do not alter the packet.
References vrt::IndicatorFields::CONTEXT_ASOC, getContextAssocLists(), and setRecord().
virtual void vrt::IndicatorFieldProvider::setContextIndicatorFieldBit (IndicatorFieldEnum_t field, bool set, bool occurrence = 0) [inline, protected, virtual]
Sets the header type, used with getOffset(.
.) and OFFSET_TABLE.
Exceptions:
VRTException If the CIF is not enabled.
VRTException If the CIF number is invalid.
References vrt::IndicatorFields::getCIFBitMask(), and vrt::IndicatorFields::getCIFNumber().
Referenced by setChangePacket().
void vrt::IndicatorFieldProvider::setControlleeIDField (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Controllee ID Indicator Field See V49.2 spec Section 9.8.3 for Controllee ID.
Parameters:
val The Controllee ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::CONTROLLEE_ID, and setL().
void vrt::IndicatorFieldProvider::setControlleeUUIDField (const UUID & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Controllee UUID Indicator Field See V49.2 spec Section 9.8.3 for Controllee UUID.
Parameters:
val The Controllee UUID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::CONTROLLEE_UUID, and setUUID().
void vrt::IndicatorFieldProvider::setControllerIDField (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Controller ID Indicator Field See V49.2 spec Section 9.8.3 for Controller ID.
Parameters:
val The Controller ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::CONTROLLER_ID, and setL().
void vrt::IndicatorFieldProvider::setControllerUUIDField (const UUID & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Controller UUID Indicator Field See V49.2 spec Section 9.8.3 for Controller UUID.
Parameters:
val The Controller UUID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::CONTROLLER_UUID, and setUUID().
void vrt::IndicatorFieldProvider::setCountryCode (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Country Code The ISO 3166 Numeric code or user-defined code for a country.
Bit 15: Set if user-defined country/entity code Bits 14..12: Reserved Bits 11..0: ISO 3166 or user-defined country/entity code Country Code uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.7 for Country Code See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Country Code (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::COUNTRY_CODE, and setI().
virtual void vrt::IndicatorFieldProvider::setDataPayloadFormat (const PayloadFormat & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [pure virtual]
Sets the Data Packet Payload Format.
This specifies the format of the data in the paired data packet stream.
Parameters:
val The payload format (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
void vrt::IndicatorFieldProvider::setDataValid (boolNull v, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Optional functionality: Gets the valid data indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException If this method is not supported or if called on a context packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setStateEventBit().
void vrt::IndicatorFieldProvider::setDeviceID (const string & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Device Identifier specifying the manufacturer and model of the device producing this context packet stream.
Parameters:
val The device identifier as a string (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::Utilities::fromStringDeviceID(), and setDeviceIdentifier().
void vrt::IndicatorFieldProvider::setDeviceIdentifier (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Device Identifier specifying the manufacturer and model of the device producing this context packet stream.
Parameters:
val The device identifier (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::DEVICE_ID, and setX().
Referenced by setDeviceID().
void vrt::IndicatorFieldProvider::setDiscontinuous (boolNull v, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Optional functionality: Gets the sample loss indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException If this method is not supported or if called on a context packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setStateEventBit().
void vrt::IndicatorFieldProvider::setDiscreteIO32 (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Discrete IO 32-bit Field (See V49.2 spec Section 9.11) All bits are user-defined.
Parameters:
val The Discrete IO 32-bit field (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::DISCRETE_IO32, and setL().
void vrt::IndicatorFieldProvider::setDiscreteIO64 (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Discrete IO 64-bit Field (See V49.2 spec Section 9.11) All bits are user-defined.
Parameters:
val The Discrete IO 64-bit field (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::DISCRETE_IO64, and setX().
void vrt::IndicatorFieldProvider::setDuration (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Duration Duration expresses the length of time that a pattern in a signal existed (Context Packets) or should exist (Command Packets).
Duration uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Duration See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
val The Duration (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::DURATION, and setX().
void vrt::IndicatorFieldProvider::setDwell (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Dwell Dwell expresses the length of time that a signal existed (Context Packets) or should exist (Command Packets).
Dwell uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Dwell See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
val The Dwell (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::DWELL, and setX().
void vrt::IndicatorFieldProvider::setEbN0 (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Energy per Bit to Noise Density ratio (Eb/N0).
Valid range is from -256dB to +255.984375dB (= 0x7FFE), with the maximum positive value (0x7FFF) designating the "Eb/N0 not used" case. If no BER has been specified, it will be set to zero following the call to this method. If set to null, both Eb/N0 and BER will be set to null. (See V49.2 spec Section 9.5.17)
Parameters:
val The Eb/N0 (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::EB_NO_BER, vrt::VRTMath::fromFloat16(), setI(), and setL().
void vrt::IndicatorFieldProvider::setEmsDeviceClass (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets EMS Device Class Conveys the general type of sensor used to generate the signal such as radar, communications, beacon.
The enumeration may also represent sub- classes such as search radar, navigation radar, broadcast commercial FM station, SATCOM, cellular, public safety radio or military radio. EMS Device Class uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.9 for EMS Device Class See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The EMS Device Class (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::EMS_DEVICE_CLASS, and setI().
void vrt::IndicatorFieldProvider::setEmsDeviceInstance (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets EMS Device Instance Unique identifier for the specific device emitting the RF signal The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
XXX See V49.2 spec Section 9.8.9 for EMS Device Instance See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The EMS Device Instance (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::EMS_DEVICE_INSTANCE, and setL().
void vrt::IndicatorFieldProvider::setEmsDeviceType (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets EMS Device Type Identifies the specific type of EMS device such as a WSR-88D (weather radar), EASAT Primary Surveillanec radar (air traffic control), Motorola MOTOTRBO radio (business radio) or Verizon LTE.
The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field. XXX See V49.2 spec Section 9.8.9 for EMS Device Type See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The EMS Device Type (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::EMS_DEVICE_TYPE, and setL().
void vrt::IndicatorFieldProvider::setEphemerisECEF (const Ephemeris & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the ECEF (Earth-Centered, Earth-Fixed) Ephemeris for the collector.
Parameters:
val The ephemeris information (null if not specified). Note that changes to the returned object do not alter the packet.
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::ECEF_EPHEM, and setRecord().
void vrt::IndicatorFieldProvider::setEphemerisReference (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Ephemeris Reference Identifier.
This is used specifies the process whose origin applies to the ephemeris returned by getEphemerisRelative().
Parameters:
val The ephemeris information (null if not specified). Note that changes to the returned object do not alter the packet.
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::EPHEM_REF, and setL().
void vrt::IndicatorFieldProvider::setEphemerisRelative (const Ephemeris & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Relative Ephemeris for the collector.
Parameters:
val The ephemeris information (null if not specified). Note that changes to the returned object do not alter the packet.
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::REL_EPHEM, and setRecord().
void vrt::IndicatorFieldProvider::setEventID (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Event ID Used to enumerate the different events that impact the interpretation of information or operations.
Enumerated events can represent simple or complex relationships such as signal crossing threshold or signal crossing threshold while aperture pointing at a specific location. Event ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.10.3 for Event ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Event ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::EVENT_ID, and setI().
void vrt::IndicatorFieldProvider::setFallTime (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Fall Time Fall Time is the delta time from 90% of maximum deviation to 10% of maximum deviation.
Deviation is referenced to the noise floor of the signal. Fall Time uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Fall Time See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
val The Fall Time (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::FALL_TIME, and setX().
void vrt::IndicatorFieldProvider::setFrequencyIF (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the IF Reference Frequency of the signal in Hz.
Parameters:
val The frequency (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromDouble64(), vrt::IndicatorFields::IF_FREQ, and setX().
void vrt::IndicatorFieldProvider::setFrequencyOffsetRF (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the RF Reference Frequency Offset of the signal in Hz.
Parameters:
val The frequency offset (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromDouble64(), vrt::IndicatorFields::RF_OFFSET, and setX().
void vrt::IndicatorFieldProvider::setFrequencyRF (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the RF Reference Frequency of the signal in Hz.
Parameters:
val The frequency (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromDouble64(), vrt::IndicatorFields::RF_FREQ, and setX().
void vrt::IndicatorFieldProvider::setFunctionID (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Function ID Used to enumerate different analog, digital and other processes performed by SID it is associated with.
For example, an enumeration of the field values can convey if it is an antenna, RF receiver, ADC, channelizer, DDC, DUC, DAC, RF upconverter or other attribute. Function ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.10.1 for Function ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Function ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::FUNCTION_ID, and setI().
void vrt::IndicatorFieldProvider::setFunctionPriorityID (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Function Priority ID Function Priority ID enables a prioritization schema to be expressed for using V49.2 Command Packets, such as in receiver, exciter, DSP and other device.
Function Priority ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.10.4 for Function Priority ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Function Priority ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::FUNCT_PRIORITY_ID, and setI().
void vrt::IndicatorFieldProvider::setGain (float gain1, float gain2, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Total Gain of the device in dB.
Parameters:
gain1 The stage 1 gain.
gain2 The stage 2 gain.
cif7field (Optional) Indicator field for the CIF7 attribute.
References setGain1(), and setGain2().
void vrt::IndicatorFieldProvider::setGain (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Total Gain of the device in dB.
This is effectively the same as setGain(val,0) except that setGain(null) will mark both gain values as unspecified. (Note that it is not possible to specify one of the gain values and leave the other as unspecified.)
Parameters:
val The total gain (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::GAIN, and setI().
void vrt::IndicatorFieldProvider::setGain1 (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Stage 1 Gain of the device in dB.
This is the front-end gain of the system. In cases where a separate Stage 1 and Stage 2 gain is not necessary, this holds the total gain of the system and Gain 2 is set to zero. If no stage 2 gain has been specified, it will be set to 0 following the call to this method.
Parameters:
val The gain (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::GAIN, and setI().
Referenced by setGain().
void vrt::IndicatorFieldProvider::setGain2 (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Stage 2 Gain of the device in dB.
This is the back-end gain of the system. In cases where a separate Stage 1 and Stage 2 gain is not necessary, the Stage 1 gain holds the total gain of the system and this is set to zero. If no stage 1 gain has been specified, it will be set to 0 following the call to this method.
Parameters:
val The gain (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::GAIN, and setI().
Referenced by setGain().
void vrt::IndicatorFieldProvider::setGeolocationGPS (const Geolocation & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Formatted GPS (Global Positioning System) Geolocation for the collector.
Parameters:
val The geolocation information (null if not specified). Note that changes to the returned object do not alter the packet.
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::GPS_EPHEM, and setRecord().
void vrt::IndicatorFieldProvider::setGeolocationINS (const Geolocation & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Formatted INS (Inertial Navigation System) Geolocation for the collector.
Parameters:
val The geolocation information (null if not specified). Note that changes to the returned object do not alter the packet.
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::INS_EPHEM, and setRecord().
void vrt::IndicatorFieldProvider::setGeoSentences (const GeoSentences & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the GPS ASCII "sentences".
These are ASCII "sentences" from a GPS (Global Positioning System) receiver, such as those conforming to NMEA-0183. Due to the great variety in GPS "sentences", this class makes little effort to do anything useful with them. Users are encouraged to use getGeolocationGPS() which essentially provides the same information, but in a consistent form.
Parameters:
val The geolocation information (null if not specified). Note that changes to the returned object do not alter the packet.
cif7field (Optional) Indicator field for the CIF7 attribute.
References getGeoSentences(), vrt::IndicatorFields::GPS_ASCII, and setRecord().
void vrt::IndicatorFieldProvider::setHealthStatus (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Health Status (See V49.2 spec Section 9.10.2) uses lower 16 bits of 32 bit word values are user defined and mapped to a defined health state.
Parameters:
val The Health Status value (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::HEALTH_STATUS, and setI().
void vrt::IndicatorFieldProvider::setHorizontalBeamwidth (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Horizontal Beamwidth in degrees.
Valid range is from 0 to 360 degrees. (See V49.2 spec Section 9.4.2)
Parameters:
val The Horizontal Beamwidth (null if not specified, which will override Vertical Beamwidth as well).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::BEAMWIDTH, vrt::VRTMath::fromFloat32(), setI(), and setL().
void vrt::IndicatorFieldProvider::setHumidity (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Humidity Percent humidity.
Bits 31..16: Reserved; 0x0 Bits 15..0: Percent humidity. 0xFFFF=100%; 0x0001=(1/65535)*100% See V49.2 spec Section 9.9.2 for Humidity
Parameters:
val The Humidity (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::HUMIDITY, and setL().
virtual void vrt::IndicatorFieldProvider::setI (int8_t cifNum, int32_t bit, int32_t xoff, int16_t val, int32_t cif7bit) [protected, pure virtual]
Packs a 16-bit integer from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by set3DPointingVectorAzimuth(), set3DPointingVectorElevation(), setAirTemperature(), setAuxGain(), setAuxGain1(), setAuxGain2(), setBitErrorRate(), setCountryCode(), setEbN0(), setEmsDeviceClass(), setEventID(), setFunctionID(), setFunctionPriorityID(), setGain(), setGain1(), setGain2(), setHealthStatus(), setHorizontalBeamwidth(), setModeID(), setModulationClass(), setModulationType(), setNoiseFigure(), setOneDecibelCompressionPoint(), setOperator(), setPhaseOffset(), setPolarizationEllipticityAngle(), setPolarizationTiltAngle(), setReferenceLevel(), setSeaAndSwellState(), setSeaGroundTemperature(), setSecondOrderInputInterceptPoint(), setSNR(), setSpatialScanType(), setTemperature(), setThirdOrderInputInterceptPoint(), setThreshold(), setThreshold1(), setThreshold2(), setTroposphericState(), and setVerticalBeamwidth().
void vrt::IndicatorFieldProvider::setIndexList (const IndexFieldList & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Index Field List.
IndexFieldList type (See V49.2 spec Section 9.3.2)
Parameters:
val The Index Field List (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References getIndexList(), vrt::IndicatorFields::INDEX_LIST, and setRecord().
void vrt::IndicatorFieldProvider::setInformationSource (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Information Source A tag to represent different types of information sources.
The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field. XXX See V49.2 spec Section 9.8.5 for Information Source See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The Information Source (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::INFORMATION_SOURCE, and setL().
void vrt::IndicatorFieldProvider::setInvertedSpectrum (boolNull v, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Optional functionality: Gets the spectral inversion indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException If this method is not supported or if called on a context packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setStateEventBit().
void vrt::IndicatorFieldProvider::setJitter (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Jitter Jitter expresses the uncertainty of the timing attribute.
The Jitter range is +/- the value expressed in the Jitter field. Jitter uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Jitter See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
val The Jitter (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::JITTER, and setX().
virtual void vrt::IndicatorFieldProvider::setL (int8_t cifNum, int32_t bit, int32_t val, int32_t cif7bit) [protected, pure virtual]
Packs a 32-bit integer from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by set3DPointingVectorAzimuth(), set3DPointingVectorElevation(), setBarometricPressure(), setBeamwidth(), setBindField(), setBitErrorRate(), setBuildVersion(), setChildrenSID(), setCIF7Belief(), setCIF7Probability(), setCitedMessageID(), setCitedSID(), setCommunicationPriorityID(), setControlleeIDField(), setControllerIDField(), setDiscreteIO32(), setEbN0(), setEmsDeviceInstance(), setEmsDeviceType(), setEphemerisReference(), setHorizontalBeamwidth(), setHumidity(), setInformationSource(), setNetworkID(), setNoiseFigure(), setOneDecibelCompressionPoint(), setOverRangeCount(), setParentsSID(), setPhaseOffset(), setPlatformClass(), setPlatformDisplay(), setPlatformInstance(), setPolarizationEllipticityAngle(), setPolarizationTiltAngle(), setRange(), setReferencePointIdentifier(), setRFFootprint(), setRFFootprintRange(), setSecondOrderInputInterceptPoint(), setSiblingsSID(), setSNR(), setSpatialReferenceType(), setThirdOrderInputInterceptPoint(), setTimeStampCalibration(), setTrackID(), setV49SpecVersion(), and setVerticalBeamwidth().
void vrt::IndicatorFieldProvider::setModeID (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Mode ID Used to enumerate the different modes or states a node associated of the SID it is bonded to.
For example, an enumeration of the field may convey Start, Stop, Reset, Pause, Restart, Load, Wait for Event, Zeroize information. Mode ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.10.2 for Mode ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Mode ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::MODE_ID, and setI().
void vrt::IndicatorFieldProvider::setModulationClass (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Modulation Class Conveys the general type of waveform used to generate a signal such as pulsed radar, pulsed linear FM radar, CW FM radar, n-ary QAM, n-ary PSK, LTE.
Modulation Class uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.9 for Modulation Class See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Modulation Class (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::MODULATION_CLASS, and setI().
void vrt::IndicatorFieldProvider::setModulationType (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Modulation Type Conveys more detailed modulation attributes that can be used to uniquely identify a waveform association to an EMS device and/or object.
Modulation Type uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.9 for Modulation Type See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Modulation Type (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::MODULATION_TYPE, and setI().
void vrt::IndicatorFieldProvider::setNetworkID (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Network ID Used to associate information to be on the same network.
Network ID uses the Generic32 bit Identifier field See V49.2 spec Section 9.8.13 for Network ID See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The Network ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::NETWORK_ID, and setL().
void vrt::IndicatorFieldProvider::setNoiseFigure (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Noise Figure of the receiver, expressed in decibels.
The Noise Figure of a receiver is a measure of the reduction in the SNR between the input of the receiver (the antenna) to the output of the RF processing chain. If no SNR has been specified, it will be set to 0 following the call to this method. If set to null, both SNR and Noise Figure will be set to null. (See V49.2 spec Section 9.5.7)
Parameters:
val The Noise Figure (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), setI(), setL(), and vrt::IndicatorFields::SNR_NOISE.
void vrt::IndicatorFieldProvider::setOffsetTime (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Offset Time Offset Time is used to measure latency between the timestamp in the V49 Packet Prologue and the timing edge when the information in the Context Packet or Command Packet became valid.
Offset Time uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Offset Time See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
val The Offset Time (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::OFFSET_TIME, and setX().
void vrt::IndicatorFieldProvider::setOneDecibelCompressionPoint (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the 1-dB Compression Point.
(See V49.2 spec Section 9.5.2)
Parameters:
val The 1-dB Compression Point (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::COMPRESS_PT, vrt::VRTMath::fromFloat16(), setI(), and setL().
void vrt::IndicatorFieldProvider::setOperator (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Operator ID Provides linkage to operator enumerations Operator ID uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.7 for Operator ID See V49.2 spec Section 9.8 for Generic16 bit Identifier field.
Parameters:
val The Operator ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::OPERATOR, and setI().
void vrt::IndicatorFieldProvider::setOverRange (boolNull v, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Optional functionality: Gets the over-range indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException If this method is not supported or if called on a context packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setStateEventBit().
void vrt::IndicatorFieldProvider::setOverRangeCount (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Over-Range Count.
This is the count of the number of over-range data samples in the single paired data packet.
Parameters:
val The count (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::OVER_RANGE, and setL().
void vrt::IndicatorFieldProvider::setParentsSID (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Parents SID See V49.2 spec Section 9.8.2 for Parents SID.
Parameters:
val The Parents SID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::PARENTS_SID, and setL().
Referenced by setParentsSIDString().
void vrt::IndicatorFieldProvider::setParentsSIDString (string val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Parents SID from a string See V49.2 spec Section 9.8.2 for Parents SID.
Parameters:
val The Parents SID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setParentsSID().
void vrt::IndicatorFieldProvider::setPeriod (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Period Period expresses the time between cyclical phenomena of a signal.
Period uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Period See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
val The Period (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::PERIOD, and setX().
void vrt::IndicatorFieldProvider::setPhaseOffset (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Phase Offset.
Phase Offset is measured from the Reference Point to the Described Signal. The unit of measure for the reference level is the angle measure in units of radians. This is sometimes called Phase Difference. (See V49.2 spec Section 9.5.8)
Parameters:
val The Phase Offset (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::PHASE, setI(), and setL().
void vrt::IndicatorFieldProvider::setPlatformClass (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Platform Class Platform ID is used to link to a generic class of the object such as ship, commercial airliner, mountain or building The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
XXX See V49.2 spec Section 9.8.8 for Platform Class See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The Platform Class (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::PLATFORM_CLASS, and setL().
void vrt::IndicatorFieldProvider::setPlatformDisplay (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Platform Display Used to link to a graphical display item The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
XXX See V49.2 spec Section 9.8.8 for Platform Display See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The Platform Display (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::PLATFORM_DISPLAY, and setL().
void vrt::IndicatorFieldProvider::setPlatformInstance (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Platform Instance Used to link to specific objects such as the United Airlines Flight 7301, Mount Shasta, or Empire State Building The V49.2 spec does not specify, but it is assumed that the Generic32 bit Identifier field is used for this field.
XXX See V49.2 spec Section 9.8.8 for Platform Instance See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The Platform Instance (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::PLATFORM_INSTANCE, and setL().
void vrt::IndicatorFieldProvider::setPolarizationEllipticityAngle (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Polarization Ellipticity Angle in units of Radians.
If no Tilt Angle has been specified, it will be set to zero following the call to this method. If set to null, both Tilt and Ellipticity Angles will be set to null. (See V49.2 spec Section 9.4.8)
Parameters:
val The Ellipticity Angle (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::POLARIZATION, setI(), and setL().
void vrt::IndicatorFieldProvider::setPolarizationTiltAngle (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Polarization Tilt Angle in units of Radians.
If no Ellipticity Angle has been specified, it will be set to zero following the call to this method. If set to null, both Tilt and Ellipticity Angles will be set to null. (See V49.2 spec Section 9.4.8)
Parameters:
val The Tilt Angle (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::POLARIZATION, setI(), and setL().
void vrt::IndicatorFieldProvider::setPulseWidth (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Pulse Width Pulse Width measures the delta time between two timing edges of a signal.
It measures the time between the rising edge and falling edge of a signal or vice versa. Pulse Width uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Pulse Width See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
val The Pulse Width (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::PULSE_WIDTH, and setX().
void vrt::IndicatorFieldProvider::setRange (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Range.
(See V49.2 spec Section 9.4.10)
Parameters:
val The range (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromDouble32(), vrt::IndicatorFields::RANGE, and setL().
virtual void vrt::IndicatorFieldProvider::setRecord (int8_t cifNum, int32_t bit, const Record * val, int32_t oldLen, int32_t cif7bit) [protected, pure virtual]
Gets a block of data.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
void vrt::IndicatorFieldProvider::setRecord (int8_t cifNum, int32_t bit, const Record & val, int32_t oldLen, int32_t cif7bit) [inline, protected]
Sets a block of data.
References setRecord().
void vrt::IndicatorFieldProvider::setRecord (int8_t cifNum, int32_t bit, const Record * val, int32_t cif7bit) [inline, protected]
Sets a block of data.
References getFieldLen(), and setRecord().
void vrt::IndicatorFieldProvider::setRecord (int8_t cifNum, int32_t bit, const Record & val, int32_t cif7bit) [inline, protected]
Sets a block of data.
References getFieldLen(), and setRecord().
void vrt::IndicatorFieldProvider::setRecord (int8_t cifNum, int32_t bit, const Record & val, const Record & old, int32_t cif7bit) [inline, protected]
Sets a block of data.
References vrt::Record::getByteLength().
Referenced by set3DPointingVectorStructured(), setCIFsArray(), setContextAssocLists(), setEphemerisECEF(), setEphemerisRelative(), setGeolocationGPS(), setGeolocationINS(), setGeoSentences(), setIndexList(), setRecord(), setSectorScanStep(), and setSpectrumField().
void vrt::IndicatorFieldProvider::setReferenceLevel (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Reference Level of the signal in dBm.
Parameters:
val The reference level (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::REF_LEVEL, and setI().
void vrt::IndicatorFieldProvider::setReferenceLocked (boolNull v, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Optional functionality: Gets the reference lock indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException If this method is not supported or if called on a context packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setStateEventBit().
void vrt::IndicatorFieldProvider::setReferencePointIdentifier (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Reference Point Identifier.
Parameters:
val The point in the system where this context applies (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::REF_POINT, and setL().
void vrt::IndicatorFieldProvider::setRFFootprint (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets RF Footprint.
RF Footprint is used to portray antenna geographical footprint on Earth via a Generic32 bit Identifier field linked to a KML Class Code in a Data Extension Packet. See V49.2 spec Section 9.8.12 for RF Footprint See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The RF Footprint (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::RF_FOOTPRINT, and setL().
void vrt::IndicatorFieldProvider::setRFFootprintRange (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets RF Footprint Range.
RF Footprint Range is used to portray antenna geographical footprint on Earth via a Generic32 bit Identifier field linked to a KML in a Data Extension Packet. See V49.2 spec Section 9.8.12 for RF Footprint Range See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The RF Footprint Range (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::RF_FOOTPRINT_RANGE, and setL().
void vrt::IndicatorFieldProvider::setRiseTime (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Rise Time Rise Time is the delta time from 10% of maximum deviation to 90% of maximum deviation.
Deviation is referenced to the noise floor of the signal. Rise Time uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.1 for Rise Time See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
val The Rise Time (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::RISE_TIME, and setX().
void vrt::IndicatorFieldProvider::setSamplePeriod (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Sample Period (inverse of Sample Rate) in sec.
Parameters:
val The sample period (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References setSampleRate().
void vrt::IndicatorFieldProvider::setSampleRate (double val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Sample Rate in Hz.
Parameters:
val The sample rate (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromDouble64(), vrt::IndicatorFields::SAMPLE_RATE, and setX().
Referenced by setSamplePeriod().
void vrt::IndicatorFieldProvider::setSeaAndSwellState (int8_t sea, int8_t swell, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Sea and Swell State Sea and Swell States use the Douglas sea and swell scale as officially defined by the United Kingdom MetOffice in "Fact Sheet No. 6".
Sea and Swell States are each a number between 0 and 9. Bits 31..16: Reserved (property of all Generic16 bit Identifier fields) Bits 15..10: User Defined Bits 9..5: Swell State Bits 4..0: Sea State Sea and Swell State uses the Generic16 bit Identifier field See V49.2 spec Section 9.9.1 for Sea and Swell State See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
sea The Sea State [0 to 9], not null
swell The Swell State [0 to 9], not null
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException if either parameter is invalid, including null
References vrt::IndicatorFields::SEA_AND_SWELL_STATE, and setI().
void vrt::IndicatorFieldProvider::setSeaAndSwellState (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Sea and Swell State Sea and Swell States use the Douglas sea and swell scale as officially defined by the United Kingdom MetOffice in "Fact Sheet No. 6".
Sea and Swell States are each a number between 0 and 9. Bits 31..16: Reserved (property of all Generic16 bit Identifier fields) Bits 15..10: User Defined Bits 9..5: Swell State Bits 4..0: Sea State Sea and Swell State uses the Generic16 bit Identifier field See V49.2 spec Section 9.9.1 for Sea and Swell State See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Sea and Swell State (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException if parameter contains invalid sea or swell values
References vrt::IndicatorFields::SEA_AND_SWELL_STATE, and setI().
void vrt::IndicatorFieldProvider::setSeaGroundTemperature (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Sea/Ground Temperature.
Sea or ground temperature in degrees Celcius. The valid range of values is from -273.15 to +511.984375 degrees Celcius. Bits 31..16: Reserved; 0x0 Bits 15..0: 16-bit floating point value with radix point to the right of bit 6. See V49.2 spec Section 9.9.2 for Sea/Ground Temperature
Parameters:
val The Sea/Ground Temperature (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::SEA_GROUND_TEMP, and setI().
void vrt::IndicatorFieldProvider::setSecondOrderInputInterceptPoint (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Second-order Input Intercept Point (IIP2).
If no IIP3 has been specified, it will be set to 0 following the call to this method. If set to null, both IIP2 and IIP3 will be set to null. (See V49.2 spec Section 9.5.6)
Parameters:
val The IIP2 (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::ICPT_PTS_2_3, setI(), and setL().
void vrt::IndicatorFieldProvider::setSectorScanStep (const ArrayOfRecords & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Sector Scan/Step Field.
Array-of-Records type (See V49.2 spec Section 9.6.2)
Parameters:
val The Sector Scan/Step Array-of-Records (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References getSectorScanStep(), vrt::IndicatorFields::SECTOR_SCN_STP, and setRecord().
void vrt::IndicatorFieldProvider::setShelfLife (const TimeStamp & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Shelf Life The Shelf Life value and format depends on the packet timestamp format indicated by TSI and TSF fields of the Packet Prologue.
See V49.2 spec Section 9.7.2 for Shelf Life
Parameters:
val The Shelf Life (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setTimeStampField(), and vrt::IndicatorFields::SHELF_LIFE.
void vrt::IndicatorFieldProvider::setSiblingsSID (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Siblings SID See V49.2 spec Section 9.8.2 for Siblings SID.
Parameters:
val The Siblings SID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setL(), and vrt::IndicatorFields::SIBLINGS_SID.
Referenced by setSiblingsSIDString().
void vrt::IndicatorFieldProvider::setSiblingsSIDString (string val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Siblings SID from a string See V49.2 spec Section 9.8.2 for Siblings SID.
Parameters:
val The Siblings SID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setSiblingsSID().
void vrt::IndicatorFieldProvider::setSignalDetected (boolNull v, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Optional functionality: Gets the signal detected indicator flag.
Parameters:
v true if the flag is set, false if not set, null if this optional flag isn't specified.
cif7field (Optional) Indicator field for the CIF7 attribute.
Exceptions:
VRTException If this method is not supported or if called on a context packet.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), and setStateEventBit().
void vrt::IndicatorFieldProvider::setSNR (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Signal-to-Noise Ratio, expressed in decibels.
If no Noise Figure has been specified, it will be set to 0 following the call to this method. If set to null, both SNR and Noise Figure will be set to null. (See V49.2 spec Section 9.5.7)
Parameters:
val The SNR (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), setI(), setL(), and vrt::IndicatorFields::SNR_NOISE.
void vrt::IndicatorFieldProvider::setSpatialReferenceType (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Spatial Reference Type.
Spatial Reference Type uses the Generic32 bit Identifier field See V49.2 spec Section 9.8.11 for Spatial Reference Type See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The Spatial Reference Type (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setL(), and vrt::IndicatorFields::SPATIAL_REF_TYPE.
void vrt::IndicatorFieldProvider::setSpatialScanType (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Spatial Scan Type.
Spatial Scan Type uses the Generic16 bit Identifier field See V49.2 spec Section 9.8.11 for Spatial Scan Type See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Spatial Scan Type (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setI(), and vrt::IndicatorFields::SPATIAL_SCAN_TYPE.
void vrt::IndicatorFieldProvider::setSpectrumField (const SpectrumField & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Spectrum Field SpectrumField type (See V49.2 spec Section 9.6.1).
Parameters:
val The Spectrum Field (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References getSpectrumField(), setRecord(), and vrt::IndicatorFields::SPECTRUM.
virtual void vrt::IndicatorFieldProvider::setStateEventBit (int32_t enable, int32_t indicator, boolNull value, int32_t cif7bit) [protected, pure virtual]
Sets the specified bit of the State and Event Indicator field.
Parameters:
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
value The value of the bits: null if the enable bit should not be set, true if the enable bit and the indicator bit should be set, false if the enable bit should be set but the indicator bit should not be set.
cif7bit Bit position of the CIF7 attribute indicator flag.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setAutomaticGainControl(), setCalibratedTimeStamp(), setDataValid(), setDiscontinuous(), setInvertedSpectrum(), setOverRange(), setReferenceLocked(), and setSignalDetected().
void vrt::IndicatorFieldProvider::setTemperature (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Temperature in degrees Celsius.
This is used to convey the temperature of any component that may affect the described signal.
Parameters:
val The temperature (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), setI(), and vrt::IndicatorFields::TEMPERATURE.
void vrt::IndicatorFieldProvider::setThirdOrderInputInterceptPoint (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Third-order Input Intercept Point (IIP3).
If no IIP2 has been specified, it will be set to 0 following the call to this method. If set to null, both IIP2 and IIP3 will be set to null. (See V49.2 spec Section 9.5.6)
Parameters:
val The IIP3 (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), vrt::IndicatorFields::ICPT_PTS_2_3, setI(), and setL().
void vrt::IndicatorFieldProvider::setThreshold (float threshold1, float threshold2, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Stage 1 and Stage 2 Threshold subfields.
(See V49.2 spec Section 9.5.13)
Parameters:
threshold1 The stage 1 threshold.
threshold2 The stage 2 threshold.
cif7field (Optional) Indicator field for the CIF7 attribute.
References setThreshold1(), and setThreshold2().
void vrt::IndicatorFieldProvider::setThreshold (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Stage 1 Threshold.
This is effectively the same as setThreshold(val,0) except that setThreshold(null) will mark both threshold values as unspecified. (Note that it is not possible to specify one of the threshold values and leave the other as unspecified.) (See V49.2 spec Section 9.5.13)
Parameters:
val The total threshold (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References setI(), and vrt::IndicatorFields::THRESHOLD.
void vrt::IndicatorFieldProvider::setThreshold1 (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Stage 1 Threshold.
In cases where Stage 1 and Stage 2 thresholds are not necessary, this holds the single threshold value and Stage 2 Threshold is set to zero. If no Stage 2 Threshold has been specified, it will be set to zero following the call to this method. (See V49.2 spec Section 9.5.13)
Parameters:
val The stage 1 threshold (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), setI(), and vrt::IndicatorFields::THRESHOLD.
Referenced by setThreshold().
void vrt::IndicatorFieldProvider::setThreshold2 (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Stage 2 Threshold.
In cases where Stage 1 and Stage 2 thresholds are not necessary, this shall be set to zero and Stage 1 Threshold holds the single threshold value. If no Stage 1 Threshold has been specified, it will be set to zero following the call to this method. (See V49.2 spec Section 9.5.13)
Parameters:
val The stage 2 threshold (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::VRTMath::fromFloat16(), setI(), and vrt::IndicatorFields::THRESHOLD.
Referenced by setThreshold().
void vrt::IndicatorFieldProvider::setTimeStampAdjustment (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Timestamp Adjustment in picoseconds.
This is the required time adjustment between the time the signal was digitized (i.e. the timestamp) and the time at the reference point.
Parameters:
val The timestamp adjustment (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References setX(), and vrt::IndicatorFields::TIME_ADJUST.
void vrt::IndicatorFieldProvider::setTimeStampCalibration (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Timestamp Calibration Time in seconds.
This is the most recent date and time when the timestamp in the Data and Context packets was known to be correct.
Parameters:
val The calibration time (null if not specified).
cif7field (Optional) Indicator field for the CIF7 attribute.
References setL(), and vrt::IndicatorFields::TIME_CALIB.
void vrt::IndicatorFieldProvider::setTimestampDetails (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Timestamp Details Timestamp Details describes the timestamps used in the Context Stream and the paired Data Stream (if present).
First Word: Bits 31..24: User Defined Bits 23..19: Reserved; 0x0 Bit 18: (G) Globally applicable? Bits 17..16: (TSE Code) Type of Timestamp Epoch provided Bits 15..14: (LSH Code) Indicates the means by which leap seconds are handled in the packet timestamps Bits 13..12: (LSP Code) Indicates the number of seconds in the current day denoted by the packet timestamps Bits 11..9: (Time Source) Indicates time reference source being used Bit 8: (E) If 0, Current POSIX Time Offset is undefined. If 1, Current POSIX Time Offset conveys the difference in seconds between UTC time and POSIX time, as a signed twos-complement number, and it represents the total leap seconds count. Bits 7..0: (Current POSIX Time Offset) See Bit 8 (E) Second Word: Bits 31..0: (Timestamp Epoch) Unsigned integer value specifying the number of whole seconds, in the epoch denoted by the TSE Code, describing the start of the epoch used for timestamps in all packets to which the Timestamp Details field applies. When the TSE Code is set to Unspecified, the value in the Timestamp Epoch field has no meaning. See V49.2 spec Section 9.7.3.4 for Timestamp Details
Parameters:
val The Timestamp Details (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setX(), and vrt::IndicatorFields::TIMESTAMP_DETAILS.
virtual void vrt::IndicatorFieldProvider::setTimeStampField (int8_t cifNum, int32_t bit, const TimeStamp & val, int32_t cif7bit) [protected, pure virtual]
Packs a TimeStamp from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setAge(), and setShelfLife().
void vrt::IndicatorFieldProvider::setTimestampSkew (int64_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Timestamp Skew Timestamp Skew conveys a time offset between channels in a system or between systems in a distributed system-of-systems architecture.
Timestamp Skew uses the 64-bit Fractional Time format where the least significant bit represents 1 femtosecond (10e-15 seconds). See V49.2 spec Section 9.7.3.2 for Timestamp Skew See V49.2 spec Section 9.7 for Fractional Time format
Parameters:
val The Timestamp Skew (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setX(), and vrt::IndicatorFields::TIMESTAMP_SKEW.
void vrt::IndicatorFieldProvider::setTrackID (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Track ID A dynamic number that is generated during operations used to indicate that information from a specrum observation or a set of spectrum observations over time is associated.
Track ID uses the Generic32 bit Identifier field See V49.2 spec Section 9.8.6 for Track ID See V49.2 spec Section 9.8 for Generic32 bit Identifier field
Parameters:
val The Track ID (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setL(), and vrt::IndicatorFields::TRACK_ID.
void vrt::IndicatorFieldProvider::setTroposphericState (int16_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets Tropospheric State Used to enumerate the state of the troposphere.
Tropospheric State uses the Generic16 bit Identifier field See V49.2 spec Section 9.9.1 for Tropospheric State See V49.2 spec Section 9.8 for Generic16 bit Identifier field
Parameters:
val The Tropospheric State (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setI(), and vrt::IndicatorFields::TROPOSPHERIC_STATE.
void vrt::IndicatorFieldProvider::setUserDefinedBits (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the User-Defined Bits from the State and Event Indicator Bits.
The definition of these bits should be included in the documentation for the relevent packet class. Unlike other bits of the State and Event Indicator Field, there is no concept of an undefined-value for user bits if the State and Event Indicator Field is present to support some other bits. As such, no "null value" is supported for the user-defined buts.
Parameters:
val true if the flag is set, false if it is not set.
cif7field (Optional) Indicator field for the CIF7 attribute.
References getOffset(), setB(), and vrt::IndicatorFields::STATE_EVENT.
virtual void vrt::IndicatorFieldProvider::setUUID (int8_t cifNum, int32_t bit, const UUID & val, int32_t cif7bit) [protected, pure virtual]
Packs a 128-bit UUID from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setControlleeUUIDField(), and setControllerUUIDField().
void vrt::IndicatorFieldProvider::setV49SpecVersion (int32_t val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets V49 Standard and Spec Compliance Number (See V49.2 spec Section 9.10.3) 0x00000001 => V49.0 0x00000002 => V49.1 0x00000003 => V49A (which implies V49.0 and V49.1) 0x00000004 => V49.2.
Parameters:
val The V49 spec version (null if not specified)
cif7field (Optional) Indicator field for the CIF7 attribute.
References setL(), and vrt::IndicatorFields::V49_COMPL.
void vrt::IndicatorFieldProvider::setVerticalBeamwidth (float val, IndicatorFieldEnum_t cif7field = CIF_NULL) [inline]
Sets the Vertical Beamwidth in degrees.
Valid range is from 0 to 360 degrees. (See V49.2 spec Section 9.4.2)
Parameters:
val The Vertical Beamwidth (null if not specified, which will override Horizontal Beamwidth as well).
cif7field (Optional) Indicator field for the CIF7 attribute.
References vrt::IndicatorFields::BEAMWIDTH, vrt::VRTMath::fromFloat32(), setI(), and setL().
virtual void vrt::IndicatorFieldProvider::setX (int8_t cifNum, int32_t bit, int64_t val, int32_t cif7bit) [protected, pure virtual]
Packs a 64-bit integer from the payload at the indicated position.
Implemented in vrt::BasicAcknowledgePacket, and vrt::BasicContextPacket.
Referenced by setAuxBandwidth(), setAuxFrequency(), setBandOffsetIF(), setBandwidth(), setBufferStatus(), setDeviceIdentifier(), setDiscreteIO64(), setDuration(), setDwell(), setFallTime(), setFrequencyIF(), setFrequencyOffsetRF(), setFrequencyRF(), setJitter(), setOffsetTime(), setPeriod(), setPulseWidth(), setRiseTime(), setSampleRate(), setTimeStampAdjustment(), setTimestampDetails(), and setTimestampSkew().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/IndicatorFields.h