VRT: vrt::MetadataEntry Class Reference
vrt::MetadataEntry Class Reference
A metadata entry in the metadata block.
#include <MetadataBlock.h>
Public Member Functions
MetadataEntry (int32_t level, const string &key, const wstring &val)
Creates a new instance with the given entries.
MetadataEntry ()
Creates a new uninitialized (null) instance.
MetadataEntry (const MetadataEntry &m)
Copy constructor.
~MetadataEntry ()
Basic destructor.
string getKey () const
Gets the key name.
int32_t getLevel () const
Gets the level of the entry.
wstring getValue () const
Gets the value.
virtual bool isNull () const
Is this a null-form packet?
int32_t readBytes (const vector< char > &buf, int32_t off, int32_t len)
Reads the entry from a byte buffer.
void setKey (const string &k)
Sets the key name.
void setKey (const string *key)
Sets the key name.
void setLevel (int32_t l)
Sets the level of the entry.
void setValue (const wstring &v)
Sets the value.
void setValue (const wstring *val)
Sets the value.
virtual string toString () const
Prints the entry in string form.
int32_t writeBytes (vector< char > &buf, int32_t off, int32_t len) const
Writes the entry to a byte buffer.
Detailed Description
A metadata entry in the metadata block.
Constructor & Destructor Documentation
vrt::MetadataEntry::~MetadataEntry () [inline]
Basic destructor.
vrt::MetadataEntry::MetadataEntry (const MetadataEntry & m)
Copy constructor.
vrt::MetadataEntry::MetadataEntry ()
Creates a new uninitialized (null) instance.
vrt::MetadataEntry::MetadataEntry (int32_t level, const string & key, const wstring & val)
Creates a new instance with the given entries.
Parameters:
level The level.
key The key.
val The value.
Member Function Documentation
string vrt::MetadataEntry::getKey () const [inline]
Gets the key name.
int32_t vrt::MetadataEntry::getLevel () const [inline]
Gets the level of the entry.
wstring vrt::MetadataEntry::getValue () const [inline]
Gets the value.
virtual bool vrt::MetadataEntry::isNull () const [inline, virtual]
Is this a null-form packet?
int32_t vrt::MetadataEntry::readBytes (const vector< char > & buf, int32_t off, int32_t len)
Reads the entry from a byte buffer.
Parameters:
buf The buffer.
off Offset into the buffer.
len Length in the byte buffer.
Exceptions:
IllegalArgumentException If the block is invalid.
void vrt::MetadataEntry::setKey (const string & k) [inline]
Sets the key name.
References setKey().
void vrt::MetadataEntry::setKey (const string * key)
Sets the key name.
Referenced by setKey().
void vrt::MetadataEntry::setLevel (int32_t l) [inline]
Sets the level of the entry.
void vrt::MetadataEntry::setValue (const wstring & v) [inline]
Sets the value.
References setValue().
void vrt::MetadataEntry::setValue (const wstring * val)
Sets the value.
Referenced by setValue().
virtual string vrt::MetadataEntry::toString () const [virtual]
Prints the entry in string form.
Reimplemented from vrt::VRTObject.
int32_t vrt::MetadataEntry::writeBytes (vector< char > & buf, int32_t off, int32_t len) const
Writes the entry to a byte buffer.
Parameters:
buf The buffer.
off Offset into the buffer.
len Length in the byte buffer.
Returns:
The number of bytes required within the byte buffer. If there are insufficient bytes to include the entire metadata block this will return a number larger than the length passed in.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/MetadataBlock.h