VRT: vrt::StreamStatePacket Class Reference
vrt::StreamStatePacket Class Reference
A.5. Stream State Packet.
#include <StreamStatePacket.h>
Public Member Functions
StreamStatePacket (const vector< char > &bbuf, bool readOnly)
Creates a new instance accessing the given data buffer.
StreamStatePacket (const BasicVRTPacket &p)
Creates a new instance from the given packet.
StreamStatePacket ()
Creates a new instance ready for the fields to be set.
SystemStatus getAggregateSystemStatus () const
Get the aggregate system status.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
SystemStatus getInputStatus () const
Get the status of the input.
SystemStatus getInternalStatus () const
Get the status of the system's internals.
wstring getMessage () const
Get any messages to better explain the processing state and/or status.
SystemStatus getOutputStatus () const
Get the status of the output.
virtual string getPacketValid (bool strict, int32_t length) const
Checks to see if the packet is valid.
SystemState getSystemState () const
Get the system state.
void setAggregateSystemStatus (SystemStatus val)
Set the aggregate system status.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setInputStatus (SystemStatus val)
Set the status of the input.
void setInternalStatus (SystemStatus val)
Set the status of the system's internals.
void setMessage (string val)
Set any messages to better explain the processing state and/or status.
void setMessage (wstring val)
Set any messages to better explain the processing state and/or status.
void setOutputStatus (SystemStatus val)
Set the status of the output.
void setSystemState (SystemState val)
Set the system state.
Static Public Attributes
static const string CLASS_ID
The class identifier in string form (FF-FF-FA:2011.0005).
static const int64_t CLASS_IDENTIFIER
The class identifier in numeric form (0xFFFFFA20110005).
static const int32_t PACKET_LENGTH
The packet length (-8) excluding the header and trailer (if applicable).
static const PacketType PACKET_TYPE
The packet type (PacketType_ExtContext).
Protected Member Functions
StreamStatePacket (const BasicVRTPacket &p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength)
Internal constructor, for use by subclasses.
virtual void toStringStream (ostringstream &str) const
Writes the packet content to a string stream in a user-friendly format.
Detailed Description
A.5. Stream State Packet.
The "stream state packet" provides describes the overall state of the system at the given reference point and provides receivers with greater insight into the current activity state of the packet's emitter.
The "state" of a system refers to its position in the state diagram of the emitter. The states are based on the following generalized state diagram, though individual systems may omit stages and/or may differ slightly:
                                                        +---------+
                                                        | PAUSING |
                                                        +---------+
                                                           ^   |
                                                           |   V
  +---------+     +--------------+     +----------+     +---------+     +----------+     +---------+
  | BOOTING | --> | INITIALIZING | --> | STARTING | --> | RUNNING | --> | STOPPING | --> | EXITING |
  +---------+     +--------------+     +----------+     +---------+     +----------+     +---------+
                                                           ^   |
                                                           |   |
                                     +------------+        |   |        +----------+
                                     | RESTARTING | -------+   +------> | BREAKING |
                                     +------------+                     +----------+
                                           ^                                  |
                                           +----------------------------------+
                                                                    +----------+     +-------------+
                                                           (*) ---> | ABORTING | --> | TERMINATING |
                                                                    +----------+     +-------------+
The states are as follows:
BOOTING - System is booting up, but not yet ready for initialization, (this state is generally "implied" and rarely visible outside of log file messages);
INITIALIZING - System is initializing;
STARTING - System has been initialized, and is preparing to run;
RUNNING - System is running, this included situations where the system is waiting for input;
STOPPING - System is done processing (e.g. in response to user input or the result of not having any more data to process) and is stopping;
EXITING - System has completed operation and is exiting normally (this state is generally "implied" and rarely visible outside of log file messages);
PAUSING - System is pausing, this is generally in response to user input, such as pausing playback of a recorded signal;
BREAKING - System is breaking out of the current running state on its way to a restart;
RESTARTING - System is restarting;
ABORTING - An error event has taking place or an "abort" signal has been sent to the system, and the system is now aborting normal operation (this state can follow any other state and might not be visible outside of log file messages); and
TERMINATING - System has aborted operation and is terminating abnormally (this state is generally "implied" and rarely visible outside of log file messages).
Some systems may split the RUNNING state into three separate states:
IDENTIFYING - System is running and is currently identifying the input format;
CONFIGURING or LOCKING - System is running, has identified the input format and is configuring itself for processing; and
PROCESSING - System is running, has identified the input format, has been configured and is processing the input.
The typical example of where the IDENTIFYING, LOCKING, and PROCESSING states are used is within a demodulator where the IDENTIFYING state implies that the demodulator is detecting the modulation type; LOCKING implies that the demodulator is trying to lock up to the signal; and PROCESSING means that the demodulator is locked to the identified signal and is demodulating it. If the demodulator looses lock, it can return to either the IDENTIFYING (it wants to re-check the modulation type) or the LOCKING state.
The "status" of a system refers to the "health" of the system's processing ability at three key points (input, internal, output) and an aggregate status indicator. The "health" is essentially a "traffic light" color coding that mimics the status lights on traditional radio equipment. The BLUE state is an addition that may be used to differentiate normal (GREEN) operation, where output is being produced, from that where there is no output being produced (e.g. a radio that is receiving and processing a signal, but there is no "user data" to output since the decoded signal consists only of "idle" indicators).
Constructor & Destructor Documentation
vrt::StreamStatePacket::StreamStatePacket ()
Creates a new instance ready for the fields to be set.
The stream ID and timecode values will be initialized to 0.
vrt::StreamStatePacket::StreamStatePacket (const BasicVRTPacket & p)
Creates a new instance from the given packet.
Parameters:
p The packet.
Exceptions:
VRTException If the packet given does not match this type.
vrt::StreamStatePacket::StreamStatePacket (const BasicVRTPacket & p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength) [protected]
Internal constructor, for use by subclasses.
Parameters:
p The packet (already initialized).
type The expected packet type.
classID The expected classID.
minPayloadLength The minimum payload length.
maxPayloadLength The maximum payload length (<0 if not pre-defined).
Exceptions:
IllegalArgumentException If packet type or classID of the packet are invalid, or if the payload length is invalid.
vrt::StreamStatePacket::StreamStatePacket (const vector< char > & bbuf, bool readOnly)
Creates a new instance accessing the given data buffer.
Parameters:
bbuf The data buffer to use.
readOnly Should users of this instance be able to modify the underlying data buffer?
Member Function Documentation
SystemStatus vrt::StreamStatePacket::getAggregateSystemStatus () const [inline]
Get the aggregate system status.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadByte().
virtual Value* vrt::StreamStatePacket::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::BasicVRTPacket.
virtual int32_t vrt::StreamStatePacket::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::BasicVRTPacket.
virtual string vrt::StreamStatePacket::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::BasicVRTPacket.
virtual ValueType vrt::StreamStatePacket::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::BasicVRTPacket.
SystemStatus vrt::StreamStatePacket::getInputStatus () const [inline]
Get the status of the input.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadByte().
SystemStatus vrt::StreamStatePacket::getInternalStatus () const [inline]
Get the status of the system's internals.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadByte().
wstring vrt::StreamStatePacket::getMessage () const [inline]
Get any messages to better explain the processing state and/or status.
Size: variable
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::getPayloadLength(), and vrt::BasicVRTPacket::unpackPayloadUTF8().
SystemStatus vrt::StreamStatePacket::getOutputStatus () const [inline]
Get the status of the output.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadByte().
virtual string vrt::StreamStatePacket::getPacketValid (bool strict, int32_t length) const [virtual]
Checks to see if the packet is valid.
This is identical to isPacketValid(int32_t) except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No packet failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a packet.
length Verifies that the length of the packet matches this value.
Returns:
Empty string ("") if it is valid, a description of the error otherwise.
Reimplemented from vrt::BasicVRTPacket.
SystemState vrt::StreamStatePacket::getSystemState () const [inline]
Get the system state.
Returns:
The value read from the packet.
References vrt::BasicVRTPacket::unpackPayloadByte().
void vrt::StreamStatePacket::setAggregateSystemStatus (SystemStatus val) [inline]
Set the aggregate system status.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadByte().
virtual void vrt::StreamStatePacket::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::BasicVRTPacket.
void vrt::StreamStatePacket::setInputStatus (SystemStatus val) [inline]
Set the status of the input.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadByte().
void vrt::StreamStatePacket::setInternalStatus (SystemStatus val) [inline]
Set the status of the system's internals.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadByte().
void vrt::StreamStatePacket::setMessage (string val) [inline]
Set any messages to better explain the processing state and/or status.
Size: variable
Parameters:
val The new value to write to the packet.
References vrt::VRTMath::lengthUTF8(), vrt::BasicVRTPacket::MAX_PAYLOAD_LENGTH, vrt::BasicVRTPacket::packPayloadUTF8(), and vrt::BasicVRTPacket::setPayloadLength().
void vrt::StreamStatePacket::setMessage (wstring val) [inline]
Set any messages to better explain the processing state and/or status.
Size: variable
Parameters:
val The new value to write to the packet.
References vrt::VRTMath::lengthUTF8(), vrt::BasicVRTPacket::MAX_PAYLOAD_LENGTH, vrt::BasicVRTPacket::packPayloadUTF8(), and vrt::BasicVRTPacket::setPayloadLength().
void vrt::StreamStatePacket::setOutputStatus (SystemStatus val) [inline]
Set the status of the output.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadByte().
void vrt::StreamStatePacket::setSystemState (SystemState val) [inline]
Set the system state.
Parameters:
val The new value to write to the packet.
References vrt::BasicVRTPacket::packPayloadByte().
virtual void vrt::StreamStatePacket::toStringStream (ostringstream & str) const [protected, virtual]
Writes the packet content to a string stream in a user-friendly format.
Parameters:
str The string stream to write to.
Reimplemented from vrt::BasicVRTPacket.
Member Data Documentation
const string vrt::StreamStatePacket::CLASS_ID [static]
The class identifier in string form (FF-FF-FA:2011.0005).
const int64_t vrt::StreamStatePacket::CLASS_IDENTIFIER [static]
The class identifier in numeric form (0xFFFFFA20110005).
const int32_t vrt::StreamStatePacket::PACKET_LENGTH [static]
The packet length (-8) excluding the header and trailer (if applicable).
A value of -8 indicates that the length is variable with a minimum length of 8 octets.
const PacketType vrt::StreamStatePacket::PACKET_TYPE [static]
The packet type (PacketType_ExtContext).
The documentation for this class was generated from the following file:
cpp_src/vrt/libm/StreamStatePacket.h