VRT: vrt::ContextAssocLists Class Reference
vrt::ContextAssocLists Class Reference
Specifies a Context Association List.
#include <IndicatorFields.h>
Public Member Functions
ContextAssocLists (const ContextAssocLists &r)
Basic copy constructor.
ContextAssocLists ()
Creates a new instance.
vector< int32_t > getAsynchronousChannel () const
Gets a copy of the Asynchronous-Channel Association List.
int32_t getAsynchronousChannelCount () const
Gets the number of Asynchronous-Channel context associations.
vector< int32_t > getAsynchronousChannelTag () const
Gets a copy of the Asynchronous-Channel Tag List.
bool getAsynchronousChannelTagsPresent () const
Are the Asynchronous-Channel context associations accompanied by Asynchronous-Channel Tags?
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
vector< int32_t > getSourceContext () const
Gets a copy of the Source Context Association List.
int32_t getSourceContextCount () const
Gets the number of source context associations.
vector< int32_t > getSystemContext () const
Gets a copy of the System Context Association List.
int32_t getSystemContextCount () const
Gets the number of system context associations.
vector< int32_t > getVectorComponent () const
Gets a copy of the Vector-Component Association List.
int32_t getVectorComponentCount () const
Gets the number of vector-component context associations.
void setAsynchronousChannel (const vector< int32_t > &val, const vector< int32_t > &tags)
Sets the Asynchronous-Channel Association List.
void setAsynchronousChannel (const vector< int32_t > &val)
Sets the Asynchronous-Channel Association List.
void setAsynchronousChannelCount (int32_t val)
Sets the number of Asynchronous-Channel context associations.
void setAsynchronousChannelTagsPresent (bool val)
Are the Asynchronous-Channel context associations accompanied by Asynchronous-Channel Tags?
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setSourceContext (const vector< int32_t > &val)
Sets the Source Context Association List.
void setSourceContextCount (int32_t val)
Sets the number of source context associations.
void setSystemContext (const vector< int32_t > &val)
Sets the System Context Association List.
void setSystemContextCount (int32_t val)
Sets the number of system context associations.
void setVectorComponent (const vector< int32_t > &val)
Sets the Vector-Component Association List.
void setVectorComponentCount (int32_t val)
Sets the number of vector-component context associations.
virtual string toString () const
Gets a basic description of the object, useful for debugging.
virtual void writeBytes (const void *buffer)
Writes bytes to this record from the specified buffer.
Detailed Description
Specifies a Context Association List.
Constructor & Destructor Documentation
vrt::ContextAssocLists::ContextAssocLists ()
Creates a new instance.
vrt::ContextAssocLists::ContextAssocLists (const ContextAssocLists & r)
Basic copy constructor.
Member Function Documentation
vector<int32_t> vrt::ContextAssocLists::getAsynchronousChannel () const
Gets a copy of the Asynchronous-Channel Association List.
Returns:
A copy of the association list (returns an arry of length 0 if there are no entries).
See also:
getAsynchronousChannelTag()
int32_t vrt::ContextAssocLists::getAsynchronousChannelCount () const [inline]
Gets the number of Asynchronous-Channel context associations.
References vrt::Record::unpackShort().
Referenced by setAsynchronousChannelCount().
vector<int32_t> vrt::ContextAssocLists::getAsynchronousChannelTag () const
Gets a copy of the Asynchronous-Channel Tag List.
Returns:
A copy of the tag list (returns an arry of length 0 if there are no entries). The inclusion of the tag list is optional; if it is omitted, this will return null.
See also:
getAsynchronousChannel()
setAsynchronousChannel(int[],int[])
bool vrt::ContextAssocLists::getAsynchronousChannelTagsPresent () const [inline]
Are the Asynchronous-Channel context associations accompanied by Asynchronous-Channel Tags?
References vrt::Record::unpackShort().
Referenced by setAsynchronousChannelCount().
virtual Value* vrt::ContextAssocLists::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::Record.
virtual int32_t vrt::ContextAssocLists::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::Record.
virtual string vrt::ContextAssocLists::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::Record.
virtual ValueType vrt::ContextAssocLists::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::Record.
vector<int32_t> vrt::ContextAssocLists::getSourceContext () const
Gets a copy of the Source Context Association List.
Returns:
A copy of the association list (returns an arry of length 0 if there are no entries).
int32_t vrt::ContextAssocLists::getSourceContextCount () const [inline]
Gets the number of source context associations.
References vrt::Record::unpackShort().
Referenced by setSourceContextCount().
vector<int32_t> vrt::ContextAssocLists::getSystemContext () const
Gets a copy of the System Context Association List.
Returns:
A copy of the association list (returns an arry of length 0 if there are no entries).
int32_t vrt::ContextAssocLists::getSystemContextCount () const [inline]
Gets the number of system context associations.
References vrt::Record::unpackShort().
Referenced by setSystemContextCount().
vector<int32_t> vrt::ContextAssocLists::getVectorComponent () const
Gets a copy of the Vector-Component Association List.
Returns:
A copy of the association list (returns an arry of length 0 if there are no entries).
int32_t vrt::ContextAssocLists::getVectorComponentCount () const [inline]
Gets the number of vector-component context associations.
References vrt::Record::unpackShort().
Referenced by setVectorComponentCount().
void vrt::ContextAssocLists::setAsynchronousChannel (const vector< int32_t > & val, const vector< int32_t > & tags)
Sets the Asynchronous-Channel Association List.
Parameters:
val The association list (an arry of length 0 if there are no entries).
tags The tag list (an arry of length 0 if there are no entries or null if not specified). The inclusion of the tag list is optional; if it is included, it must have the same length as list.
Exceptions:
VRTException if tags is given but has an invalid length.
See also:
getAsynchronousChannelTag()
void vrt::ContextAssocLists::setAsynchronousChannel (const vector< int32_t > & val)
Sets the Asynchronous-Channel Association List.
This is identical to setAsynchronousChannel(list,null).
Parameters:
val The association list (an arry of length 0 if there are no entries).
void vrt::ContextAssocLists::setAsynchronousChannelCount (int32_t val) [inline]
Sets the number of Asynchronous-Channel context associations.
References getAsynchronousChannelCount(), and getAsynchronousChannelTagsPresent().
void vrt::ContextAssocLists::setAsynchronousChannelTagsPresent (bool val)
Are the Asynchronous-Channel context associations accompanied by Asynchronous-Channel Tags?
virtual void vrt::ContextAssocLists::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::Record.
void vrt::ContextAssocLists::setSourceContext (const vector< int32_t > & val)
Sets the Source Context Association List.
Parameters:
val The association list (an arry of length 0 if there are no entries).
void vrt::ContextAssocLists::setSourceContextCount (int32_t val) [inline]
Sets the number of source context associations.
References getSourceContextCount().
void vrt::ContextAssocLists::setSystemContext (const vector< int32_t > & val)
Sets the System Context Association List.
Parameters:
val The association list (an arry of length 0 if there are no entries).
void vrt::ContextAssocLists::setSystemContextCount (int32_t val) [inline]
Sets the number of system context associations.
References getSystemContextCount().
void vrt::ContextAssocLists::setVectorComponent (const vector< int32_t > & val)
Sets the Vector-Component Association List.
Parameters:
val The association list (an arry of length 0 if there are no entries).
void vrt::ContextAssocLists::setVectorComponentCount (int32_t val) [inline]
Sets the number of vector-component context associations.
References getVectorComponentCount().
virtual string vrt::ContextAssocLists::toString () const [virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::Record.
virtual void vrt::ContextAssocLists::writeBytes (const void * buffer) [inline, virtual]
Writes bytes to this record from the specified buffer.
Parameters:
buffer The buffer to read from.
Reimplemented from vrt::Record.
References vrt::Record::setByteLength().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/IndicatorFields.h