VRT: vrt::VRTWriter Class Reference
vrt::VRTWriter Class Reference
Writes VRT packets which may optionally be included in VRL frames.
#include <VRTWriter.h>
Public Member Functions
VRTWriter (TransportProtocol transport, const string &host, int32_t port, const string &device, VRTEventListener *listener, map< string, string > options)
Creates a new instance.
VRTWriter (const string &host, int32_t port, const string &device, bool useFrames, bool useCRC, uint8_t ttl=1)
Creates a new instance.
~VRTWriter ()
Destroys the current instance, closing the socket if required.
void send (const BasicVRTPacket &p)
Deprecated: Use sendPacket.
void sendAllPackets (const vector< BasicVRTPacket > &packets)
Sends a set of packets via the socket.
void sendPacket (const BasicVRTPacket *p)
Sends a packet in a logical frame or frames (where applicable).
void sendPacket (const BasicVRTPacket &p)
Sends a packet in a logical frame or frames (where applicable).
void sendPackets (const BasicVRTPacket &p)
Sends a packet in a logical frame or frames (where applicable).
void sendPackets (const BasicVRTPacket *p)
Sends a packet in a logical frame or frames (where applicable).
void sendPackets (const BasicVRTPacket &p0, const BasicVRTPacket &p1, const BasicVRTPacket &p2=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &p3=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &p4=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &p5=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &p6=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &p7=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &p8=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &p9=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &pA=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &pB=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &pC=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &pD=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &pE=BasicVRTPacket::NULL_PACKET, const BasicVRTPacket &pF=BasicVRTPacket::NULL_PACKET)
Sends a set of packets in a logical frame or frames (where applicable).
void sendPackets (const BasicVRTPacket *p0, const BasicVRTPacket *p1, const BasicVRTPacket *p2=NULL, const BasicVRTPacket *p3=NULL, const BasicVRTPacket *p4=NULL, const BasicVRTPacket *p5=NULL, const BasicVRTPacket *p6=NULL, const BasicVRTPacket *p7=NULL, const BasicVRTPacket *p8=NULL, const BasicVRTPacket *p9=NULL, const BasicVRTPacket *pA=NULL, const BasicVRTPacket *pB=NULL, const BasicVRTPacket *pC=NULL, const BasicVRTPacket *pD=NULL, const BasicVRTPacket *pE=NULL, const BasicVRTPacket *pF=NULL)
Sends a set of packets in a logical frame or frames (where applicable).
void sendPackets (const vector< BasicVRTPacket > &packets)
Sends a set of packets in a logical frame or frames (where applicable).
void sendPackets (const vector< BasicVRTPacket * > &packets)
Sends a set of packets in a logical frame or frames (where applicable).
void transmit (const BasicVRTPacket &p)
Deprecated: Use sendPacket.
Detailed Description
Writes VRT packets which may optionally be included in VRL frames.
The choice between un-framed VRT packets and using VRL frames must be made at the time the class is instantiated. If frames are used, there is also an option to use CRC protection for the frames.
This implements Threadable to support use of TCP is used in "server mode" (i.e. opening a TCP server socket to accept connections). When in this mode the thread is used to support the acceptance of "client" connections. When a packet is sent any connected "clients" will receive a copy of the packet (if none are connected the packet is just discarded).
Prior to Oct 2013 this class used multicast.h, which limited its applicability to only UDP/Multicast input. This was changed in Oct 2013 to support UDP/Unicast and TCP, accordingly the inclusion of multicast.h was dropped.
Constructor & Destructor Documentation
vrt::VRTWriter::VRTWriter (const string & host, int32_t port, const string & device, bool useFrames, bool useCRC, uint8_t ttl = 1)
Creates a new instance.
Parameters:
host The host to connect to (null = wildcard address).
port The port number.
device The device to connect to (e.g. "eth0", "eth1.101") (null = use default).
useFrames Should packets be sent embedded in VRL frames?
useCRC Should frames provide CRC protection? (This parameter only applies if frames are in use.)
ttl Time to live for the multicast packet (this should usually be set to 1).
Exceptions:
VRTException If an I/O exception occurs.
vrt::VRTWriter::VRTWriter (TransportProtocol transport, const string & host, int32_t port, const string & device, VRTEventListener * listener, map< string, string > options)
Creates a new instance.
The options provided to control the socket and connection may include any of the "Socket Creation Options" listed at the top of NetUtilities plus the following:
    VRL_FRAME  - Use VRL frames when sending VRT packets.  [Default = false]
    VRL_CRC    - Include CRC with VRL frames sent.         [Default = false]
    VRL_BREAK  - The number of octets before splitting a multi-packet
                 send into multiple frames. This can also take one of
                 the following special values:
                   0 = Send all packets individually
                  -1 = Use default
                  -2 = Use default based on protocol   (~60 KiB for UDP)
                  -3 = Use default based on MTU        (usually ~1,500 octets)
It is suggested that users start with the default set of options provided by NetUtilities#getDefaultSocketOptions. Starting with an empty map (or simply passing in null) will use the o/s defaults, which may not be ideal for use with VITA-49 streams.
Parameters:
transport The transport to use.
host The host to connect to (null = wildcard address).
port The port number (null = any port).
device The device to connect to (e.g. "eth0", "eth1.101") (null = use default).
listener The primary listener *and* the listener used to handle any warnings during startup (if null, any startup warnings will print to the console). After startup, this will be registered the same as calling:
                     if (listener != null) {
                       addErrorWarningListener(listener);
                       addSentPacketListener(listener,null);
                     }
options Map of options to set (can be null).
Exceptions:
IOException If an I/O exception occurs.
vrt::VRTWriter::~VRTWriter ()
Destroys the current instance, closing the socket if required.
Member Function Documentation
void vrt::VRTWriter::send (const BasicVRTPacket & p) [inline]
Deprecated: Use sendPacket.
References sendPacket().
void vrt::VRTWriter::sendAllPackets (const vector< BasicVRTPacket > & packets) [inline]
Sends a set of packets via the socket.
Prior to Dec 2013, sendPackets was a vararg macro, which prevented us from overloading the method signature, hence sendAllPackets was used even though it was inconsistent with other uses. Since the re-working of the various sendAllPackets(..) functions, the use of the sendAllPackets name is no longer required.
Deprecated:
Since Dec 2013, use sendPackets(..).
References sendPackets().
void vrt::VRTWriter::sendPacket (const BasicVRTPacket * p)
Sends a packet in a logical frame or frames (where applicable).
The actual transmitted packet will have the packet count updated as necessary, however the packet object passed in will not be altered. This method does not block until the packet has been sent. To see the actual packet sent and verification of sending, the listener can be set when this class is created.
Parameters:
p The packet to send.
Exceptions:
VRTException If an I/O exception occurs.
void vrt::VRTWriter::sendPacket (const BasicVRTPacket & p) [inline]
Sends a packet in a logical frame or frames (where applicable).
The actual transmitted packet will have the packet count updated as necessary, however the packet object passed in will not be altered. This method does not block until the packet has been sent. To see the actual packet sent and verification of sending, the listener can be set when this class is created.
Parameters:
p The packet to send.
Exceptions:
VRTException If an I/O exception occurs.
Referenced by send(), sendPackets(), and transmit().
void vrt::VRTWriter::sendPackets (const BasicVRTPacket & p) [inline]
Sends a packet in a logical frame or frames (where applicable).
This is identical to calling sendPacket(p).
Parameters:
p The packet to send.
Exceptions:
VRTException If an I/O exception occurs.
References sendPacket().
void vrt::VRTWriter::sendPackets (const BasicVRTPacket * p) [inline]
Sends a packet in a logical frame or frames (where applicable).
This is identical to calling sendPacket(p).
Parameters:
p The packet to send.
Exceptions:
VRTException If an I/O exception occurs.
References sendPacket().
void vrt::VRTWriter::sendPackets (const BasicVRTPacket & p0, const BasicVRTPacket & p1, const BasicVRTPacket & p2 = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & p3 = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & p4 = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & p5 = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & p6 = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & p7 = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & p8 = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & p9 = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & pA = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & pB = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & pC = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & pD = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & pE = BasicVRTPacket::NULL_PACKET, const BasicVRTPacket & pF = BasicVRTPacket::NULL_PACKET)
Sends a set of packets in a logical frame or frames (where applicable).
The actual transmitted packet will have the packet count updated as necessary, however the packet object passed in will not be altered. This method does not block until the packet has been sent. To see the actual packet sent and verification of sending, the listener can be set when this class is created.
Note that none of the supplied arguments may be null (only the default arguments at the end may be null).
Parameters:
p0 Packet to send #1.
p1 Packet to send #2.
p2 Packet to send #3.
p3 Packet to send #4.
p4 Packet to send #5.
p5 Packet to send #6.
p6 Packet to send #7.
p7 Packet to send #8.
p8 Packet to send #9.
p9 Packet to send #10.
pA Packet to send #11.
pB Packet to send #12.
pC Packet to send #13.
pD Packet to send #14.
pE Packet to send #15.
pF Packet to send #16.
Exceptions:
VRTException If an I/O exception occurs.
void vrt::VRTWriter::sendPackets (const BasicVRTPacket * p0, const BasicVRTPacket * p1, const BasicVRTPacket * p2 = NULL, const BasicVRTPacket * p3 = NULL, const BasicVRTPacket * p4 = NULL, const BasicVRTPacket * p5 = NULL, const BasicVRTPacket * p6 = NULL, const BasicVRTPacket * p7 = NULL, const BasicVRTPacket * p8 = NULL, const BasicVRTPacket * p9 = NULL, const BasicVRTPacket * pA = NULL, const BasicVRTPacket * pB = NULL, const BasicVRTPacket * pC = NULL, const BasicVRTPacket * pD = NULL, const BasicVRTPacket * pE = NULL, const BasicVRTPacket * pF = NULL)
Sends a set of packets in a logical frame or frames (where applicable).
The actual transmitted packet will have the packet count updated as necessary, however the packet object passed in will not be altered. This method does not block until the packet has been sent. To see the actual packet sent and verification of sending, the listener can be set when this class is created.
Note that none of the supplied arguments may be null (only the default arguments at the end may be null).
Prior to Dec 2013, sendPackets was a vararg macro, however this caused issues if the vararg parameters weren't exactly pointers to a BasicVRTPacket (i.e. bad things would happen if one was a pointer to a BasicDataPacket). Accordingly this was changed, but does limit the number of packets to 16, which should be sufficient for most uses.
Parameters:
p0 Packet to send #1.
p1 Packet to send #2.
p2 Packet to send #3.
p3 Packet to send #4.
p4 Packet to send #5.
p5 Packet to send #6.
p6 Packet to send #7.
p7 Packet to send #8.
p8 Packet to send #9.
p9 Packet to send #10.
pA Packet to send #11.
pB Packet to send #12.
pC Packet to send #13.
pD Packet to send #14.
pE Packet to send #15.
pF Packet to send #16.
Exceptions:
VRTException If an I/O exception occurs.
void vrt::VRTWriter::sendPackets (const vector< BasicVRTPacket > & packets)
Sends a set of packets in a logical frame or frames (where applicable).
The actual transmitted packet will have the packet count updated as necessary, however the packet object passed in will not be altered. This method does not block until the packet has been sent. To see the actual packet sent and verification of sending, the listener can be set when this class is created.
Parameters:
packets The packets to send.
Exceptions:
VRTException If an I/O exception occurs.
void vrt::VRTWriter::sendPackets (const vector< BasicVRTPacket * > & packets)
Sends a set of packets in a logical frame or frames (where applicable).
The actual transmitted packet will have the packet count updated as necessary, however the packet object passed in will not be altered. This method does not block until the packet has been sent. To see the actual packet sent and verification of sending, the listener can be set when this class is created.
Parameters:
packets The packets to send.
Exceptions:
VRTException If an I/O exception occurs.
Referenced by sendAllPackets().
void vrt::VRTWriter::transmit (const BasicVRTPacket & p) [inline]
Deprecated: Use sendPacket.
References sendPacket().
The documentation for this class was generated from the following file:
cpp_src/vrt/net/VRTWriter.h