VRT: vrt::Record Class Reference
vrt::Record Class Reference
Defines a record that could be in a BasicVRTPacket.
#include <Record.h>
Public Member Functions
Record (int32_t len, bool strictEquality=true)
Creates a new instance with the given length.
Record (const Record &r)
Creates a new instance sharing the buffers of the one specified.
virtual bool equals (const VRTObject &o) const
virtual int32_t getByteLength () const
Gets the length in bytes.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
virtual bool isNullValue () const
A record is considered null if it has no data.
virtual void readBytes (void *buffer) const
Reads bytes from this record to the specified buffer.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
virtual string toString () const
Gets a basic description of the object, useful for debugging.
virtual void writeBytes (const void *buffer)
Writes bytes to this record from the specified buffer.
Protected Member Functions
boolNull getStateEventBit (int32_t off, int32_t enable, int32_t indicator) const
Unpacks a state event bit from the record.
void packAscii (int32_t off, string val, int32_t len)
Packs an ASCII string into the record.
void packBoolean (int32_t off, bool val)
Packs a boolean value into the record.
void packBoolNull (int32_t off, boolNull val)
Packs a boolNull value into the record.
void packByte (int32_t off, int8_t val)
Packs an 8-bit integer into the record.
void packBytes (int32_t off, void *val, int32_t len)
Packs a block of bytes into the record.
void packBytes (int32_t off, const vector< char > &val, int32_t len)
Packs a block of bytes into the record.
void packDouble (int32_t off, double val)
Packs a 64-bit floating-point value into the record.
void packFloat (int32_t off, float val)
Packs a 32-bit floating-point value into the record.
void packInetAddr (int32_t off, const InetAddress &val)
Packs a InetAddress into the record.
void packInt (int32_t off, int32_t val)
Packs a 32-bit integer into the record.
void packLong (int32_t off, int64_t val)
Packs a 64-bit integer into the record.
void packMetadata (int32_t off, MetadataBlock val, int32_t len)
Packs a metadata block into the record.
void packShort (int32_t off, int16_t val)
Packs a 16-bit integer into the record.
void packTimeStamp (int32_t off, const TimeStamp &val, IntegerMode epoch)
Packs a TimeStamp into the record.
void packUTF8 (int32_t off, wstring val, int32_t len)
Packs a UTF-8 string into the record.
void packUTF8 (int32_t off, string val, int32_t len)
Packs a UTF-8 string into the record.
void packUUID (int32_t off, const UUID &val)
Packs a UUID into the record.
virtual void setByteLength (int32_t len, int32_t off=-1)
Sets the length in bytes with any additional bytes added/removed from the given point (-1=end).
string unpackAscii (int32_t off, int32_t len) const
Unpacks an ASCII string from the record.
bool unpackBit (int32_t off, int32_t bit) const
Unpacks an bit from the record.
bool unpackBoolean (int32_t off) const
Unpacks a boolean value from the record.
boolNull unpackBoolNull (int32_t off) const
Unpacks a boolNull value from the record.
int8_t unpackByte (int32_t off) const
Unpacks an 8-bit integer from the record.
void * unpackBytes (int32_t off, void *val, int32_t len) const
Unpacks a block of bytes from the record.
vector< char > unpackBytes (int32_t off, int32_t len) const
Unpacks a block of bytes from the record.
double unpackDouble (int32_t off) const
Unpacks a 64-bit floating-point value from the record.
float unpackFloat (int32_t off) const
Unpacks a 32-bit floating-point value from the record.
InetAddress unpackInetAddr (int32_t off) const
Unpacks a InetAddress from the record.
int32_t unpackInt (int32_t off) const
Unpacks a 32-bit integer from the record.
int64_t unpackLong (int32_t off) const
Unpacks a 64-bit integer from the record.
MetadataBlock unpackMetadata (int32_t off, int32_t len) const
Unpacks a metadata block from the record.
int16_t unpackShort (int32_t off) const
Unpacks a 16-bit integer from the record.
TimeStamp unpackTimeStamp (int32_t off, IntegerMode epoch) const
Unpacks a TimeStamp from the record.
wstring unpackUTF8 (int32_t off, int32_t len) const
Unpacks a UTF-8 string from the record.
UUID unpackUUID (int32_t off) const
Unpacks a UUID from the record.
Protected Attributes
vector< char > buf
Internal Use Only: The data buffer used.
Detailed Description
Defines a record that could be in a BasicVRTPacket.
Constructor & Destructor Documentation
vrt::Record::Record (const Record & r)
Creates a new instance sharing the buffers of the one specified.
vrt::Record::Record (int32_t len, bool strictEquality = true)
Creates a new instance with the given length.
Parameters:
strictEquality Should the equals(..) check ensure strict equality by checking to see that both the data and class match? If false, only the data is checked.
len The initial length of the record.
Member Function Documentation
virtual int32_t vrt::Record::getByteLength () const [inline, virtual]
Gets the length in bytes.
References buf.
Referenced by vrt::GeoSentences::getSentences(), and vrt::IndicatorFieldProvider::setRecord().
virtual Value* vrt::Record::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::HasFields.
Reimplemented in vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, and vrt::Point.
virtual int32_t vrt::Record::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::HasFields.
Reimplemented in vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, and vrt::Point.
virtual string vrt::Record::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::HasFields.
Reimplemented in vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, and vrt::Point.
virtual ValueType vrt::Record::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::HasFields.
Reimplemented in vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, and vrt::Point.
boolNull vrt::Record::getStateEventBit (int32_t off, int32_t enable, int32_t indicator) const [protected]
Unpacks a state event bit from the record.
virtual bool vrt::Record::isNullValue () const [inline, virtual]
A record is considered null if it has no data.
Reimplemented from vrt::VRTObject.
References buf.
void vrt::Record::packAscii (int32_t off, string val, int32_t len) [inline, protected]
Packs an ASCII string into the record.
References buf.
Referenced by vrt::GeoSentences::setSentences().
void vrt::Record::packBoolean (int32_t off, bool val) [inline, protected]
Packs a boolean value into the record.
References buf.
void vrt::Record::packBoolNull (int32_t off, boolNull val) [inline, protected]
Packs a boolNull value into the record.
References buf.
void vrt::Record::packByte (int32_t off, int8_t val) [inline, protected]
Packs an 8-bit integer into the record.
References buf.
void vrt::Record::packBytes (int32_t off, void * val, int32_t len) [inline, protected]
Packs a block of bytes into the record.
References buf, and packBytes().
void vrt::Record::packBytes (int32_t off, const vector< char > & val, int32_t len) [inline, protected]
Packs a block of bytes into the record.
References buf.
Referenced by packBytes().
void vrt::Record::packDouble (int32_t off, double val) [inline, protected]
Packs a 64-bit floating-point value into the record.
References buf.
Referenced by vrt::Point::setPositionX(), vrt::Point::setPositionY(), vrt::Point::setPositionZ(), vrt::Point::setVelocityX(), vrt::Point::setVelocityY(), and vrt::Point::setVelocityZ().
void vrt::Record::packFloat (int32_t off, float val) [inline, protected]
Packs a 32-bit floating-point value into the record.
References buf.
Referenced by vrt::Point::setAccelerationX(), vrt::Point::setAccelerationY(), vrt::Point::setAccelerationZ(), vrt::Point::setAttitudeAlpha(), vrt::Point::setAttitudeBeta(), and vrt::Point::setAttitudePhi().
void vrt::Record::packInetAddr (int32_t off, const InetAddress & val) [inline, protected]
Packs a InetAddress into the record.
References buf.
void vrt::Record::packInt (int32_t off, int32_t val) [inline, protected]
Packs a 32-bit integer into the record.
References buf.
Referenced by vrt::Geolocation::setAltitude(), vrt::Ephemeris::setAttitudeAlpha(), vrt::Ephemeris::setAttitudeBeta(), vrt::Ephemeris::setAttitudePhi(), vrt::ArrayOfRecords::setBitMappedIndicator(), vrt::Geolocation::setHeadingAngle(), vrt::Geolocation::setLatitude(), vrt::Geolocation::setLongitude(), vrt::Geolocation::setMagneticVariation(), vrt::AbstractGeolocation::setManufacturerIdentifier(), vrt::Ephemeris::setPositionX(), vrt::Ephemeris::setPositionY(), vrt::Ephemeris::setPositionZ(), vrt::GeoSentences::setSentences(), vrt::Geolocation::setSpeedOverGround(), vrt::Geolocation::setTrackAngle(), vrt::Ephemeris::setVelocityX(), vrt::Ephemeris::setVelocityY(), and vrt::Ephemeris::setVelocityZ().
void vrt::Record::packLong (int32_t off, int64_t val) [inline, protected]
Packs a 64-bit integer into the record.
References buf.
void vrt::Record::packMetadata (int32_t off, MetadataBlock val, int32_t len) [inline, protected]
Packs a metadata block into the record.
References buf.
void vrt::Record::packShort (int32_t off, int16_t val) [inline, protected]
Packs a 16-bit integer into the record.
References buf.
void vrt::Record::packTimeStamp (int32_t off, const TimeStamp & val, IntegerMode epoch) [inline, protected]
Packs a TimeStamp into the record.
References buf.
void vrt::Record::packUTF8 (int32_t off, wstring val, int32_t len) [inline, protected]
Packs a UTF-8 string into the record.
References buf, and packUTF8().
void vrt::Record::packUTF8 (int32_t off, string val, int32_t len) [inline, protected]
Packs a UTF-8 string into the record.
References buf.
Referenced by packUTF8().
void vrt::Record::packUUID (int32_t off, const UUID & val) [inline, protected]
Packs a UUID into the record.
References buf.
virtual void vrt::Record::readBytes (void * buffer) const [inline, virtual]
Reads bytes from this record to the specified buffer.
Parameters:
buffer The buffer to write to.
References buf.
virtual void vrt::Record::setByteLength (int32_t len, int32_t off = -1) [protected, virtual]
Sets the length in bytes with any additional bytes added/removed from the given point (-1=end).
Referenced by vrt::GeoSentences::setSentences(), vrt::ArrayOfRecords::writeBytes(), vrt::IndexFieldList::writeBytes(), vrt::ContextAssocLists::writeBytes(), and vrt::GeoSentences::writeBytes().
virtual void vrt::Record::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::HasFields.
Reimplemented in vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, and vrt::Point.
virtual string vrt::Record::toString () const [inline, virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::VRTObject.
Reimplemented in vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, and vrt::Point.
string vrt::Record::unpackAscii (int32_t off, int32_t len) const [inline, protected]
Unpacks an ASCII string from the record.
References buf.
Referenced by vrt::GeoSentences::getSentences().
bool vrt::Record::unpackBit (int32_t off, int32_t bit) const [protected]
Unpacks an bit from the record.
bool vrt::Record::unpackBoolean (int32_t off) const [inline, protected]
Unpacks a boolean value from the record.
References buf.
boolNull vrt::Record::unpackBoolNull (int32_t off) const [inline, protected]
Unpacks a boolNull value from the record.
References buf.
int8_t vrt::Record::unpackByte (int32_t off) const [inline, protected]
Unpacks an 8-bit integer from the record.
References buf.
Referenced by vrt::SpectrumField::getAveragingType(), vrt::ArrayOfRecords::getHeaderSize(), vrt::IndexFieldList::getIndexEntrySize(), vrt::SpectrumField::getSpectrumType(), vrt::SpectrumField::getWindowTime(), vrt::SpectrumField::getWindowType(), and vrt::AbstractGeolocation::setManufacturerIdentifier().
void* vrt::Record::unpackBytes (int32_t off, void * val, int32_t len) const [inline, protected]
Unpacks a block of bytes from the record.
References buf, and unpackBytes().
vector<char> vrt::Record::unpackBytes (int32_t off, int32_t len) const [inline, protected]
Unpacks a block of bytes from the record.
References buf.
Referenced by vrt::ArrayOfRecords::getApplicationSpecificHeader(), and unpackBytes().
double vrt::Record::unpackDouble (int32_t off) const [inline, protected]
Unpacks a 64-bit floating-point value from the record.
References buf.
Referenced by vrt::Point::getPositionX(), vrt::Point::getPositionY(), vrt::Point::getPositionZ(), vrt::Point::getVelocityX(), vrt::Point::getVelocityY(), and vrt::Point::getVelocityZ().
float vrt::Record::unpackFloat (int32_t off) const [inline, protected]
Unpacks a 32-bit floating-point value from the record.
References buf.
Referenced by vrt::Point::getAccelerationX(), vrt::Point::getAccelerationY(), vrt::Point::getAccelerationZ(), vrt::Point::getAttitudeAlpha(), vrt::Point::getAttitudeBeta(), and vrt::Point::getAttitudePhi().
InetAddress vrt::Record::unpackInetAddr (int32_t off) const [inline, protected]
Unpacks a InetAddress from the record.
References buf.
int32_t vrt::Record::unpackInt (int32_t off) const [inline, protected]
Unpacks a 32-bit integer from the record.
References buf.
Referenced by vrt::Geolocation::getAltitude(), vrt::Ephemeris::getAttitudeAlpha(), vrt::Ephemeris::getAttitudeBeta(), vrt::Ephemeris::getAttitudePhi(), vrt::ArrayOfRecords::getBitMappedIndicator(), vrt::Geolocation::getHeadingAngle(), vrt::IndexFieldList::getIndexEntriesCount(), vrt::Geolocation::getLatitude(), vrt::Geolocation::getLongitude(), vrt::Geolocation::getMagneticVariation(), vrt::AbstractGeolocation::getManufacturerIdentifier(), vrt::SpectrumField::getNumAverages(), vrt::SpectrumField::getNumWindowPoints(), vrt::Ephemeris::getPositionX(), vrt::Ephemeris::getPositionY(), vrt::Ephemeris::getPositionZ(), vrt::ArrayOfRecords::getRecordCount(), vrt::ArrayOfRecords::getRecordSize(), vrt::SpectrumField::getSpectrumF1Index(), vrt::SpectrumField::getSpectrumF2Index(), vrt::Geolocation::getSpeedOverGround(), vrt::ArrayOfRecords::getTotalFieldSize(), vrt::IndexFieldList::getTotalFieldSize(), vrt::Geolocation::getTrackAngle(), vrt::Ephemeris::getVelocityX(), vrt::Ephemeris::getVelocityY(), vrt::Ephemeris::getVelocityZ(), vrt::SpectrumField::getWeightingFactor(), vrt::SpectrumField::getWindowTimeDeltaFloat(), vrt::SpectrumField::getWindowTimeDeltaInt(), and vrt::GeoSentences::writeBytes().
int64_t vrt::Record::unpackLong (int32_t off) const [inline, protected]
Unpacks a 64-bit integer from the record.
References buf.
Referenced by vrt::SpectrumField::getResolution(), and vrt::SpectrumField::getSpan().
MetadataBlock vrt::Record::unpackMetadata (int32_t off, int32_t len) const [inline, protected]
Unpacks a metadata block from the record.
References buf.
int16_t vrt::Record::unpackShort (int32_t off) const [inline, protected]
Unpacks a 16-bit integer from the record.
References buf.
Referenced by vrt::ContextAssocLists::getAsynchronousChannelCount(), vrt::ContextAssocLists::getAsynchronousChannelTagsPresent(), vrt::ContextAssocLists::getSourceContextCount(), vrt::ContextAssocLists::getSystemContextCount(), and vrt::ContextAssocLists::getVectorComponentCount().
TimeStamp vrt::Record::unpackTimeStamp (int32_t off, IntegerMode epoch) const [inline, protected]
Unpacks a TimeStamp from the record.
References buf.
wstring vrt::Record::unpackUTF8 (int32_t off, int32_t len) const [inline, protected]
Unpacks a UTF-8 string from the record.
References buf.
UUID vrt::Record::unpackUUID (int32_t off) const [inline, protected]
Unpacks a UUID from the record.
References buf.
virtual void vrt::Record::writeBytes (const void * buffer) [inline, virtual]
Writes bytes to this record from the specified buffer.
Parameters:
buffer The buffer to read from.
Reimplemented in vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, and vrt::ArrayOfRecords.
References buf.
Member Data Documentation
vector<char> vrt::Record::buf [protected]
Internal Use Only: The data buffer used.
Referenced by getByteLength(), isNullValue(), packAscii(), packBoolean(), packBoolNull(), packByte(), packBytes(), packDouble(), packFloat(), packInetAddr(), packInt(), packLong(), packMetadata(), packShort(), packTimeStamp(), packUTF8(), packUUID(), readBytes(), unpackAscii(), unpackBoolean(), unpackBoolNull(), unpackByte(), unpackBytes(), unpackDouble(), unpackFloat(), unpackInetAddr(), unpackInt(), unpackLong(), unpackMetadata(), unpackShort(), unpackTimeStamp(), unpackUTF8(), unpackUUID(), and writeBytes().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/Record.h