VRT: vrt::VRTObject Class Reference
vrt::VRTObject Class Reference
A basic root-level object definition.
#include <VRTObject.h>
Public Member Functions
VRTObject ()
Basic no-argument constructor.
VRTObject (const VRTObject &o)
Basic copy constructor.
virtual ~VRTObject ()
Basic destructor.
void _delete ()
Internal Use Only: Deletes the object
virtual bool equals (const VRTObject *o) const
Tests this object for equality with another one.
virtual bool equals (const VRTObject &o) const
Tests this object for equality with another one.
const type_info & getClass () const
Gets the type_info for the class.
string getClassName () const
Gets the name of the class.
virtual bool isNullValue () const
Is this object equal to null.
bool operator!= (const VRTObject *o) const
The == operator is the same as calling !equals(.
bool operator!= (const VRTObject &o) const
The == operator is the same as calling !equals(.
bool operator== (const VRTObject *o) const
The == operator is the same as calling equals(.
bool operator== (const VRTObject &o) const
The == operator is the same as calling equals(.
virtual string toString () const
Converts this class its string form.
Static Public Member Functions
static bool equal (const VRTObject *a, const VRTObject *b)
Tests two VRTObjects for equality.
static bool equal (const VRTObject &a, const VRTObject &b)
Tests two VRTObjects for equality.
Friends
class MutexLock
Detailed Description
A basic root-level object definition.
This definition is extremely similar to the Java Object class and allows subclasses to more-closely follow their Java counterparts.
Constructor & Destructor Documentation
vrt::VRTObject::VRTObject (const VRTObject & o) [inline]
Basic copy constructor.
vrt::VRTObject::VRTObject () [inline]
Basic no-argument constructor.
virtual vrt::VRTObject::~VRTObject () [inline, virtual]
Basic destructor.
Member Function Documentation
void vrt::VRTObject::_delete ()
Internal Use Only: Deletes the object
static bool vrt::VRTObject::equal (const VRTObject * a, const VRTObject * b) [inline, static]
Tests two VRTObjects for equality.
References equals().
static bool vrt::VRTObject::equal (const VRTObject & a, const VRTObject & b) [inline, static]
Tests two VRTObjects for equality.
References equals().
virtual bool vrt::VRTObject::equals (const VRTObject * o) const [virtual]
Tests this object for equality with another one.
Since this function was added *after* the one that takes in a reference, the default implementation is:
    bool VRTObject::equals (const VRTObject *o) const {
      return (o != NULL) && equals(*o);
    }
Parameters:
o The unknown object.
Returns:
true if they are identical, false otherwise.
virtual bool vrt::VRTObject::equals (const VRTObject & o) const [virtual]
Tests this object for equality with another one.
Reimplemented in vrt::AbstractVRAFile, vrt::BasicVRLFrame, vrt::BasicVRTPacket, vrt::InetAddress, vrt::ConstPacketIterator, vrt::UUID, vrt::VRTException, and vrt::VRTEvent.
Referenced by equal().
const type_info& vrt::VRTObject::getClass () const [inline]
Gets the type_info for the class.
string vrt::VRTObject::getClassName () const
Gets the name of the class.
virtual bool vrt::VRTObject::isNullValue () const [inline, virtual]
Is this object equal to null.
Reimplemented in vrt::BasicVRTPacket, vrt::InetAddress, vrt::LeapSeconds, vrt::PayloadFormat, vrt::Record, vrt::TimeStamp, vrt::UUID, vrt::Value, vrt::VRTException, vrt::Socket, and vrt::VRTEvent.
bool vrt::VRTObject::operator!= (const VRTObject * o) const [inline]
The == operator is the same as calling !equals(.
.)
bool vrt::VRTObject::operator!= (const VRTObject & o) const [inline]
The == operator is the same as calling !equals(.
.)
bool vrt::VRTObject::operator== (const VRTObject * o) const [inline]
The == operator is the same as calling equals(.
.)
bool vrt::VRTObject::operator== (const VRTObject & o) const [inline]
The == operator is the same as calling equals(.
.)
virtual string vrt::VRTObject::toString () const [virtual]
Converts this class its string form.
Reimplemented in vrt::AbstractVRAFile, vrt::BasicVRLFrame, vrt::BasicVRTPacket, vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, vrt::InetAddress, vrt::MetadataEntry, vrt::MetadataBlock, vrt::ConstPacketIterator, vrt::PayloadFormat, vrt::Record, vrt::TimeStamp, vrt::UUID, vrt::Value, vrt::VRTException, vrt::Point, vrt::NetIO, vrt::Socket, and vrt::VRTEvent.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/VRTObject.h