VRT: vrt::AbstractGeolocation Class Reference
vrt::AbstractGeolocation Class Reference
Represents a GPS or INS geolocation fix.
#include <IndicatorFields.h>
Public Member Functions
AbstractGeolocation (const AbstractGeolocation &r)
Basic copy constructor.
AbstractGeolocation (size_t len)
Creates a new instance with the given size.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
string getManufacturerID () const
Gets the manufacturer of the GPS/INS device.
int32_t getManufacturerIdentifier () const
Gets the manufacturer of the GPS/INS device.
TimeStamp getTimeStamp () const
Gets the time stamp for the geolocation fix.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setManufacturerID (const string &oui)
Sets the manufacturer of the GPS/INS device.
void setManufacturerIdentifier (int32_t oui)
Sets the manufacturer of the GPS/INS device.
virtual string toString () const
Gets a basic description of the object, useful for debugging.
Protected Member Functions
virtual void setTimeStamp (const TimeStamp &ts)
Sets the time stamp for the geolocation fix.
Detailed Description
Represents a GPS or INS geolocation fix.
The fact that GeoSentences does not extend this class is not accidental.
See also:
Geolocation
Ephemeris
Constructor & Destructor Documentation
vrt::AbstractGeolocation::AbstractGeolocation (size_t len)
Creates a new instance with the given size.
Parameters:
len The record length in bytes.
vrt::AbstractGeolocation::AbstractGeolocation (const AbstractGeolocation & r)
Basic copy constructor.
Member Function Documentation
virtual Value* vrt::AbstractGeolocation::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::Record.
Reimplemented in vrt::Geolocation, vrt::Ephemeris, and vrt::GeoSentences.
virtual int32_t vrt::AbstractGeolocation::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::Record.
Reimplemented in vrt::Geolocation, vrt::Ephemeris, and vrt::GeoSentences.
virtual string vrt::AbstractGeolocation::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::Record.
Reimplemented in vrt::Geolocation, vrt::Ephemeris, and vrt::GeoSentences.
virtual ValueType vrt::AbstractGeolocation::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::Record.
Reimplemented in vrt::Geolocation, vrt::Ephemeris, and vrt::GeoSentences.
string vrt::AbstractGeolocation::getManufacturerID () const [inline]
Gets the manufacturer of the GPS/INS device.
Returns:
The GPS/INS manufacturer OUI.
References getManufacturerIdentifier(), and vrt::Utilities::toStringOUI().
int32_t vrt::AbstractGeolocation::getManufacturerIdentifier () const [inline]
Gets the manufacturer of the GPS/INS device.
Returns:
The GPS/INS manufacturer OUI.
References vrt::Record::unpackInt().
Referenced by getManufacturerID().
TimeStamp vrt::AbstractGeolocation::getTimeStamp () const
Gets the time stamp for the geolocation fix.
Returns:
The time stamp for the geolocation fix or a null time if such is not supported.
Reimplemented in vrt::GeoSentences.
virtual void vrt::AbstractGeolocation::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::Record.
Reimplemented in vrt::Geolocation, vrt::Ephemeris, and vrt::GeoSentences.
void vrt::AbstractGeolocation::setManufacturerID (const string & oui) [inline]
Sets the manufacturer of the GPS/INS device.
Parameters:
oui The GPS/INS manufacturer OUI.
Exceptions:
VRTException If the OUI is invalid.
References vrt::Utilities::fromStringOUI(), and setManufacturerIdentifier().
void vrt::AbstractGeolocation::setManufacturerIdentifier (int32_t oui) [inline]
Sets the manufacturer of the GPS/INS device.
Parameters:
oui The GPS/INS manufacturer OUI.
Exceptions:
VRTException If the OUI is invalid.
References vrt::Record::packInt(), and vrt::Record::unpackByte().
Referenced by setManufacturerID().
virtual void vrt::AbstractGeolocation::setTimeStamp (const TimeStamp & ts) [protected, virtual]
Sets the time stamp for the geolocation fix.
Parameters:
ts The time stamp for the geolocation fix.
Reimplemented in vrt::Geolocation, and vrt::Ephemeris.
virtual string vrt::AbstractGeolocation::toString () const [virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::Record.
Reimplemented in vrt::Geolocation, vrt::Ephemeris, and vrt::GeoSentences.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/IndicatorFields.h