VRT: vrt::ArrayOfRecords Class Reference
vrt::ArrayOfRecords Class Reference
Specifies an Array of Records.
#include <IndicatorFields.h>
Public Member Functions
ArrayOfRecords (const ArrayOfRecords &r)
Basic copy constructor.
ArrayOfRecords ()
Creates a new instance.
bool addRecord (const Record &val, int32_t idx=-1)
Adds Record(s) to the Array of Records.
int32_t addRecords (const vector< Record > &val, int32_t idx=-1)
Adds Record(s) to the Array of Records.
vector< char > getApplicationSpecificHeader () const
Gets a copy of the Application-Specific Header as a byte buffer.
int32_t getBitMappedIndicator () const
Gets the Bit-mapped indicator for optional record subfields.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
int32_t getHeaderSize () const
Gets the size of the optional Application-Specific Header in number of 32-bit words.
void getRecord (int32_t idx, Record &rec) const
Gets a copy of a single Record.
int32_t getRecordCount () const
Gets the number of Records.
vector< Record > getRecords (int32_t idx=0, int32_t num=-1) const
Gets a copy of the Array of Records.
int32_t getRecordSize () const
Gets the size of each Record in number of 32-bit words.
int32_t getTotalFieldSize () const
Gets the total size of Array Of Records in number of 32-bit words.
void setApplicationSpecificHeader (const char *val, size_t bytes)
Sets the Application-Specific Header If val pointer is null, Application-Specific Header is only resized to the number of bytes specified.
void setApplicationSpecificHeader (const vector< char > &val)
Sets the Application-Specific Header.
void setBitMappedIndicator (int32_t val)
Sets the Bit-mapped indicator for optional record subfields.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setRecordCount (int32_t val, int32_t off=-1)
Sets the number of Records.
void setRecords (const vector< Record > &val)
Sets the Array of Records.
void setRecordSize (int32_t val)
Sets the size of each Record in number of 32-bit words.
virtual string toString () const
Gets a basic description of the object, useful for debugging.
virtual void writeBytes (const void *buffer)
Writes bytes to this record from the specified buffer.
Detailed Description
Specifies an Array of Records.
Constructor & Destructor Documentation
vrt::ArrayOfRecords::ArrayOfRecords ()
Creates a new instance.
vrt::ArrayOfRecords::ArrayOfRecords (const ArrayOfRecords & r)
Basic copy constructor.
Member Function Documentation
bool vrt::ArrayOfRecords::addRecord (const Record & val, int32_t idx = -1)
Adds Record(s) to the Array of Records.
Parameters:
val The Array of Records to add.
idx The index to insert the new Records.
Returns:
True if successfully inserted Record; False otherwise.
int32_t vrt::ArrayOfRecords::addRecords (const vector< Record > & val, int32_t idx = -1)
Adds Record(s) to the Array of Records.
All Records must be the same size. Function returns upon encountering a Record of differing size.
Parameters:
val The Array of Records to add.
idx The index to insert the new Records. Records are added to the end for invalid indices.
Returns:
The number of Records inserted. Number may be less than total attempted if a Record of different size is encountered.
vector<char> vrt::ArrayOfRecords::getApplicationSpecificHeader () const [inline]
Gets a copy of the Application-Specific Header as a byte buffer.
Returns:
A copy of the Application-Specific Header (returns an arry of length 0 if none).
References getHeaderSize(), and vrt::Record::unpackBytes().
int32_t vrt::ArrayOfRecords::getBitMappedIndicator () const [inline]
Gets the Bit-mapped indicator for optional record subfields.
References vrt::Record::unpackInt().
virtual Value* vrt::ArrayOfRecords::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::Record.
virtual int32_t vrt::ArrayOfRecords::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::Record.
virtual string vrt::ArrayOfRecords::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::Record.
virtual ValueType vrt::ArrayOfRecords::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::Record.
int32_t vrt::ArrayOfRecords::getHeaderSize () const [inline]
Gets the size of the optional Application-Specific Header in number of 32-bit words.
References vrt::Record::unpackByte().
Referenced by getApplicationSpecificHeader().
void vrt::ArrayOfRecords::getRecord (int32_t idx, Record & rec) const
Gets a copy of a single Record.
Parameters:
idx Index of record to get.
rec Record to be populated with results. Will be resized if necessary. Set to Null Record if there are no entries or index is invalid.
int32_t vrt::ArrayOfRecords::getRecordCount () const [inline]
Gets the number of Records.
References vrt::Record::unpackInt().
vector<Record> vrt::ArrayOfRecords::getRecords (int32_t idx = 0, int32_t num = -1) const
Gets a copy of the Array of Records.
Parameters:
idx Index of first record to get. Invalid indicies result in empty vector returned.
num Number of records to get. Invalid number (i.e. negative or too high) result in max available from index specified.
Returns:
A copy of the Array of Records (returns an arry of length 0 if there are no entries).
int32_t vrt::ArrayOfRecords::getRecordSize () const [inline]
Gets the size of each Record in number of 32-bit words.
References vrt::Record::unpackInt().
int32_t vrt::ArrayOfRecords::getTotalFieldSize () const [inline]
Gets the total size of Array Of Records in number of 32-bit words.
References vrt::Record::unpackInt().
void vrt::ArrayOfRecords::setApplicationSpecificHeader (const char * val, size_t bytes)
Sets the Application-Specific Header If val pointer is null, Application-Specific Header is only resized to the number of bytes specified.
Parameters:
val The Application-Specific Header (an arry of length 0 if none).
bytes The size of Application-Specific Header in bytes.
Exceptions:
VRTException if size of Application-Specific header exceeds 255 32-bit words
VRTException if size of Application-Specific header is negative
void vrt::ArrayOfRecords::setApplicationSpecificHeader (const vector< char > & val)
Sets the Application-Specific Header.
Parameters:
val The Application-Specific Header (an arry of length 0 if none).
Exceptions:
VRTException if size of Application-Specific header exceeds 255 32-bit words
void vrt::ArrayOfRecords::setBitMappedIndicator (int32_t val) [inline]
Sets the Bit-mapped indicator for optional record subfields.
References vrt::Record::packInt().
virtual void vrt::ArrayOfRecords::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::Record.
void vrt::ArrayOfRecords::setRecordCount (int32_t val, int32_t off = -1)
Sets the number of Records.
void vrt::ArrayOfRecords::setRecords (const vector< Record > & val)
Sets the Array of Records.
Parameters:
val The Array of Records (an arry of length 0 if there are no entries).
void vrt::ArrayOfRecords::setRecordSize (int32_t val)
Sets the size of each Record in number of 32-bit words.
virtual string vrt::ArrayOfRecords::toString () const [virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::Record.
virtual void vrt::ArrayOfRecords::writeBytes (const void * buffer) [inline, virtual]
Writes bytes to this record from the specified buffer.
Parameters:
buffer The buffer to read from.
Reimplemented from vrt::Record.
References vrt::Record::setByteLength().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/IndicatorFields.h