VRT: vrt::TimeStamp Class Reference
vrt::TimeStamp Class Reference
An immutable time stamp.
#include <TimeStamp.h>
Public Member Functions
TimeStamp (IntegerMode tsiMode, FractionalMode tsfMode, uint32_t tsi, uint64_t tsf, LeapSeconds *ls, double sr=DOUBLE_NAN)
Creates a new instance.
TimeStamp (IntegerMode tsiMode, FractionalMode tsfMode, uint32_t tsi, uint64_t tsf, double sr=DOUBLE_NAN)
Creates a new instance, using the default leap-second reference.
TimeStamp (IntegerMode epoch, uint32_t sec, uint64_t ps, double sr=DOUBLE_NAN)
Creates a new instance, using the default leap-second reference.
TimeStamp (const TimeStamp &ts)
Copy constructor.
TimeStamp ()
Basic no-argument constructor.
~TimeStamp ()
Destructor.
TimeStamp addPicoSeconds (int64_t ps) const
Adds the specified number of picoseconds to the current time and returns the resulting time.
TimeStamp addSamples (int64_t samples, double _sr) const
Adds the specified number of picoseconds to the current time and returns the resulting time.
TimeStamp addSeconds (int64_t sec) const
Adds the specified number of seconds to the current time and returns the resulting time.
TimeStamp addTime (int64_t sec, int64_t fsec, double _sr) const
TimeStamp addTime (int64_t sec, int64_t ps) const
Adds the specified number of picoseconds to the current time and returns the resulting time.
char compareTo (const TimeStamp &other) const
Compares time stamp values.
bool equals (const VRTObject &ts) const
Equals method that checks for strict equality.
double getDoubleSeconds (double sr) const
Gets the floating point time stamp in UTC seconds (if GPS it converts to UTC first) given a sampling rate.
double getDoubleSeconds () const
Gets the floating point time stamp in UTC seconds (if GPS it converts to UTC first).
IntegerMode getEpoch () const
Gets the epoch used.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
FractionalMode getFractionalMode () const
Gets the time stamp mode used for fractional seconds.
double getFractionalSeconds () const
Gets the fractional time stamp as a fraction of a second.
int64_t getGPSSeconds () const
Gets the integer time stamp in GPS seconds (if UTC it converts to GPS first).
IntegerMode getIntegerMode () const
Gets the time stamp mode used for integral seconds.
LeapSeconds * getLeapSecondRef () const
Gets the leap-seconds reference used.
double getMidasSeconds () const
Gets the integer time stamp in Midas seconds.
double getMidasTime () const
Gets the integer and fractional time stamp in Midas seconds.
int64_t getNORADSeconds (boolNull leapCounted=_NULL) const
Gets the integer time stamp in NORAD seconds (if GPS it converts to UTC first then from UTC to NORAD).
uint64_t getPicoSeconds () const
Gets the fractional time stamp in picoseconds.
uint64_t getPicoSeconds (double sr) const
Gets the fractional time stamp in picoseconds.
int64_t getPOSIXSeconds () const
Gets the integer time stamp in POSIX seconds (if GPS it converts to UTC first then from UTC to POSIX).
uint64_t getSampleCount () const
Gets the fractional time stamp in samples.
double getSampleRate () const
Gets the sample rate.
uint32_t getSecondsGPS () const
Gets the integer time stamp in GPS seconds (if UTC it converts to GPS first).
uint32_t getSecondsNORAD (boolNull leapCounted=_NULL) const
Gets the integer time stamp in NORAD seconds (if GPS it converts to UTC first then from UTC to NORAD).
uint32_t getSecondsPOSIX () const
Gets the integer time stamp in POSIX seconds (if GPS it converts to UTC first then from UTC to POSIX).
uint32_t getSecondsUTC () const
Gets the integer time stamp in UTC seconds (if GPS it converts to UTC first).
uint64_t getTimeStampFractional () const
Gets the fractional time stamp.
uint32_t getTimeStampInteger () const
Gets the integer time stamp.
int64_t getUTCSeconds () const
Gets the integer time stamp in UTC seconds (if GPS it converts to UTC first).
virtual bool isNullValue () const
A record is considered null both the integer and fractional modes are set to None.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
TimeStamp toGPS () const
Converts from UTC or GPS time to GPS.
string toString () const
A textural representation of the time stamp.
string toStringGPS () const
A textural representation of the time stamp in UTC.
string toStringUTC () const
A textural representation of the time stamp in UTC.
string toStringUTC (string format) const
Internal Use Only (Experimental)
TimeStamp toUTC () const
Converts from UTC or GPS time to UTC.
Static Public Member Functions
static TimeStamp forNoradTime (int32_t seconds, int64_t picoseconds, int32_t year, LeapSeconds *_ls)
static TimeStamp forNoradTime (int32_t seconds, int64_t picoseconds)
static TimeStamp forTime (int32_t year, int32_t mon, int32_t day, int32_t hour, int32_t min, int32_t wsec, int64_t psec, int32_t zone, IntegerMode tsiMode, LeapSeconds *ls)
Converts a time specifier to a time stamp.
static TimeStamp forTime (int32_t year, int32_t mon, int32_t day, int32_t hour, int32_t min, int32_t wsec, int64_t psec, int32_t zone, IntegerMode _tsiMode)
Converts a time specifier to a time stamp.
static TimeStamp forTimeIRIG (int32_t seconds, int32_t minutes, int32_t hours, int32_t days, int32_t hundreths, LeapSeconds *ls)
Creates a time stamp from an IRIG time.
static TimeStamp forTimeIRIG (int32_t seconds, int32_t minutes, int32_t hours, int32_t days, int32_t hundreths)
Creates a time stamp from an IRIG time.
static TimeStamp forTimeIRIG (int32_t seconds, int32_t minutes, int32_t hours, int32_t days, LeapSeconds *_ls)
Creates a time stamp from an IRIG time.
static TimeStamp forTimeIRIG (int32_t seconds, int32_t minutes, int32_t hours, int32_t days)
Creates a time stamp from an IRIG time.
static TimeStamp forTimeMidas (double seconds, double fractionalSeconds, LeapSeconds *_ls)
Creates a time stamp from a Midas time.
static TimeStamp forTimeMidas (double seconds, double fractionalSeconds)
Creates a time stamp from a Midas time.
static TimeStamp forTimeNORAD (int32_t seconds, int64_t picoseconds, boolNull leapCounted, int32_t year, LeapSeconds *_ls)
Creates a time stamp from a NORAD time.
static TimeStamp forTimeNORAD (int32_t seconds, int64_t picoseconds, int32_t year, LeapSeconds *_ls)
Creates a time stamp from a NORAD time.
static TimeStamp forTimeNORAD (int32_t seconds, int64_t picoseconds, boolNull leapCounted=_NULL)
Creates a time stamp from a NORAD time.
static TimeStamp forTimePOSIX (int64_t seconds, int64_t picoseconds, LeapSeconds *ls)
Creates a time stamp from a POSIX time.
static TimeStamp forTimePOSIX (int64_t seconds, int64_t picoseconds)
Creates a time stamp from a POSIX time.
static TimeStamp forTimePTP (int64_t seconds, int64_t nanoseconds, LeapSeconds *_ls)
Creates a GPS time stamp from a PTP time.
static TimeStamp forTimePTP (int64_t seconds, int64_t nanoseconds)
Creates a GPS time stamp from a PTP time.
static TimeStamp getSystemTime (LeapSeconds *ls)
Gets a time stamp using system time.
static TimeStamp getSystemTime ()
Gets a time stamp using system time.
static TimeStamp parseTime (string time, IntegerMode tsiMode, LeapSeconds *ls)
Parses a time stamp in one of the following ISO 8601 formats.
static TimeStamp parseTime (string time, IntegerMode _tsiMode)
Parses a time stamp in one of the ISO 8601 formats documented in parseTime(time, tsiMode, ls).
Static Public Attributes
static const int32_t GPS2PTP
Delta between GPS and PTP epochs.
static const int32_t GPS2UTC
Delta between GPS and UTC epochs.
static const IntegerMode GPS_EPOCH
The GPS epoch.
static const double HALF_PICOSECOND
The value of 1/2 picosecond in seconds.
static const int32_t MIDAS2POSIX
Delta between Midas and POSIX epochs.
static const TimeStamp NO_TIME_STAMP
An empty time stamp.
static const IntegerMode NULL_EPOCH
The "null" epoch.
static const double ONE_PICOSECOND
The value of 1 picosecond in seconds.
static const int64_t ONE_SEC
The value of 1 second in picoseconds.
static const uint64_t ONE_SECOND
The value of 1 second in picoseconds (unsigned variant).
static const IntegerMode UTC_EPOCH
The UTC epoch.
static const TimeStamp Y2K_GPS
This is equal to the start of the year 2000 in the GPS epoch and provides a reasonable minimum bounds for most time values.
Detailed Description
An immutable time stamp.
For time values (i.e. the integer time mode is not None or Other), there are four different "epochs" that are supported by this class (see below); however all time values stored within this class will be in UTC or GPS time.
UTC (per VITA-49 specification)
This measures number of 1-second clock tics since 1 JAN 1970. Note that the VITA-49 specification is extremely clear on the point that this includes leap seconds.
This class makes the assumption that only times after 1 JAN 1972 (or zero) are used. This is important since prior to 1 JAN 1972 the duration of 1 UTC second differed from the definition used today (since 1 JAN 1972 the duration of 1 UTC second matches the SI, TAI, and GPS definitions). It is also assumed that exactly 11 leap seconds took place between 1 JAN 1970 and 6 JAN 1980. This "11 leap second" assumption is consistent with the example provided in IEEE 1588-2008 (see section B.2 of [2]) that shows an 8 leap-second difference between UTC and TAI on 1 Jan 1970 and the officially-accepted 19 leap-second difference between UTC and TAI on 1 Jan 1980 (see [4]).
    1:  LS  = (Leap Seconds Added Between 1 Jan 1970 to 6 Jan 1980)
    2:  LS  = (Leap Seconds 1 Jan 1970 to 1 Jan 1980) + (Leap Seconds 1 Jan 1980 to 6 Jan 1980)
    3:  LS  = (Leap Seconds 1 Jan 1970 to 1 Jan 1980) +               0
    3:  LS  = (Leap Seconds 1 Jan 1970 to 1 Jan 1980)
    4:  LS  = (Total Leap Seconds on 1 Jan 1980) - (Total Leap Seconds on 1 Jan 1970)
    5:  LS  =                 19                 - (Total Leap Seconds on 1 Jan 1970)
    6:  LS  =                 19                 -                  8
    7:  LS  =                                    11
   3 - by definition no leap seconds are added mid-month
   4 - basic expansion
   5 - per USNO, see [4]
   6 - per IEEE 1588-2008, see [2]
Although UTC time includes leap seconds. The number of leap seconds elapsed must still be looked up every time a conversion is made to another time format and/or a time string (year-month-day).
GPS (per VITA-49 specification)
This measures number of 1-second clock tics since 6 JAN 1980. In practice, this is usually the most efficient form to use as there is never a need to worry about leap second adjustments.
POSIX (in seconds since start of epoch)
The POSIX time is extremely common on most computers, but it is extremely ill-defined. Many sources say that POSIX time is equal to UTC time, but (especially when represented in seconds-since-epoch form) that is simply not true. The true POSIX epoch is equal to:
    POSIX Seconds    =    (days since 1 Jan 1970) * (86,400 sec/day) + (seconds of current day)
Note that the above equation differs from UTC time in that, UTC time is not fixed at 86,400 sec/day, but rather can be 86,399 sec/day (subtract a leap second), 86,400 sec/day (normal), or 86,401 sec/day (add a leap second). This implicitly yields:
    POSIX Seconds    =    (days since 1 Jan 1970) * (86,400 sec/day) + (seconds of current day)
                     =    (UTC seconds since 1 JAN 1970) - (UTC leap-seconds since 1 JAN 1970)
When a POSIX time it converted to a string (i.e. year-month-day hours:min:sec) it will match the string for a UTC time ~99.9996% of the time -- this is why people say it is equal to UTC. Anyone who cares about precision time should be immediately concerned about the ~0.0004% of the time where it is just plain wrong (~0.0004% matches the 12 times of the year where a leap-second can be added/removed).
The most problematic thing with POSIX time is that it contains no information about the number of leap-seconds that it didn't count. This means that it is impossible to determine the correct time when at the point of a leap-second insertion and means that basic math on the times won't suffice to determine the number UTC seconds elapsed between two POSIX time stamps.
There is a discontinuity in the POSIX time epoch at the point where a leap-second is added/removed. This class makes no guarantees with regards to the behavior at the point of the discontinuity and may report the time immediately before or immediately after the discontinuity (plus any fractional seconds).
Midas (in seconds since start of epoch)
Midas time is effectively identical to POSIX time but with an epoch starting at 1 Jan 1950, and with fractional seconds represented as a fraction rather than the number of picoseconds.
    Midas Seconds    =    (days since 1 Jan 1950) * (86,400 sec/day) + (seconds of current day)
                     =    (POSIX Seconds) + (seconds between 1 Jan 1950 and 1 Jan 1970)
                     =    (POSIX Seconds) + MIDAS2POSIX
All conversions to/from Midas time involve an intermediate conversion to/from POSIX time and are subject to the same issues with respect to leap-seconds.
The conversion to/from fractional seconds as used in Midas time and picoseconds is simply done using the following equation:
    Fractional Sec   =    (number of picoseconds) / (picoseconds in one second)
                     =    (number of picoseconds) / ONE_SEC
NORAD/IRIG (in seconds since start of current year)
NORAD time is a fairly common one to use, particularly for aerospace-based applications. NORAD time measures the number of seconds since the start of the current UTC year. IRIG time measures day-of-year and seconds-of-day (which effectively equates to seconds-of-year after multiplying day-of-year by 86,400 sec/day).
     +------------------------+-----------+-------------+
     |      TIME-OF-YEAR      |  CONTROL  | TIME-OF-DAY |
     | SEC | MIN | HRS | DAYS | FUNCTIONS |  (seconds)  |
     +-----+-----+-----+------+-----------+-------------+
     |     |     |     |      |           |             |
     +-----+-----+-----+------+-----------+-------------+
                    IRIG Format B (see [1])
      +------------------------------------+-----------+
      |              TIME-OF-YEAR          |  CONTROL  |
      | SEC | MIN | HRS | DAYS | 1/100 SEC | FUNCTIONS |
      +-----+-----+-----+------+-----------+-----------+
      |     |     |     |      |           |           |
      +-----+-----+-----+------+-----------+-----------+
                    IRIG Format G (see [1])
Unfortunately the NORAD definition is some-what ambiguous as to how mid-year leap-seconds are handled, while IRIG is ambiguous in application. This leads to two possible definitions for NORAD (and IRIG-based) time:
    NORAD Seconds    =    (UTC seconds since start of current year)
                  -- OR --
    NORAD Seconds    =    (POSIX seconds since start of current year)
                     =    ((day of year - 1) * (86,400 sec/day)) + (seconds of current day)           [= IRIG B]
                     =    ((day of year - 1) * (86,400 sec/day)) + ((hr * 3600) + (min * 60) + sec)   [= IRIG B/G]
                     =    (UTC seconds since start of current year) - (mid-year leap-seconds)
IRIG time, as reported, follows the second definition (though it is unclear how the 61st second is to be reported during a leap-second addition, see section 2.6 of [1]). The issue with IRIG time is that devices reading the IRIG time will be able to detect the leap second but will not be able to discern that a mid-year leap-second has taken place by exclusively looking at the IRIG time reported subsequent to the leap-second addition.
As of current (Jan 2012), it has been 14+ years since the last mid-year leap second, so there is little reason to believe that past experience will be a good behavior of future behavior (14 years being longer than the life-cycle of most equipment.) It fact, it is well-known that a number of recently-produced devices that read IRIG time and produce a NORAD/UTC time-stamp differ with regards to their implementation. Accordingly, the NORAD-/IRIG-centric functions permit the specification of which form to use, and also allow a default to be set at run-time (see VRTConfig).
One of the inherent issues with using NORAD/IRIG time is that it is necessary to separately provide an indication as to the relevant year. The functions in this class that support a NORAD to UTC conversion allow the the year to be specified. If the year is given as -1, the following algorithm is used to derive the year from the local system clock:
The current year is taken from the local system clock, which is presumed to be approximate enough to estimate the current year within a couple days
If a late-December NORAD time is seen in early-January, the previous year is used
If an early-January NORAD time is seen in late-December, the subsequent year is used
Otherwise the current year is used
The above algorithm gives a few days leeway to account for cases where data that is time-stamped at the end of one year (e.g. 31 DEC) does not get processed until the beginning of the next year (e.g. 1 JAN). It also gives allowances for the local system to be approximate-at-best rather than being locked to a stable time source; and for the local system time to be using POSIX time where an end-of-year leap second gives rise to some ambiguity (see above).
If the second definition is used, there will be a discontinuity in the NORAD time epoch at the point where a leap-second is added/removed. This class makes no guarantees with regards to the behavior at the point of the discontinuity and may report the time immediately before or immediately after the discontinuity (plus any fractional seconds).
Precision Time Protocol (PTP)
PTP is an IEEE standard (see [2]) for clock synchronization among computing devices for situations where "precision" time is required but where the (direct or indirect) cost of a GPS receiver is prohibitive.
PTP provides seconds and nanoseconds referenced to 1 Jan 1970 TAI which differs from 1 Jan 1970 UTC by 8 seconds (see section B.2 of [2]). PTP counts TAI seconds (which are identical to GPS seconds) and has a fixed reference to GPS time (see section 5.3.3 and Table B.1 of [2]):
    GPS Seconds = PTP Seconds - 315,964,819 seconds
Only a basic conversion from PTP is provided. Although it would be viable to include a PTP reader that connects to the applicable sockets, it is currently outside the scope of this library.
HasFields
The following implementation is used for the HasFields methods, but note that since the TimeStamp is immutable they are read-only:
     ID | Name                 | Type
    ----+----------------------+---------------
      0 | String               | String
      1 | StringUTC            | String
      2 | StringGPS            | String
      3 | Epoch                | Int8
      4 | IntegerMode          | Int8
      5 | FractionalMode       | Int8
      6 | UTCSeconds           | Int64
      7 | GPSSeconds           | Int64
      8 | NORADSeconds         | Int64
      9 | POSIXSeconds         | Int64
     10 | MidasTime            | Double
     11 | MidasSeconds         | Double
     12 | PicoSeconds          | Int64
     13 | FractionalSeconds    | Double
     14 | TimeStampInteger     | Int64
     15 | TimeStampFractional  | Int64
    ----+----------------------+---------------
References
     [1] Timing Committee / Range Commanders Council / Telecommunications and Timing
         Group. "IRIG Serial Time Code Formats." IRIG Standard 200-98. Secretariat,
         Range Commanders Council, U.S. Army White Sands Missile Range Pub. May 1998.
     [2] IEEE Instrumentation and Measurement Society. "IEEE Standard for a Precision
         Clock Synchronization Protocol for Networked Measurement and Control Systems."
         IEEE Std 1588-2008. The Institute of Electrical and Electronics Engineers,
         Inc. 24 July 2008.
     [3] USNO. "Leap Seconds." Time Service Dept., U.S. Naval Observatory.
         http://tycho.usno.navy.mil/leapsec.html Last Accessed 15 September 2011.
         (Note: The companion to this is [4].)
     [4] USNO. "tai-utc.dat" Time Service Dept., U.S. Naval Observatory.
         http://maia.usno.navy.mil/ser7/tai-utc.dat or
         ftp://maia.usno.navy.mil/ser7/tai-utc.dat Last Accessed 19 January 2012.
         (Note: This is the same file used by the LeapSeconds class and
         is alternately titled "tai_utc_data.txt" by some systems. It is also
         described in Appendix D of [5].)
     [5] Klyne, G., C. Newman. "Date and Time on the Internet: Timestamps." Network
         Working Group. RFC3339. July 2002.
Constructor & Destructor Documentation
vrt::TimeStamp::TimeStamp ()
Basic no-argument constructor.
Just creates a TimeStamp with integer and fractional modes set to None.
Referenced by forTimePTP().
vrt::TimeStamp::TimeStamp (const TimeStamp & ts)
Copy constructor.
vrt::TimeStamp::~TimeStamp () [inline]
Destructor.
vrt::TimeStamp::TimeStamp (IntegerMode epoch, uint32_t sec, uint64_t ps, double sr = DOUBLE_NAN)
Creates a new instance, using the default leap-second reference.
Parameters:
epoch The epoch used (must be UTC or GPS).
sec The whole seconds (32-bit unsigned number).
ps The picoseconds.
sr The sampling rate.
Exceptions:
VRTException if tsi is less than 0 or greater than 0xFFFFFFFF; or if tsi is null and tsiMode is not None; or if tsf is null and tsfMode is not None; or if the fractional time stamp mode is RealTime and the value (in picoseconds) is greater than or equal to one second.
vrt::TimeStamp::TimeStamp (IntegerMode tsiMode, FractionalMode tsfMode, uint32_t tsi, uint64_t tsf, double sr = DOUBLE_NAN)
Creates a new instance, using the default leap-second reference.
Parameters:
tsiMode The IntegerMode mode used.
tsfMode The FractionalMode mode used.
tsi The IntegerMode value.
tsf The FractionalMode value.
sr The sampling rate.
Exceptions:
VRTException if tsi is less than 0 or greater than 0xFFFFFFFF; or if tsi is null and tsiMode is not None; or if tsf is null and tsfMode is not None; or if the fractional time stamp mode is RealTime and the value (in picoseconds) is greater than or equal to one second.
vrt::TimeStamp::TimeStamp (IntegerMode tsiMode, FractionalMode tsfMode, uint32_t tsi, uint64_t tsf, LeapSeconds * ls, double sr = DOUBLE_NAN)
Creates a new instance.
Parameters:
tsiMode The IntegerMode mode used.
tsfMode The FractionalMode mode used.
tsi The IntegerMode value.
tsf The FractionalMode value.
ls The leap-seconds reference to use.
sr The sampling rate.
Exceptions:
VRTException if tsi is less than 0 or greater than 0xFFFFFFFFL; or if tsi is null and tsiMode is not None; or if tsf is null and tsfMode is not None; or if the fractional time stamp mode is RealTime and the value (in picoseconds) is greater than or equal to one second.
Member Function Documentation
TimeStamp vrt::TimeStamp::addPicoSeconds (int64_t ps) const [inline]
Adds the specified number of picoseconds to the current time and returns the resulting time.
This is identical to addTime(0L,ps).
Parameters:
ps The number of picoseconds.
Returns:
A new time object representing the resulting time.
Exceptions:
VRTException If the getIntegerMode() is not IntegerMode_UTC or IntegerMode_GPS or if getFractionalMode() is not FractionalMode_RealTime.
References addTime(), and ONE_SEC.
Referenced by addSamples(), and vrt::BasicContextPacket::getAdjustedTimeStamp().
TimeStamp vrt::TimeStamp::addSamples (int64_t samples, double _sr) const [inline]
Adds the specified number of picoseconds to the current time and returns the resulting time.
This is identical to addTime(0L,ps).
Parameters:
samples The number of samples.
_sr The sample rate.
Returns:
A new time object representing the resulting time.
Exceptions:
VRTException If the getIntegerMode() is not IntegerMode_UTC or IntegerMode_GPS or if getFractionalMode() is not FractionalMode_RealTime or FractionalMode_SampleCount.
References addPicoSeconds(), addTime(), and ONE_SEC.
TimeStamp vrt::TimeStamp::addSeconds (int64_t sec) const [inline]
Adds the specified number of seconds to the current time and returns the resulting time.
This is identical to addTime(sec,0L) except that it will not throw an exception if getFractionalMode() is not FractionalMode_RealTime.
Parameters:
sec The number of seconds.
Returns:
A new time object representing the resulting time.
Exceptions:
VRTException If the getIntegerMode() is not IntegerMode_UTC or IntegerMode_GPS .
References addTime().
TimeStamp vrt::TimeStamp::addTime (int64_t sec, int64_t ps) const [inline]
Adds the specified number of picoseconds to the current time and returns the resulting time.
    r = t.addTime(sec, ps)
    implies: r.getTimeStampInteger()    = t.getTimeStampInteger()    + sec
             r.getTimeStampFractional() = t.getTimeStampFractional() + ps
Note that if the value of ps exceeds ONE_SEC, the input parameters will be normalized with:
    sec = (ps / ONE_SEC) + sec;
    ps  = (ps % ONE_SEC);
Note that subtracting time can be accomplished simply by calling addTime(-sec,-ps). Both sec and ps must be signed negative to accomplish the subtraction of seconds+picoseconds.
This method maintains the functionality that the following will all of the following are equal (assuming time never exceeds 0xFFFFFFFF, not drops below the start of the epoch):
    r = t.addTime(a,b)
    r = t.addTime(a,0L).addTime(0L,b)
    r = t.addTime(0L,b).addTime(a,0L)
Parameters:
sec The number of seconds.
ps The number of picoseconds.
Returns:
A new time object representing the resulting time.
Exceptions:
VRTException If the getIntegerMode() is not IntegerMode_UTC or IntegerMode_GPS or if getFractionalMode() is not FractionalMode_RealTime.
References ONE_SEC.
Referenced by addPicoSeconds(), addSamples(), and addSeconds().
char vrt::TimeStamp::compareTo (const TimeStamp & other) const
Compares time stamp values.
If the time stamps have different epochs, this method will attempt to convert both to GPS and will throw a VRTException if unable to do so. If the fractional time stamp values have a different reference, an VRTException will be thrown. This method assumes that any "wrap-arround" within the fractional time stamp is accounted for in the integral time stamp. If two GPS/UTC times are compared, this will return 0 iff they represent exactly the same instant in time.
Returns:
<0 if this is comes before than other, =0 if this is comes at the same point as other, >0 if this is comes after than other.
Exceptions:
VRTException If the current time stamp is not GPS or UTC.
bool vrt::TimeStamp::equals (const VRTObject & ts) const
Equals method that checks for strict equality.
Two time stamps representing the same point but using different epoch (UTC vs GPS) will not be considered equal.
Parameters:
ts The object to compare to this one.
Returns:
true if exactly equal, false otherwise.
static TimeStamp vrt::TimeStamp::forNoradTime (int32_t seconds, int64_t picoseconds, int32_t year, LeapSeconds * _ls) [inline, static]
Deprecated:
use forTimeNORAD(..)
References forTimeNORAD().
static TimeStamp vrt::TimeStamp::forNoradTime (int32_t seconds, int64_t picoseconds) [inline, static]
Deprecated:
use forTimeNORAD(..)
References forTimeNORAD(), and vrt::LeapSeconds::getDefaultInstance().
static TimeStamp vrt::TimeStamp::forTime (int32_t year, int32_t mon, int32_t day, int32_t hour, int32_t min, int32_t wsec, int64_t psec, int32_t zone, IntegerMode tsiMode, LeapSeconds * ls) [static]
Converts a time specifier to a time stamp.
Parameters:
year The year (1981 to 2099).
mon The month (1 to 12).
day The day of month (1 to 31).
hour The hour of day (0 to 23).
min The minute of hour (0 to 59).
wsec The whole seconds (0 to 60).
psec Any picoseconds.
zone The time-zone delta in seconds.
tsiMode The time epoch (must be IntegerMode_GPS or IntegerMode_UTC).
ls The leap seconds instance to use.
Returns:
The time stamp.
static TimeStamp vrt::TimeStamp::forTime (int32_t year, int32_t mon, int32_t day, int32_t hour, int32_t min, int32_t wsec, int64_t psec, int32_t zone, IntegerMode _tsiMode) [inline, static]
Converts a time specifier to a time stamp.
Parameters:
year The year (1981 to 2099).
mon The month (1 to 12).
day The day of month (1 to 31).
hour The hour of day (0 to 23).
min The minute of hour (0 to 59).
wsec The whole seconds (0 to 60).
psec Any picoseconds.
zone The time-zone delta in seconds.
_tsiMode The time epoch (must be IntegerMode_GPS or IntegerMode_UTC).
Returns:
The time stamp.
References vrt::LeapSeconds::getDefaultInstance().
static TimeStamp vrt::TimeStamp::forTimeIRIG (int32_t seconds, int32_t minutes, int32_t hours, int32_t days, int32_t hundreths, LeapSeconds * ls) [static]
Creates a time stamp from an IRIG time.
This function implicitly knows that IRIG time does not indicate if any mid-year leap-seconds that have occurred nor does it count them (except in rare situations that the IRIG time stamp is seen as a leap-second is being added [i.e. 23:59:60], in which case this function returns forTimeIRIG(59,59,23,days,hundreths,ls).addSeconds(1)); as such, it always consults the applicable leap-seconds table to check for scheduled mid-year leap-seconds.
Parameters:
seconds The number of whole seconds since the start of the minute (0 to 59[+1]).
minutes The number of whole minutes since the start of the hour (0 to 59).
hours The number of whole hours since the start of the day (0 to 23).
days The number of whole days since the start of the year (0 to 365[+1]) where 1=Jan1, 2=Jan2, ..., 32=Feb1, ...).
hundreths The number of whole 1/100 seconds since the start of the current second (0 to 99).
ls The leap seconds instance to use.
Returns:
The corresponding TimeStamp.
Exceptions:
IllegalArgumentException If an invalid parameter is specified.
static TimeStamp vrt::TimeStamp::forTimeIRIG (int32_t seconds, int32_t minutes, int32_t hours, int32_t days, int32_t hundreths) [inline, static]
Creates a time stamp from an IRIG time.
This is the same as forTimeIRIG(seconds,minutes,hours,days,hundreths,LeapSeconds::getDefaultInstance())
Parameters:
seconds The number of whole seconds since the start of the minute (0 to 59[+1]).
minutes The number of whole minutes since the start of the hour (0 to 59).
hours The number of whole hours since the start of the day (0 to 23).
days The number of whole days since the start of the year (0 to 365[+1]) where 1=Jan1, 2=Jan2, ..., 32=Feb1, ...).
hundreths The number of whole 1/100 seconds since the start of the current second (0 to 99).
Returns:
The corresponding TimeStamp.
Exceptions:
IllegalArgumentException If an invalid parameter is specified.
References forTimeIRIG(), and vrt::LeapSeconds::getDefaultInstance().
static TimeStamp vrt::TimeStamp::forTimeIRIG (int32_t seconds, int32_t minutes, int32_t hours, int32_t days, LeapSeconds * _ls) [inline, static]
Creates a time stamp from an IRIG time.
This is the same as forTimeIRIG(seconds,minutes,hours,days,0,ls)
Parameters:
seconds The number of whole seconds since the start of the minute (0 to 59[+1]).
minutes The number of whole minutes since the start of the hour (0 to 59).
hours The number of whole hours since the start of the day (0 to 23).
days The number of whole days since the start of the year (0 to 365[+1]) where 1=Jan1, 2=Jan2, ..., 32=Feb1, ...).
_ls The leap seconds instance to use (null to use default).
Returns:
The corresponding TimeStamp.
Exceptions:
IllegalArgumentException If an invalid parameter is specified.
References forTimeIRIG().
static TimeStamp vrt::TimeStamp::forTimeIRIG (int32_t seconds, int32_t minutes, int32_t hours, int32_t days) [inline, static]
Creates a time stamp from an IRIG time.
This is the same as forTimeIRIG(seconds,minutes,hours,days,0,LeapSeconds::getDefaultInstance())
Parameters:
seconds The number of whole seconds since the start of the minute (0 to 59[+1]).
minutes The number of whole minutes since the start of the hour (0 to 59).
hours The number of whole hours since the start of the day (0 to 23).
days The number of whole days since the start of the year (0 to 365[+1]) where 1=Jan1, 2=Jan2, ..., 32=Feb1, ...).
Returns:
The corresponding TimeStamp.
Exceptions:
IllegalArgumentException If an invalid parameter is specified.
References vrt::LeapSeconds::getDefaultInstance().
Referenced by forTimeIRIG().
static TimeStamp vrt::TimeStamp::forTimeMidas (double seconds, double fractionalSeconds, LeapSeconds * _ls) [inline, static]
Creates a time stamp from a Midas time.
This is identical to:
    forTimePOSIX(seconds - MIDAS2POSIX, ONE_SEC * fractionalSeconds, ls)
WARNING: seconds must be an integral value and fractionalSeconds must be a value on the range [0,1). Failure to follow this will result in undefined behavior.
Parameters:
seconds The number of whole seconds since the Midas epoch.
fractionalSeconds The fractional seconds since the start of the current second.
_ls The leap seconds instance to use (null to use default).
Returns:
The corresponding TimeStamp.
Exceptions:
VRTException if the time corresponds to a value prior to 1972/01/01.
References forTimePOSIX(), MIDAS2POSIX, and ONE_SEC.
static TimeStamp vrt::TimeStamp::forTimeMidas (double seconds, double fractionalSeconds) [inline, static]
Creates a time stamp from a Midas time.
This is identical to:
    forTimePOSIX(seconds - MIDAS2POSIX, ONE_SEC * fractionalSeconds)
WARNING: seconds must be an integral value and fractionalSeconds must be a value on the range [0,1). Failure to follow this will result in undefined behavior.
Parameters:
seconds The number of whole seconds since the Midas epoch.
fractionalSeconds The fractional seconds since the start of the current second.
Returns:
The corresponding TimeStamp.
Exceptions:
VRTException if the time corresponds to a value prior to 1972/01/01.
References forTimePOSIX(), MIDAS2POSIX, and ONE_SEC.
static TimeStamp vrt::TimeStamp::forTimeNORAD (int32_t seconds, int64_t picoseconds, boolNull leapCounted, int32_t year, LeapSeconds * _ls) [inline, static]
Creates a time stamp from a NORAD time.
The NORAD time epoch is measured in number of 1-second intervals elapsed since the start of the current UTC year; however, there is some ambiguity as to whether a mid-year leap second is counted or not counted. At the time this function was written (2011), it had been 14+ years since the last mid-year leap second, so there is little reason to believe that past experience in this regard is a good indicator of future behavior.
Automatic Year Setting: When converting NORAD time to UTC, the number of UTC seconds at the start of the current year is added in. If the year is not given (i.e. -1), the current year is used. However, if a late-December time is seen in early-January, the previous year is used. Similarly if an early-January time is seen in late-December, the subsequent year is used. This is done to account for cases where data that is time-stamped at the end of one year does not get processed until the beginning of the next year.
Parameters:
seconds The number of whole seconds since the start of the year.
picoseconds The number of picoseconds since the start of the current second.
leapCounted Were any mid-year leap seconds counted (true) or skipped (false)? If this is _NULL, the value of VRTConfig::getNoradLeapSecCounted() is used.
year The year to use (-1 for automatic, otherwise after 1972).
_ls The leap seconds instance to use.
Returns:
The corresponding TimeStamp.
References vrt::VRTConfig::getNoradLeapSecCounted().
static TimeStamp vrt::TimeStamp::forTimeNORAD (int32_t seconds, int64_t picoseconds, int32_t year, LeapSeconds * _ls) [inline, static]
Creates a time stamp from a NORAD time.
The NORAD time epoch is measured in number of 1-second intervals elapsed since the start of the current UTC year; however, there is some ambiguity as to whether a mid-year leap second is counted or not counted. This is the same as forTimeNORAD(seconds, picoseconds, _NULL, year, ls)
Parameters:
seconds The number of whole seconds since the start of the year.
picoseconds The number of picoseconds since the start of the current second.
year The year to use (-1 for automatic, otherwise after 1972).
_ls The leap seconds instance to use.
Returns:
The corresponding TimeStamp.
References forTimeNORAD().
static TimeStamp vrt::TimeStamp::forTimeNORAD (int32_t seconds, int64_t picoseconds, boolNull leapCounted = _NULL) [inline, static]
Creates a time stamp from a NORAD time.
The NORAD time epoch is measured in number of 1-second intervals elapsed since the start of the current UTC year; however, there is some ambiguity as to whether a mid-year leap second is counted or not counted. This is the same as forTimeNORAD(seconds, picoseconds, -1, null)
Parameters:
seconds The number of whole seconds since the start of the year.
picoseconds The number of picoseconds since the start of the current second.
leapCounted Were any mid-year leap seconds counted (true) or skipped (false)? If this is _NULL, the value of VRTConfig::getNoradLeapSecCounted() is used.
Returns:
The corresponding TimeStamp.
References vrt::LeapSeconds::getDefaultInstance().
Referenced by forNoradTime(), and forTimeNORAD().
static TimeStamp vrt::TimeStamp::forTimePOSIX (int64_t seconds, int64_t picoseconds, LeapSeconds * ls) [static]
Creates a time stamp from a POSIX time.
See lengthy discussion at top of this class for details regarding POSIX to UTC conversions.
Parameters:
seconds The number of whole seconds since the POSIX epoch.
picoseconds The number of picoseconds since the start of the current second.
ls The leap seconds instance to use (null to use default).
Returns:
The corresponding TimeStamp.
Exceptions:
VRTException if the time corresponds to a value prior to 1972/01/01.
static TimeStamp vrt::TimeStamp::forTimePOSIX (int64_t seconds, int64_t picoseconds) [inline, static]
Creates a time stamp from a POSIX time.
See lengthy discussion at top of this class for details regarding POSIX to UTC conversions.
Parameters:
seconds The number of whole seconds since the POSIX epoch.
picoseconds The number of picoseconds since the start of the current second.
Returns:
The corresponding TimeStamp.
Exceptions:
VRTException if the time corresponds to a value prior to 1972/01/01.
References vrt::LeapSeconds::getDefaultInstance().
Referenced by forTimeMidas().
static TimeStamp vrt::TimeStamp::forTimePTP (int64_t seconds, int64_t nanoseconds, LeapSeconds * _ls) [inline, static]
Creates a GPS time stamp from a PTP time.
This only supports times after 6 Jan 1980 since there is a simple conversion from PTP to GPS time. It is possible to convert from PTP to UTC for dates between 1 Jan 1972 (not 1 Jan 1970) and 6 Jan 1980, but it would add significant complication to what is otherwise a trivial function that the compiler can easily in-line.
Parameters:
seconds The number of whole seconds since the PTP epoch.
nanoseconds The number of nanoseconds since the start of the current second.
_ls The leap seconds instance to use.
Returns:
The corresponding TimeStamp.
Exceptions:
VRTException if the time corresponds to a value prior to 1980/01/06.
References GPS2PTP, and TimeStamp().
static TimeStamp vrt::TimeStamp::forTimePTP (int64_t seconds, int64_t nanoseconds) [inline, static]
Creates a GPS time stamp from a PTP time.
This only supports times after 6 Jan 1980 since there is a simple conversion from PTP to GPS time. It is possible to convert from PTP to UTC for dates between 1 Jan 1972 (not 1 Jan 1970) and 6 Jan 1980, but it would add significant complication to what is otherwise a trivial function that the compiler can easily in-line.
Parameters:
seconds The number of whole seconds since the PTP epoch.
nanoseconds The number of nanoseconds since the start of the current second.
Returns:
The corresponding TimeStamp.
Exceptions:
VRTException if the time corresponds to a value prior to 1980/01/06.
References vrt::LeapSeconds::getDefaultInstance().
double vrt::TimeStamp::getDoubleSeconds (double sr) const
Gets the floating point time stamp in UTC seconds (if GPS it converts to UTC first) given a sampling rate.
including fractional seconds.
Parameters:
sr the sampling rate
Returns:
The floating point time stamp. This will be a double-precision floating point number.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getUTCSeconds()
double vrt::TimeStamp::getDoubleSeconds () const
Gets the floating point time stamp in UTC seconds (if GPS it converts to UTC first).
including fractional seconds.
Returns:
The floating point time stamp. This will be a double-precision floating point number.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getUTCSeconds()
IntegerMode vrt::TimeStamp::getEpoch () const
Gets the epoch used.
Returns:
GPS_EPOCH or UTC_EPOCH or NULL_EPOCH if neither apply. This will return NULL_EPOCH any time FractionalMode_SampleCount or FractionalMode_FreeRunningCount is in use.
See also:
getIntegerMode()
getFractionalMode()
virtual Value* vrt::TimeStamp::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::HasFields.
virtual int32_t vrt::TimeStamp::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::HasFields.
virtual string vrt::TimeStamp::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::HasFields.
virtual ValueType vrt::TimeStamp::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::HasFields.
FractionalMode vrt::TimeStamp::getFractionalMode () const [inline]
Gets the time stamp mode used for fractional seconds.
See also:
getTimeStampFractional()
Referenced by getMidasTime().
double vrt::TimeStamp::getFractionalSeconds () const [inline]
Gets the fractional time stamp as a fraction of a second.
This is identical to the following (done in double-precision):
    getPicoSeconds() / ONE_SEC
Returns:
The fractional time stamp.
Exceptions:
VRTException If the fractional time stamp is not RealTime.
References getPicoSeconds(), and ONE_SEC.
Referenced by getMidasTime().
int64_t vrt::TimeStamp::getGPSSeconds () const [inline]
Gets the integer time stamp in GPS seconds (if UTC it converts to GPS first).
Returns:
The integer time stamp. This will be an unsigned 32-bit value as a long.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getSecondsGPS()
References getSecondsGPS().
IntegerMode vrt::TimeStamp::getIntegerMode () const [inline]
Gets the time stamp mode used for integral seconds.
See also:
getTimeStampInteger()
LeapSeconds* vrt::TimeStamp::getLeapSecondRef () const [inline]
Gets the leap-seconds reference used.
Returns:
The leap-seconds reference used.
double vrt::TimeStamp::getMidasSeconds () const [inline]
Gets the integer time stamp in Midas seconds.
This is identical to:
     getPOSIXSeconds() + MIDAS2POSIX
Returns:
The integer time stamp.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getSecondsPOSIX()
References getPOSIXSeconds(), and MIDAS2POSIX.
Referenced by getMidasTime().
double vrt::TimeStamp::getMidasTime () const [inline]
Gets the integer and fractional time stamp in Midas seconds.
This is identical to:
     getMidasSeconds() + getFractionalSeconds()    // using RealTime
    or
     getMidasSeconds()                             // not using RealTime
WARNING: This will result in a loss of precision! Users are advised to use getMidasSeconds and getFractionalSeconds to avoid this loss of precision.
Returns:
The integer and fractional time stamp with some loss of precision.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getSecondsPOSIX()
References getFractionalMode(), getFractionalSeconds(), and getMidasSeconds().
int64_t vrt::TimeStamp::getNORADSeconds (boolNull leapCounted = _NULL) const [inline]
Gets the integer time stamp in NORAD seconds (if GPS it converts to UTC first then from UTC to NORAD).
Parameters:
leapCounted Were any mid-year leap seconds counted (true) or skipped (false)? If this is _NULL, the value of VRTConfig::getNoradLeapSecCounted() is used.
Returns:
The integer time stamp. This will be an unsigned 32-bit value as a long.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getSecondsNORAD()
References vrt::VRTConfig::getNoradLeapSecCounted().
Referenced by getSecondsNORAD().
uint64_t vrt::TimeStamp::getPicoSeconds () const
Gets the fractional time stamp in picoseconds.
Returns:
The fractional time stamp.
Exceptions:
VRTException If the fractional time stamp is not RealTime.
Referenced by getFractionalSeconds().
uint64_t vrt::TimeStamp::getPicoSeconds (double sr) const
Gets the fractional time stamp in picoseconds.
Parameters:
sr The sample rate (only applicable for tsf of FractionalMode_SampleCount)
Returns:
The fractional time stamp.
Exceptions:
VRTException If the fractional time stamp is not RealTime.
Referenced by vrt::VRTMath::packTimeStamp().
int64_t vrt::TimeStamp::getPOSIXSeconds () const
Gets the integer time stamp in POSIX seconds (if GPS it converts to UTC first then from UTC to POSIX).
Returns:
The integer time stamp. This will be an unsigned 32-bit value as a long.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getSecondsPOSIX()
Referenced by getMidasSeconds(), and getSecondsPOSIX().
uint64_t vrt::TimeStamp::getSampleCount () const
Gets the fractional time stamp in samples.
Returns:
The fractional time stamp.
Exceptions:
VRTException If the fractional time stamp is not SampleCount
double vrt::TimeStamp::getSampleRate () const
Gets the sample rate.
Returns:
the sample rate.
uint32_t vrt::TimeStamp::getSecondsGPS () const
Gets the integer time stamp in GPS seconds (if UTC it converts to GPS first).
Returns:
The integer time stamp. This will be an unsigned 32-bit value as an int.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getGPSSeconds()
Referenced by getGPSSeconds(), and vrt::VRTMath::packTimeStamp().
uint32_t vrt::TimeStamp::getSecondsNORAD (boolNull leapCounted = _NULL) const [inline]
Gets the integer time stamp in NORAD seconds (if GPS it converts to UTC first then from UTC to NORAD).
Parameters:
leapCounted Were any mid-year leap seconds counted (true) or skipped (false)? If this is _NULL, the value of VRTConfig::getNoradLeapSecCounted() is used.
Returns:
The integer time stamp. This will be an unsigned 32-bit value as an int.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getNORADSeconds()
References getNORADSeconds().
uint32_t vrt::TimeStamp::getSecondsPOSIX () const [inline]
Gets the integer time stamp in POSIX seconds (if GPS it converts to UTC first then from UTC to POSIX).
Returns:
The integer time stamp. This will be an unsigned 32-bit value as an int.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getPOSIXSeconds()
References getPOSIXSeconds().
uint32_t vrt::TimeStamp::getSecondsUTC () const
Gets the integer time stamp in UTC seconds (if GPS it converts to UTC first).
Returns:
The integer time stamp. This will be an unsigned 32-bit value as an int.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getUTCSeconds()
Referenced by getUTCSeconds(), and vrt::VRTMath::packTimeStamp().
static TimeStamp vrt::TimeStamp::getSystemTime (LeapSeconds * ls) [static]
Gets a time stamp using system time.
This time should be considered unreliable as it is using gettimeofday(..) as its data source rather than a precision time reference. The resolution of this time stamp is only as good as that provided by the O/S, and will never be better than 1 micorsecond.
Parameters:
ls The leap-seconds reference to use.
static TimeStamp vrt::TimeStamp::getSystemTime () [inline, static]
Gets a time stamp using system time.
This time should be considered unreliable as it is using gettimeofday(..) as its data source rather than a precision time reference. The resolution of this time stamp is only as good as that provided by the O/S, and will never be better than 1 micorsecond.
References vrt::LeapSeconds::getDefaultInstance().
uint64_t vrt::TimeStamp::getTimeStampFractional () const [inline]
Gets the fractional time stamp.
Be sure to consult getFractionalMode() to find out the type of time stamp used.
Returns:
The fractional time stamp (returns 0 for FractionalMode_None).
uint32_t vrt::TimeStamp::getTimeStampInteger () const [inline]
Gets the integer time stamp.
Be sure to consult getIntegerMode() to find out the type of time stamp used.
Returns:
The integer time stamp (returns 0 for IntegerMode_None). This will be an unsigned 32-bit value.
int64_t vrt::TimeStamp::getUTCSeconds () const [inline]
Gets the integer time stamp in UTC seconds (if GPS it converts to UTC first).
Returns:
The integer time stamp. This will be an unsigned 32-bit value as a long.
Exceptions:
VRTException If the time stamp is not GPS or UTC.
See also:
getSecondsUTC()
References getSecondsUTC().
virtual bool vrt::TimeStamp::isNullValue () const [inline, virtual]
A record is considered null both the integer and fractional modes are set to None.
Reimplemented from vrt::VRTObject.
static TimeStamp vrt::TimeStamp::parseTime (string time, IntegerMode tsiMode, LeapSeconds * ls) [static]
Parses a time stamp in one of the following ISO 8601 formats.
    yyyy-mm-ddThh:mm:ss.sss        (TimeZone = +0 hours)
    yyyy-mm-ddThh:mm:ss.sssZ       (TimeZone = +0 hours)
    yyyy-mm-ddThh:mm:ss.sss+zz     (TimeZone = +zz hours)
    yyyy-mm-ddThh:mm:ss.sss-zz     (TimeZone = -zz hours)
    yyyy-mm-ddThh:mm:ss.sss+zz:zz  (TimeZone = +zz:zz hours)
    yyyy-mm-ddThh:mm:ss.sss-zz:zz  (TimeZone = -zz:zz hours)
Parameters:
time The time string.
tsiMode The time epoch (must be IntegerMode_GPS or IntegerMode_UTC).
ls The leap seconds instance to use.
Returns:
The parsed time stamp.
static TimeStamp vrt::TimeStamp::parseTime (string time, IntegerMode _tsiMode) [inline, static]
Parses a time stamp in one of the ISO 8601 formats documented in parseTime(time, tsiMode, ls).
Parameters:
time The time string.
_tsiMode The time epoch (must be IntegerMode_GPS or IntegerMode_UTC).
Returns:
The parsed time stamp.
References vrt::LeapSeconds::getDefaultInstance().
virtual void vrt::TimeStamp::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::HasFields.
TimeStamp vrt::TimeStamp::toGPS () const
Converts from UTC or GPS time to GPS.
This operation does nothing to the fractional time seconds, and is only valid for dates after 1-Jan-1980.
Returns:
this if already in GPS, otherwise a new TimeStamp in UTC time representing the same time.
Exceptions:
VRTException If the current time stamp is not GPS or UTC.
string vrt::TimeStamp::toString () const [virtual]
A textural representation of the time stamp.
If the integer mode is IntegerMode_GPS or IntegerMode_UTC and fractional mode is FractionalMode_None or FractionalMode_RealTime (i.e. the 90% use case) the output will be an RFC3339-compatible time stamp with 0 (no fractional time stamp) or 12 (picoseconds) decimal places followed by either " (GPS)" or " (UTC)". Other time stamps will use a custom format.
References:
    Klyne, G. and C. Newman. "RFC3339 - Date and Time on the Internet: Timestamps."
    Network Working Group. July 2002. http://www.faqs.org/rfcs/rfc3339.html
    (accessed 2009-07-31).
Returns:
A textural representation of the time stamp, or null if both IntegerMode and FractionalMode are None.
Reimplemented from vrt::VRTObject.
string vrt::TimeStamp::toStringGPS () const
A textural representation of the time stamp in UTC.
This is identical to the time stamp produced by ts.toGPS().toString() except that the " (GPS)" suffix is omitted.
Returns:
A textural representation of the time stamp, or null if both IntegerMode and FractionalMode are None.
string vrt::TimeStamp::toStringUTC () const
A textural representation of the time stamp in UTC.
This is identical to the time stamp produced by ts.toUTC().toString() except that the " (UTC)" suffix is omitted.
Returns:
A textural representation of the time stamp, or null if both IntegerMode and FractionalMode are None.
string vrt::TimeStamp::toStringUTC (string format) const
Internal Use Only (Experimental)
TimeStamp vrt::TimeStamp::toUTC () const
Converts from UTC or GPS time to UTC.
This operation does nothing to the fractional time seconds, and is only valid for dates after 1-Jan-1980.
Returns:
this if already in UTC, otherwise a new TimeStamp in GPS time representing the same time.
Exceptions:
VRTException If the current time stamp is not GPS or UTC.
Member Data Documentation
const int32_t vrt::TimeStamp::GPS2PTP [static]
Delta between GPS and PTP epochs.
    GPS2PTP = 315,964,819 seconds
Referenced by forTimePTP().
const int32_t vrt::TimeStamp::GPS2UTC [static]
Delta between GPS and UTC epochs.
    GPS2UTC = (days 1 Jan 1970 to 6 Jan 1980) * (86,400 sec/day) + (leap seconds)
    GPS2UTC = (3,657 days) * (86,400 sec/day) + (11 seconds)
    GPS2UTC = 315,964,811 seconds
See top of class for a detailed discussion regarding number of leap seconds added between 1 Jan 1970 and 6 Jan 1980.
const IntegerMode vrt::TimeStamp::GPS_EPOCH [static]
The GPS epoch.
const double vrt::TimeStamp::HALF_PICOSECOND [static]
The value of 1/2 picosecond in seconds.
    HALF_PICOSECOND = 0.500e-12 seconds
const int32_t vrt::TimeStamp::MIDAS2POSIX [static]
Delta between Midas and POSIX epochs.
    MIDAS2POSIX = (days 1 Jan 1950 to 1 Jan 1970) * (86,400 sec/day)
    MIDAS2POSIX = 631,152,000 seconds
Referenced by forTimeMidas(), and getMidasSeconds().
const TimeStamp vrt::TimeStamp::NO_TIME_STAMP [static]
An empty time stamp.
This is equal to:
    NO_TIME_STAMP = TimeStamp(IntegerMode.None, FractionalMode.None, null, null)
const IntegerMode vrt::TimeStamp::NULL_EPOCH [static]
The "null" epoch.
const double vrt::TimeStamp::ONE_PICOSECOND [static]
The value of 1 picosecond in seconds.
    ONE_PICOSECOND = (1.0 / ONE_SEC) = 1e-12 seconds
Note that this is explicitly defined as 1e-12 rather than the division shown above to avoid rounding errors that may otherwise be introduced.
const int64_t vrt::TimeStamp::ONE_SEC [static]
The value of 1 second in picoseconds.
    ONE_SEC = 1000000000000 picoseconds
Referenced by addPicoSeconds(), addSamples(), addTime(), forTimeMidas(), and getFractionalSeconds().
const uint64_t vrt::TimeStamp::ONE_SECOND [static]
The value of 1 second in picoseconds (unsigned variant).
    ONE_SECOND = 1000000000000 picoseconds
const IntegerMode vrt::TimeStamp::UTC_EPOCH [static]
The UTC epoch.
const TimeStamp vrt::TimeStamp::Y2K_GPS [static]
This is equal to the start of the year 2000 in the GPS epoch and provides a reasonable minimum bounds for most time values.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/TimeStamp.h