VRT: vrt::AbstractVRAFile Class Reference
vrt::AbstractVRAFile Class Reference
Defines a VRA file type.
#include <AbstractVRAFile.h>
Public Member Functions
AbstractVRAFile (const AbstractVRAFile &f)
Basic copy constructor for the class.
~AbstractVRAFile ()
Basic destructor for the class.
virtual void append (BasicVRTPacket &p)
Optional functionality: Appends a VRTPacket to the end of the file.
virtual ConstPacketIterator begin () const
Gets an iterator over the packets in the container.
virtual void close ()
Closes this file and releases any system resources associated with it.
virtual ConstPacketIterator end () const
Gets an iterator pointing to one position past the end of the packets in the container.
virtual bool equals (const AbstractVRAFile &f) const
Checks for equality with another file.
virtual bool equals (const VRTObject &o) const
Checks for equality with an unknown object.
void flush ()
Flushes this file by writing any buffered output to the underlying stream.
virtual int64_t getFileLength () const
Gets the total length of the file in bytes including the header and trailer.
void * getHeaderPointer ()
Internal Use Only: Gets a copy of the VRA header.
virtual BasicVRTPacket * getThisPacket (ConstPacketIterator &pi, bool skip) const
Internal Use Only: Called by the iterator to get the next packet beginning at the specified offset.
string getURI () const
Gets the URI for the file.
int32_t getVersion () const
Gets the file version.
virtual void gotoNextPacket (ConstPacketIterator &pi) const
Internal Use Only: Called by the iterator to determine if there is a next packet that begins at the specified offset.
bool isCRCValid () const
Checks to see if the CRC for the frame is valid.
virtual bool isFileValid (int64_t length) const
Checks to see if the file is valid.
virtual bool isFileValid () const
Checks to see if the file is valid.
void setVersion (int32_t version)
Optional functionality: Sets the file version.
virtual string toString () const
Gets a free-form description of the file.
virtual void updateCRC ()
This will compute the CRC value for the file and set it in the CRC field.
virtual void updateFileLength ()
This will compute the length of the file and set it in the FileLength field.
Static Public Attributes
static const int8_t DEFAULT_VERSION = 1
The default file version used for a new output file.
static const string FILE_NAME_EXT
The file name extension for a VRA file.
static const int32_t HEADER_LENGTH = 20
The length of the header in bytes.
static const int64_t MAX_FILE_LENGTH = __INT64_C(0x7FFFFFFFFFFFFFFF)
The maximum length of the file in bytes (header + payload + trailer).
static const int64_t MAX_PAYLOAD_LENGTH = MAX_FILE_LENGTH - HEADER_LENGTH - TRAILER_LENGTH
The maximum length of the payload in bytes.
static const int8_t MAX_VERSION_SUPPORTED = 1
The maximum file version supported by this version of the library.
static const string MIME_TYPE
The MIME type for a VRA file.
static const int64_t MIN_FILE_LENGTH = HEADER_LENGTH + TRAILER_LENGTH
The minimum length of the file in bytes (header + no payload).
static const int8_t MIN_VERSION_SUPPORTED = 1
The minimum file version supported by this version of the library.
static const int32_t TRAILER_LENGTH = 0
The length of the trailer in bytes.
static const int VRA_FAW = 0x56524146
This is the 32-bit FWA (frame alignment word) marking the start of a VRAF file.
static const char VRA_FAW_0 = 0x56
This is the 1st recorded byte of the 32-bit FWA (VRA_FAW).
static const char VRA_FAW_1 = 0x52
This is the 2nd recorded byte of the 32-bit FWA (VRA_FAW).
static const char VRA_FAW_2 = 0x41
This is the 3rd recorded byte of the 32-bit FWA (VRA_FAW).
static const char VRA_FAW_3 = 0x46
This is the 4th recorded byte of the 32-bit FWA (VRA_FAW).
Protected Member Functions
AbstractVRAFile (string _uri, bool _isRead, bool _isWrite, bool _isSetSize, bool _isSetCRC, bool _isStrict)
Internal Use Only: Creates a new instance, but does not open it yet.
virtual void flush (bool force)
Flush the content to the disk.
int64_t getFileLengthHeader () const
Gets the file length from the header (0 if unspecified).
virtual int64_t getFileLengthOS () const =0
Gets the file length from the O/S or -1 if unknown.
virtual int64_t getFileLengthRW () const =0
Gets the read/write length.
virtual void open ()
Opens the file.
virtual int32_t read (int64_t off, void *ptr, int32_t len) const =0
Reads from the file.
virtual void readHeader ()
Reads the header in.
void setCRC (int32_t crc)
Sets the CRC in the header.
void setFileLengthHeader (int64_t len)
Sets the file length in the header (0 if unspecified).
virtual void write (int64_t off, void *ptr, int32_t len, bool flush)=0
Writes to the file.
void write (int64_t off, void *ptr, int32_t len)
Writes to the file.
virtual void writeHeader ()
Write the header to disk.
Protected Attributes
bool isRead
bool isSetCRC
bool isSetSize
bool isStrict
bool isWrite
string uri
Detailed Description
Defines a VRA file type.
The most frequently used implementations of interface this is BasicVRAFile. Most implementations that extend this class will only need to override the following methods:
    close
    flush
    getFileLengthOS
    getFileLengthRW
    open
    read
    write
Constructor & Destructor Documentation
vrt::AbstractVRAFile::~AbstractVRAFile () [inline]
Basic destructor for the class.
vrt::AbstractVRAFile::AbstractVRAFile (const AbstractVRAFile & f)
Basic copy constructor for the class.
vrt::AbstractVRAFile::AbstractVRAFile (string _uri, bool _isRead, bool _isWrite, bool _isSetSize, bool _isSetCRC, bool _isStrict) [protected]
Internal Use Only: Creates a new instance, but does not open it yet.
Subclasses must call open() as part of the constructor.
Parameters:
_uri The URI for the file (null if n/a).
_isRead Is the file being opened for reading?
_isWrite Is the file being opened for writing?
_isSetSize Should the size be set on write? (ignored if read-only)
_isSetCRC Should the CRC be set on write? (ignored if read-only)
_isStrict Should strict packet checks be used on write?
Member Function Documentation
virtual void vrt::AbstractVRAFile::append (BasicVRTPacket & p) [virtual]
Optional functionality: Appends a VRTPacket to the end of the file.
Parameters:
p The packet to append.
Exceptions:
UnsupportedOperationException If this method is not supported
virtual ConstPacketIterator vrt::AbstractVRAFile::begin () const [virtual]
Gets an iterator over the packets in the container.
This is intended to be used similar to the following:
    for (ConstPacketIterator pi = x.begin(); pi != x.end(); ++pi) {
      std::cout << "packet = " << (*pi) << std::endl;
    }
Implements vrt::PacketContainer.
virtual void vrt::AbstractVRAFile::close () [virtual]
Closes this file and releases any system resources associated with it.
If the file is already closed then invoking this method has no effect.
Reimplemented in vrt::BasicVRAFile.
virtual ConstPacketIterator vrt::AbstractVRAFile::end () const [virtual]
Gets an iterator pointing to one position past the end of the packets in the container.
See begin for a usage example.
Implements vrt::PacketContainer.
virtual bool vrt::AbstractVRAFile::equals (const AbstractVRAFile & f) const [virtual]
Checks for equality with another file.
Reimplemented from vrt::VRTObject.
virtual bool vrt::AbstractVRAFile::equals (const VRTObject & o) const [inline, virtual]
Checks for equality with an unknown object.
Two VRA files are considered equal if they have the same values for getVersion() and getFileLength() and the packets contained in their payloads are identical. The actual implementation classes are not considered relevant for checking equality.
Note that this specifically permits different values in the FileLength field (and consequently CRC header field) since setting it to 0 (in the header) and using the file length as reported by the O/S is not considered a significant difference in the file content.
Parameters:
o The unknown object (can be null).
Returns:
true if they are identical, false otherwise. (This will always returns false if the object is null.)
virtual void vrt::AbstractVRAFile::flush (bool force) [protected, virtual]
Flush the content to the disk.
Overriding classes should call super.flush(true) if they wish to make sure that the FileLength and CRC get updated.
Parameters:
force Force contents to be flushed, otherwise skip for now.
Reimplemented in vrt::BasicVRAFile.
void vrt::AbstractVRAFile::flush () [inline]
Flushes this file by writing any buffered output to the underlying stream.
If no "flushing" is required (e.g. for a read-only file), invoking this method has no effect.
virtual int64_t vrt::AbstractVRAFile::getFileLength () const [virtual]
Gets the total length of the file in bytes including the header and trailer.
Returns:
The total length of the file in bytes or -1 if unknown.
int64_t vrt::AbstractVRAFile::getFileLengthHeader () const [inline, protected]
Gets the file length from the header (0 if unspecified).
virtual int64_t vrt::AbstractVRAFile::getFileLengthOS () const [protected, pure virtual]
Gets the file length from the O/S or -1 if unknown.
Implemented in vrt::BasicVRAFile.
virtual int64_t vrt::AbstractVRAFile::getFileLengthRW () const [protected, pure virtual]
Gets the read/write length.
This is the index of the last octet that has been read from or written to the file. This may either be the maximum value of the read/write pointer *OR* the size of the file if such is known prior to reading/writing.
Implemented in vrt::BasicVRAFile.
void* vrt::AbstractVRAFile::getHeaderPointer () [inline]
Internal Use Only: Gets a copy of the VRA header.
This is intended for use in implementing equals and has little value otherwise. The value returned must be treated as read-only, and may or may not change to reflect future changes!
Returns:
A copy of the header, this will be a pointer to a byte buffer of length HEADER_LENGTH.
virtual BasicVRTPacket* vrt::AbstractVRAFile::getThisPacket (ConstPacketIterator & pi, bool skip) const [virtual]
Internal Use Only: Called by the iterator to get the next packet beginning at the specified offset.
Parameters:
pi The packet iterator being used.
skip Skip over packet returning NULL, but update internal counters.
Returns:
The packet.
Exceptions:
NoSuchElementException If no such element exists.
Implements vrt::PacketContainer.
string vrt::AbstractVRAFile::getURI () const [inline]
Gets the URI for the file.
Returns:
The URI for the file or null if not applicable.
int32_t vrt::AbstractVRAFile::getVersion () const [inline]
Gets the file version.
virtual void vrt::AbstractVRAFile::gotoNextPacket (ConstPacketIterator & pi) const [virtual]
Internal Use Only: Called by the iterator to determine if there is a next packet that begins at the specified offset.
Parameters:
pi The packet iterator being used.
Returns:
true if there is another packet beginning at the specified offset and false otherwise.
Implements vrt::PacketContainer.
bool vrt::AbstractVRAFile::isCRCValid () const [inline]
Checks to see if the CRC for the frame is valid.
This will always return true when the CRC is set to the special BasicVRLFrame#NO_CRC value.
Returns:
true if it is valid, false otherwise.
References vrt::BasicVRLFrame::NO_CRC.
virtual bool vrt::AbstractVRAFile::isFileValid (int64_t length) const [virtual]
Checks to see if the file is valid.
This method adds an extra length check onto the basic checks performed by isFileValid(). The most common use for this method is to verify that a packet read from disk matches the length expected.
Parameters:
length Verifies that the length of the packet matches this value.
Returns:
true if it is valid, false otherwise.
virtual bool vrt::AbstractVRAFile::isFileValid () const [virtual]
Checks to see if the file is valid.
This checks the overall structure of the file and verifies the checksum (if specified). It also checks to see that the length of the file as reported in the frame header is equal to the length of the header and trailer plus the length of each packet in the trailer. For the purposes of the packet length check, only the length of a packet is considered, no consideration is made to the validity of the packet.
Returns:
true if it is valid, false otherwise.
virtual void vrt::AbstractVRAFile::open () [protected, virtual]
Opens the file.
Overriding classes should call super.open() once the file has been opened in order to ensure the header fields have been read in (if applicable) and initialized.
Reimplemented in vrt::BasicVRAFile.
virtual int32_t vrt::AbstractVRAFile::read (int64_t off, void * ptr, int32_t len) const [protected, pure virtual]
Reads from the file.
Parameters:
off File offset at which to begin reading.
ptr Pointer to the buffer to hold the data read in.
len The maximum number of octets to read.
Returns:
The number of octets actually read in.
Exceptions:
VRTException If the file is write-only.
Implemented in vrt::BasicVRAFile.
virtual void vrt::AbstractVRAFile::readHeader () [protected, virtual]
Reads the header in.
void vrt::AbstractVRAFile::setCRC (int32_t crc) [inline, protected]
Sets the CRC in the header.
Parameters:
crc The CRC or BasicVRLFrame#NO_CRC if no crc is being used.
References writeHeader().
void vrt::AbstractVRAFile::setFileLengthHeader (int64_t len) [inline, protected]
Sets the file length in the header (0 if unspecified).
Parameters:
len The new length value (in octets).
References writeHeader().
void vrt::AbstractVRAFile::setVersion (int32_t version) [inline]
Optional functionality: Sets the file version.
Parameters:
version The file version. Use DEFAULT_VERSION to indicate the default version should be used.
Exceptions:
UnsupportedOperationException If this method is not supported
IllegalArgumentException If the version number provided is invalid.
References writeHeader().
virtual string vrt::AbstractVRAFile::toString () const [virtual]
Gets a free-form description of the file.
Note that the content and structure of this string is implementation dependant and may change at any time.
Returns:
A free-form string describing the file.
Reimplemented from vrt::VRTObject.
virtual void vrt::AbstractVRAFile::updateCRC () [virtual]
This will compute the CRC value for the file and set it in the CRC field.
All successful calls to one of the set methods on this file will result in the CRC field being updated, but that usually means that the CRC was merely set to the special BasicVRLFrame#NO_CRC value.
virtual void vrt::AbstractVRAFile::updateFileLength () [virtual]
This will compute the length of the file and set it in the FileLength field.
All successful calls to one of the write methods on this file will result in the FileLength field being updated, but that usually means that the FileLength field was merely set to zero indicating that the file length should be obtained from the O/S.
virtual void vrt::AbstractVRAFile::write (int64_t off, void * ptr, int32_t len, bool flush) [protected, pure virtual]
Writes to the file.
This should call flush(doFlush) following the write.
Parameters:
off File offset at which to begin writing.
ptr Pointer to the buffer containing the data to write.
len The number of octets to write.
flush Flush to disk? Setting this to false disables header updates and flushing to disk, even if required.
Exceptions:
VRTException If the file is read-only.
Implemented in vrt::BasicVRAFile.
void vrt::AbstractVRAFile::write (int64_t off, void * ptr, int32_t len) [inline, protected]
Writes to the file.
Parameters:
off File offset at which to begin writing (EOF to write at end of file).
ptr Pointer to the buffer containing the data to write.
len The number of octets to write.
Exceptions:
VRTException If the file is read-only.
virtual void vrt::AbstractVRAFile::writeHeader () [protected, virtual]
Write the header to disk.
Referenced by setCRC(), setFileLengthHeader(), and setVersion().
Member Data Documentation
const int8_t vrt::AbstractVRAFile::DEFAULT_VERSION = 1 [static]
The default file version used for a new output file.
    DEFAULT_VERSION = 1
const string vrt::AbstractVRAFile::FILE_NAME_EXT [static]
The file name extension for a VRA file.
    FILE_NAME_EXT = ".vra"
const int32_t vrt::AbstractVRAFile::HEADER_LENGTH = 20 [static]
The length of the header in bytes.
    HEADER_LENGTH = 20
const int64_t vrt::AbstractVRAFile::MAX_FILE_LENGTH = __INT64_C(0x7FFFFFFFFFFFFFFF) [static]
The maximum length of the file in bytes (header + payload + trailer).
Note that this is NOT an absolute limit imposed by the VRA specification, but the limit imposed by the specification in situations where the FileSize field is used and/or the underlying file system doesn't provide the required file size details. In most cases, this is far in excess of what any file system can handle.
    MAX_FILE_LENGTH = 0x7FFFFFFFFFFFFFFF
See also:
getFileLength()
const int64_t vrt::AbstractVRAFile::MAX_PAYLOAD_LENGTH = MAX_FILE_LENGTH - HEADER_LENGTH - TRAILER_LENGTH [static]
The maximum length of the payload in bytes.
    MAX_PAYLOAD_LENGTH = MAX_FILE_LENGTH - HEADER_LENGTH - TRAILER_LENGTH
const int8_t vrt::AbstractVRAFile::MAX_VERSION_SUPPORTED = 1 [static]
The maximum file version supported by this version of the library.
    MAX_VERSION_SUPPORTED = 1
const string vrt::AbstractVRAFile::MIME_TYPE [static]
The MIME type for a VRA file.
    MIME_TYPE = "application/x-vita-radio-archive"
const int64_t vrt::AbstractVRAFile::MIN_FILE_LENGTH = HEADER_LENGTH + TRAILER_LENGTH [static]
The minimum length of the file in bytes (header + no payload).
Note that this is the absolute limit imposed by the VRA specification and results in a near-useless frame with no payload packets.
    MIN_FILE_LENGTH = HEADER_LENGTH + TRAILER_LENGTH
See also:
getFileLength()
const int8_t vrt::AbstractVRAFile::MIN_VERSION_SUPPORTED = 1 [static]
The minimum file version supported by this version of the library.
    MIN_VERSION_SUPPORTED = 1
const int32_t vrt::AbstractVRAFile::TRAILER_LENGTH = 0 [static]
The length of the trailer in bytes.
    TRAILER_LENGTH = 0
const int vrt::AbstractVRAFile::VRA_FAW = 0x56524146 [static]
This is the 32-bit FWA (frame alignment word) marking the start of a VRAF file.
This is also commonly known as the "magic number" for the file.
    VRA_FAW = 0x56524146 = { 'V', 'R', 'A', 'F' }
const char vrt::AbstractVRAFile::VRA_FAW_0 = 0x56 [static]
This is the 1st recorded byte of the 32-bit FWA (VRA_FAW).
const char vrt::AbstractVRAFile::VRA_FAW_1 = 0x52 [static]
This is the 2nd recorded byte of the 32-bit FWA (VRA_FAW).
const char vrt::AbstractVRAFile::VRA_FAW_2 = 0x41 [static]
This is the 3rd recorded byte of the 32-bit FWA (VRA_FAW).
const char vrt::AbstractVRAFile::VRA_FAW_3 = 0x46 [static]
This is the 4th recorded byte of the 32-bit FWA (VRA_FAW).
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/AbstractVRAFile.h