VRT: vrt::HasFields Class Reference
vrt::HasFields Class Reference
Interface indicating that an object has queriable fields.
#include <HasFields.h>
Public Member Functions
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
Value * getFieldByName (const string &name) const
Gets the value of a field, based on the field's name.
virtual int32_t getFieldCount () const
Gets the number of fields.
int32_t getFieldID (const string &name) const
Gets the ID of the given field.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
void setField (int32_t id, const Value &val)
Sets the value of a field, based on the field's id.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setFieldByName (const string &name, const Value &val)
Sets the value of a field, based on the field's name.
void setFieldByName (const string &name, const Value *val)
Sets the value of a field, based on the field's name.
Detailed Description
Interface indicating that an object has queriable fields.
This is intended for use in automated processing where the names of the fields that need to be accessed aren't known at compile-time.
WARNING: This class is not intended for "general purpose" use as a super class and should only be extended by instances of VRTObject.
Member Function Documentation
virtual Value* vrt::HasFields::getField (int32_t id) const [inline, virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::BasicVRTPacket, vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, vrt::InetAddress, vrt::PayloadFormat, vrt::Record, vrt::TimeStamp, vrt::UUID, vrt::Point, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
Value* vrt::HasFields::getFieldByName (const string & name) const
Gets the value of a field, based on the field's name.
This will accept array entries and sub-fields. Examples:
    getFieldByName("FOO")
    getFieldByName("BAR[2]")
    getFieldByName("FOO.BAZ")
    getFieldByName("BAR[2].BAZ")
    getFieldByName("FOO.BAR[2].BAZ")
When handling sub-entries (e.g. getFieldByName("FOO.BAZ")) the following decision tree is used:
       +------------------------+  no
       | Is "FOO" a valid name? |----> throw exception
       +------------------------+
                  |yes
                  V
       +------------------------+  yes
       | Is FOO a null value?   |----> return a null value
       +------------------------+
                  |no
                  V
       +------------------------+  no
       | Does FOO implement     |----> throw exception
       | HasFields?             |
       +------------------------+
                  |yes
                  V
       +------------------------+  no
       | Is "BAR" a valid name? |----> throw exception
       +------------------------+
                  |yes
                  V
       +------------------------+  yes
       | Is BAR a null value?   |----> return a null value
       +------------------------+
                  |no
                  V
        return value of FOO.BAR
Note in the above decision tree that the case of "FOO" being null results in a null value being returned which bypasses the checks for the validity of "BAZ". Indexed values (e.g. getFieldByName("BAR[2].BAZ")) are similarly handled with a null value being returned if a higher-up entry is null without checking the validity of the lower entries.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
name The name of the field (see getFieldName).
Returns:
Pointer to the given value (see getField for details). This will never be NULL but may be a pointer a value for which isNullValue() returns true -- this is intentionally done so that code in the following form will be valid:
    Value *val = x.getFieldByName(name);
    if (!isNull(val)) {
      ...
    }
    delete val;
virtual int32_t vrt::HasFields::getFieldCount () const [inline, virtual]
Gets the number of fields.
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::BasicVRTPacket, vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, vrt::InetAddress, vrt::PayloadFormat, vrt::Record, vrt::TimeStamp, vrt::UUID, vrt::Point, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
int32_t vrt::HasFields::getFieldID (const string & name) const
Gets the ID of the given field.
There is a 1:1 mapping of field ID's and names such that for all n = [0,getFieldCount()), n == getFieldID(getFieldName(n)) is true.
Parameters:
name The field name.
Returns:
The field ID (on range [0,getFieldCount())).
Exceptions:
VRTException if the field name is invalid.
virtual string vrt::HasFields::getFieldName (int32_t id) const [inline, virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::BasicVRTPacket, vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, vrt::InetAddress, vrt::PayloadFormat, vrt::Record, vrt::TimeStamp, vrt::UUID, vrt::Point, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
virtual ValueType vrt::HasFields::getFieldType (int32_t id) const [inline, virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::BasicVRTPacket, vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, vrt::InetAddress, vrt::PayloadFormat, vrt::Record, vrt::TimeStamp, vrt::UUID, vrt::Point, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
void vrt::HasFields::setField (int32_t id, const Value & val) [inline]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val The given value (must be of the applicable type).
References setField().
virtual void vrt::HasFields::setField (int32_t id, const Value * val) [inline, virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::BasicVRTPacket, vrt::AbstractGeolocation, vrt::Geolocation, vrt::Ephemeris, vrt::GeoSentences, vrt::ContextAssocLists, vrt::IndexFieldList, vrt::ArrayOfRecords, vrt::SpectrumField, vrt::InetAddress, vrt::PayloadFormat, vrt::Record, vrt::TimeStamp, vrt::UUID, vrt::Point, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
Referenced by setField().
void vrt::HasFields::setFieldByName (const string & name, const Value & val) [inline]
Sets the value of a field, based on the field's name.
This will accept array entries and sub-fields similar to getFieldByName.
Parameters:
name The name of the field (see getFieldName).
val The given value (must be of the applicable type).
References setFieldByName().
void vrt::HasFields::setFieldByName (const string & name, const Value * val)
Sets the value of a field, based on the field's name.
This will accept array entries and sub-fields similar to getFieldByName.
Parameters:
name The name of the field (see getFieldName).
val Pointer to the given value (must be of the applicable type).
Referenced by setFieldByName().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/HasFields.h