VRT: vrt::Threadable Class Reference
vrt::Threadable Class Reference
Utility class that handles common issues regarding threadable objects.
#include <Threadable.h>
Public Member Functions
Threadable (const Threadable &t)
Basic copy constructor.
Threadable ()
Basic no-argument constructor.
~Threadable ()
Basic copy constructor.
void close ()
Stops the object running.
VRTException * getAbortError () const
Get the error that caused the thread to abort.
Status getStatus () const
Gets the current status.
bool isDone () const
Is this thread done?
bool isStarted () const
Is this thread started?
void join ()
Joins the object's thread.
void run ()
Runs the processing in the current thread.
virtual void start ()
Starts the object running in a new thread.
virtual void stop (bool wait=true)
Tells the object to stop running.
Protected Member Functions
virtual void runThread ()=0
Runs the thread.
virtual void shutdown ()
Closes any connections, This will always be called at the end of a call to run().
void sleep (int64_t millis) const
Sleeps for a given duration or until stopNow() is true.
void sleepUntil (int64_t sysTime) const
Sleeps until a given system time (see Utilities#currentTimeMillis()) or until stopNow() is true.
bool stopNow () const
Should this thread stop now?
void super_restart ()
Restarts the object in a new thread.
Detailed Description
Utility class that handles common issues regarding threadable objects.
Constructor & Destructor Documentation
vrt::Threadable::Threadable ()
Basic no-argument constructor.
vrt::Threadable::Threadable (const Threadable & t)
Basic copy constructor.
vrt::Threadable::~Threadable ()
Basic copy constructor.
Member Function Documentation
void vrt::Threadable::close () [inline]
Stops the object running.
This is identical to stop(true).
References stop().
VRTException* vrt::Threadable::getAbortError () const
Get the error that caused the thread to abort.
The caller is responsible for deleting the returned object if not null.
Returns:
The error that caused run() to abort. This will return null if not done (see isDone()) and/or if it completed "normally".
Status vrt::Threadable::getStatus () const
Gets the current status.
Note that during a restart the results of calling this function will be unpredictable.
bool vrt::Threadable::isDone () const [inline]
Is this thread done?
bool vrt::Threadable::isStarted () const [inline]
Is this thread started?
void vrt::Threadable::join ()
Joins the object's thread.
void vrt::Threadable::run ()
Runs the processing in the current thread.
In general, start should be used to start processing.
virtual void vrt::Threadable::runThread () [protected, pure virtual]
Runs the thread.
Implemented in vrt::NetIO.
virtual void vrt::Threadable::shutdown () [protected, virtual]
Closes any connections, This will always be called at the end of a call to run().
Reimplemented in vrt::NetIO.
void vrt::Threadable::sleep (int64_t millis) const [protected]
Sleeps for a given duration or until stopNow() is true.
Parameters:
millis The sleep duration in ms.
void vrt::Threadable::sleepUntil (int64_t sysTime) const [protected]
Sleeps until a given system time (see Utilities#currentTimeMillis()) or until stopNow() is true.
Parameters:
sysTime The system time to wait for (in ms).
virtual void vrt::Threadable::start () [virtual]
Starts the object running in a new thread.
Exceptions:
VRTException If already running.
Reimplemented in vrt::NetIO.
Referenced by super_restart().
virtual void vrt::Threadable::stop (bool wait = true) [virtual]
Tells the object to stop running.
Parameters:
wait Wait for the thread to complete (true)?
Reimplemented in vrt::NetIO.
Referenced by close(), and super_restart().
bool vrt::Threadable::stopNow () const [inline, protected]
Should this thread stop now?
void vrt::Threadable::super_restart () [inline, protected]
Restarts the object in a new thread.
If an object supports restarts it should define the following:
    public: void restart () { super_restart(); }
References start(), and stop().
The documentation for this class was generated from the following file:
cpp_src/vrt/net/Threadable.h