VRT: vrt::IndexFieldList Class Reference
vrt::IndexFieldList Class Reference
Specifies a Index Field List.
#include <IndicatorFields.h>
Public Member Functions
IndexFieldList (const IndexFieldList &r)
Basic copy constructor.
IndexFieldList ()
Creates a new instance.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
vector< int32_t > getIndexEntries () const
Gets a copy of the Index Field List.
int32_t getIndexEntriesCount () const
Gets the number of Index Entries.
int8_t getIndexEntrySize () const
Gets the size of each Index Entry in number of Bytes.
int32_t getTotalFieldSize () const
Gets the total size of Index List Field in number of 32-bit words.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setIndexEntries (const vector< int8_t > &val)
void setIndexEntries (const vector< int16_t > &val)
void setIndexEntries (const vector< int32_t > &val)
void setIndexEntries (const vector< int32_t > &val, int8_t bpe)
Sets the Index Field List.
void setIndexEntriesCount (int32_t val)
Sets the number of Index Entries.
void setIndexEntrySize (int8_t val)
Sets the size of each Index Entry in number of Bytes.
virtual string toString () const
Gets a basic description of the object, useful for debugging.
virtual void writeBytes (const void *buffer)
Writes bytes to this record from the specified buffer.
Detailed Description
Specifies a Index Field List.
Constructor & Destructor Documentation
vrt::IndexFieldList::IndexFieldList ()
Creates a new instance.
vrt::IndexFieldList::IndexFieldList (const IndexFieldList & r)
Basic copy constructor.
Member Function Documentation
virtual Value* vrt::IndexFieldList::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::Record.
virtual int32_t vrt::IndexFieldList::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::Record.
virtual string vrt::IndexFieldList::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::Record.
virtual ValueType vrt::IndexFieldList::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::Record.
vector<int32_t> vrt::IndexFieldList::getIndexEntries () const
Gets a copy of the Index Field List.
Returns:
A copy of the Index Field list (returns an arry of length 0 if there are no entries).
int32_t vrt::IndexFieldList::getIndexEntriesCount () const [inline]
Gets the number of Index Entries.
References vrt::Record::unpackInt().
int8_t vrt::IndexFieldList::getIndexEntrySize () const [inline]
Gets the size of each Index Entry in number of Bytes.
References vrt::Record::unpackByte().
int32_t vrt::IndexFieldList::getTotalFieldSize () const [inline]
Gets the total size of Index List Field in number of 32-bit words.
References vrt::Record::unpackInt().
virtual void vrt::IndexFieldList::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::Record.
void vrt::IndexFieldList::setIndexEntries (const vector< int32_t > & val, int8_t bpe)
Sets the Index Field List.
Parameters:
val The Index Field List (an arry of length 0 if there are no entries).
bpe The number of bytes to use per element; 0 to use current setting.
void vrt::IndexFieldList::setIndexEntriesCount (int32_t val)
Sets the number of Index Entries.
void vrt::IndexFieldList::setIndexEntrySize (int8_t val)
Sets the size of each Index Entry in number of Bytes.
virtual string vrt::IndexFieldList::toString () const [virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::Record.
virtual void vrt::IndexFieldList::writeBytes (const void * buffer) [inline, virtual]
Writes bytes to this record from the specified buffer.
Parameters:
buffer The buffer to read from.
Reimplemented from vrt::Record.
References vrt::Record::setByteLength().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/IndicatorFields.h