VRT: vrt::BasicContextPacket Class Reference
vrt::BasicContextPacket Class Reference
A basic but full-featured implementation of a VRT IF Context packet.
#include <BasicContextPacket.h>
Public Member Functions
BasicContextPacket (vector< char > *buf_ptr, bool readOnly=false)
BasicContextPacket (const vector< char > &buf, bool readOnly=false)
Creates a new instance accessing the given data buffer.
BasicContextPacket (const vector< char > &buf, ssize_t start, ssize_t end, bool readOnly=false)
BasicContextPacket (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
BasicContextPacket ()
Creates a new instance that can be written to.
BasicContextPacket (const void *buf, size_t len, bool readOnly=false)
Creates a new instance accessing the given data buffer.
BasicContextPacket (const BasicVRTPacket &p, int64_t classID)
Internal constructor, for use by subclasses.
BasicContextPacket (const BasicVRTPacket &p)
Basic copy constructor.
~BasicContextPacket ()
Basic destructor.
virtual void addCIF1 (bool add=true, bool occurrence=false)
Adds or removes a CIF Sets the Enable Indicator of CIF0 and adds or removes 4-bytes for the CIF.
virtual void addCIF2 (bool add=true, bool occurrence=false)
virtual void addCIF3 (bool add=true, bool occurrence=false)
virtual void addCIF7 (bool add=true, bool occurrence=false)
virtual ArrayOfRecords get3DPointingVectorStructured (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the 3D Pointing Vector (Structured).
TimeStamp getAdjustedTimeStamp () const
Gets the adjusted time stamp of the packet.
virtual ArrayOfRecords getCIFsArray (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the CIFs Array.
ContextAssocLists getContextAssocLists (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Context Association Lists.
virtual PayloadFormat getDataPayloadFormat (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Functions that require PayloadFormat type from BasicVRTPacket.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
GeoSentences getGeoSentences (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the GPS ASCII "sentences".
IndexFieldList getIndexList (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Index Field List.
virtual string getPacketValid (bool strict, int32_t length) const
Checks to see if the packet is valid.
virtual ArrayOfRecords getSectorScanStep (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Sector Scan/Step Field.
virtual SpectrumField getSpectrumField (IndicatorFieldEnum_t cif7field=CIF_NULL) const
Gets the Spectrum Field SpectrumField type (See V49.2 spec Section 9.6.1).
virtual bool isChangePacket () const
Indicates if any fields have changes since the last packet in this stream.
virtual bool resetForResend (const TimeStamp &t)
Prepares a packet for resend resetting any non-persistent values and clearing the context change flags.
virtual void setDataPayloadFormat (const PayloadFormat &val, IndicatorFieldEnum_t cif7field=CIF_NULL)
Sets the Data Packet Payload Format.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
virtual void setPacketType (PacketType t)
Optional functionality: Sets the packet type.
Protected Member Functions
BasicContextPacket (const BasicVRTPacket &p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength)
Internal constructor, for use by subclasses.
virtual int8_t getB (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const
Unpacks a 16-bit integer from the payload at the indicated position.
virtual int32_t getCIF7Offset (int32_t attr, int32_t len, bool occurrence=0) const
Gets the offset of the CIF7 attribute Offset is from the start of a field of size specified.
virtual int32_t getContextIndicatorField0 (bool occurrence=0) const
Gets the header type, used with getOffset(.
virtual int32_t getContextIndicatorField1 (bool occurrence=0) const
virtual int32_t getContextIndicatorField2 (bool occurrence=0) const
virtual int32_t getContextIndicatorField3 (bool occurrence=0) const
virtual int32_t getContextIndicatorField7 (bool occurrence=0) const
Ephemeris getEphemeris (int8_t cifNum, int32_t field, int32_t cif7bit) const
Used for unpacking ephemeris records.
virtual int32_t getFieldLen (int8_t cifNum, int32_t field, int32_t parent=0) const
Gets the length of the given field when present (-1 if variable, -2 if not found).
Geolocation getGeolocation (int8_t cifNum, int32_t field, int32_t cif7bit) const
Functions that require pack/unpack functions from BasicVRTPacket.
virtual int16_t getI (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const
Unpacks a 16-bit integer from the payload at the indicated position.
virtual int32_t getL (int8_t cifNum, int32_t bit, int32_t cif7bit) const
Unpacks a 32-bit integer from the payload at the indicated position.
virtual int32_t getL24 (int8_t cifNum, int32_t bit, int32_t offset, int32_t cif7bit) const
Unpacks a 32-bit integer from the payload at the indicated position.
virtual int32_t getOffset (int8_t cifNum, int32_t field) const
Gets the offset for the given context indicator field relative to the location of the first occurrence of CIF0.
virtual boolNull getStateEventBit (int32_t enable, int32_t indicator, int32_t cif7bit) const
Gets the specified bit from the State and Event Indicator field.
virtual TimeStamp getTimeStampField (int8_t cifNum, int32_t bit, int32_t cif7bit) const
Unpacks a TimeStamp from the payload at the indicated position.
virtual int32_t getTotalFieldSize (int32_t fieldLen, bool occurrence=0) const
Gets the total size of the field, including all CIF7 attributes.
virtual UUID getUUID (int8_t cifNum, int32_t bit, int32_t cif7bit) const
Unpacks a 128-bit UUID from the payload at the indicated position.
virtual int64_t getX (int8_t cifNum, int32_t bit, int32_t cif7bit) const
Unpacks a 64-bit integer from the payload at the indicated position.
virtual void setB (int8_t cifNum, int32_t bit, int32_t xoff, int8_t val, int32_t cif7bit)
Packs a 16-bit integer from the payload at the indicated position.
virtual void setCIF7Bit (int32_t cif7bit, bool set, bool occurrence=false)
virtual void setContextIndicatorField0Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setContextIndicatorField1Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setContextIndicatorField2Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setContextIndicatorField3Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setContextIndicatorField7Bit (int32_t bit, bool set, bool occurrence=0)
virtual void setI (int8_t cifNum, int32_t bit, int32_t xoff, int16_t val, int32_t cif7bit)
Packs a 16-bit integer from the payload at the indicated position.
virtual void setL (int8_t cifNum, int32_t bit, int32_t val, int32_t cif7bit)
Packs a 32-bit integer from the payload at the indicated position.
virtual void setRecord (int8_t cifNum, int32_t bit, const Record *val, int32_t oldLen, int32_t cif7bit)
Gets a block of data.
virtual void setStateEventBit (int32_t enable, int32_t indicator, boolNull value, int32_t cif7bit)
Sets the specified bit of the State and Event Indicator field.
virtual void setTimeStampField (int8_t cifNum, int32_t bit, const TimeStamp &val, int32_t cif7bit)
Packs a TimeStamp from the payload at the indicated position.
virtual void setUUID (int8_t cifNum, int32_t bit, const UUID &val, int32_t cif7bit)
Packs a 128-bit UUID from the payload at the indicated position.
virtual void setX (int8_t cifNum, int32_t bit, int64_t val, int32_t cif7bit)
Packs a 64-bit integer from the payload at the indicated position.
virtual void toStringStream (ostringstream &str) const
Writes the packet content to a string stream in a user-friendly format.
Detailed Description
A basic but full-featured implementation of a VRT IF Context packet.
The following implementation is used for the HasFields methods:
     ID | Name                     | Type
    ----+--------------------------+------------------
    N+0 | ChangePacket             | Bool
    N+1 | ReferencePointIdentifier | Int32
    N+2 | Bandwidth                | Double
    N+3 | FrequencyIF              | Double
    N+4 | FrequencyRF              | Double
    N+5 | FrequencyOffsetRF        | Double
    N+6 | BandOffsetIF             | Double
    N+7 | ReferenceLevel           | Float
    N+8 | Gain                     | Float
    N+9 | Gain1                    | Float (can not set to null)
    N+10| Gain2                    | Float (can not set to null)
    N+11| OverRangeCount           | Int64
    N+12| SampleRate               | Double
    N+13| SamplePeriod             | Double
    N+14| TimeStampAdjustment      | Int64
    N+15| TimeStampCalibration     | Int32
    N+16| Temperature              | Float
    N+17| DeviceID                 | String
    N+18| CalibratedTimeStamp      | BoolNull
    N+19| DataValid                | BoolNull
    N+20| ReferenceLocked          | BoolNull
    N+21| SignalDetected           | BoolNull
    N+22| InvertedSpectrum         | BoolNull
    N+23| OverRange                | BoolNull
    N+24| Discontinuous            | BoolNull
    N+25| UserDefinedBits          | Int8
    N+26| DataPayloadFormat        | PayloadFormat
    N+27| GeolocationGPS           | Geolocation
    N+28| GeolocationINS           | Geolocation
    N+29| EphemerisECEF            | Ephemeris
    N+30| EphemerisRelative        | Ephemeris
    N+31| EphemerisReference       | Int32
    N+32| GeoSentences             | GeoSentences
    N+33| ContextAssocLists        | ContextAssocLists
    // TODO - update comment w/ accurate CIF0 info, and additional CIFs
    // TODO - also update hasFields implementation, of course
    ----+--------------------------+------------------
    (N = number of fields in BasicVRTPacket)
Constructor & Destructor Documentation
vrt::BasicContextPacket::~BasicContextPacket () [inline]
Basic destructor.
vrt::BasicContextPacket::BasicContextPacket (const BasicVRTPacket & p)
Basic copy constructor.
vrt::BasicContextPacket::BasicContextPacket (const BasicVRTPacket & p, int64_t classID)
Internal constructor, for use by subclasses.
Parameters:
p The packet (already initialized).
classID The expected classID.
Exceptions:
VRTException If packet type or classID of the packet are invalid.
vrt::BasicContextPacket::BasicContextPacket (const void * buf, size_t len, bool readOnly = false)
Creates a new instance accessing the given data buffer.
Parameters:
buf The pointer to the packet buffer.
len The length of the packet buffer.
readOnly Should users of this instance be able to modify the underlying data buffer?
vrt::BasicContextPacket::BasicContextPacket ()
Creates a new instance that can be written to.
Initially this will just be a simple context packet with no fields set (other than the required packet length of 8 and a default stream ID of 0).
vrt::BasicContextPacket::BasicContextPacket (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
Initially this will just be a simple context packet with no fields set (other than the required packet length of 8 and a default stream ID of 0), but will have the underlying buffers pre-allocated as required.
Parameters:
bufsize The anticipated buffer size.
vrt::BasicContextPacket::BasicContextPacket (const vector< char > & buf, bool readOnly = false)
Creates a new instance accessing the given data buffer.
Note that when the buffer lengths are given, only the most minimal of error checking is done. Users should call isPacketValid() to verify that the packet is valid. Invalid packets can result unpredictable behavior, but this is explicitly allowed (to the extent possible) so that applications creating packets can use this class even if the packet isn't yet "valid".
Parameters:
buf The data buffer to use.
readOnly Should users of this instance be able to modify the underlying data buffer?
Exceptions:
VRTException If the offset is negative or greater than the length of the buffer given. Also thrown if the buffer length is -1 and a copy can not be made because the sizes in the header of the packet are invalid.
vrt::BasicContextPacket::BasicContextPacket (const BasicVRTPacket & p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength) [protected]
Internal constructor, for use by subclasses.
Parameters:
p The packet (already initialized).
type The expected packet type.
classID The expected classID.
minPayloadLength The minimum payload length.
maxPayloadLength The maximum payload length (<0 if not pre-defined).
Exceptions:
VRTException If packet type or classID of the packet are invalid, or if the payload length is invalid.
Member Function Documentation
virtual void vrt::BasicContextPacket::addCIF1 (bool add = true, bool occurrence = false) [virtual]
Adds or removes a CIF Sets the Enable Indicator of CIF0 and adds or removes 4-bytes for the CIF.
Parameters:
add True = add CIF (default), False = remove CIF
occurrence Value is ignored and assumed to be 0.
Implements vrt::IndicatorFieldProvider.
virtual ArrayOfRecords vrt::BasicContextPacket::get3DPointingVectorStructured (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the 3D Pointing Vector (Structured).
Parameters:
cif7field Indicator field for the CIF7 attribute.
Returns:
3D Pointing Vector as an Array-of-Records (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getOffset(), and vrt::BasicVRTPacket::unpackPayloadRecord().
TimeStamp vrt::BasicContextPacket::getAdjustedTimeStamp () const [inline]
Gets the adjusted time stamp of the packet.
This is implemented as follows:
  public: TimeStamp getAdjustedTimeStamp () const {
    int64_t adj = getTimeStampAdjustment();
    return (adj == INT64_NULL)? getTimeStamp() : getTimeStamp().addPicoSeconds(adj);
  }
Returns:
The adjusted time stamp of the packet (never null).
References vrt::TimeStamp::addPicoSeconds(), vrt::BasicVRTPacket::getTimeStamp(), and vrt::IndicatorFieldProvider::getTimeStampAdjustment().
virtual int8_t vrt::BasicContextPacket::getB (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const [protected, virtual]
Unpacks a 16-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual int32_t vrt::BasicContextPacket::getCIF7Offset (int32_t attr, int32_t len, bool occurrence = 0) const [protected, virtual]
Gets the offset of the CIF7 attribute Offset is from the start of a field of size specified.
Parameters:
attr CIF7 attribute bitmask
len Length of the field
occurrence False (0) if first occurrence (default; almost everything), True (1) if second occurrence (only Errors for BasicAcknowledgePacket)
Returns:
Offset from start of field
Reimplemented from vrt::IndicatorFieldProvider.
virtual ArrayOfRecords vrt::BasicContextPacket::getCIFsArray (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the CIFs Array.
Parameters:
cif7field Indicator field for the CIF7 attribute.
Returns:
The CIFs Array as an Array-of-Records (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getOffset(), and vrt::BasicVRTPacket::unpackPayloadRecord().
ContextAssocLists vrt::BasicContextPacket::getContextAssocLists (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the Context Association Lists.
These lists indicate the other context/data streams associated with this one.
Parameters:
cif7field Indicator field for the CIF7 attribute.
Returns:
The context association lists (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getOffset(), and vrt::BasicVRTPacket::unpackPayloadRecord().
virtual int32_t vrt::BasicContextPacket::getContextIndicatorField0 (bool occurrence = 0) const [inline, protected, virtual]
Gets the header type, used with getOffset(.
.) and OFFSET_TABLE.
Implements vrt::IndicatorFieldProvider.
References vrt::BasicVRTPacket::bbuf, vrt::BasicVRTPacket::getPrologueLength(), and vrt::VRTMath::unpackInt().
virtual PayloadFormat vrt::BasicContextPacket::getDataPayloadFormat (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Functions that require PayloadFormat type from BasicVRTPacket.
Gets the Data Packet Payload Format. This specifies the format of the data in the paired data packet stream.
Parameters:
cif7field Indicator field for the CIF7 attribute.
Returns:
The payload format (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getOffset(), and getX().
Ephemeris vrt::BasicContextPacket::getEphemeris (int8_t cifNum, int32_t field, int32_t cif7bit) const [inline, protected, virtual]
Used for unpacking ephemeris records.
Implements vrt::IndicatorFieldProvider.
References getOffset(), and vrt::BasicVRTPacket::unpackPayloadRecord().
virtual Value* vrt::BasicContextPacket::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::StandardContextPacket.
virtual int32_t vrt::BasicContextPacket::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::StandardContextPacket.
virtual int32_t vrt::BasicContextPacket::getFieldLen (int8_t cifNum, int32_t field, int32_t parent = 0) const [protected, virtual]
Gets the length of the given field when present (-1 if variable, -2 if not found).
Parameters:
cifNum number of CIF that field belongs to.
field bitmask associated with field of interest.
parent length of parent field
Returns:
size of field of interest in bytes.
Exceptions:
VRTException If the CIF number is invalid.
Implements vrt::IndicatorFieldProvider.
virtual string vrt::BasicContextPacket::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::StandardContextPacket.
virtual ValueType vrt::BasicContextPacket::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::StandardContextPacket.
Geolocation vrt::BasicContextPacket::getGeolocation (int8_t cifNum, int32_t field, int32_t cif7bit) const [inline, protected, virtual]
Functions that require pack/unpack functions from BasicVRTPacket.
Used for unpacking geolocation records. Used for unpacking ephemeris records. Used for unpacking geolocation records.
Implements vrt::IndicatorFieldProvider.
References getOffset(), and vrt::BasicVRTPacket::unpackPayloadRecord().
GeoSentences vrt::BasicContextPacket::getGeoSentences (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the GPS ASCII "sentences".
These are ASCII "sentences" from a GPS (Global Positioning System) receiver, such as those conforming to NMEA-0183. Due to the great variety in GPS "sentences", this class makes little effort to do anything useful with them. Users are encouraged to use getGeolocationGPS() which essentially provides the same information, but in a consistent form.
Parameters:
cif7field Indicator field for the CIF7 attribute.
Returns:
The geolocation information (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getOffset(), and vrt::BasicVRTPacket::unpackPayloadRecord().
virtual int16_t vrt::BasicContextPacket::getI (int8_t cifNum, int32_t bit, int32_t xoff, int32_t cif7bit) const [protected, virtual]
Unpacks a 16-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
IndexFieldList vrt::BasicContextPacket::getIndexList (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the Index Field List.
Parameters:
cif7field Indicator field for the CIF7 attribute.
Returns:
The Index Field List (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getOffset(), and vrt::BasicVRTPacket::unpackPayloadRecord().
virtual int32_t vrt::BasicContextPacket::getL (int8_t cifNum, int32_t bit, int32_t cif7bit) const [protected, virtual]
Unpacks a 32-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual int32_t vrt::BasicContextPacket::getL24 (int8_t cifNum, int32_t bit, int32_t offset, int32_t cif7bit) const [protected, virtual]
Unpacks a 32-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual int32_t vrt::BasicContextPacket::getOffset (int8_t cifNum, int32_t field) const [protected, virtual]
Gets the offset for the given context indicator field relative to the location of the first occurrence of CIF0.
CIF7 is considered an invalid CIF number. For access to the second occurrence of CIFs (i.e. Error fields in Ack packets), add 8 to the CIF number, effectively setting the 4th bit (mod8 gives field, div8 gives occurrence).
Parameters:
cifNum number of CIF that field belongs to.
field bitmask associated with field of interest.
Returns:
offset in bytes from beginning of CIF payload, or CIF7 as described above.
Exceptions:
VRTException If the CIF number is invalid.
Implements vrt::IndicatorFieldProvider.
Referenced by get3DPointingVectorStructured(), getCIFsArray(), getContextAssocLists(), getDataPayloadFormat(), getEphemeris(), getGeolocation(), getGeoSentences(), getIndexList(), getSectorScanStep(), and getSpectrumField().
virtual string vrt::BasicContextPacket::getPacketValid (bool strict, int32_t length) const [virtual]
Checks to see if the packet is valid.
This is identical to isPacketValid(int32_t) except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No packet failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a packet.
length Verifies that the length of the packet matches this value.
Returns:
Empty string ("") if it is valid, a description of the error otherwise.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::BasicControlPacket, and vrt::StandardContextPacket.
virtual ArrayOfRecords vrt::BasicContextPacket::getSectorScanStep (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the Sector Scan/Step Field.
Parameters:
cif7field Indicator field for the CIF7 attribute.
Returns:
The Sector Scan/Step Array-of-Records (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getOffset(), and vrt::BasicVRTPacket::unpackPayloadRecord().
virtual SpectrumField vrt::BasicContextPacket::getSpectrumField (IndicatorFieldEnum_t cif7field = CIF_NULL) const [inline, virtual]
Gets the Spectrum Field SpectrumField type (See V49.2 spec Section 9.6.1).
Parameters:
cif7field Indicator field for the CIF7 attribute.
Returns:
The Spectrum Field (null if not specified). Note that changes to the returned object do not alter the packet.
Implements vrt::IndicatorFieldProvider.
References vrt::IndicatorFields::getCIFBitMask(), vrt::IndicatorFields::getCIFNumber(), getOffset(), and vrt::BasicVRTPacket::unpackPayloadRecord().
virtual boolNull vrt::BasicContextPacket::getStateEventBit (int32_t enable, int32_t indicator, int32_t cif7bit) const [protected, virtual]
Gets the specified bit from the State and Event Indicator field.
Parameters:
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
cif7bit Bit position of the CIF7 indicator flag.
Returns:
null if field is not present, null if the enable bit is not set, true if the enable bit is set and the indicator bit is set, false if the enable bit is set but the indicator bit is not set.
Implements vrt::IndicatorFieldProvider.
virtual TimeStamp vrt::BasicContextPacket::getTimeStampField (int8_t cifNum, int32_t bit, int32_t cif7bit) const [protected, virtual]
Unpacks a TimeStamp from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual int32_t vrt::BasicContextPacket::getTotalFieldSize (int32_t fieldLen, bool occurrence = 0) const [protected, virtual]
Gets the total size of the field, including all CIF7 attributes.
Parameters:
fieldLen Length of the field w/o including CIF7 attributes
occurrence False (0) if first occurrence (default; almost everything), True (1) if second occurrence (only Errors for BasicAcknowledgePacket)
Returns:
Length of the field including CIF7 attributes
Implements vrt::IndicatorFieldProvider.
virtual UUID vrt::BasicContextPacket::getUUID (int8_t cifNum, int32_t bit, int32_t cif7bit) const [protected, virtual]
Unpacks a 128-bit UUID from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual int64_t vrt::BasicContextPacket::getX (int8_t cifNum, int32_t bit, int32_t cif7bit) const [protected, virtual]
Unpacks a 64-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
Referenced by getDataPayloadFormat().
virtual bool vrt::BasicContextPacket::isChangePacket () const [inline, virtual]
Indicates if any fields have changes since the last packet in this stream.
Packet streams that do not support this concept, should always return true indicating that the recipient must read the packet to determine if there was a change. An IF Data stream will always return true.
Returns:
true if anything in the packet may have changed since the last context packet, false if nothing has changed since the last context packet.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::BasicControlPacket.
virtual bool vrt::BasicContextPacket::resetForResend (const TimeStamp & t) [virtual]
Prepares a packet for resend resetting any non-persistent values and clearing the context change flags.
This is implemented as follows:
    bool BasicContextPacket::resetForResend (const TimeStamp &t) {
      BasicVRTPacket::resetForResend(t);
      setChangePacket(false);
      setOverRangeCount(null);
      setOverRange(null);
      setDiscontinuous(null);
      return true;
    }
Parameters:
t The new time stamp.
Returns:
true
Reimplemented from vrt::BasicVRTPacket.
virtual void vrt::BasicContextPacket::setB (int8_t cifNum, int32_t bit, int32_t xoff, int8_t val, int32_t cif7bit) [protected, virtual]
Packs a 16-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicContextPacket::setDataPayloadFormat (const PayloadFormat & val, IndicatorFieldEnum_t cif7field = CIF_NULL) [virtual]
Sets the Data Packet Payload Format.
This specifies the format of the data in the paired data packet stream.
Parameters:
val The payload format (null if not specified).
cif7field Indicator field for the CIF7 attribute.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicContextPacket::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::StandardContextPacket.
virtual void vrt::BasicContextPacket::setI (int8_t cifNum, int32_t bit, int32_t xoff, int16_t val, int32_t cif7bit) [protected, virtual]
Packs a 16-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicContextPacket::setL (int8_t cifNum, int32_t bit, int32_t val, int32_t cif7bit) [protected, virtual]
Packs a 32-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicContextPacket::setPacketType (PacketType t) [inline, virtual]
Optional functionality: Sets the packet type.
Parameters:
t The packet type.
Exceptions:
VRTException If this method is not supported.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::BasicControlPacket, and vrt::BasicQueryAcknowledgePacket.
virtual void vrt::BasicContextPacket::setRecord (int8_t cifNum, int32_t bit, const Record * val, int32_t oldLen, int32_t cif7bit) [protected, virtual]
Gets a block of data.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicContextPacket::setStateEventBit (int32_t enable, int32_t indicator, boolNull value, int32_t cif7bit) [protected, virtual]
Sets the specified bit of the State and Event Indicator field.
Parameters:
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
value The value of the bits: null if the enable bit should not be set, true if the enable bit and the indicator bit should be set, false if the enable bit should be set but the indicator bit should not be set.
cif7bit Bit position of the CIF7 indicator flag.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicContextPacket::setTimeStampField (int8_t cifNum, int32_t bit, const TimeStamp & val, int32_t cif7bit) [protected, virtual]
Packs a TimeStamp from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicContextPacket::setUUID (int8_t cifNum, int32_t bit, const UUID & val, int32_t cif7bit) [protected, virtual]
Packs a 128-bit UUID from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicContextPacket::setX (int8_t cifNum, int32_t bit, int64_t val, int32_t cif7bit) [protected, virtual]
Packs a 64-bit integer from the payload at the indicated position.
Implements vrt::IndicatorFieldProvider.
virtual void vrt::BasicContextPacket::toStringStream (ostringstream & str) const [protected, virtual]
Writes the packet content to a string stream in a user-friendly format.
Parameters:
str The string stream to write to.
Reimplemented from vrt::BasicVRTPacket.
Reimplemented in vrt::BasicControlPacket, vrt::BasicQueryAcknowledgePacket, and vrt::StandardContextPacket.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/BasicContextPacket.h