VRT: vrt::BasicVRTPacket Class Reference
vrt::BasicVRTPacket Class Reference
A basic but full-featured implementation of BasicVRTPacket.
#include <BasicVRTPacket.h>
Public Member Functions
BasicVRTPacket (const vector< char > &buf, ssize_t start, ssize_t end, bool readOnly=false)
Creates a new instance accessing the given data buffer.
BasicVRTPacket (const vector< char > &buf, bool readOnly=false)
Creates a new instance accessing the given data buffer.
BasicVRTPacket (vector< char > *buf_ptr, bool readOnly)
Creates a new instance accessing the given data buffer.
BasicVRTPacket (const void *buf, size_t len, bool readOnly=false)
Creates a new instance accessing the given data buffer.
BasicVRTPacket (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
BasicVRTPacket (const BasicVRTPacket &p)
Basic copy constructor for the class.
BasicVRTPacket ()
Basic no-argument constructor for the class.
~BasicVRTPacket ()
Basic destructor for the class.
virtual bool equals (const VRTObject &o) const
virtual bool equals (const BasicVRTPacket &o) const
Checks for equality with an unknown object.
virtual string getClassID () const
Gets the class identifier as a string.
virtual int64_t getClassIdentifier () const
Gets the packet class identifier.
virtual int16_t getClassIdentifierICC ()
Gets the Information Class Code (ICC) from the packet class identifier.
virtual int32_t getClassIdentifierOUI ()
Gets the Organizational Unique Identifier (OUI) from the packet class identifier.
virtual int16_t getClassIdentifierPCC ()
Gets the Packet Class Code (PCC) from the packet class identifier.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
virtual int32_t getHeaderLength () const
Gets the header length in bytes (does not include packet specific prologue or trailer).
vector< char > getPacket () const
Reads the packet content as a vector.
virtual int32_t getPacketCount () const
Gets the packet count.
virtual int32_t getPacketLength () const
Gets the packet length in bytes.
char * getPacketPointer ()
Experimental, use with care: Gets a pointer to the packet content.
char * getPacketPointer_type ()
Experimental, use with care: Gets a pointer to the packet content.
virtual PacketType getPacketType () const
Gets the packet type.
virtual string getPacketValid (bool strict, int32_t length) const
Checks to see if the packet is valid.
string getPacketValid (bool strict) const
Checks to see if the packet is valid.
vector< char > getPacketVector () const
Reads the packet content as a vector.
virtual int32_t getPadBitCount () const
Gets the number of pad bits inserted following the data in the payload such that the payload section is always a multiple of 4-bytes in length.
vector< char > getPayload () const
Reads the packet payload as a vector.
int32_t getPayloadLength () const
Gets the payload length in bytes.
char * getPayloadPointer ()
Experimental, use with care: Gets a pointer to the packet payload.
virtual int32_t getPktSpecificPrologueLength () const
Gets the packet specific prologue (PSP) length in bytes.
virtual int32_t getPrologueLength () const
Gets the prologue length in bytes (includes header and packet specific prologue, but does not include trailer).
int64_t getStreamCode () const
Internal use only: Swaps packet buffer contents.
virtual string getStreamID () const
Gets the 32-bit packet stream identifier as a string.
virtual int32_t getStreamIdentifier () const
Gets the 32-bit packet stream identifier.
virtual TimeStamp getTimeStamp (double sr) const
Gets the time stamp of the packet for the given sampling rate.
virtual TimeStamp getTimeStamp () const
Gets the time stamp of the packet.
int32_t getTrailerLength () const
Gets the trailer length in bytes.
bool hasPacketSpecificPrologue () const
Does this packet have a packet specific prologue?
bool hasTrailer () const
Does this packet have a trailer?
bool headerEquals (const BasicVRTPacket &p) const
Checks for header equality with another BasicVRTPacket.
virtual boolNull isCancelMode () const
Command packets only: Gets the Cancel Mode (L).
virtual bool isChangePacket () const
Indicates if any fields have changes since the last packet in this stream.
bool isCommand () const
Is the packet type a command packet?
bool isContext () const
Is the packet type a context packet?
virtual boolNull isControlAckMode () const
Command packets only: Gets the Control/Ack Mode (ACK).
bool isData () const
Is the packet type a data packet?
virtual bool isNullValue () const
Is this object equal to null.
bool isPacketValid (int32_t length) const
Checks to see if the packet is valid.
bool isPacketValid () const
Checks to see if the packet is valid.
virtual boolNull isSpectrumMode () const
Data packets only: Gets the Signal Spectrum Data Mode (S).
virtual boolNull isTimeStampMode () const
Context packets only: Gets the Time Stamp Mode (TSM).
bool payloadEquals (const BasicVRTPacket &p) const
Checks for payload equality with another BasicVRTPacket.
bool pktSpecificPrologueEquals (const BasicVRTPacket &p) const
Checks for packet specific prologue (PSP) equality with another BasicVRTPacket.
bool prologueEquals (const BasicVRTPacket &p) const
Checks for prologue equality with another BasicVRTPacket.
int32_t readPacket (void *buffer, int32_t poff, int32_t len) const
Reads the packet payload into the provided buffer.
int32_t readPayload (void *buffer, int32_t poff, int32_t len) const
Reads the packet payload into the provided buffer.
virtual bool resetForResend (const TimeStamp &t)
Prepares a packet for resend resetting any non-persistent values and clearing the context change flags.
virtual void setCancelMode (bool v)
Optional functionality: Command packets only: Gets the Cancel Mode (L).
virtual void setClassID (string v)
Optional functionality: Sets the packet class identifier.
virtual void setClassIdentifier (int32_t oui, int16_t icc, int16_t pcc)
Optional functionality: Sets the packet class identifier.
virtual void setClassIdentifier (int64_t v)
Optional functionality: Sets the packet class identifier.
virtual void setControlAckMode (bool v)
Optional functionality: Command packets only: Sets the Control/Ack Mode (ACK).
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
virtual void setPacketCount (int32_t v)
Optional functionality: Sets the packet count.
virtual void setPacketType (PacketType t)
Optional functionality: Sets the packet type.
virtual void setPadBitCount (int32_t bits, int32_t bitsPerSample)
Optional functionality: Sets the number of pad bits inserted following the data in the payload such that the payload section is always a multiple of 4-bytes in length (see getPadBitCount() for a detailed discussion about the reporting of pad bits).
void setPayload (void *buffer, int32_t length)
Optional functionality: Sets the content of the packet payload and updates the length of the payload.
void setPayload (vector< char > buffer)
Optional functionality: Sets the content of the packet payload and updates the length of the payload.
virtual void setPayloadLength (int32_t v)
Optional functionality: Sets the payload length in bytes.
virtual void setSpectrumMode (bool v)
Optional functionality: Data packets only: Sets the Signal Spectrum Data Mode (S).
virtual void setStreamID (string v)
Optional functionality: Sets the 32-bit packet stream identifier.
virtual void setStreamIdentifier (int32_t v)
Optional functionality: Sets the 32-bit packet stream identifier.
virtual void setTimeStamp (const TimeStamp &v)
Optional functionality: Sets the time stamp for the packet.
virtual void setTimeStampMode (bool v)
Optional functionality: Context packets only: Sets the Time Stamp Mode (TSM).
void swap (BasicVRTPacket *pkt)
Internal Use Only: Does a buffer swap.
void swap (vector< char > *buffer)
Internal Use Only: Does a buffer swap.
virtual string toString () const
Converts this class its string form.
bool trailerEquals (const BasicVRTPacket &p, bool exact) const
Checks for trailer equality with another BasicVRTPacket.
bool trailerEquals (const BasicVRTPacket &p) const
Checks for trailer equality with another BasicVRTPacket.
void writePayload (void *buffer, int32_t poff, int32_t len)
Optional functionality: Writes to the packet payload, but does NOT update the length of the payload.
Static Public Member Functions
static int32_t getPacketLength (const vector< char > &buf, int32_t off)
Internal Use Only: Get VRT packet length using a buffer input.
static int64_t getStreamCode (const void *ptr)
Internal use only: Gets the packet stream code.
static void setPacketCount (void *ptr, int32_t v)
Internal Use Only: Sets the packet count.
Public Attributes
vector< char > bbuf
Packet buffer (always includes the header).
Static Public Attributes
static const int32_t MAX_HEADER_LENGTH = 7*4
The maximum length of the header in bytes (all optional fields included).
static const int32_t MAX_PACKET_LENGTH = 65536*4
The maximum length of the packet in bytes (header + payload + trailer).
static const int32_t MAX_PAYLOAD_LENGTH = MAX_PACKET_LENGTH - MAX_PROLOGUE_LENGTH - MAX_TRAILER_LENGTH
The de-facto maximum length of the payload in bytes.
static const int32_t MAX_PKT_SPECIFIC_PROLOGUE_LENGTH = 10*4
The maximum length of the packet specific prologue (PSP) in bytes (all optional fields included).
static const int32_t MAX_PROLOGUE_LENGTH = MAX_HEADER_LENGTH + MAX_PKT_SPECIFIC_PROLOGUE_LENGTH
The maximum length of the prologue in bytes (all optional fields included).
static const int32_t MAX_TRAILER_LENGTH = 1*4
The maximum length of the trailer in bytes.
static const BasicVRTPacket NULL_PACKET
Represents a null VRT packet.
Protected Member Functions
BasicVRTPacket (const BasicVRTPacket &p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength)
Internal constructor, for use by subclasses.
bool hasStreamIdentifier () const
Internal use only: Does the packet type have a stream identifier.
void packPayloadAscii (int32_t off, string val, int32_t len)
Packs an ASCII string into the payload of the packet.
void packPayloadBoolean (int32_t off, bool val)
Packs a boolean value into the payload of the packet.
void packPayloadBoolNull (int32_t off, boolNull val)
Packs a boolNull value into the payload of the packet.
void packPayloadByte (int32_t off, char val)
Packs an 8-bit integer into the payload of the packet.
void packPayloadBytes (int32_t off, const void *val, int32_t len)
Packs a block of bytes into the payload of the packet.
void packPayloadBytes (int32_t off, const vector< char > &val, int32_t len)
Packs a block of bytes into the payload of the packet.
void packPayloadDouble (int32_t off, double val)
Packs a 64-bit floating-point value into the payload of the packet.
void packPayloadFloat (int32_t off, float val)
Packs a 32-bit floating-point value into the payload of the packet.
void packPayloadInetAddr (int32_t off, InetAddress val)
Packs a InetAddress into the payload of the packet.
void packPayloadInt (int32_t off, int32_t val)
Packs a 32-bit integer into the payload of the packet.
void packPayloadLong (int32_t off, int64_t val)
Packs a 64-bit integer into the payload of the packet.
void packPayloadMetadata (int32_t off, MetadataBlock val, int32_t len)
Packs a metadata block into the payload of the packet.
void packPayloadRecord (int32_t off, Record val)
Packs a record value into the payload of the packet.
void packPayloadShort (int32_t off, int16_t val)
Packs a 16-bit integer into the payload of the packet.
void packPayloadTimeStamp (int32_t off, TimeStamp val, IntegerMode epoch)
Packs a TimeStamp into the payload of the packet.
void packPayloadUTF8 (int32_t off, string val, int32_t len)
Packs a UTF-8 string into the payload of the packet.
void packPayloadUTF8 (int32_t off, wstring val, int32_t len)
Packs a UTF-8 string into the payload of the packet.
void packPayloadUUID (int32_t off, UUID val)
Packs a UUID into the payload of the packet.
void setPacketLength (int32_t v)
Internal use only: Sets the packet length.
void shiftHeader (int32_t field, int32_t bytes, bool present)
Internal use only: Shifts the header.
int32_t shiftPacketSpecificPrologue (int32_t off, int32_t bytes, bool add)
Internal use only: Shifts the packet specific prologue (PSP).
int32_t shiftPayload (int32_t off, int32_t bytes, bool add)
Internal use only: Shifts the payload.
void shiftTrailer (bool add)
Internal use only: Shifts the trailer.
virtual void toStringStream (ostringstream &str) const
Writes the packet content to a string stream in a user-friendly format.
string unpackPayloadAscii (int32_t off, int32_t len) const
Unpacks an ASCII string from the payload of the packet.
bool unpackPayloadBoolean (int32_t off) const
Unpacks a boolean value from the payload of the packet.
boolNull unpackPayloadBoolNull (int32_t off) const
Unpacks a boolNull value from the payload of the packet.
char unpackPayloadByte (int32_t off) const
Unpacks an 8-bit integer from the payload of the packet.
void * unpackPayloadBytes (int32_t off, void *val, int32_t len) const
Unpacks a block of bytes from the payload of the packet.
vector< char > unpackPayloadBytes (int32_t off, int32_t len) const
Unpacks a block of bytes from the payload of the packet.
double unpackPayloadDouble (int32_t off) const
Unpacks a 64-bit floating-point value from the payload of the packet.
float unpackPayloadFloat (int32_t off) const
Unpacks a 32-bit floating-point value from the payload of the packet.
InetAddress unpackPayloadInetAddr (int32_t off) const
Unpacks a InetAddress from the payload of the packet.
int32_t unpackPayloadInt (int32_t off) const
Unpacks a 32-bit integer from the payload of the packet.
int64_t unpackPayloadLong (int32_t off) const
Unpacks a 64-bit integer from the payload of the packet.
MetadataBlock unpackPayloadMetadata (int32_t off, int32_t len) const
Unpacks a metadata block from the payload of the packet.
void unpackPayloadRecord (int32_t off, Record &rec) const
Unpacks a record from the payload of the packet.
int16_t unpackPayloadShort (int32_t off) const
Unpacks a 16-bit integer from the payload of the packet.
TimeStamp unpackPayloadTimeStamp (int32_t off, IntegerMode epoch) const
Unpacks a TimeStamp from the payload of the packet.
wstring unpackPayloadUTF8 (int32_t off, int32_t len) const
Unpacks a UTF-8 string from the payload of the packet.
UUID unpackPayloadUUID (int32_t off) const
Unpacks a UUID from the payload of the packet.
Static Protected Member Functions
static boolNull getStateEventBit (const vector< char > &buf, int32_t off, int32_t enable, int32_t indicator)
Gets the specified bit from the trailer.
static void setStateEventBit (vector< char > &buf, int32_t off, int32_t enable, int32_t indicator, boolNull value)
Optional functionality: Sets the specified bit from the trailer.
Protected Attributes
bool readOnly
Is this instance read-only?
Friends
class VRTReader
Detailed Description
A basic but full-featured implementation of BasicVRTPacket.
The following implementation is used for the HasFields methods:
     ID | Name      | Type
    ----+-----------+-----------
     0  | StreamID  | String
     1  | ClassID   | String
     2  | TimeStamp | TimeStamp
    ----+-----------+-----------
Constructor & Destructor Documentation
vrt::BasicVRTPacket::~BasicVRTPacket () [inline]
Basic destructor for the class.
vrt::BasicVRTPacket::BasicVRTPacket ()
Basic no-argument constructor for the class.
vrt::BasicVRTPacket::BasicVRTPacket (const BasicVRTPacket & p)
Basic copy constructor for the class.
Parameters:
p The packet to copy.
vrt::BasicVRTPacket::BasicVRTPacket (int32_t bufsize)
Creates a new instance with a default anticipated length that can be written to.
Initially this will just be a simple data packet with no fields set (other than the required packet length of 4), but will have the underlying buffers pre-allocated as required.
Parameters:
bufsize The anticipated buffer size.
vrt::BasicVRTPacket::BasicVRTPacket (const void * buf, size_t len, bool readOnly = false)
Creates a new instance accessing the given data buffer.
Parameters:
buf The pointer to the packet buffer.
len The length of the packet buffer.
readOnly Should users of this instance be able to modify the underlying data buffer?
vrt::BasicVRTPacket::BasicVRTPacket (vector< char > * buf_ptr, bool readOnly)
Creates a new instance accessing the given data buffer.
Parameters:
buf_ptr The pointer to the packet buffer.
readOnly Should users of this instance be able to modify the underlying data buffer?
vrt::BasicVRTPacket::BasicVRTPacket (const vector< char > & buf, bool readOnly = false)
Creates a new instance accessing the given data buffer.
Parameters:
buf The pointer to the packet buffer.
readOnly Should users of this instance be able to modify the underlying data buffer?
vrt::BasicVRTPacket::BasicVRTPacket (const vector< char > & buf, ssize_t start, ssize_t end, bool readOnly = false)
Creates a new instance accessing the given data buffer.
Parameters:
buf The pointer to the packet buffer.
start The start point in buffer to use.
end The end point in buffer to use.
readOnly Should users of this instance be able to modify the underlying data buffer?
vrt::BasicVRTPacket::BasicVRTPacket (const BasicVRTPacket & p, PacketType type, int64_t classID, int32_t minPayloadLength, int32_t maxPayloadLength) [protected]
Internal constructor, for use by subclasses.
Parameters:
p The packet (already initialized).
type The expected packet type.
classID The expected classID.
minPayloadLength The minimum payload length.
maxPayloadLength The maximum payload length (<0 if not pre-defined).
Exceptions:
VRTException If packet type or classID of the packet are invalid, or if the payload length is invalid.
Member Function Documentation
virtual bool vrt::BasicVRTPacket::equals (const BasicVRTPacket & o) const [virtual]
Checks for equality with an unknown object.
Two VRT packets are considered equal if the content of the packets is bit-for-bit identical. The actual implementation classes are not considered relevant for checking equality.
Parameters:
o The unknown object.
Returns:
true if they are identical, false otherwise. (This will always returns false if the object is null.)
Reimplemented from vrt::VRTObject.
virtual string vrt::BasicVRTPacket::getClassID () const [virtual]
Gets the class identifier as a string.
This will return the class identifier in the form CC-CC-CC:IIII.PPPP where CC-CC-CC is the standard hexadecimal representation of the OUI (see IEEE standard 802-2001), IIII is the hexadecimal representation of the ICC and PPPP is the hexadecimal representation of the PCC.
Returns:
The packet class identifier as a string or null if not specified.
virtual int64_t vrt::BasicVRTPacket::getClassIdentifier () const [virtual]
Gets the packet class identifier.
Note that the the packet class identifier is the union of the three distinct parts of the class identifier: OUI, ICC, and PCC. This method allows for easy comparison of the class identifier as a whole. Note that if this is null, the OUI, ICC, and PCC will all be null; if this is non-null, the OUI, ICC, and PCC will all be non-null.
Returns:
The packet class identifier or INT8_NULL if not specified.
Referenced by vrt::StandardDataPacket::getPayloadFormat().
virtual int16_t vrt::BasicVRTPacket::getClassIdentifierICC () [virtual]
Gets the Information Class Code (ICC) from the packet class identifier.
This is a user-defined value specified by the OUI (see getClassIdentifierOUI()) that defined this packet class.
Returns:
The ICC or null if not specified.
virtual int32_t vrt::BasicVRTPacket::getClassIdentifierOUI () [virtual]
Gets the Organizational Unique Identifier (OUI) from the packet class identifier.
The OUI is a 24-bit IEEE-assigned identifier for the organization that defined the packet class.
Returns:
The OUI or null if not specified.
virtual int16_t vrt::BasicVRTPacket::getClassIdentifierPCC () [virtual]
Gets the Packet Class Code (PCC) from the packet class identifier.
This is a user-defined value specified by the OUI (see getClassIdentifierOUI()) that defined this packet class.
Returns:
The ICC or null if not specified.
virtual Value* vrt::BasicVRTPacket::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::HasFields.
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
virtual int32_t vrt::BasicVRTPacket::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::HasFields.
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
virtual string vrt::BasicVRTPacket::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::HasFields.
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
virtual ValueType vrt::BasicVRTPacket::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::HasFields.
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
virtual int32_t vrt::BasicVRTPacket::getHeaderLength () const [virtual]
Gets the header length in bytes (does not include packet specific prologue or trailer).
The length of the header will be a value up to MAX_HEADER_LENGTH. The header length will always be a multiple of 4-bytes.
Returns:
The length of the header in bytes.
vector<char> vrt::BasicVRTPacket::getPacket () const
Reads the packet content as a vector.
Referenced by getPacketVector().
virtual int32_t vrt::BasicVRTPacket::getPacketCount () const [virtual]
Gets the packet count.
This is the modulo-16 count of all packets on this stream.
Returns:
The packet count (0..15).
static int32_t vrt::BasicVRTPacket::getPacketLength (const vector< char > & buf, int32_t off) [inline, static]
Internal Use Only: Get VRT packet length using a buffer input.
virtual int32_t vrt::BasicVRTPacket::getPacketLength () const [inline, virtual]
Gets the packet length in bytes.
The length of the header will be a value up to MAX_PACKET_LENGTH (see MAX_PACKET_LENGTH for explanation as to why actual packet lengths used are usually a lot less than this number). The packet length will always be a multiple of 4-bytes.
Returns:
The total length of the packet in bytes.
References bbuf.
Referenced by getPayloadLength().
char* vrt::BasicVRTPacket::getPacketPointer ()
Experimental, use with care: Gets a pointer to the packet content.
Referenced by getPacketPointer_type().
char* vrt::BasicVRTPacket::getPacketPointer_type () [inline]
Experimental, use with care: Gets a pointer to the packet content.
Deprecated:
This function is present for backwards-compatibility with a user-extension, the proper function to use is getPacketPointer().
References getPacketPointer().
virtual PacketType vrt::BasicVRTPacket::getPacketType () const [virtual]
Gets the packet type.
Referenced by hasStreamIdentifier().
virtual string vrt::BasicVRTPacket::getPacketValid (bool strict, int32_t length) const [virtual]
Checks to see if the packet is valid.
This is identical to isPacketValid(int32_t) except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No packet failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a packet.
length Verifies that the length of the packet matches this value.
Returns:
Empty string ("") if it is valid, a description of the error otherwise.
Reimplemented in vrt::BasicCommandPacket, vrt::BasicContextPacket, vrt::BasicControlPacket, vrt::BasicDataPacket, vrt::StandardDataPacket, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
string vrt::BasicVRTPacket::getPacketValid (bool strict) const [inline]
Checks to see if the packet is valid.
This is identical to isPacketValid() except that a description of the error is returned.
Parameters:
strict Should strict checking be done, or just enough to verify that things are OK for reading. No packet failing strict checking should ever be sent out, but it may be useful to disable strict checking when reading in a packet.
Returns:
Empty string ("") if it is valid, a description of the error otherwise.
Referenced by isPacketValid().
vector<char> vrt::BasicVRTPacket::getPacketVector () const [inline]
Reads the packet content as a vector.
Deprecated:
This function is present for backwards-compatibility with a user-extension, the proper function to use is getPacket().
References getPacket().
virtual int32_t vrt::BasicVRTPacket::getPadBitCount () const [virtual]
Gets the number of pad bits inserted following the data in the payload such that the payload section is always a multiple of 4-bytes in length.
The number of pad bits is stored in five of the (formerly-reserved) bits in the ClassID block in the header as part of the suggested VITA-49.0 modifications (i.e. VITA-49.0b), but could be specified elsewhere for some user-defined class types. (The default implementation exclusively follows VITA-49.0b.)
Note that reporting the number of pad bits is optional in situations where the number of pad bits is less than the length of a single sample (this may occur when using the link-efficient packing mode with a data format that does not evenly divide into a 32-/64-bit length). In this situation, the number of pad bits is implicit and can be determined after consideration of the data payload format and payload length (see BasicDataPacket#getDataLength()). This usage matches the VITA-49.0 specification.
Returns:
The number of pad bits *reported* for a data packet. This will return 0 for context packets and data packets that do not report the number of pad bits.
See also:
getPayloadLength()
BasicDataPacket::getDataLength()
vector<char> vrt::BasicVRTPacket::getPayload () const
Reads the packet payload as a vector.
int32_t vrt::BasicVRTPacket::getPayloadLength () const [inline]
Gets the payload length in bytes.
The payload length is a derived value computed as:
    payloadLength = getPacketLength() - getPrologueLength() - getTrailerLength()
The payload length will always be a multiple of 4-bytes.
Returns:
The length of the payload in bytes.
References getPacketLength(), getPrologueLength(), and getTrailerLength().
Referenced by vrt::BasicDataPacket::getData(), vrt::ReferencePointPacket::getDescription(), vrt::StreamStatePacket::getMessage(), vrt::EphemerisPacket::getPointCount(), and vrt::BasicDataPacket::setData().
char* vrt::BasicVRTPacket::getPayloadPointer ()
Experimental, use with care: Gets a pointer to the packet payload.
virtual int32_t vrt::BasicVRTPacket::getPktSpecificPrologueLength () const [virtual]
Gets the packet specific prologue (PSP) length in bytes.
The length of the PSP will be a value up to MAX_PKT_SPECIFIC_PROLOGUE_LENGTH. The PSP length will always be a multiple of 4-bytes.
Returns:
The length of the packet specific prologue in bytes.
Reimplemented in vrt::BasicCommandPacket, and vrt::BasicControlPacket.
virtual int32_t vrt::BasicVRTPacket::getPrologueLength () const [virtual]
Gets the prologue length in bytes (includes header and packet specific prologue, but does not include trailer).
The length of the prologue will be a value up to MAX_PROLOGUE_LENGTH. The prologue length will always be a multiple of 4-bytes.
Returns:
The length of the prologue in bytes.
Reimplemented in vrt::BasicCommandPacket, and vrt::BasicControlPacket.
Referenced by vrt::BasicContextPacket::getContextIndicatorField0(), vrt::BasicDataPacket::getDataByte(), vrt::BasicDataPacket::getDataDouble(), vrt::BasicDataPacket::getDataFloat(), vrt::BasicDataPacket::getDataInt(), vrt::BasicDataPacket::getDataLong(), vrt::BasicDataPacket::getDataShort(), getPayloadLength(), packPayloadAscii(), packPayloadBoolean(), packPayloadBoolNull(), packPayloadByte(), packPayloadBytes(), packPayloadDouble(), packPayloadFloat(), packPayloadInetAddr(), packPayloadInt(), packPayloadLong(), packPayloadMetadata(), packPayloadRecord(), packPayloadShort(), packPayloadTimeStamp(), packPayloadUTF8(), packPayloadUUID(), vrt::BasicDataPacket::setDataByte(), vrt::BasicDataPacket::setDataDouble(), vrt::BasicDataPacket::setDataFloat(), vrt::BasicDataPacket::setDataInt(), vrt::BasicDataPacket::setDataLong(), vrt::BasicDataPacket::setDataShort(), unpackPayloadAscii(), unpackPayloadBoolean(), unpackPayloadBoolNull(), unpackPayloadByte(), unpackPayloadBytes(), unpackPayloadDouble(), unpackPayloadFloat(), unpackPayloadInetAddr(), unpackPayloadInt(), unpackPayloadLong(), unpackPayloadMetadata(), unpackPayloadRecord(), unpackPayloadShort(), unpackPayloadTimeStamp(), unpackPayloadUTF8(), and unpackPayloadUUID().
static boolNull vrt::BasicVRTPacket::getStateEventBit (const vector< char > & buf, int32_t off, int32_t enable, int32_t indicator) [static, protected]
Gets the specified bit from the trailer.
By default all of the "is" methods that access the trailer call this method with the appropriate bit values (no other combinations of inputs is valid):
    Name                Enable Indicator
    ====================================
    CalibratedTimeStamp   31      19
    DataValid             30      18
    ReferenceLocked       29      17
    AutomaticGainControl  28      16
    SignalDetected        27      15
    InvertedSpectrum      26      14
    OverRange             25      13
    Discontinuious        24      12
    Bit11                 23      11 (Data and ExtData Only)
    Bit10                 22      10 (Data and ExtData Only)
    Bit9                  21       9 (Data and ExtData Only)
    Bit8                  20       8 (Data and ExtData Only)
Parameters:
buf The data buffer.
off The offset into the data buffer.
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
Returns:
null if there is no trailer, null if the enable bit is not set, true if the enable bit is set and the indicator bit is set, false if the enable bit is set but the indicator bit is not set.
static int64_t vrt::BasicVRTPacket::getStreamCode (const void * ptr) [static]
Internal use only: Gets the packet stream code.
Parameters:
ptr Pointer to the packet content.
Returns:
The packet stream code.
int64_t vrt::BasicVRTPacket::getStreamCode () const
Internal use only: Swaps packet buffer contents.
Internal use only: Swaps packet buffer contents. Internal use only: Gets the packet stream code. The stream code is a 64-bit value equal to: 0xt0000000ssssssss where t = is the numeric value corresponding to the packet type s = the stream identifier or 0x00000000 if not specified This is used as the hashtable key when doing packet sequence accounting since the counters are unique to the stream and type.
Returns:
The packet stream code.
virtual string vrt::BasicVRTPacket::getStreamID () const [virtual]
Gets the 32-bit packet stream identifier as a string.
Returns:
The stream identifier or null if not specified.
virtual int32_t vrt::BasicVRTPacket::getStreamIdentifier () const [virtual]
Gets the 32-bit packet stream identifier.
Returns:
The stream identifier or INT4_NULL if not specified.
virtual TimeStamp vrt::BasicVRTPacket::getTimeStamp (double sr) const [virtual]
Gets the time stamp of the packet for the given sampling rate.
Parameters:
sr the sampling rate
Returns:
The time stamp of the packet (never null).
virtual TimeStamp vrt::BasicVRTPacket::getTimeStamp () const [virtual]
Gets the time stamp of the packet.
Returns:
The time stamp of the packet (never null).
Referenced by vrt::BasicContextPacket::getAdjustedTimeStamp().
int32_t vrt::BasicVRTPacket::getTrailerLength () const
Gets the trailer length in bytes.
Note that the presence of the trailer is an all-or-nothing, so this method return either MAX_TRAILER_LENGTH or 0.
Returns:
The length of the trailer in bytes.
Referenced by getPayloadLength().
bool vrt::BasicVRTPacket::hasPacketSpecificPrologue () const
Does this packet have a packet specific prologue?
bool vrt::BasicVRTPacket::hasStreamIdentifier () const [inline, protected]
Internal use only: Does the packet type have a stream identifier.
References getPacketType().
bool vrt::BasicVRTPacket::hasTrailer () const
Does this packet have a trailer?
bool vrt::BasicVRTPacket::headerEquals (const BasicVRTPacket & p) const
Checks for header equality with another BasicVRTPacket.
The headers of two VRT packets are considered equal if the content of the headers is bit-for-bit identical. The contents of the payload and trailer need not be equal for this method to return true. However, any two packets for which equals returns true, must have this method return true as well.
Parameters:
p The other packet.
Returns:
true if they are identical, false otherwise. (This will always returns false if the packet is null.)
virtual boolNull vrt::BasicVRTPacket::isCancelMode () const [virtual]
Command packets only: Gets the Cancel Mode (L).
This indicates if a command packet is a Control-Cancel packet:
    true  = Control-Cancel packet
    false = Not a Control-Cancel packet (which leaves Control or one of the Ack subtypes).
    null  = Error: not a command packet
Returns:
true or false as indicated above or null if this is not a command packet.
virtual bool vrt::BasicVRTPacket::isChangePacket () const [virtual]
Indicates if any fields have changes since the last packet in this stream.
Packet streams that do not support this concept, should always return true indicating that the recipient must read the packet to determine if there was a change. An IF Data stream will always return true.
Returns:
true if anything in the packet may have changed since the last context packet, false if nothing has changed since the last context packet.
Reimplemented in vrt::BasicContextPacket, and vrt::BasicControlPacket.
bool vrt::BasicVRTPacket::isCommand () const
Is the packet type a command packet?
bool vrt::BasicVRTPacket::isContext () const
Is the packet type a context packet?
virtual boolNull vrt::BasicVRTPacket::isControlAckMode () const [virtual]
Command packets only: Gets the Control/Ack Mode (ACK).
This indicates if a command packet is a Control or Ack subtype:
    true  = Ack subtype
    false = Control subtype
    null  = Error: not a command packet
Returns:
true or false as indicated above or null if this is not a command packet.
bool vrt::BasicVRTPacket::isData () const
Is the packet type a data packet?
virtual bool vrt::BasicVRTPacket::isNullValue () const [inline, virtual]
Is this object equal to null.
Reimplemented from vrt::VRTObject.
References bbuf.
bool vrt::BasicVRTPacket::isPacketValid (int32_t length) const [inline]
Checks to see if the packet is valid.
This method adds an extra length check onto the basic checks performed by isPacketValid(). The most common use for this method is to verify that a packet read from a socket matches the length expected.
Parameters:
length Verifies that the length of the packet matches this value.
Returns:
true if it is valid, false otherwise.
References getPacketValid().
bool vrt::BasicVRTPacket::isPacketValid () const [inline]
Checks to see if the packet is valid.
This checks the overall structure of the packet (i.e. length is correct, reserved bits set to 0, etc.). It does not check the content of the packet or the validity of the data in the packet (the state and event indicators are provided for that purpose).
Returns:
true if it is valid, false otherwise.
References getPacketValid().
virtual boolNull vrt::BasicVRTPacket::isSpectrumMode () const [virtual]
Data packets only: Gets the Signal Spectrum Data Mode (S).
This indicates if a data packet is used to convey Signal Spectrum Data.
    true  = Signal Data Packet contains spectral or frequency domain data.
    false = Signal Data Packet contains time domain data.
    null  = Error: not a data packet
Returns:
true or false as indicated above or null if this is a data packet.
virtual boolNull vrt::BasicVRTPacket::isTimeStampMode () const [virtual]
Context packets only: Gets the Time Stamp Mode (TSM).
This indicates if a context packet is being used to convey timing of context events related to the signal with fine or coarse resolution:
    true  = Time stamp fields indicate *precise* timing of context changes (to the
            resolution of the system)
    false = Time stamp fields indicate *general* timing of the context changes (i.e.
            the change occurred within the time interval covered by this packet)
    null  = Error: not a context packet
Returns:
true or false as indicated above or null if this is a data packet.
void vrt::BasicVRTPacket::packPayloadAscii (int32_t off, string val, int32_t len) [inline, protected]
Packs an ASCII string into the payload of the packet.
References bbuf, getPrologueLength(), vrt::VRTMath::packAscii(), and setPayloadLength().
Referenced by vrt::ReferencePointPacket::setName(), and vrt::EphemerisPacket::setProducedBy().
void vrt::BasicVRTPacket::packPayloadBoolean (int32_t off, bool val) [inline, protected]
Packs a boolean value into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packBoolean().
void vrt::BasicVRTPacket::packPayloadBoolNull (int32_t off, boolNull val) [inline, protected]
Packs a boolNull value into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packBoolNull().
void vrt::BasicVRTPacket::packPayloadByte (int32_t off, char val) [inline, protected]
Packs an 8-bit integer into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packByte().
Referenced by vrt::EphemerisPacket::setAccFixType(), vrt::StreamStatePacket::setAggregateSystemStatus(), vrt::EphemerisPacket::setAttFixType(), vrt::StreamStatePacket::setInputStatus(), vrt::StreamStatePacket::setInternalStatus(), vrt::StreamStatePacket::setOutputStatus(), vrt::EphemerisPacket::setPosFixType(), vrt::StreamStatePacket::setSystemState(), and vrt::EphemerisPacket::setVelFixType().
void vrt::BasicVRTPacket::packPayloadBytes (int32_t off, const void * val, int32_t len) [inline, protected]
Packs a block of bytes into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packBytes().
void vrt::BasicVRTPacket::packPayloadBytes (int32_t off, const vector< char > & val, int32_t len) [inline, protected]
Packs a block of bytes into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packBytes().
void vrt::BasicVRTPacket::packPayloadDouble (int32_t off, double val) [inline, protected]
Packs a 64-bit floating-point value into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packDouble().
void vrt::BasicVRTPacket::packPayloadFloat (int32_t off, float val) [inline, protected]
Packs a 32-bit floating-point value into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packFloat().
void vrt::BasicVRTPacket::packPayloadInetAddr (int32_t off, InetAddress val) [inline, protected]
Packs a InetAddress into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packInetAddr().
void vrt::BasicVRTPacket::packPayloadInt (int32_t off, int32_t val) [inline, protected]
Packs a 32-bit integer into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packInt().
Referenced by vrt::ReferencePointPacket::setRefPointID().
void vrt::BasicVRTPacket::packPayloadLong (int32_t off, int64_t val) [inline, protected]
Packs a 64-bit integer into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packLong().
Referenced by vrt::EphemerisPacket::setFixDelta(), and vrt::TimestampAccuracyPacket::setTimestampAccuracy().
void vrt::BasicVRTPacket::packPayloadMetadata (int32_t off, MetadataBlock val, int32_t len) [inline, protected]
Packs a metadata block into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packMetadata().
void vrt::BasicVRTPacket::packPayloadRecord (int32_t off, Record val) [inline, protected]
Packs a record value into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packRecord().
void vrt::BasicVRTPacket::packPayloadShort (int32_t off, int16_t val) [inline, protected]
Packs a 16-bit integer into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packShort().
void vrt::BasicVRTPacket::packPayloadTimeStamp (int32_t off, TimeStamp val, IntegerMode epoch) [inline, protected]
Packs a TimeStamp into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packTimeStamp().
Referenced by vrt::EphemerisPacket::setFixTime().
void vrt::BasicVRTPacket::packPayloadUTF8 (int32_t off, string val, int32_t len) [inline, protected]
Packs a UTF-8 string into the payload of the packet.
References bbuf, getPrologueLength(), vrt::VRTMath::packUTF8(), and setPayloadLength().
void vrt::BasicVRTPacket::packPayloadUTF8 (int32_t off, wstring val, int32_t len) [inline, protected]
Packs a UTF-8 string into the payload of the packet.
References bbuf, getPrologueLength(), vrt::VRTMath::packUTF8(), and setPayloadLength().
Referenced by vrt::ReferencePointPacket::setDescription(), and vrt::StreamStatePacket::setMessage().
void vrt::BasicVRTPacket::packPayloadUUID (int32_t off, UUID val) [inline, protected]
Packs a UUID into the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::packUUID().
bool vrt::BasicVRTPacket::payloadEquals (const BasicVRTPacket & p) const
Checks for payload equality with another BasicVRTPacket.
The payloads of two VRT packets are considered equal if the content of the payloads is bit-for-bit identical. The contents of the prologue and trailer need not be equal for this method to return true. However, any two packets for which equals returns true, must have this method return true as well. This will always return false if the tqo packets have different payload lengths.
Parameters:
p The other packet.
Returns:
true if they are identical, false otherwise. (This will always returns false if the packet is null.)
bool vrt::BasicVRTPacket::pktSpecificPrologueEquals (const BasicVRTPacket & p) const
Checks for packet specific prologue (PSP) equality with another BasicVRTPacket.
The PSPs of two VRT packets are considered equal if the content of the PSPs is bit-for-bit identical. The contents of the payload and trailer need not be equal for this method to return true. However, any two packets for which equals returns true, must have this method return true as well.
Parameters:
p The other packet.
Returns:
true if they are identical, false otherwise. (This will always returns false if the packet is null.)
bool vrt::BasicVRTPacket::prologueEquals (const BasicVRTPacket & p) const
Checks for prologue equality with another BasicVRTPacket.
The prologues of two VRT packets are considered equal if the content of the prologues is bit-for-bit identical. The contents of the payload and trailer need not be equal for this method to return true. However, any two packets for which equals returns true, must have this method return true as well.
Parameters:
p The other packet.
Returns:
true if they are identical, false otherwise. (This will always returns false if the packet is null.)
int32_t vrt::BasicVRTPacket::readPacket (void * buffer, int32_t poff, int32_t len) const
Reads the packet payload into the provided buffer.
Parameters:
buffer The buffer to read into.
poff The payload offset to start reading from.
len The maximum length to read in.
Returns:
The number of bytes read or -1 if the end of the payload has been reached.
int32_t vrt::BasicVRTPacket::readPayload (void * buffer, int32_t poff, int32_t len) const
Reads the packet payload into the provided buffer.
Parameters:
buffer The buffer to read into.
poff The payload offset to start reading from.
len The maximum length to read in.
Returns:
The number of bytes read or -1 if the end of the payload has been reached.
virtual bool vrt::BasicVRTPacket::resetForResend (const TimeStamp & t) [virtual]
Prepares a packet for resend resetting any non-persistent values and clearing the context change flags.
At a minimum this will update the time stamp. This is implemented as follows:
    bool BasicVRTPacket::resetForResend (const TimeStamp &t) {
      setTimeStamp(t);
      return false;
    }
Parameters:
t The new time stamp.
Returns:
true if non-persistent values and the change flags have been reset, false if only the time stamp has been updated.
Reimplemented in vrt::BasicContextPacket.
virtual void vrt::BasicVRTPacket::setCancelMode (bool v) [virtual]
Optional functionality: Command packets only: Gets the Cancel Mode (L).
Parameters:
v The new value, see isCancelMode() for details.
Exceptions:
VRTException If this method is not supported or if the packet type doesn't support this setting.
virtual void vrt::BasicVRTPacket::setClassID (string v) [virtual]
Optional functionality: Sets the packet class identifier.
Parameters:
v The packet class identifier or null if not specified.
Exceptions:
VRTException If this method is not supported.
VRTException If the value passed in is invalid.
virtual void vrt::BasicVRTPacket::setClassIdentifier (int32_t oui, int16_t icc, int16_t pcc) [virtual]
Optional functionality: Sets the packet class identifier.
Parameters:
oui The new OUI value.
icc The new ICC value.
pcc The new PCC value.
Exceptions:
VRTException If this method is not supported.
VRTException If the value passed in is invalid.
virtual void vrt::BasicVRTPacket::setClassIdentifier (int64_t v) [virtual]
Optional functionality: Sets the packet class identifier.
See getClassIdentifier() for details.
Parameters:
v The packet class identifier or INT64_NULL if not specified.
Exceptions:
VRTException If this method is not supported.
VRTException If the value passed in is invalid.
virtual void vrt::BasicVRTPacket::setControlAckMode (bool v) [virtual]
Optional functionality: Command packets only: Sets the Control/Ack Mode (ACK).
Parameters:
v The new value, see isControlAckMode() for details.
Exceptions:
VRTException If this method is not supported or if the packet type doesn't support this setting.
virtual void vrt::BasicVRTPacket::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::HasFields.
Reimplemented in vrt::BasicContextPacket, vrt::BasicDataPacket, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
static void vrt::BasicVRTPacket::setPacketCount (void * ptr, int32_t v) [static]
Internal Use Only: Sets the packet count.
This is the modulo-16 count of all packets on this stream.
Parameters:
ptr Pointer to the packet content.
v The packet count (0..15).
Exceptions:
VRTException If the value passed in is invalid.
virtual void vrt::BasicVRTPacket::setPacketCount (int32_t v) [virtual]
Optional functionality: Sets the packet count.
This is the modulo-16 count of all packets on this stream.
Parameters:
v The packet count (0..15).
Exceptions:
VRTException If this method is not supported.
VRTException If the value passed in is invalid.
void vrt::BasicVRTPacket::setPacketLength (int32_t v) [protected]
Internal use only: Sets the packet length.
virtual void vrt::BasicVRTPacket::setPacketType (PacketType t) [virtual]
Optional functionality: Sets the packet type.
Parameters:
t The packet type.
Exceptions:
VRTException If this method is not supported.
Reimplemented in vrt::BasicAcknowledgePacket, vrt::BasicCommandPacket, vrt::BasicContextPacket, vrt::BasicControlPacket, vrt::BasicDataPacket, and vrt::BasicQueryAcknowledgePacket.
virtual void vrt::BasicVRTPacket::setPadBitCount (int32_t bits, int32_t bitsPerSample) [virtual]
Optional functionality: Sets the number of pad bits inserted following the data in the payload such that the payload section is always a multiple of 4-bytes in length (see getPadBitCount() for a detailed discussion about the reporting of pad bits).
This function will *not* alter the packet if the number of pad bits is implicit (or zero) when in strict VITA-49.0 (rather than VITA-49.0b) mode.
Note: It is not possible to report the number of pad bits if the ClassID is not set. If this function is called with a non-zero value, the number of pad bits is not implicit and the ClassID is not set, an exception will be thrown.
Assuming this method is supported, it is safe to call this method on a non-data packet with a value of zero.
In most cases, this method should not be called directly (except to clear it by setting a value of zero); rather this should be called by BasicDataPacket#setDataLength(int32_t).
Parameters:
bits The number of pad bits to report.
bitsPerSample Number of bits per sample. This is used to determine if the number of pad bits is implicit. Note the value of bitsPerSample is irrelevant when bits is zero, therefore users can just call setPadBitCount(0,0) to set the field to zero (where applicable).
See also:
setPayloadLength(int32_t)
BasicDataPacket::setDataLength(int32_t)
Exceptions:
VRTException If this method is not supported.
VRTException If this method is called with a non-zero value for a non-data packet or if the number of bits is not implicit and the ClassID is not set.
void vrt::BasicVRTPacket::setPayload (void * buffer, int32_t length) [inline]
Optional functionality: Sets the content of the packet payload and updates the length of the payload.
Parameters:
buffer The new payload.
length The number of bytes to copy from the buffer into the payload.
Exceptions:
VRTException If this method is not supported
References setPayloadLength(), and writePayload().
void vrt::BasicVRTPacket::setPayload (vector< char > buffer) [inline]
Optional functionality: Sets the content of the packet payload and updates the length of the payload.
Parameters:
buffer The new payload.
Exceptions:
VRTException If this method is not supported
virtual void vrt::BasicVRTPacket::setPayloadLength (int32_t v) [virtual]
Optional functionality: Sets the payload length in bytes.
The packet length is recomputed and trailer is shifted as required. The payload length must be a multiple of 4-bytes.
Parameters:
v The length of the payload in bytes.
Exceptions:
VRTException If this method is not supported.
VRTException If the value passed in is invalid.
Referenced by packPayloadAscii(), packPayloadUTF8(), vrt::ReferencePointPacket::setDescription(), vrt::StreamStatePacket::setMessage(), and setPayload().
virtual void vrt::BasicVRTPacket::setSpectrumMode (bool v) [virtual]
Optional functionality: Data packets only: Sets the Signal Spectrum Data Mode (S).
Parameters:
v The new value, see isSpectrumMode() for details.
Exceptions:
VRTException If this method is not supported or if the packet type doesn't support this setting.
static void vrt::BasicVRTPacket::setStateEventBit (vector< char > & buf, int32_t off, int32_t enable, int32_t indicator, boolNull value) [static, protected]
Optional functionality: Sets the specified bit from the trailer.
By default all of the "set" methods that access the trailer call this method with the appropriate bit values (see getStateEventBit for a list).
Parameters:
buf The data buffer.
off The offset into the data buffer.
enable Bit position of the enable flag.
indicator Bit position of the indicator flag.
value The value of the bits: null if the enable bit should not be set, true if the enable bit and the indicator bit should be set, false if the enable bit should be set but the indicator bit should not be set.
virtual void vrt::BasicVRTPacket::setStreamID (string v) [virtual]
Optional functionality: Sets the 32-bit packet stream identifier.
Parameters:
v The stream identifier or null if not specified.
Exceptions:
VRTException If this method is not supported.
virtual void vrt::BasicVRTPacket::setStreamIdentifier (int32_t v) [virtual]
Optional functionality: Sets the 32-bit packet stream identifier.
Parameters:
v The stream identifier or INT4_NULL if not specified.
Exceptions:
VRTException If this method is not supported.
virtual void vrt::BasicVRTPacket::setTimeStamp (const TimeStamp & v) [virtual]
Optional functionality: Sets the time stamp for the packet.
Parameters:
v The new time stamp.
Exceptions:
VRTException If this method is not supported.
virtual void vrt::BasicVRTPacket::setTimeStampMode (bool v) [virtual]
Optional functionality: Context packets only: Sets the Time Stamp Mode (TSM).
Parameters:
v The new value, see isTimeStampMode() for details.
Exceptions:
VRTException If this method is not supported or if the packet type doesn't support this setting.
void vrt::BasicVRTPacket::shiftHeader (int32_t field, int32_t bytes, bool present) [protected]
Internal use only: Shifts the header.
Creates or removes space for values in header.
Parameters:
field bit field used to identify if field is currently included and the offset based on other fields that may be present.
bytes size of value to be included or removed.
present true if need space to store value associated with field, false if the value is not present in header.
int32_t vrt::BasicVRTPacket::shiftPacketSpecificPrologue (int32_t off, int32_t bytes, bool add) [protected]
Internal use only: Shifts the packet specific prologue (PSP).
Insert or remove bytes at given offset.
Parameters:
off Offset w/in PSP to insert/remove bytes. off>=0 indicates value exists already, while off<0 indicates it is not present.
bytes Non-negative number of bytes to insert or remove.
add Indicates whether to add or remove bytes. Nothing is done if True and value exists, or if False and value is not present.
Returns:
Non-negative value of off param, regardless of action taken (or not taken).
int32_t vrt::BasicVRTPacket::shiftPayload (int32_t off, int32_t bytes, bool add) [protected]
Internal use only: Shifts the payload.
Insert or remove bytes at given offset.
Parameters:
off Offset w/in payload to insert/remove bytes. off>=0 indicates value exists already, while off<0 indicates it is not present.
bytes Non-negative number of bytes to insert or remove.
add Indicates whether to add or remove bytes. Nothing is done if True and value exists, or if False and value is not present.
Returns:
Non-negative value of off param, regardless of action taken (or not taken).
void vrt::BasicVRTPacket::shiftTrailer (bool add) [protected]
Internal use only: Shifts the trailer.
Add or removes trailer of size MAX_TRAILER_LENGTH.
Parameters:
add Indicates whether to add or remove trailer. If add is false, removes trailer from the packet and unsets the Trailer bit in the header. If add is true, increases packet by MAX_TRAILER_LENGTH and sets Trailer bit in header.
void vrt::BasicVRTPacket::swap (BasicVRTPacket * pkt) [inline]
Internal Use Only: Does a buffer swap.
References bbuf, and readOnly.
void vrt::BasicVRTPacket::swap (vector< char > * buffer) [inline]
Internal Use Only: Does a buffer swap.
References bbuf, and readOnly.
virtual string vrt::BasicVRTPacket::toString () const [virtual]
Converts this class its string form.
Reimplemented from vrt::VRTObject.
virtual void vrt::BasicVRTPacket::toStringStream (ostringstream & str) const [protected, virtual]
Writes the packet content to a string stream in a user-friendly format.
Parameters:
str The string stream to write to.
Reimplemented in vrt::BasicAcknowledgePacket, vrt::BasicCommandPacket, vrt::BasicContextPacket, vrt::BasicControlPacket, vrt::BasicDataPacket, vrt::BasicQueryAcknowledgePacket, vrt::StandardDataPacket, vrt::EphemerisPacket, vrt::NoDataPacket, vrt::ReferencePointPacket, vrt::StandardContextPacket, vrt::StreamStatePacket, and vrt::TimestampAccuracyPacket.
bool vrt::BasicVRTPacket::trailerEquals (const BasicVRTPacket & p, bool exact) const
Checks for trailer equality with another BasicVRTPacket.
This method allows two different interpretations of trailer equality:
Exact: With "exact" equality, the trailers of two VRT packets are considered equal if the content of the trailers is either bit-for-bit identical, or if both packets omit the trailers.
Equal: With "equal" equality, the trailers of two VRT packets are considered equal if the content of the trailers conveys the same meaning. Conveying the same meaning means that the enable bits in the trailer are checked first. Any values not enabled, are ignored when comparing. In this form, a packet with no trailer is considered equal to a packet with a trailer that has nothing enabled.
Regardless of the comparison used, any two packets for which equals returns true, must have this method return true as well. This method will always return true if comparing two context packets since they do not contain trailers.
Parameters:
p The other packet.
exact true to use the Exact comparison, false to use the Equal comparison.
Returns:
true if they are identical, false otherwise. (This will always returns false if the packet is null.)
bool vrt::BasicVRTPacket::trailerEquals (const BasicVRTPacket & p) const [inline]
Checks for trailer equality with another BasicVRTPacket.
This method is identical to trailerEquals(p,true). In most cases, use of trailerEquals(p,false) is more appropriate for comparing trailers.
Parameters:
p The other packet.
Returns:
true if they are identical, false otherwise. (This will always returns false if the packet is null.)
string vrt::BasicVRTPacket::unpackPayloadAscii (int32_t off, int32_t len) const [inline, protected]
Unpacks an ASCII string from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackAscii().
Referenced by vrt::ReferencePointPacket::getName(), and vrt::EphemerisPacket::getProducedBy().
bool vrt::BasicVRTPacket::unpackPayloadBoolean (int32_t off) const [inline, protected]
Unpacks a boolean value from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackBoolean().
boolNull vrt::BasicVRTPacket::unpackPayloadBoolNull (int32_t off) const [inline, protected]
Unpacks a boolNull value from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackBoolNull().
char vrt::BasicVRTPacket::unpackPayloadByte (int32_t off) const [inline, protected]
Unpacks an 8-bit integer from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackByte().
Referenced by vrt::EphemerisPacket::getAccFixType(), vrt::StreamStatePacket::getAggregateSystemStatus(), vrt::EphemerisPacket::getAttFixType(), vrt::StreamStatePacket::getInputStatus(), vrt::StreamStatePacket::getInternalStatus(), vrt::StreamStatePacket::getOutputStatus(), vrt::EphemerisPacket::getPosFixType(), vrt::StreamStatePacket::getSystemState(), and vrt::EphemerisPacket::getVelFixType().
void* vrt::BasicVRTPacket::unpackPayloadBytes (int32_t off, void * val, int32_t len) const [inline, protected]
Unpacks a block of bytes from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackBytes().
vector<char> vrt::BasicVRTPacket::unpackPayloadBytes (int32_t off, int32_t len) const [inline, protected]
Unpacks a block of bytes from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackBytes().
double vrt::BasicVRTPacket::unpackPayloadDouble (int32_t off) const [inline, protected]
Unpacks a 64-bit floating-point value from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackDouble().
float vrt::BasicVRTPacket::unpackPayloadFloat (int32_t off) const [inline, protected]
Unpacks a 32-bit floating-point value from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackFloat().
InetAddress vrt::BasicVRTPacket::unpackPayloadInetAddr (int32_t off) const [inline, protected]
Unpacks a InetAddress from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackInetAddr().
int32_t vrt::BasicVRTPacket::unpackPayloadInt (int32_t off) const [inline, protected]
Unpacks a 32-bit integer from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackInt().
Referenced by vrt::ReferencePointPacket::getRefPointID().
int64_t vrt::BasicVRTPacket::unpackPayloadLong (int32_t off) const [inline, protected]
Unpacks a 64-bit integer from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackLong().
Referenced by vrt::EphemerisPacket::getFixDelta(), and vrt::TimestampAccuracyPacket::getTimestampAccuracy().
MetadataBlock vrt::BasicVRTPacket::unpackPayloadMetadata (int32_t off, int32_t len) const [inline, protected]
Unpacks a metadata block from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackMetadata().
void vrt::BasicVRTPacket::unpackPayloadRecord (int32_t off, Record & rec) const [inline, protected]
Unpacks a record from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackRecord().
Referenced by vrt::BasicContextPacket::get3DPointingVectorStructured(), vrt::BasicContextPacket::getCIFsArray(), vrt::BasicContextPacket::getContextAssocLists(), vrt::BasicContextPacket::getEphemeris(), vrt::BasicContextPacket::getGeolocation(), vrt::BasicContextPacket::getGeoSentences(), vrt::BasicContextPacket::getIndexList(), vrt::BasicContextPacket::getSectorScanStep(), and vrt::BasicContextPacket::getSpectrumField().
int16_t vrt::BasicVRTPacket::unpackPayloadShort (int32_t off) const [inline, protected]
Unpacks a 16-bit integer from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackShort().
TimeStamp vrt::BasicVRTPacket::unpackPayloadTimeStamp (int32_t off, IntegerMode epoch) const [inline, protected]
Unpacks a TimeStamp from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackTimeStamp().
Referenced by vrt::EphemerisPacket::getFixTime().
wstring vrt::BasicVRTPacket::unpackPayloadUTF8 (int32_t off, int32_t len) const [inline, protected]
Unpacks a UTF-8 string from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackUTF8().
Referenced by vrt::ReferencePointPacket::getDescription(), and vrt::StreamStatePacket::getMessage().
UUID vrt::BasicVRTPacket::unpackPayloadUUID (int32_t off) const [inline, protected]
Unpacks a UUID from the payload of the packet.
References bbuf, getPrologueLength(), and vrt::VRTMath::unpackUUID().
void vrt::BasicVRTPacket::writePayload (void * buffer, int32_t poff, int32_t len)
Optional functionality: Writes to the packet payload, but does NOT update the length of the payload.
Parameters:
buffer The buffer to with the new data.
poff The payload offset to start writing to.
len The length to write.
Exceptions:
VRTException If this method is not supported or if there is insufficient room to write to.
Referenced by setPayload().
Member Data Documentation
vector<char> vrt::BasicVRTPacket::bbuf
Packet buffer (always includes the header).
Referenced by vrt::BasicContextPacket::getContextIndicatorField0(), vrt::BasicDataPacket::getDataByte(), vrt::BasicDataPacket::getDataDouble(), vrt::BasicDataPacket::getDataFloat(), vrt::BasicDataPacket::getDataInt(), vrt::BasicDataPacket::getDataLong(), vrt::BasicDataPacket::getDataShort(), getPacketLength(), isNullValue(), packPayloadAscii(), packPayloadBoolean(), packPayloadBoolNull(), packPayloadByte(), packPayloadBytes(), packPayloadDouble(), packPayloadFloat(), packPayloadInetAddr(), packPayloadInt(), packPayloadLong(), packPayloadMetadata(), packPayloadRecord(), packPayloadShort(), packPayloadTimeStamp(), packPayloadUTF8(), packPayloadUUID(), vrt::BasicDataPacket::setDataByte(), vrt::BasicDataPacket::setDataDouble(), vrt::BasicDataPacket::setDataFloat(), vrt::BasicDataPacket::setDataInt(), vrt::BasicDataPacket::setDataLong(), vrt::BasicDataPacket::setDataShort(), swap(), unpackPayloadAscii(), unpackPayloadBoolean(), unpackPayloadBoolNull(), unpackPayloadByte(), unpackPayloadBytes(), unpackPayloadDouble(), unpackPayloadFloat(), unpackPayloadInetAddr(), unpackPayloadInt(), unpackPayloadLong(), unpackPayloadMetadata(), unpackPayloadRecord(), unpackPayloadShort(), unpackPayloadTimeStamp(), unpackPayloadUTF8(), and unpackPayloadUUID().
const int32_t vrt::BasicVRTPacket::MAX_HEADER_LENGTH = 7*4 [static]
The maximum length of the header in bytes (all optional fields included).
Note that in cases where optional fields are not included, the header will be shorter.
    MAX_HEADER_LENGTH = 7*4
See also:
getHeaderLength()
const int32_t vrt::BasicVRTPacket::MAX_PACKET_LENGTH = 65536*4 [static]
The maximum length of the packet in bytes (header + payload + trailer).
Note that this is the absolute limit imposed by the VRT specification. The underlying transport protocols used (e.g. IP, UDP, TCP, etc.) have limits lower than this.
    MAX_PACKET_LENGTH = 65536*4
See also:
getPacketLength()
const int32_t vrt::BasicVRTPacket::MAX_PAYLOAD_LENGTH = MAX_PACKET_LENGTH - MAX_PROLOGUE_LENGTH - MAX_TRAILER_LENGTH [static]
The de-facto maximum length of the payload in bytes.
Note that the de-jure limit can be up to 28 bytes more than this when optional fields in the header, packet specific prologue, and trailer are dropped. In practice this difference is nearly meaningless since (as noted with MAX_PACKET_LENGTH) this value exceeds the limits of the underlying transport protocols.
    MAX_PAYLOAD_LENGTH = MAX_PACKET_LENGTH - MAX_PROLOGUE_LENGTH - MAX_TRAILER_LENGTH
See also:
getPayloadLength()
Referenced by vrt::ReferencePointPacket::setDescription(), and vrt::StreamStatePacket::setMessage().
const int32_t vrt::BasicVRTPacket::MAX_PKT_SPECIFIC_PROLOGUE_LENGTH = 10*4 [static]
The maximum length of the packet specific prologue (PSP) in bytes (all optional fields included).
Note that in cases where optional fields are not included, the PSP will be shorter.
    MAX_PKT_SPECIFIC_PROLOGUE_LENGTH = 10*4
See also:
getPktSpecificPrologueLength()
const int32_t vrt::BasicVRTPacket::MAX_PROLOGUE_LENGTH = MAX_HEADER_LENGTH + MAX_PKT_SPECIFIC_PROLOGUE_LENGTH [static]
The maximum length of the prologue in bytes (all optional fields included).
Note that in cases where optional fields are not included, the prologue will be shorter.
    MAX_PROLOGUE_LENGTH = MAX_HEADER_LENGTH + MAX_PKT_SPECIFIC_PROLOGUE_LENGTH
See also:
getPrologueLength()
const int32_t vrt::BasicVRTPacket::MAX_TRAILER_LENGTH = 1*4 [static]
The maximum length of the trailer in bytes.
    MAX_TRAILER_LENGTH = 1*4
See also:
getTrailerLength()
const BasicVRTPacket vrt::BasicVRTPacket::NULL_PACKET [static]
Represents a null VRT packet.
bool vrt::BasicVRTPacket::readOnly [protected]
Is this instance read-only?
Referenced by swap().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/BasicVRTPacket.h