VRT: vrt::Socket Class Reference
vrt::Socket Class Reference
Internal Use Only: Class to hold a BSD-style socket with accompanying information.
#include <NetUtilities.h>
Public Member Functions
~Socket ()
Destructor.
Socket * accept (map< string, string > &options)
Accepts a new TCP client connection.
void close ()
Closes the socket.
int32_t getMTU () const
Internal Use Only: Gets the MTU applicable for the socket.
TransportProtocol getTransportProtocol () const
What type of socket is this?
virtual bool isNullValue () const
Is this object equal to null.
bool isOpen () const
Is the socket open?
int32_t read (void *buf, size_t len)
Reads data from the socket.
int32_t read (void *buf, int32_t len)
Reads data from the socket.
void shutdownSocket ()
Stops the socket's i/o but does not close it.
virtual string toString () const
Converts this class its string form.
int32_t write (const void *buf, size_t len)
Writes data to the socket.
int32_t write (const void *buf, int32_t len)
Writes data to the socket.
Static Public Member Functions
static Socket * createTCPServerSocket (bool isOutput, const string &host, int32_t port, const string &device, map< string, string > &options, int32_t bufLength)
Creates a new TCP Server socket.
static Socket * createTCPSocket (bool isOutput, const string &host, int32_t port, const string &device, map< string, string > &options, int32_t bufLength)
Creates a new TCP (Client) socket.
static Socket * createUDPSocket (bool isOutput, const string &host, int32_t port, const string &device, map< string, string > &options, int32_t bufLength)
Creates a new UDP datagram socket.
Detailed Description
Internal Use Only: Class to hold a BSD-style socket with accompanying information.
Note that this class does NOT have a copy constructor. This is because the destructor for the class calls close() and because permitting copies may cause consistency problem in the socket interactions.
Constructor & Destructor Documentation
vrt::Socket::~Socket ()
Destructor.
Member Function Documentation
Socket* vrt::Socket::accept (map< string, string > & options)
Accepts a new TCP client connection.
Parameters:
options Map of options to set (can be null). See top of NetUtilities for details.
Returns:
The new client socket or null if no connection is available within the time set by SO_TIMEOUT.
Exceptions:
VRTException If this is not a TCP_SERVER socket or if an i/o error occurs.
void vrt::Socket::close ()
Closes the socket.
This function is safe to call multiple times.
static Socket* vrt::Socket::createTCPServerSocket (bool isOutput, const string & host, int32_t port, const string & device, map< string, string > & options, int32_t bufLength) [static]
Creates a new TCP Server socket.
Parameters:
isOutput Is this socket being created for output (true) or input (false)?
host The host to connect to (null = wildcard address).
port The port number.
device The device to connect to (e.g. "eth0", "eth1.101") (null = use default).
options Map of options to set (can be null). See top of NetUtilities for details.
bufLength The buffer length in bytes.
Returns:
The socket.
Exceptions:
VRTException If an I/O error occurs.
static Socket* vrt::Socket::createTCPSocket (bool isOutput, const string & host, int32_t port, const string & device, map< string, string > & options, int32_t bufLength) [static]
Creates a new TCP (Client) socket.
Parameters:
isOutput Is this socket being created for output (true) or input (false)?
host The host to connect to (null = wildcard address).
port The port number.
device The device to connect to (e.g. "eth0", "eth1.101") (null = use default).
options Map of options to set (can be null). See top of NetUtilities for details.
bufLength The buffer length in bytes.
Returns:
The socket.
Exceptions:
VRTException If an I/O error occurs.
static Socket* vrt::Socket::createUDPSocket (bool isOutput, const string & host, int32_t port, const string & device, map< string, string > & options, int32_t bufLength) [static]
Creates a new UDP datagram socket.
Parameters:
isOutput Is this socket being created for output (true) or input (false)?
host The host to connect to (null = wildcard address).
port The port number.
device The device to connect to (e.g. "eth0", "eth1.101") (null = use default).
options Map of options to set (can be null). See top of NetUtilities for details.
bufLength The buffer length in bytes.
Returns:
The socket.
Exceptions:
VRTException If an I/O error occurs.
int32_t vrt::Socket::getMTU () const [inline]
Internal Use Only: Gets the MTU applicable for the socket.
TransportProtocol vrt::Socket::getTransportProtocol () const [inline]
What type of socket is this?
virtual bool vrt::Socket::isNullValue () const [inline, virtual]
Is this object equal to null.
Reimplemented from vrt::VRTObject.
bool vrt::Socket::isOpen () const [inline]
Is the socket open?
int32_t vrt::Socket::read (void * buf, size_t len) [inline]
Reads data from the socket.
If this is a UDP socket, this will receive a complete datagram (up to the given length) and will return the length. If this is a TCP client socket this will attempt to read in the specified number of octets.
Parameters:
buf The buffer to receive the data. (OUTPUT)
len The length of the buffer.
Returns:
The number of octets received. Returns 0 on a timeout and -1 on EOF.
Exceptions:
VRTException If this is a TCP_SERVER socket or if an i/o error occurs.
References read().
int32_t vrt::Socket::read (void * buf, int32_t len)
Reads data from the socket.
If this is a UDP socket, this will receive a complete datagram (up to the given length) and will return the length. If this is a TCP client socket this will attempt to read in the specified number of octets.
Parameters:
buf The buffer to receive the data. (OUTPUT)
len The length of the buffer.
Returns:
The number of octets received. Returns 0 on a timeout and -1 on EOF.
Exceptions:
VRTException If this is a TCP_SERVER socket or if an i/o error occurs.
Referenced by read().
void vrt::Socket::shutdownSocket ()
Stops the socket's i/o but does not close it.
This will stop the low-level socket from receiving any more data, but will still permit reads until the low-level buffers are empty. Following a call to this, a call to read for which there is no data will return EOF rather than 0.
virtual string vrt::Socket::toString () const [virtual]
Converts this class its string form.
Reimplemented from vrt::VRTObject.
int32_t vrt::Socket::write (const void * buf, size_t len) [inline]
Writes data to the socket.
If this is a UDP socket, this will transmit a complete datagram. If this is a TCP client socket this will write the data to the stream.
Parameters:
buf The buffer to receive the data. (INPUT)
len The length of the buffer.
Returns:
The number of octets sent. Returns 0 on a timeout and -1 on EOF.
Exceptions:
VRTException If this is a TCP_SERVER socket or if an i/o error occurs.
References write().
int32_t vrt::Socket::write (const void * buf, int32_t len)
Writes data to the socket.
If this is a UDP socket, this will transmit a complete datagram. If this is a TCP client socket this will write the data to the stream.
Parameters:
buf The buffer to receive the data. (INPUT)
len The length of the buffer.
Returns:
The number of octets sent. Returns 0 on a timeout and -1 on EOF.
Exceptions:
VRTException If this is a TCP_SERVER socket or if an i/o error occurs.
Referenced by write().
The documentation for this class was generated from the following file:
cpp_src/vrt/net/NetUtilities.h