VRT: vrt::InetAddress Class Reference
vrt::InetAddress Class Reference
An IPv4 or IPv6 Internet address.
#include <InetAddress.h>
Public Member Functions
InetAddress (const struct in6_addr &addr)
Creates a new instance, using the specified address.
InetAddress (const struct in_addr &addr)
Creates a new instance, using the specified address.
InetAddress (const void *addr, size_t off, size_t len)
Creates a new instance, using the specified address from a buffer.
InetAddress (const vector< char > &addr, size_t off=0)
Creates a new instance, using the specified address from a buffer.
InetAddress (const char *addr)
Creates a new instance, using an address given as a string.
InetAddress (const string &addr)
Creates a new instance, using an address given as a string.
InetAddress (const InetAddress &addr)
Copy constructor.
InetAddress ()
Basic no-argument constructor.
~InetAddress ()
Destructor.
virtual bool equals (const InetAddress &addr) const
Checks to see if two addresses are equal.
virtual bool equals (const VRTObject &o) const
Checks to see if two addresses are equal.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
virtual string getHostAddress () const
Converts the address to a string.
virtual bool isIPv4 () const
Is this an IPv4 address?
virtual bool isMulticastAddress () const
Indicates if the given address is a multicast address.
virtual bool isNullValue () const
An address is considered null if it is set to 0.0.0.0 or ::0.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
virtual void setHostAddress (const char *addr)
Converts a string to an address.
virtual void setHostAddress (const string &addr)
Converts a string to an address.
struct in_addr toIPv4 () const
Gets this address as an IPv4 address.
struct in6_addr toIPv6 () const
Gets this address as an IPv6 address.
virtual string toString () const
Converts the address to a string.
Static Public Member Functions
static InetAddress getLocalHost ()
Gets the local host address (not the loop-back address).
static InetAddress getLoopbackAddress ()
Gets the loop-back address (this will be 127.0.0.1 or ::1).
Detailed Description
An IPv4 or IPv6 Internet address.
Constructor & Destructor Documentation
vrt::InetAddress::~InetAddress () [inline]
Destructor.
vrt::InetAddress::InetAddress ()
Basic no-argument constructor.
vrt::InetAddress::InetAddress (const InetAddress & addr)
Copy constructor.
vrt::InetAddress::InetAddress (const string & addr)
Creates a new instance, using an address given as a string.
vrt::InetAddress::InetAddress (const char * addr)
Creates a new instance, using an address given as a string.
vrt::InetAddress::InetAddress (const vector< char > & addr, size_t off = 0)
Creates a new instance, using the specified address from a buffer.
If off is 0 and the vector size is 4, then a 4-byte IPv4 address is used, otherwise a 16-byte IPv6 address is assumed.
Parameters:
addr The given address.
off The offset into the array.
vrt::InetAddress::InetAddress (const void * addr, size_t off, size_t len)
Creates a new instance, using the specified address from a buffer.
If off is 0 and the vector size is 4, then a 4-byte IPv4 address is used, otherwise a 16-byte IPv6 address is assumed.
Parameters:
addr The given address.
off The offset into the array.
len The length of the address (4=IPv4, 16=IPv6).
vrt::InetAddress::InetAddress (const struct in_addr & addr)
Creates a new instance, using the specified address.
Parameters:
addr The given address.
vrt::InetAddress::InetAddress (const struct in6_addr & addr)
Creates a new instance, using the specified address.
Parameters:
addr The given address.
Member Function Documentation
virtual bool vrt::InetAddress::equals (const InetAddress & addr) const [virtual]
Checks to see if two addresses are equal.
Note that for the purposes of this check "0.0.0.0" and "::0" are considered NOT EQUAL even though both are considered a "null value" (the difference being IPv4 null vs IPv6 null).
Reimplemented from vrt::VRTObject.
virtual bool vrt::InetAddress::equals (const VRTObject & o) const [virtual]
Checks to see if two addresses are equal.
Note that for the purposes of this check "0.0.0.0" and "::0" are considered NOT EQUAL even though both are considered a "null value" (the difference being IPv4 null vs IPv6 null).
virtual Value* vrt::InetAddress::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::HasFields.
virtual int32_t vrt::InetAddress::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::HasFields.
virtual string vrt::InetAddress::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::HasFields.
virtual ValueType vrt::InetAddress::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::HasFields.
virtual string vrt::InetAddress::getHostAddress () const [virtual]
Converts the address to a string.
Referenced by toString().
static InetAddress vrt::InetAddress::getLocalHost () [static]
Gets the local host address (not the loop-back address).
static InetAddress vrt::InetAddress::getLoopbackAddress () [static]
Gets the loop-back address (this will be 127.0.0.1 or ::1).
The choice of IPv4 vs IPv6 is based on the VRT_PREFER_IPV6_ADDRESSES setting (see VRTConfig).
virtual bool vrt::InetAddress::isIPv4 () const [virtual]
Is this an IPv4 address?
virtual bool vrt::InetAddress::isMulticastAddress () const [virtual]
Indicates if the given address is a multicast address.
virtual bool vrt::InetAddress::isNullValue () const [virtual]
An address is considered null if it is set to 0.0.0.0 or ::0.
Reimplemented from vrt::VRTObject.
virtual void vrt::InetAddress::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::HasFields.
virtual void vrt::InetAddress::setHostAddress (const char * addr) [virtual]
Converts a string to an address.
virtual void vrt::InetAddress::setHostAddress (const string & addr) [virtual]
Converts a string to an address.
struct in_addr vrt::InetAddress::toIPv4 () const [inline, read]
Gets this address as an IPv4 address.
If the address is only representable as an IPv6 address, 0.0.0.0 is returned.
struct in6_addr vrt::InetAddress::toIPv6 () const [inline, read]
Gets this address as an IPv6 address.
Referenced by vrt::VRTMath::packInetAddr().
virtual string vrt::InetAddress::toString () const [inline, virtual]
Converts the address to a string.
Reimplemented from vrt::VRTObject.
References getHostAddress().
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/InetAddress.h