VRT: vrt::NetIO Class Reference
vrt::NetIO Class Reference
Internal Use Only: Provides the basic network I/O functions used by both VRTReader and VRTWriter.
#include <NetIO.h>
Classes
class QueuedPacketHandler
Internal Use Only: Handles any packets on the queue.
Public Member Functions
NetIO (bool isOutput, TransportProtocol transport, const string &host, int32_t port, const string &device, VRTEventListener *listener, const map< string, string > &options, int32_t bufLength)
Creates a new instance.
virtual ~NetIO ()
Destructor.
int32_t getActiveConnectionCount ()
Internal Use Only: Gets the number of active connections.
virtual void start ()
Starts the object running in a new thread.
virtual void stop (bool wait=true)
Tells the object to stop running.
virtual string toString () const
Provides a description of the instance useful for debugging.
Protected Member Functions
int32_t _tcpSocketRead (void *buf, int32_t off, int32_t len, bool required)
Read from TCP socket with special handling for socket errors.
bool checkSockets ()
Checks the current sockets, reconnecting as needed.
void clearQueue ()
Pops a packet off of the queue.
void closeClientSockets ()
Closes only the client sockets.
void closeSockets ()
Closes the sockets.
virtual void handle (vector< char > *buffer, int32_t length)
Handles the packet read in.
void openSockets ()
Closes the sockets.
vector< char > * popPacket ()
Pops a packet off of the queue.
void pushPacket (vector< char > *p)
Adds a packet to the processing queue.
void pushPackets (vector< char > *first, vector< vector< char > * > *rest)
Adds a set of packets to the processing queue.
vector< char > * receiveBuffer (bool autoPush)
Reads a single buffer from the input stream.
virtual vector< char > * receiveBufferTCP (bool autoPush)
Receive a packet via UDP.
virtual vector< char > * receiveBufferUDP (bool autoPush)
Receive a packet via UDP.
virtual void reconnect (const VRTEventListener &warnings)
Requests a reconnect and waits for it to be done.
virtual void runInputThread ()
Version of runThread() for an input connection.
virtual void runOutputThread ()
Version of runThread() for an output connection.
virtual void runThread ()
Runs the thread.
void sendBuffer (const void *buf, int32_t len)
Sends the UDP datagram *or* TCP buffer of data.
void sendBuffer (int32_t len)
Sends the UDP datagram *or* TCP buffer of data.
virtual void shutdown ()
Closes any connections, This will always be called at the end of a call to run().
void shutdownClientSockets ()
Shutdown only the client sockets.
void shutdownSockets ()
Stops any future read/write on the sockets, but does not close them.
Protected Attributes
vector< char > buffer
VRTContextListener * ctxListener
Socket * datagramSocket
string device
int32_t doShutdown
VRTEvent event
VRTEventListener * evtListener
int32_t frameCounter
string host
InetAddress hostAddr
bool isOutput
int32_t lengthReadIn
map< int64_t, int32_t > packetCounters
queue< vector< char > * > packetsReadIn
VRTObject packetsReadInLock
int32_t port
QueuedPacketHandler * queuedPacketHandler
int32_t queueLimitOctets
int32_t queueLimitPackets
bool reconnectDone
VRTException reconnectError
bool reconnectNow
map< string, string > socketOptions
int64_t tcpServerCheck
Socket * tcpServerSocket
vector< Socket * > * tcpSockets
TransportProtocol transport
Static Protected Attributes
static vector< char > * BUFFER_PUSHED
Indicates that a buffer was already handled.
Friends
class QueuedPacketHandler
Detailed Description
Internal Use Only: Provides the basic network I/O functions used by both VRTReader and VRTWriter.
Warning: This class is public to support documentation and testing. Users should never access this class directly (even when trying to give a generic "parent" class) as it is subject to change without notice as is the fact that any sub-class extends this class.
Constructor & Destructor Documentation
vrt::NetIO::NetIO (bool isOutput, TransportProtocol transport, const string & host, int32_t port, const string & device, VRTEventListener * listener, const map< string, string > & options, int32_t bufLength)
Creates a new instance.
The options provided to control the socket and connection may include any of the "Socket Creation Options" listed at the top of NetUtilities plus the following:
    INITIAL_TIMEOUT     - The approximate timeout (in seconds) applied when
                          checking for the initial packets. If the complete
                          initial context is not received before the first
                          packet received after this time has elapsed, it
                          will be reported as an error if appropriate). This
                          can also take one of the following special values:
                            -1 = Unlimited wait time.
                            -2 = Use "legacy mode" (pre 2011 version of library)
    QUEUE_LIMIT_PACKETS - Maximum receive queue size in number of packets
                          [Default = 1024]
    QUEUE_LIMIT_OCTETS  - Maximum receive queue size in octets (total of all
                          packets in queue) [Default = 8 MiB]
It is suggested that users start with the default set of options provided by NetUtilities#getDefaultSocketOptions. Starting with an empty map (or simply passing in null) will use the o/s defaults, which may not be ideal for use with VITA-49 streams.
Parameters:
isOutput Is this connection for output (true) or input (false)?
transport The transport being used.
host The host to connect to (null = wildcard address).
port The port number.
device The device to connect to (e.g. "eth0", "eth1.101") (null = use default).
listener The primary listener to use.
options Map of options to set (can be null).
bufLength The buffer length to use.
Exceptions:
VRTException If an I/O execution occurs.
virtual vrt::NetIO::~NetIO () [virtual]
Destructor.
Member Function Documentation
int32_t vrt::NetIO::_tcpSocketRead (void * buf, int32_t off, int32_t len, bool required) [protected]
Read from TCP socket with special handling for socket errors.
Parameters:
buf The buffer to read data into.
off The offset into the buffer.
len The number of octets to read.
required Is this a mandatory read?
Returns:
Output value from the socket read (number of octets read or EOF flag) *or* -999 if the read failed and/or the read had a required length and EOF was reached first.
bool vrt::NetIO::checkSockets () [protected]
Checks the current sockets, reconnecting as needed.
Also connects to any TCP clients.
Returns:
true if processing can continue, false otherwise.
void vrt::NetIO::clearQueue () [protected]
Pops a packet off of the queue.
void vrt::NetIO::closeClientSockets () [protected]
Closes only the client sockets.
void vrt::NetIO::closeSockets () [protected]
Closes the sockets.
int32_t vrt::NetIO::getActiveConnectionCount () [inline]
Internal Use Only: Gets the number of active connections.
This will be:
    -1  = UDP        (UDP is connectionless)
     0  = TCP Server (no active clients)
     N  = TCP Server (N  active clients)
     1  = TCP Client
Returns:
The number of active connections.
virtual void vrt::NetIO::handle (vector< char > * buffer, int32_t length) [protected, virtual]
Handles the packet read in.
Parameters:
buffer The data read in.
length The number of bytes read in. [This is here for backwards-compatibility, it is always called with a value equal to buffer.length.]
Reimplemented in vrt::VRTReader.
void vrt::NetIO::openSockets () [protected]
Closes the sockets.
vector<char>* vrt::NetIO::popPacket () [protected]
Pops a packet off of the queue.
void vrt::NetIO::pushPacket (vector< char > * p) [inline, protected]
Adds a packet to the processing queue.
References pushPackets().
void vrt::NetIO::pushPackets (vector< char > * first, vector< vector< char > * > * rest) [protected]
Adds a set of packets to the processing queue.
This makes sure that all are pushed together at the same time.
Referenced by pushPacket().
vector<char>* vrt::NetIO::receiveBuffer (bool autoPush) [protected]
Reads a single buffer from the input stream.
This method can not be used directly when the reader is running as a thread.
Parameters:
autoPush Automatically push received packet onto queue if doing so would be more optimal than just returning it. (This is a "suggestion" in that the function is free to disregard the value of this and return the received buffer.)
Returns:
The buffer received or null if none read in. If autoPush=true and a buffer is added to the queue this must return BUFFER_PUSHED.
Exceptions:
VRTException If an exception occurs.
virtual vector<char>* vrt::NetIO::receiveBufferTCP (bool autoPush) [protected, virtual]
Receive a packet via UDP.
Reimplemented in vrt::VRTReader.
virtual vector<char>* vrt::NetIO::receiveBufferUDP (bool autoPush) [protected, virtual]
Receive a packet via UDP.
Reimplemented in vrt::VRTReader.
virtual void vrt::NetIO::reconnect (const VRTEventListener & warnings) [protected, virtual]
Requests a reconnect and waits for it to be done.
Reimplemented in vrt::VRTReader.
virtual void vrt::NetIO::runInputThread () [protected, virtual]
Version of runThread() for an input connection.
Referenced by runThread().
virtual void vrt::NetIO::runOutputThread () [protected, virtual]
Version of runThread() for an output connection.
Referenced by runThread().
virtual void vrt::NetIO::runThread () [inline, protected, virtual]
Runs the thread.
Implements vrt::Threadable.
References runInputThread(), and runOutputThread().
void vrt::NetIO::sendBuffer (const void * buf, int32_t len) [protected]
Sends the UDP datagram *or* TCP buffer of data.
Parameters:
buf The pointer to the data to send.
len The number of octets in the buffer to send.
void vrt::NetIO::sendBuffer (int32_t len) [inline, protected]
Sends the UDP datagram *or* TCP buffer of data.
Parameters:
len The number of octets in the buffer to send.
virtual void vrt::NetIO::shutdown () [protected, virtual]
Closes any connections, This will always be called at the end of a call to run().
Reimplemented from vrt::Threadable.
void vrt::NetIO::shutdownClientSockets () [protected]
Shutdown only the client sockets.
void vrt::NetIO::shutdownSockets () [protected]
Stops any future read/write on the sockets, but does not close them.
This permits i/o to continue until the underlying buffers are empty.
virtual void vrt::NetIO::start () [virtual]
Starts the object running in a new thread.
Exceptions:
VRTException If already running.
Reimplemented from vrt::Threadable.
virtual void vrt::NetIO::stop (bool wait = true) [virtual]
Tells the object to stop running.
Parameters:
wait Wait for the thread to complete (true)?
Reimplemented from vrt::Threadable.
virtual string vrt::NetIO::toString () const [virtual]
Provides a description of the instance useful for debugging.
Returns:
A debugging string.
Reimplemented from vrt::VRTObject.
Member Data Documentation
vector<char>* vrt::NetIO::BUFFER_PUSHED [static, protected]
Indicates that a buffer was already handled.
The documentation for this class was generated from the following file:
cpp_src/vrt/net/NetIO.h