VRT: vrt::SpectrumField Class Reference
vrt::SpectrumField Class Reference
Specifies a Spectrum Field.
#include <IndicatorFields.h>
Public Member Functions
SpectrumField (const SpectrumField &r)
Basic copy constructor.
SpectrumField ()
Creates a new instance.
virtual int8_t getAveragingType () const
AveragingType: word 0, bits 15..8.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
virtual int32_t getNumAverages () const
NumAverages: word 8.
virtual int32_t getNumTransformPoints () const
virtual int32_t getNumWindowPoints () const
NumWindowPoints: word 3.
virtual double getResolution () const
Resolution: words 4-5 64-bit floating-point w/ radix point to the right of bit 20.
virtual double getSpan () const
Span: words 6-7 64-bit floating-point w/ radix point to the right of bit 20.
virtual int32_t getSpectrumF1Index () const
SpectrumF1Index: word 10.
virtual int32_t getSpectrumF2Index () const
SpectrumF2Index: word 11.
virtual int8_t getSpectrumType () const
SpectrumType: word 0, bits 7..0.
virtual int32_t getWeightingFactor () const
WeightingFactor: word 9.
virtual int8_t getWindowTime () const
WindowTime: word 0, bits 19..16.
virtual double getWindowTimeDeltaFloat () const
WindowTimeDelta(float): word 13 32-bit floating-point w/ radix point to the right of bit 12.
virtual int32_t getWindowTimeDeltaInt () const
WindowTimeDelta(int): word 12 32-bit integer.
virtual int8_t getWindowType () const
WindowType: word 1, bits 7..0.
virtual void setAveragingType (int8_t val)
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
virtual void setNumAverages (int32_t val)
virtual void setNumTransformPoints (int32_t val)
virtual void setNumWindowPoints (int32_t val)
virtual void setResolution (double val)
virtual void setSpan (double val)
virtual void setSpectrumF1Index (int32_t val)
virtual void setSpectrumF2Index (int32_t val)
virtual void setSpectrumType (int8_t val)
virtual void setWeightingFactor (int32_t val)
virtual void setWindowTime (int8_t val)
virtual void setWindowTimeDeltaFloat (double val)
virtual void setWindowTimeDeltaInt (int32_t val)
virtual void setWindowType (int8_t val)
virtual string toString () const
Gets a basic description of the object, useful for debugging.
Detailed Description
Specifies a Spectrum Field.
Constructor & Destructor Documentation
vrt::SpectrumField::SpectrumField ()
Creates a new instance.
vrt::SpectrumField::SpectrumField (const SpectrumField & r)
Basic copy constructor.
Member Function Documentation
virtual int8_t vrt::SpectrumField::getAveragingType () const [inline, virtual]
AveragingType: word 0, bits 15..8.
References vrt::Record::unpackByte().
virtual Value* vrt::SpectrumField::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::Record.
virtual int32_t vrt::SpectrumField::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::Record.
virtual string vrt::SpectrumField::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::Record.
virtual ValueType vrt::SpectrumField::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::Record.
virtual int32_t vrt::SpectrumField::getNumAverages () const [inline, virtual]
NumAverages: word 8.
References vrt::Record::unpackInt().
virtual int32_t vrt::SpectrumField::getNumWindowPoints () const [inline, virtual]
NumWindowPoints: word 3.
References vrt::Record::unpackInt().
virtual double vrt::SpectrumField::getResolution () const [inline, virtual]
Resolution: words 4-5 64-bit floating-point w/ radix point to the right of bit 20.
References vrt::VRTMath::toDouble64(), and vrt::Record::unpackLong().
virtual double vrt::SpectrumField::getSpan () const [inline, virtual]
Span: words 6-7 64-bit floating-point w/ radix point to the right of bit 20.
References vrt::VRTMath::toDouble64(), and vrt::Record::unpackLong().
virtual int32_t vrt::SpectrumField::getSpectrumF1Index () const [inline, virtual]
SpectrumF1Index: word 10.
References vrt::Record::unpackInt().
virtual int32_t vrt::SpectrumField::getSpectrumF2Index () const [inline, virtual]
SpectrumF2Index: word 11.
References vrt::Record::unpackInt().
virtual int8_t vrt::SpectrumField::getSpectrumType () const [inline, virtual]
SpectrumType: word 0, bits 7..0.
References vrt::Record::unpackByte().
virtual int32_t vrt::SpectrumField::getWeightingFactor () const [inline, virtual]
WeightingFactor: word 9.
References vrt::Record::unpackInt().
virtual int8_t vrt::SpectrumField::getWindowTime () const [inline, virtual]
WindowTime: word 0, bits 19..16.
References vrt::Record::unpackByte().
virtual double vrt::SpectrumField::getWindowTimeDeltaFloat () const [inline, virtual]
WindowTimeDelta(float): word 13 32-bit floating-point w/ radix point to the right of bit 12.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
virtual int32_t vrt::SpectrumField::getWindowTimeDeltaInt () const [inline, virtual]
WindowTimeDelta(int): word 12 32-bit integer.
References vrt::Record::unpackInt().
virtual int8_t vrt::SpectrumField::getWindowType () const [inline, virtual]
WindowType: word 1, bits 7..0.
References vrt::Record::unpackByte().
virtual void vrt::SpectrumField::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::Record.
virtual string vrt::SpectrumField::toString () const [virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::Record.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/IndicatorFields.h