VRT: vrt::Geolocation Class Reference
vrt::Geolocation Class Reference
Represents a GPS or INS geolocation fix.
#include <IndicatorFields.h>
Public Member Functions
Geolocation (const Geolocation &r)
Basic copy constructor.
Geolocation ()
Creates a new instance.
double getAltitude () const
Gets the altitude of the fix.
virtual Value * getField (int32_t id) const
Gets the value of a field, based on the field's id.
virtual int32_t getFieldCount () const
Gets the number of fields.
virtual string getFieldName (int32_t id) const
Gets the name of the given field.
virtual ValueType getFieldType (int32_t id) const
Gets the type associated with a given field.
double getHeadingAngle () const
Gets the heading of the vehicle.
double getLatitude () const
Gets the latitude of the fix.
double getLongitude () const
Gets the longitude of the fix.
double getMagneticVariation () const
Gets the magnetic variation from true north.
double getSpeedOverGround () const
Gets the speed over the ground.
double getTrackAngle () const
Gets the heading of the vehicle.
void setAltitude (double val)
Gets the altitude of the fix.
virtual void setField (int32_t id, const Value *val)
Sets the value of a field, based on the field's id.
void setHeadingAngle (double val)
Gets the heading of the vehicle.
void setLatitude (double val)
Gets the latitude of the fix.
void setLongitude (double val)
Gets the longitude of the fix.
void setMagneticVariation (double val)
Gets the magnetic variation from true north.
void setSpeedOverGround (double val)
Gets the speed over the ground.
void setTimeStamp (const TimeStamp &ts)
Sets the time stamp for the geolocation fix.
void setTrackAngle (double val)
Gets the heading of the vehicle.
virtual string toString () const
Gets a basic description of the object, useful for debugging.
Detailed Description
Represents a GPS or INS geolocation fix.
See also:
Ephemeris
GeoSentences
Constructor & Destructor Documentation
vrt::Geolocation::Geolocation ()
Creates a new instance.
vrt::Geolocation::Geolocation (const Geolocation & r)
Basic copy constructor.
Member Function Documentation
double vrt::Geolocation::getAltitude () const [inline]
Gets the altitude of the fix.
Returns:
The altitude in meters (whether this is MSL or WGS-84 is defined elsewhere).
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
virtual Value* vrt::Geolocation::getField (int32_t id) const [virtual]
Gets the value of a field, based on the field's id.
WARNING: The caller is responsible for deleting the memory referenced by the returned pointer.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
Pointer to the given value.
Reimplemented from vrt::AbstractGeolocation.
virtual int32_t vrt::Geolocation::getFieldCount () const [virtual]
Gets the number of fields.
Reimplemented from vrt::AbstractGeolocation.
virtual string vrt::Geolocation::getFieldName (int32_t id) const [virtual]
Gets the name of the given field.
In 90% of cases the field name will be identical to the name used in the applicable get/set function except without the get/set prefix (e.g. "SourceContext" for "getSourceContext"). It is possible to access the names of all fields via the following:
    for (int32_t id = 0; id < getFieldCount(); id++) {
      // id is the field ID
      getFieldName(id);
    }
In situations where it is desirable to access all available fields, it is faster to use the field ID as this eliminates any string comparisons.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field name.
Exceptions:
VRTException if the field id is invalid.
Reimplemented from vrt::AbstractGeolocation.
virtual ValueType vrt::Geolocation::getFieldType (int32_t id) const [virtual]
Gets the type associated with a given field.
Parameters:
id The field ID (on range [0,getFieldCount())).
Returns:
The field type (n > 0) or -N if the field is a vector of values where N is the component type of the vector.
Reimplemented from vrt::AbstractGeolocation.
double vrt::Geolocation::getHeadingAngle () const [inline]
Gets the heading of the vehicle.
The vehicle heading specifies the vehicle orientation.
Returns:
The vehicle heading in degrees.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Geolocation::getLatitude () const [inline]
Gets the latitude of the fix.
Returns:
The latitude in degrees.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Geolocation::getLongitude () const [inline]
Gets the longitude of the fix.
Returns:
The longitude in degrees.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Geolocation::getMagneticVariation () const [inline]
Gets the magnetic variation from true north.
Returns:
The magnetic variation in degrees.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Geolocation::getSpeedOverGround () const [inline]
Gets the speed over the ground.
Returns:
The speed over the ground in meters/second.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
double vrt::Geolocation::getTrackAngle () const [inline]
Gets the heading of the vehicle.
The track angle specifies the direction of travel.
Returns:
The track angle in degrees.
References vrt::VRTMath::toDouble32(), and vrt::Record::unpackInt().
void vrt::Geolocation::setAltitude (double val) [inline]
Gets the altitude of the fix.
Parameters:
val The altitude in meters (whether this is MSL or WGS-84 is defined elsewhere).
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
virtual void vrt::Geolocation::setField (int32_t id, const Value * val) [virtual]
Sets the value of a field, based on the field's id.
Parameters:
id The field ID (on range [0,getFieldCount())).
val Pointer to the given value (must be of the applicable type).
Reimplemented from vrt::AbstractGeolocation.
void vrt::Geolocation::setHeadingAngle (double val) [inline]
Gets the heading of the vehicle.
The vehicle heading specifies the vehicle orientation.
Parameters:
val The vehicle heading in degrees.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Geolocation::setLatitude (double val) [inline]
Gets the latitude of the fix.
Parameters:
val val The latitude in degrees.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Geolocation::setLongitude (double val) [inline]
Gets the longitude of the fix.
Parameters:
val The longitude in degrees.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Geolocation::setMagneticVariation (double val) [inline]
Gets the magnetic variation from true north.
Parameters:
val The magnetic variation in degrees.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Geolocation::setSpeedOverGround (double val) [inline]
Gets the speed over the ground.
Parameters:
val The speed over the ground in meters/second.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
void vrt::Geolocation::setTimeStamp (const TimeStamp & ts) [inline, virtual]
Sets the time stamp for the geolocation fix.
Parameters:
ts The time stamp for the geolocation fix.
Reimplemented from vrt::AbstractGeolocation.
void vrt::Geolocation::setTrackAngle (double val) [inline]
Gets the heading of the vehicle.
The track angle specifies the direction of travel.
Parameters:
val The track angle in degrees.
References vrt::VRTMath::fromDouble32(), and vrt::Record::packInt().
virtual string vrt::Geolocation::toString () const [virtual]
Gets a basic description of the object, useful for debugging.
Returns:
A basic description of the object.
Reimplemented from vrt::AbstractGeolocation.
The documentation for this class was generated from the following file:
cpp_src/vrt/lib/IndicatorFields.h