VRT: vrt::VRTMath Namespace Reference
vrt::VRTMath Namespace Reference
Supports conversions to/from the various numeric representations used within a VITA 49 packet.
Classes
struct type_requirement< true, T >
Functions
float _fromHalfInternal (int16_t bits)
Converts an IEEE 754-2008 half-precision floating-point (storage only) bit representation to an IEEE 754 single-precision floating-point value.
int16_t _toHalfInternal (float val)
Internal Use Only: Converts an IEEE 754 single-precision floating-point value to the bits equating to an IEEE 754-2008 half-precision (storage only) value.
int64_t doubleToRawLongBits (double val)
Converts an IEEE-764 double into the corresponding 64-bits contained in a 64-bit integer.
int32_t floatToRawIntBits (float val)
Converts an IEEE-764 float into the corresponding 32-bits contained in a 32-bit integer.
int16_t fromDouble16 (int32_t radixPoint, double val)
Converts a float to a 32-bit fixed point number.
int32_t fromDouble32 (int32_t radixPoint, double val)
Converts a float to a 32-bit fixed point number.
int64_t fromDouble64 (int32_t radixPoint, double val)
Converts a float to a 64-bit fixed point number.
int16_t fromFloat16 (int32_t radixPoint, float val)
Converts a float to a 16-bit fixed point number.
int32_t fromFloat32 (int32_t radixPoint, float val)
Converts a float to a 32-bit fixed point number.
int64_t fromFloat64 (int32_t radixPoint, float val)
Converts a float to a 64-bit fixed point number.
float fromHalf (int16_t bits)
Converts an IEEE 754-2008 half-precision floating-point (storage only) bit representation to an IEEE 754 single-precision floating-point value.
int16_t fromInt16 (int32_t radixPoint, int32_t val)
Converts an int32_t to a 16-bit fixed point number.
int32_t fromInt32 (int32_t radixPoint, int32_t val)
Converts an int32_t to a 32-bit fixed point number.
int64_t fromInt64 (int32_t radixPoint, int32_t val)
Converts an int32_t to a 64-bit fixed point number.
int16_t fromLong16 (int32_t radixPoint, int64_t val)
Converts a int64_t to a 16-bit fixed point number.
int32_t fromLong32 (int32_t radixPoint, int64_t val)
Converts a int64_t to a 32-bit fixed point number.
int64_t fromLong64 (int32_t radixPoint, int64_t val)
Converts a int64_t to a 64-bit fixed point number.
double fromVRTFloat (DataItemFormat form, int32_t dSize, int64_t bits)
Converts from the packed bits for a VRT floating-point to an IEEE-754 double-precision floating-point value.
double fromVRTFloat32 (bool sign, int32_t eSize, int32_t dSize, int32_t bits)
Internal Use Only: Converts from the packed bits for a VRT floating-point to an IEEE-754 double-precision floating-point value without normal safety checks.
double fromVRTFloat64 (bool sign, int32_t eSize, int32_t dSize, int64_t bits)
Internal Use Only: Converts from the packed bits for a VRT floating-point to an IEEE-754 double-precision floating-point value without normal safety checks.
float intBitsToFloat (int32_t bits)
Converts the 32-bits corresponding to an IEEE-764 float, as contained in a 32-bit integer, into an IEEE-764 float.
int32_t lengthUTF8 (const string &val)
Computes the length a UTF-8 string will need in a buffer.
int32_t lengthUTF8 (const wstring &val)
Computes the length a UTF-8 string will need in a buffer.
double longBitsToDouble (int64_t bits)
Converts the 64-bits corresponding to an IEEE-764 double, as contained in a 64-bit integer, into an IEEE-764 double.
int32_t packAscii (vector< char > &buf, int32_t off, const wstring &val, int32_t length)
Pack a ASCII string into a buffer.
int32_t packAscii (void *ptr, int32_t off, const wstring &val, int32_t length)
Pack a ASCII string into a buffer.
int32_t packAscii (vector< char > &buf, int32_t off, const string &val, int32_t length)
Pack a ASCII string into a buffer.
int32_t packAscii (void *ptr, int32_t off, const string &val, int32_t length)
Pack a ASCII string into a buffer.
void packBits32 (void *ptr, int32_t bitOffset, int32_t bitCount, int32_t bits)
Internal Use Only: Writes bits to a buffer without safety checks.
void packBits64 (void *ptr, int32_t bitOffset, int32_t bitCount, int64_t bits)
Internal Use Only: Writes bits to a buffer without safety checks.
void packBoolean (vector< char > &buf, int32_t off, bool val)
Pack a boolean into a buffer.
void packBoolean (void *ptr, int32_t off, bool val)
Pack a boolean into a buffer.
void packBoolNull (vector< char > &buf, int32_t off, boolNull val)
Pack a boolean into a buffer.
void packBoolNull (void *ptr, int32_t off, boolNull val)
Pack a boolean into a buffer.
void packByte (vector< char > &buf, int32_t off, char val)
Pack byte data into byte buffer.
void packByte (void *ptr, int32_t off, char val)
Pack byte data into byte buffer.
void packBytes (vector< char > &buf, int32_t off, const void *buffer, int32_t len)
Pack an array of bytes into the buffer.
void packBytes (vector< char > &buf, int32_t off, const vector< char > &buffer, int32_t len)
Pack an array of bytes into the buffer.
void packDouble (vector< char > &buf, int32_t off, double val, ByteOrder rep=BIG_ENDIAN)
Pack double data into byte buffer.
void packDouble (void *ptr, int32_t off, double val, ByteOrder rep=BIG_ENDIAN)
Pack double data into byte buffer.
void packFloat (vector< char > &buf, int32_t off, float val, ByteOrder rep=BIG_ENDIAN)
Pack float data into byte buffer.
void packFloat (void *ptr, int32_t off, float val, ByteOrder rep=BIG_ENDIAN)
Pack float data into byte buffer.
void packInetAddr (vector< char > &buf, int32_t off, const InetAddress &val)
Pack a 16-byte IPv6 address into a buffer.
void packInetAddr (void *ptr, int32_t off, const InetAddress &val)
Pack a 16-byte IPv6 address into a buffer.
void packInt (vector< char > &buf, int32_t off, int32_t val, ByteOrder rep=BIG_ENDIAN)
Pack int data into byte buffer.
void packInt (void *ptr, int32_t off, int32_t val, ByteOrder rep=BIG_ENDIAN)
Pack int data into byte buffer.
void packInt24 (vector< char > &buf, int32_t off, int32_t val, ByteOrder rep=BIG_ENDIAN)
Internal Use Only: Pack a 24-bit integer value as an int data from a byte buffer.
void packInt24 (void *ptr, int32_t off, int32_t val, ByteOrder rep=BIG_ENDIAN)
Internal Use Only: Pack a 24-bit integer value as an int data from a byte buffer.
void packLong (vector< char > &buf, int32_t off, int64_t val, ByteOrder rep=BIG_ENDIAN)
Pack long data into byte buffer.
void packLong (void *ptr, int32_t off, int64_t val, ByteOrder rep=BIG_ENDIAN)
Pack long data into byte buffer.
int32_t packMetadata (vector< char > &buf, int32_t off, const MetadataBlock &val, int32_t len)
Pack a metadata block into a buffer.
void packRecord (vector< char > &buf, int32_t off, const Record &val)
Pack a record into a buffer.
void packShort (vector< char > &buf, int32_t off, int16_t val, ByteOrder rep=BIG_ENDIAN)
Pack short data into byte buffer.
void packShort (void *ptr, int32_t off, int16_t val, ByteOrder rep=BIG_ENDIAN)
Pack short data into byte buffer.
void packTimeStamp (vector< char > &buf, int32_t off, const TimeStamp &val, IntegerMode epoch, ByteOrder rep=BIG_ENDIAN)
Pack a VITA 49.0 time stamp into a buffer.
void packTimeStamp (void *ptr, int32_t off, const TimeStamp &val, IntegerMode epoch, ByteOrder rep=BIG_ENDIAN)
Pack a VITA 49.0 time stamp into a buffer.
void packUByte (vector< char > &buf, int32_t off, unsigned char val)
Pack unsigned byte data into byte buffer.
void packUByte (void *ptr, int32_t off, unsigned char val)
Pack unsigned byte data into byte buffer.
void packUInt (vector< char > &buf, int32_t off, uint32_t val, ByteOrder rep=BIG_ENDIAN)
Pack unsigned int data into byte buffer.
void packUInt (void *ptr, int32_t off, uint32_t val, ByteOrder rep=BIG_ENDIAN)
Pack unsigned int data into byte buffer.
void packUInt24 (vector< char > &buf, int32_t off, int32_t val, ByteOrder rep=BIG_ENDIAN)
Internal Use Only: Pack a 24-bit integer value as an int data from a byte buffer.
void packUInt24 (void *ptr, int32_t off, int32_t val, ByteOrder rep=BIG_ENDIAN)
Internal Use Only: Pack a 24-bit integer value as an int data from a byte buffer.
void packULong (vector< char > &buf, int32_t off, uint64_t val, ByteOrder rep=BIG_ENDIAN)
Pack unsigned long data into byte buffer.
void packULong (void *ptr, int32_t off, uint64_t val, ByteOrder rep=BIG_ENDIAN)
Pack unsigned long data into byte buffer.
void packUShort (vector< char > &buf, int32_t off, uint16_t val, ByteOrder rep=BIG_ENDIAN)
Pack unsigned short data into byte buffer.
void packUShort (void *ptr, int32_t off, uint16_t val, ByteOrder rep=BIG_ENDIAN)
Pack unsigned short data into byte buffer.
int32_t packUTF8 (vector< char > &buf, int32_t off, const string &val, int32_t length)
Pack a UTF-8 string into a buffer.
int32_t packUTF8 (void *ptr, int32_t off, const string &val, int32_t length)
Pack a UTF-8 string into a buffer.
int32_t packUTF8 (vector< char > &buf, int32_t off, const wstring &val, int32_t length)
Pack a UTF-8 string into a buffer.
int32_t packUTF8 (void *ptr, int32_t off, const wstring &val, int32_t length)
Pack a UTF-8 string into a buffer.
void packUUID (vector< char > &buf, int32_t off, const UUID &val)
Pack a 16-byte UUID into a buffer.
void packUUID (void *ptr, int32_t off, const UUID &val)
Pack a 16-byte UUID into a buffer.
template<typename T1 , typename T2 >
T2 safecastT1ToT2 (T1 val)
Converts an from one type to another type of same size using memcpy.
double toDouble16 (int32_t radixPoint, int16_t bits)
Converts a 16-bit fixed point number to a float.
double toDouble32 (int32_t radixPoint, int32_t bits)
Converts a 32-bit fixed point number to a float.
double toDouble64 (int32_t radixPoint, int64_t bits)
Converts a 64-bit fixed point number to a float.
float toFloat16 (int32_t radixPoint, int16_t bits)
Converts a 16-bit fixed point number to a float.
float toFloat32 (int32_t radixPoint, int32_t bits)
Converts a 32-bit fixed point number to a float.
float toFloat64 (int32_t radixPoint, int64_t bits)
Converts a 64-bit fixed point number to a float.
int16_t toHalf (float val)
Converts an IEEE 754 single-precision floating-point value to the bits equating to an IEEE 754-2008 half-precision (storage only) value.
int32_t toInt16 (int32_t radixPoint, int16_t bits)
Converts a 16-bit fixed point number to an int.
int32_t toInt32 (int32_t radixPoint, int32_t bits)
Converts a 32-bit fixed point number to an int.
int32_t toInt64 (int32_t radixPoint, int64_t bits)
Converts a 64-bit fixed point number to an int.
int64_t toLong16 (int32_t radixPoint, int16_t bits)
Converts a 16-bit fixed point number to a long.
int64_t toLong32 (int32_t radixPoint, int32_t bits)
Converts a 32-bit fixed point number to a long.
int64_t toLong64 (int32_t radixPoint, int64_t bits)
Converts a 64-bit fixed point number to a long.
int64_t toVRTFloat (DataItemFormat form, int32_t dSize, double val)
Converts from an IEEE-754 double-precision floating-point value to the packed bits for a VRT floating-point.
int32_t toVRTFloat32 (bool sign, int32_t eSize, int32_t dSize, double val)
Internal Use Only: Converts from an IEEE-754 double-precision floating-point value to the packed bits for a VRT floating-point without normal safety checks.
int64_t toVRTFloat64 (bool sign, int32_t eSize, int32_t dSize, double val)
Internal Use Only: Converts from an IEEE-754 double-precision floating-point value to the packed bits for a VRT floating-point without normal safety checks.
string unpackAscii (const vector< char > &buf, int32_t off, int32_t len)
Unpack a ASCII string from a buffer.
string unpackAscii (const void *ptr, int32_t off, int32_t len)
Unpack a ASCII string from a buffer.
int32_t unpackBits32 (const void *ptr, int32_t bitOffset, int32_t bitCount)
Internal Use Only: Reads bits from a buffer without safety checks.
int64_t unpackBits64 (const void *ptr, int32_t bitOffset, int32_t bitCount)
Internal Use Only: Reads bits from a buffer without safety checks.
bool unpackBoolean (const vector< char > &buf, int32_t off)
Unpack a boolean from a buffer.
bool unpackBoolean (const void *ptr, int32_t off)
Unpack a boolean from a buffer.
boolNull unpackBoolNull (const vector< char > &buf, int32_t off)
Unpack a boolean from a buffer.
boolNull unpackBoolNull (const void *ptr, int32_t off)
Unpack a boolean from a buffer.
char unpackByte (const vector< char > &buf, int32_t off)
Unpack byte data from a byte buffer.
char unpackByte (const void *ptr, int32_t off)
Unpack byte data from a byte buffer.
void * unpackBytes (const vector< char > &buf, int32_t off, void *buffer, int32_t len)
Unpack an array of bytes from a buffer.
vector< char > unpackBytes (const vector< char > &buf, int32_t off, int32_t len)
Unpack an array of bytes from a buffer.
double unpackDouble (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack double data from a byte buffer.
double unpackDouble (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack double data from a byte buffer.
float unpackFloat (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack float data from a byte buffer.
float unpackFloat (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack float data from a byte buffer.
InetAddress unpackInetAddr (const vector< char > &buf, int32_t off)
Unpack a 16-byte IPv6 address from a buffer.
InetAddress unpackInetAddr (const void *ptr, int32_t off)
Unpack a 16-byte IPv6 address from a buffer.
int32_t unpackInt (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack int data from a byte buffer.
int32_t unpackInt (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack int data from a byte buffer.
int32_t unpackInt24 (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Internal Use Only: Unpack a 24-bit integer value as an int data from a byte buffer
int32_t unpackInt24 (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Internal Use Only: Unpack a 24-bit integer value as an int data from a byte buffer
int64_t unpackLong (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack long data from a byte buffer.
int64_t unpackLong (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack long data from a byte buffer.
MetadataBlock unpackMetadata (const vector< char > &buf, int32_t off, int32_t len)
Unpack a metadata block into a buffer.
void unpackRecord (const vector< char > &buf, int32_t off, Record &val)
Pack a record into a buffer.
int16_t unpackShort (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack short data from a byte buffer.
int16_t unpackShort (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack short data from a byte buffer.
TimeStamp unpackTimeStamp (const vector< char > &buf, int32_t off, IntegerMode epoch, ByteOrder rep=BIG_ENDIAN)
Unpack an VITA 49.0 time stamp from a buffer.
TimeStamp unpackTimeStamp (const void *ptr, int32_t off, IntegerMode epoch, ByteOrder rep=BIG_ENDIAN)
Unpack an VITA 49.0 time stamp from a buffer.
unsigned char unpackUByte (const vector< char > &buf, int32_t off)
Unpack unsigned byte data from a byte buffer.
unsigned char unpackUByte (const void *ptr, int32_t off)
Unpack unsigned byte data from a byte buffer.
uint32_t unpackUInt (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack unsigned int data from a byte buffer.
uint32_t unpackUInt (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack unsigned int data from a byte buffer.
uint32_t unpackUInt24 (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Internal Use Only: Unpack an unsigned 24-bit integer value as an int data from a byte buffer
uint32_t unpackUInt24 (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Internal Use Only: Unpack an unsigned 24-bit integer value as an int data from a byte buffer
uint64_t unpackULong (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack unsigned long data from a byte buffer.
uint64_t unpackULong (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack unsigned long data from a byte buffer.
uint16_t unpackUShort (const vector< char > &buf, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack unsigned short data from a byte buffer.
uint16_t unpackUShort (const void *ptr, int32_t off, ByteOrder rep=BIG_ENDIAN)
Unpack unsigned short data from a byte buffer.
wstring unpackUTF8 (const vector< char > &buf, int32_t off, int32_t len, wchar_t replacement='?')
Unpack a modified UTF-8 string from a buffer.
wstring unpackUTF8 (const void *ptr, int32_t off, int32_t len, wchar_t replacement='?')
Unpack a modified UTF-8 string from a buffer.
UUID unpackUUID (const vector< char > &buf, int32_t off)
Unpack a 16-byte UUID from a buffer.
UUID unpackUUID (const void *ptr, int32_t off)
Unpack a 16-byte UUID from a buffer.
Detailed Description
Supports conversions to/from the various numeric representations used within a VITA 49 packet.
The name VRTMath is a bit of an anachronism in that the only "math" done on the special data types used in a VITA 49 (VRT) packet is in the functions that convert between these special types and standard Java/C++ data types.
IEEE 754-2008 16-bit Floating-Point Numbers
The use of 16-bit IEEE 754-2008 floating-point numbers is not currently part of the VITA 49 standard, but is under consideration for inclusion in a future revision. Their inclusion here is to support the necessary analysis work that would precede any such inclusion.
Since IEEE 754-2008 16-bit floating-point numbers are a storage-only format and are not supported by Java or C++ (though some C++ compilers have non-standard extensions for them) the routines necessary for converting between 16-bit floating-point numbers (called "half-precision") and single-precision numbers are included here.
VRT Floating-Point Numbers
Supports conversion between an IEEE-754 floating-point value and the packed packed bits for a VRT floating-point.
Although VRT floating-point values can express many values in multiple ways within the binary form (e.g. 1/4 or 2/8) this function outputs the values in a "normalized form" where the output value will have a 1 in the most-significant-(non-sign-)bit of the mantissa, excepting for small values close to zero where the exponent is zero. This mirrors the behavior of IEEE-754 floating-point values, excepting that the highest bit is always present (not just for "denormal" values).
Since the range of VRT floating-point numbers is [0,1) (signed) or [-1,1) (unsigned) any values below/above that range will be converted to the smallest/largest value possible in that range. Any NaN values passed in will be converted to zero. This is similar to the standard behavior for IEEE 754 numbers when converting them to an integer.
VRT Fixed-Point Numbers
Supports fixed-point numbers compatible with VRT.
    Example:
    31                                  0
    [00000000|00000000|0000oooo|oooooooo]
                           ^ radixPoint = 12
    20-bit whole number (2's complement) + 12 bit binary fraction
    Convert to/from double: toDouble32(20, bits)  -> val
                            fromDouble32(20, val) -> bits
Note that all of the VRT fixed-point conversions assume that a valid radix point has been given, and will have unspecified behavior if the radix point is invalid.
Any values given that are out-of-range with respect to the output will be automatically converted to the nearest in-range value, and any floating-point NaN values given will become zero. Where the fixed-point value has less precision than the input value, the input value will be "rounded" to the nearest fixed-point value.
Implementation Note: Prior versions of this library took a "garbage in garbage out" approach to out-of-range values in the interest of maximizing performance. Unfortunately the rounding involved in converting the numbers to fixed point created a situation where input values extremely close to the min/max limits could end up rounded to an out-of-range value and result in a bogus result. In the end the code to perform a conversion to the nearest in-range value (for all input values) is no more complex than the code required to support this special-case situation, hence the current approach.
Summary
Convert to/from long
Convert to/from int
Convert to/from double
Convert to/from float
IEEE 754 16-bit Floating-Point
n/a
n/a
n/a
n/a
n/a
n/a
toHalf(..)
fromHalf(..)
VRT Floating-Point
n/a
n/a
n/a
n/a
toVRTFloat(..)
fromVRTFloat(..)
TBD
TBD
VRT 64-bit Fixed Point
toLong64(..)
fromLong64(..)
toInt64(..)
fromInt64(..)
toDouble64(..)
fromDouble64(..)
toFloat64(..)
fromFloat64(..)
VRT 32-bit Fixed Point
toLong32(..)
fromLong32(..)
toInt32(..)
fromInt32(..)
toDouble32(..)
fromDouble32(..)
toFloat32(..)
fromFloat32(..)
VRT 16-bit Fixed Point
toLong16(..)
fromLong16(..)
toInt16(..)
fromInt16(..)
toDouble16(..)
fromDouble16(..)
toFloat16(..)
fromFloat16(..)
Function Documentation
float vrt::VRTMath::_fromHalfInternal (int16_t bits)
Converts an IEEE 754-2008 half-precision floating-point (storage only) bit representation to an IEEE 754 single-precision floating-point value.
This is the "internal library" call provided as a companion to fromHalf(..) and should never be called directly.
Parameters:
bits The bits representing the half-precision value.
Returns:
The single-precision value.
Referenced by fromHalf().
int16_t vrt::VRTMath::_toHalfInternal (float val)
Internal Use Only: Converts an IEEE 754 single-precision floating-point value to the bits equating to an IEEE 754-2008 half-precision (storage only) value.
This is the "internal library" call provided as a companion to toHalf(..) and should never be called directly.
Parameters:
val The single-precision value.
Returns:
The bits representing the half-precision value.
Referenced by toHalf().
int64_t vrt::VRTMath::doubleToRawLongBits (double val) [inline]
Converts an IEEE-764 double into the corresponding 64-bits contained in a 64-bit integer.
The name of this function is patterned after the Java function (as this provides some consistency between the Java and C++ version), but the implementation is entirely different.
References doubleToRawLongBits().
Referenced by doubleToRawLongBits().
int32_t vrt::VRTMath::floatToRawIntBits (float val) [inline]
Converts an IEEE-764 float into the corresponding 32-bits contained in a 32-bit integer.
The name of this function is patterned after the Java function (as this provides some consistency between the Java and C++ version), but the implementation is entirely different.
References floatToRawIntBits().
Referenced by floatToRawIntBits().
int16_t vrt::VRTMath::fromDouble16 (int32_t radixPoint, double val) [inline]
Converts a float to a 32-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..15).
val The floating-point value.
Returns:
The bits representing the fixed-point number.
References fromDouble16().
Referenced by fromDouble16(), and fromFloat16().
int32_t vrt::VRTMath::fromDouble32 (int32_t radixPoint, double val) [inline]
Converts a float to a 32-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..31).
val The floating-point value.
Returns:
The bits representing the fixed-point number.
References fromDouble32().
Referenced by fromDouble32(), fromFloat32(), vrt::Geolocation::setAltitude(), vrt::Ephemeris::setAttitudeAlpha(), vrt::Ephemeris::setAttitudeBeta(), vrt::Ephemeris::setAttitudePhi(), vrt::Geolocation::setHeadingAngle(), vrt::Geolocation::setLatitude(), vrt::Geolocation::setLongitude(), vrt::Geolocation::setMagneticVariation(), vrt::Ephemeris::setPositionX(), vrt::Ephemeris::setPositionY(), vrt::Ephemeris::setPositionZ(), vrt::IndicatorFieldProvider::setRange(), vrt::Geolocation::setSpeedOverGround(), vrt::Geolocation::setTrackAngle(), vrt::Ephemeris::setVelocityX(), vrt::Ephemeris::setVelocityY(), and vrt::Ephemeris::setVelocityZ().
int64_t vrt::VRTMath::fromDouble64 (int32_t radixPoint, double val) [inline]
Converts a float to a 64-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..63).
val The floating-point value.
Returns:
The bits representing the fixed-point number.
References fromDouble64().
Referenced by fromDouble64(), fromFloat64(), vrt::IndicatorFieldProvider::setAuxBandwidth(), vrt::IndicatorFieldProvider::setAuxFrequency(), vrt::IndicatorFieldProvider::setBandOffsetIF(), vrt::IndicatorFieldProvider::setBandwidth(), vrt::IndicatorFieldProvider::setFrequencyIF(), vrt::IndicatorFieldProvider::setFrequencyOffsetRF(), vrt::IndicatorFieldProvider::setFrequencyRF(), and vrt::IndicatorFieldProvider::setSampleRate().
int16_t vrt::VRTMath::fromFloat16 (int32_t radixPoint, float val) [inline]
Converts a float to a 16-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..15).
val The floating-point value.
Returns:
The bits representing the fixed-point number.
References fromDouble16(), and fromFloat16().
Referenced by fromFloat16(), vrt::IndicatorFieldProvider::set3DPointingVectorAzimuth(), vrt::IndicatorFieldProvider::set3DPointingVectorElevation(), vrt::IndicatorFieldProvider::setAirTemperature(), vrt::IndicatorFieldProvider::setAuxGain1(), vrt::IndicatorFieldProvider::setAuxGain2(), vrt::IndicatorFieldProvider::setBitErrorRate(), vrt::IndicatorFieldProvider::setEbN0(), vrt::IndicatorFieldProvider::setGain1(), vrt::IndicatorFieldProvider::setGain2(), vrt::IndicatorFieldProvider::setNoiseFigure(), vrt::IndicatorFieldProvider::setOneDecibelCompressionPoint(), vrt::IndicatorFieldProvider::setPhaseOffset(), vrt::IndicatorFieldProvider::setPolarizationEllipticityAngle(), vrt::IndicatorFieldProvider::setPolarizationTiltAngle(), vrt::IndicatorFieldProvider::setReferenceLevel(), vrt::IndicatorFieldProvider::setSeaGroundTemperature(), vrt::IndicatorFieldProvider::setSecondOrderInputInterceptPoint(), vrt::IndicatorFieldProvider::setSNR(), vrt::IndicatorFieldProvider::setTemperature(), vrt::IndicatorFieldProvider::setThirdOrderInputInterceptPoint(), vrt::IndicatorFieldProvider::setThreshold1(), and vrt::IndicatorFieldProvider::setThreshold2().
int32_t vrt::VRTMath::fromFloat32 (int32_t radixPoint, float val) [inline]
Converts a float to a 32-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..31).
val The floating-point value.
Returns:
The bits representing the fixed-point number.
References fromDouble32(), and fromFloat32().
Referenced by fromFloat32(), vrt::IndicatorFieldProvider::setBeamwidth(), vrt::IndicatorFieldProvider::setHorizontalBeamwidth(), and vrt::IndicatorFieldProvider::setVerticalBeamwidth().
int64_t vrt::VRTMath::fromFloat64 (int32_t radixPoint, float val) [inline]
Converts a float to a 64-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..63).
val The floating-point value.
Returns:
The bits representing the fixed-point number.
References fromDouble64(), and fromFloat64().
Referenced by fromFloat64().
float vrt::VRTMath::fromHalf (int16_t bits) [inline]
Converts an IEEE 754-2008 half-precision floating-point (storage only) bit representation to an IEEE 754 single-precision floating-point value.
    References:
      [1] IEEE 754-2008.
      [2] Jeroen van der Zijp. "Fast Half Float Conversions." November
          2008 (Revised September 2010).
          ftp://ftp.fox-toolkit.org/pub/fasthalffloatconversion.pdf
      [3] Free Software Foundation, Inc. "Using the GNU Compiler Collection
          (GCC)." 2013. [Section 6.12 "Half-Precision Floating Point."]
          http://gcc.gnu.org/onlinedocs/gcc/Half_002dPrecision.html
          [Last Accessed 5 Aug 2013]
      [4] Intel. "Intel C++ Compiler XE 13.1 User and Reference Guides."
          Document Number 323273-131US. 2013. ["Intrinsics for Converting
          Half Floats."]
          http://software.intel.com/sites/products/documentation/doclib/iss/2013/compiler/cpp-lin/GUID-23C8FF6D-3D66-4961-A3A0-E2A7DC874304.htm
          [Last Accessed 5 Aug 2013]
Parameters:
bits The bits representing the half-precision value.
Returns:
The single-precision value.
References _fromHalfInternal(), and fromHalf().
Referenced by fromHalf().
int16_t vrt::VRTMath::fromInt16 (int32_t radixPoint, int32_t val) [inline]
Converts an int32_t to a 16-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..15).
val The integer value.
Returns:
The bits representing the fixed-point number.
References fromInt16().
Referenced by fromInt16().
int32_t vrt::VRTMath::fromInt32 (int32_t radixPoint, int32_t val) [inline]
Converts an int32_t to a 32-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..31).
val The integer value.
Returns:
The bits representing the fixed-point number.
References fromInt32().
Referenced by fromInt32().
int64_t vrt::VRTMath::fromInt64 (int32_t radixPoint, int32_t val) [inline]
Converts an int32_t to a 64-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..63).
val The integer value.
Returns:
The bits representing the fixed-point number.
References fromInt64(), and fromLong64().
Referenced by fromInt64().
int16_t vrt::VRTMath::fromLong16 (int32_t radixPoint, int64_t val) [inline]
Converts a int64_t to a 16-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..15).
val The integer value.
Returns:
The bits representing the fixed-point number.
References fromLong16().
Referenced by fromLong16().
int32_t vrt::VRTMath::fromLong32 (int32_t radixPoint, int64_t val) [inline]
Converts a int64_t to a 32-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..31).
val The integer value.
Returns:
The bits representing the fixed-point number.
References fromLong32().
Referenced by fromLong32().
int64_t vrt::VRTMath::fromLong64 (int32_t radixPoint, int64_t val) [inline]
Converts a int64_t to a 64-bit fixed point number.
Parameters:
radixPoint The radix point of the number (1..63).
val The integer value.
Returns:
The bits representing the fixed-point number.
References fromLong64().
Referenced by fromInt64(), and fromLong64().
double vrt::VRTMath::fromVRTFloat (DataItemFormat form, int32_t dSize, int64_t bits)
Converts from the packed bits for a VRT floating-point to an IEEE-754 double-precision floating-point value.
Despite the fact that toVRTFloat normalizes its output values, this function will support all of the valid VRT forms and convert them to their respective IEEE-754 value. Since IEEE-754 values are normalized this process results not reflective.
    References:
      [1] ANSI/VITA 49.0, Appendix D
      [2] IEEE-754
Parameters:
form The data item format. This must be one of the VRT floating-point formats.
dSize The data size in bits (2..63).
bits The packed bits to convert.
Returns:
The IEEE-754 floating-point number.
double vrt::VRTMath::fromVRTFloat32 (bool sign, int32_t eSize, int32_t dSize, int32_t bits)
Internal Use Only: Converts from the packed bits for a VRT floating-point to an IEEE-754 double-precision floating-point value without normal safety checks.
Parameters:
sign Is output signed?
eSize The number of exponent bits (1 to 6).
dSize The data size in bits (2..63).
bits The packed bits to convert.
double vrt::VRTMath::fromVRTFloat64 (bool sign, int32_t eSize, int32_t dSize, int64_t bits)
Internal Use Only: Converts from the packed bits for a VRT floating-point to an IEEE-754 double-precision floating-point value without normal safety checks.
Parameters:
sign Is output signed?
eSize The number of exponent bits (1 to 6).
dSize The data size in bits (2..63).
bits The packed bits to convert.
float vrt::VRTMath::intBitsToFloat (int32_t bits) [inline]
Converts the 32-bits corresponding to an IEEE-764 float, as contained in a 32-bit integer, into an IEEE-764 float.
The name of this function is patterned after the Java function (as this provides some consistency between the Java and C++ version), but the implementation is entirely different.
References intBitsToFloat().
Referenced by intBitsToFloat().
int32_t vrt::VRTMath::lengthUTF8 (const string & val) [inline]
Computes the length a UTF-8 string will need in a buffer.
Parameters:
val The string
Returns:
The length required to hold the entire UTF-8 string.
References lengthUTF8(), and packUTF8().
int32_t vrt::VRTMath::lengthUTF8 (const wstring & val) [inline]
Computes the length a UTF-8 string will need in a buffer.
Parameters:
val The string
Returns:
The length required to hold the entire UTF-8 string.
References lengthUTF8(), and packUTF8().
Referenced by lengthUTF8(), vrt::ReferencePointPacket::setDescription(), and vrt::StreamStatePacket::setMessage().
double vrt::VRTMath::longBitsToDouble (int64_t bits) [inline]
Converts the 64-bits corresponding to an IEEE-764 double, as contained in a 64-bit integer, into an IEEE-764 double.
The name of this function is patterned after the Java function (as this provides some consistency between the Java and C++ version), but the implementation is entirely different.
References longBitsToDouble().
Referenced by longBitsToDouble().
int32_t vrt::VRTMath::packAscii (vector< char > & buf, int32_t off, const wstring & val, int32_t length) [inline]
Pack a ASCII string into a buffer.
Any non-ASCII characters or ASCII control characters will be replaces with '?' upon insertion. If val is longer than len it will be truncated without explicit warning. If val is shorter than len it will be padded out with ASCII NUL characters to fill the length.
Parameters:
buf Byte array of data [OUTPUT]
off Offset into array
val Value to pack [INPUT]
length Length of the string in the buffer.
Returns:
The actual length required to hold the entire string. (This is for compatibility with packUTF8(..), but in practice just returns val.length().)
References packAscii().
int32_t vrt::VRTMath::packAscii (void * ptr, int32_t off, const wstring & val, int32_t length)
Pack a ASCII string into a buffer.
Any non-ASCII characters or ASCII control characters will be replaces with '?' upon insertion. If val is longer than len it will be truncated without explicit warning. If val is shorter than len it will be padded out with ASCII NUL characters to fill the length.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into array
val Value to pack [INPUT]
length Length of the string in the buffer.
Returns:
The actual length required to hold the entire string. (This is for compatibility with packUTF8(..), but in practice just returns val.length().)
int32_t vrt::VRTMath::packAscii (vector< char > & buf, int32_t off, const string & val, int32_t length) [inline]
Pack a ASCII string into a buffer.
Any non-ASCII characters or ASCII control characters will be replaces with '?' upon insertion. If val is longer than len it will be truncated without explicit warning. If val is shorter than len it will be padded out with ASCII NUL characters to fill the length.
Parameters:
buf Byte array of data [OUTPUT]
off Offset into array
val Value to pack [INPUT]
length Length of the string in the buffer.
Returns:
The actual length required to hold the entire string. (This is for compatibility with packUTF8(..), but in practice just returns val.length().)
References packAscii().
int32_t vrt::VRTMath::packAscii (void * ptr, int32_t off, const string & val, int32_t length)
Pack a ASCII string into a buffer.
Any non-ASCII characters or ASCII control characters will be replaces with '?' upon insertion. If val is longer than len it will be truncated without explicit warning. If val is shorter than len it will be padded out with ASCII NUL characters to fill the length.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into array
val Value to pack [INPUT]
length Length of the string in the buffer.
Returns:
The actual length required to hold the entire string. (This is for compatibility with packUTF8(..), but in practice just returns val.length().)
Referenced by packAscii(), and vrt::BasicVRTPacket::packPayloadAscii().
void vrt::VRTMath::packBits32 (void * ptr, int32_t bitOffset, int32_t bitCount, int32_t bits)
Internal Use Only: Writes bits to a buffer without safety checks.
void vrt::VRTMath::packBits64 (void * ptr, int32_t bitOffset, int32_t bitCount, int64_t bits)
Internal Use Only: Writes bits to a buffer without safety checks.
void vrt::VRTMath::packBoolean (vector< char > & buf, int32_t off, bool val) [inline]
Pack a boolean into a buffer.
The boolean is stored as:
    true  = +1
    false = -1
Parameters:
buf byte array of data [OUTPUT]
off Offset into array
val value to pack [INPUT]
References packBoolean().
void vrt::VRTMath::packBoolean (void * ptr, int32_t off, bool val) [inline]
Pack a boolean into a buffer.
The boolean is stored as:
    true  = +1
    false = -1
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into array
val value to pack [INPUT]
References packBoolean().
Referenced by packBoolean(), and vrt::BasicVRTPacket::packPayloadBoolean().
void vrt::VRTMath::packBoolNull (vector< char > & buf, int32_t off, boolNull val) [inline]
Pack a boolean into a buffer.
The boolean is stored as:
    null  =  0
    true  = +1
    false = -1
Parameters:
buf byte array of data [OUTPUT]
off Offset into array
val value to pack [INPUT]
References packBoolNull().
void vrt::VRTMath::packBoolNull (void * ptr, int32_t off, boolNull val) [inline]
Pack a boolean into a buffer.
The boolean is stored as:
    null  =  0
    true  = +1
    false = -1
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into array
val value to pack [INPUT]
References packBoolNull().
Referenced by packBoolNull(), and vrt::BasicVRTPacket::packPayloadBoolNull().
void vrt::VRTMath::packByte (vector< char > & buf, int32_t off, char val) [inline]
Pack byte data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
References packByte().
void vrt::VRTMath::packByte (void * ptr, int32_t off, char val) [inline]
Pack byte data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
Referenced by packByte(), and vrt::BasicVRTPacket::packPayloadByte().
void vrt::VRTMath::packBytes (vector< char > & buf, int32_t off, const void * buffer, int32_t len) [inline]
Pack an array of bytes into the buffer.
Parameters:
buf byte array of data [OUTPUT]
off Offset into array
buffer The buffer to pack into the array [INPUT]
len The length to pack.
Exceptions:
VRTException If off, boff or len are invalid.
References packBytes().
void vrt::VRTMath::packBytes (vector< char > & buf, int32_t off, const vector< char > & buffer, int32_t len) [inline]
Pack an array of bytes into the buffer.
Parameters:
buf byte array of data [OUTPUT]
off Offset into array
buffer The buffer to pack into the array [INPUT]
len The length to pack.
Exceptions:
VRTException If buffer.length != len.
References packBytes().
Referenced by packBytes(), and vrt::BasicVRTPacket::packPayloadBytes().
void vrt::VRTMath::packDouble (vector< char > & buf, int32_t off, double val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack double data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packDouble().
void vrt::VRTMath::packDouble (void * ptr, int32_t off, double val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack double data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packDouble().
Referenced by packDouble(), and vrt::BasicVRTPacket::packPayloadDouble().
void vrt::VRTMath::packFloat (vector< char > & buf, int32_t off, float val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack float data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packFloat().
void vrt::VRTMath::packFloat (void * ptr, int32_t off, float val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack float data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packFloat().
Referenced by packFloat(), and vrt::BasicVRTPacket::packPayloadFloat().
void vrt::VRTMath::packInetAddr (vector< char > & buf, int32_t off, const InetAddress & val) [inline]
Pack a 16-byte IPv6 address into a buffer.
Parameters:
buf byte array of data [OUTPUT]
off Offset into array
val value to pack [INPUT]
References vrt::InetAddress::toIPv6().
void vrt::VRTMath::packInetAddr (void * ptr, int32_t off, const InetAddress & val) [inline]
Pack a 16-byte IPv6 address into a buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into array
val value to pack [INPUT]
References vrt::InetAddress::toIPv6().
Referenced by vrt::BasicVRTPacket::packPayloadInetAddr().
void vrt::VRTMath::packInt (vector< char > & buf, int32_t off, int32_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack int data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packInt().
void vrt::VRTMath::packInt (void * ptr, int32_t off, int32_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack int data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packInt().
Referenced by packInt(), vrt::BasicVRTPacket::packPayloadInt(), and packTimeStamp().
void vrt::VRTMath::packInt24 (vector< char > & buf, int32_t off, int32_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Internal Use Only: Pack a 24-bit integer value as an int data from a byte buffer.
Any high-order bits (i.e. bits 24 to 31) are ignored.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packInt24().
void vrt::VRTMath::packInt24 (void * ptr, int32_t off, int32_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Internal Use Only: Pack a 24-bit integer value as an int data from a byte buffer.
Any high-order bits (i.e. bits 24 to 31) are ignored.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packInt24().
Referenced by packInt24(), and packUInt24().
void vrt::VRTMath::packLong (vector< char > & buf, int32_t off, int64_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack long data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packLong().
void vrt::VRTMath::packLong (void * ptr, int32_t off, int64_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack long data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packLong().
Referenced by packLong(), vrt::BasicVRTPacket::packPayloadLong(), and packTimeStamp().
int32_t vrt::VRTMath::packMetadata (vector< char > & buf, int32_t off, const MetadataBlock & val, int32_t len)
Pack a metadata block into a buffer.
Parameters:
buf byte array of data
off Offset into array
val The metadata block to pack
len The length of the block
Referenced by vrt::BasicVRTPacket::packPayloadMetadata().
void vrt::VRTMath::packRecord (vector< char > & buf, int32_t off, const Record & val)
Pack a record into a buffer.
Parameters:
buf byte array of data
off Offset into array
val The record to pack
Referenced by vrt::BasicVRTPacket::packPayloadRecord().
void vrt::VRTMath::packShort (vector< char > & buf, int32_t off, int16_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack short data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packShort().
void vrt::VRTMath::packShort (void * ptr, int32_t off, int16_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack short data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packShort().
Referenced by vrt::BasicVRTPacket::packPayloadShort(), and packShort().
void vrt::VRTMath::packTimeStamp (vector< char > & buf, int32_t off, const TimeStamp & val, IntegerMode epoch, ByteOrder rep = BIG_ENDIAN) [inline]
Pack a VITA 49.0 time stamp into a buffer.
Parameters:
buf byte array of data [OUTPUT]
off Offset into array
val value to pack [INPUT]
epoch The epoch to use (must be either IntegerMode_UTC or IntegerMode_GPS).
rep The byte representation to use
References packTimeStamp().
void vrt::VRTMath::packTimeStamp (void * ptr, int32_t off, const TimeStamp & val, IntegerMode epoch, ByteOrder rep = BIG_ENDIAN) [inline]
Pack a VITA 49.0 time stamp into a buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into array
val value to pack [INPUT]
epoch The epoch to use (must be either IntegerMode_UTC or IntegerMode_GPS).
rep The byte representation to use
References vrt::TimeStamp::getPicoSeconds(), vrt::TimeStamp::getSecondsGPS(), vrt::TimeStamp::getSecondsUTC(), packInt(), and packLong().
Referenced by vrt::BasicVRTPacket::packPayloadTimeStamp(), and packTimeStamp().
void vrt::VRTMath::packUByte (vector< char > & buf, int32_t off, unsigned char val) [inline]
Pack unsigned byte data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
References packUByte().
void vrt::VRTMath::packUByte (void * ptr, int32_t off, unsigned char val) [inline]
Pack unsigned byte data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
References packUByte().
Referenced by packUByte().
void vrt::VRTMath::packUInt (vector< char > & buf, int32_t off, uint32_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack unsigned int data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packUInt().
void vrt::VRTMath::packUInt (void * ptr, int32_t off, uint32_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack unsigned int data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packUInt().
Referenced by packUInt().
void vrt::VRTMath::packUInt24 (vector< char > & buf, int32_t off, int32_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Internal Use Only: Pack a 24-bit integer value as an int data from a byte buffer.
Any high-order bits (i.e. bits 24 to 31) are ignored.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packUInt24().
void vrt::VRTMath::packUInt24 (void * ptr, int32_t off, int32_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Internal Use Only: Pack a 24-bit integer value as an int data from a byte buffer.
Any high-order bits (i.e. bits 24 to 31) are ignored.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packInt24(), and packUInt24().
Referenced by packUInt24().
void vrt::VRTMath::packULong (vector< char > & buf, int32_t off, uint64_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack unsigned long data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packULong().
void vrt::VRTMath::packULong (void * ptr, int32_t off, uint64_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack unsigned long data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packULong().
Referenced by packULong().
void vrt::VRTMath::packUShort (vector< char > & buf, int32_t off, uint16_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack unsigned short data into byte buffer.
Parameters:
buf Packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packUShort().
void vrt::VRTMath::packUShort (void * ptr, int32_t off, uint16_t val, ByteOrder rep = BIG_ENDIAN) [inline]
Pack unsigned short data into byte buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into output array
val value to pack [INPUT]
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
References packUShort().
Referenced by packUShort().
int32_t vrt::VRTMath::packUTF8 (vector< char > & buf, int32_t off, const string & val, int32_t length) [inline]
Pack a UTF-8 string into a buffer.
If val is longer than len it will be truncated without explicit warning. If val is shorter than len it will be padded out with ASCII NUL characters to fill the length.
Parameters:
buf Byte array of data [OUTPUT]
off Offset into array
val Value to pack [INPUT]
length Length of the string in the buffer.
Returns:
The length required to hold the entire UTF-8 string. If this is less than or equal to length, it means that the entire string has been stored in the buffer. If this is greater than length, it means that only part of the string has been stored in the buffer and that a buffer with the specified size would be required to hold the entire string. Note that since the individual characters UTF-8 can take from 1 to 4 bytes when stored, this can be used to indicate the required size for a re-sized buffer.
References packUTF8().
int32_t vrt::VRTMath::packUTF8 (void * ptr, int32_t off, const string & val, int32_t length)
Pack a UTF-8 string into a buffer.
If val is longer than len it will be truncated without explicit warning. If val is shorter than len it will be padded out with ASCII NUL characters to fill the length.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into array
val Value to pack [INPUT]
length Length of the string in the buffer.
Returns:
The length required to hold the entire UTF-8 string. If this is less than or equal to length, it means that the entire string has been stored in the buffer. If this is greater than length, it means that only part of the string has been stored in the buffer and that a buffer with the specified size would be required to hold the entire string. Note that since the individual characters UTF-8 can take from 1 to 4 bytes when stored, this can be used to indicate the required size for a re-sized buffer.
int32_t vrt::VRTMath::packUTF8 (vector< char > & buf, int32_t off, const wstring & val, int32_t length) [inline]
Pack a UTF-8 string into a buffer.
If val is longer than len it will be truncated without explicit warning. If val is shorter than len it will be padded out with ASCII NUL characters to fill the length.
Parameters:
buf Byte array of data [OUTPUT]
off Offset into array
val Value to pack [INPUT]
length Length of the string in the buffer.
Returns:
The length required to hold the entire UTF-8 string. If this is less than or equal to length, it means that the entire string has been stored in the buffer. If this is greater than length, it means that only part of the string has been stored in the buffer and that a buffer with the specified size would be required to hold the entire string. Note that since the individual characters UTF-8 can take from 1 to 4 bytes when stored, this can be used to indicate the required size for a re-sized buffer.
References packUTF8().
int32_t vrt::VRTMath::packUTF8 (void * ptr, int32_t off, const wstring & val, int32_t length)
Pack a UTF-8 string into a buffer.
If val is longer than len it will be truncated without explicit warning. If val is shorter than len it will be padded out with ASCII NUL characters to fill the length.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into array
val Value to pack [INPUT]
length Length of the string in the buffer.
Returns:
The length required to hold the entire UTF-8 string. If this is less than or equal to length, it means that the entire string has been stored in the buffer. If this is greater than length, it means that only part of the string has been stored in the buffer and that a buffer with the specified size would be required to hold the entire string. Note that since the individual characters UTF-8 can take from 1 to 4 bytes when stored, this can be used to indicate the required size for a re-sized buffer.
Referenced by lengthUTF8(), vrt::BasicVRTPacket::packPayloadUTF8(), and packUTF8().
void vrt::VRTMath::packUUID (vector< char > & buf, int32_t off, const UUID & val) [inline]
Pack a 16-byte UUID into a buffer.
Parameters:
buf byte array of data [OUTPUT]
off Offset into array
val value to pack [INPUT]
References vrt::UUID::getValue().
void vrt::VRTMath::packUUID (void * ptr, int32_t off, const UUID & val) [inline]
Pack a 16-byte UUID into a buffer.
Parameters:
ptr Pointer to packed byte array [OUTPUT]
off Offset into array
val value to pack [INPUT]
References vrt::UUID::getValue().
Referenced by vrt::BasicVRTPacket::packPayloadUUID().
template<typename T1 , typename T2 > T2 vrt::VRTMath::safecastT1ToT2 (T1 val) [inline]
Converts an from one type to another type of same size using memcpy.
templateparam T1 From-type templateparam T2 To-type
Parameters:
val Value to convert from (should have type T1)
Returns:
Value as type T2
References safecastT1ToT2().
Referenced by safecastT1ToT2().
double vrt::VRTMath::toDouble16 (int32_t radixPoint, int16_t bits) [inline]
Converts a 16-bit fixed point number to a float.
Parameters:
radixPoint The radix point of the number (1..15).
bits The bits representing the fixed-point number.
Returns:
The floating-point value of the fixed point number.
References toDouble16().
Referenced by toDouble16(), and toFloat16().
double vrt::VRTMath::toDouble32 (int32_t radixPoint, int32_t bits) [inline]
Converts a 32-bit fixed point number to a float.
Parameters:
radixPoint The radix point of the number (1..31).
bits The bits representing the fixed-point number.
Returns:
The floating-point value of the fixed point number.
References toDouble32().
Referenced by vrt::Geolocation::getAltitude(), vrt::Ephemeris::getAttitudeAlpha(), vrt::Ephemeris::getAttitudeBeta(), vrt::Ephemeris::getAttitudePhi(), vrt::Geolocation::getHeadingAngle(), vrt::Geolocation::getLatitude(), vrt::Geolocation::getLongitude(), vrt::Geolocation::getMagneticVariation(), vrt::Ephemeris::getPositionX(), vrt::Ephemeris::getPositionY(), vrt::Ephemeris::getPositionZ(), vrt::IndicatorFieldProvider::getRange(), vrt::Geolocation::getSpeedOverGround(), vrt::Geolocation::getTrackAngle(), vrt::Ephemeris::getVelocityX(), vrt::Ephemeris::getVelocityY(), vrt::Ephemeris::getVelocityZ(), vrt::SpectrumField::getWindowTimeDeltaFloat(), toDouble32(), and toFloat32().
double vrt::VRTMath::toDouble64 (int32_t radixPoint, int64_t bits) [inline]
Converts a 64-bit fixed point number to a float.
Parameters:
radixPoint The radix point of the number (1..63).
bits The bits representing the fixed-point number.
Returns:
The floating-point value of the fixed point number.
References toDouble64().
Referenced by vrt::IndicatorFieldProvider::getAuxBandwidth(), vrt::IndicatorFieldProvider::getAuxFrequency(), vrt::IndicatorFieldProvider::getBandOffsetIF(), vrt::IndicatorFieldProvider::getBandwidth(), vrt::IndicatorFieldProvider::getFrequencyIF(), vrt::IndicatorFieldProvider::getFrequencyOffsetRF(), vrt::IndicatorFieldProvider::getFrequencyRF(), vrt::SpectrumField::getResolution(), vrt::IndicatorFieldProvider::getSampleRate(), vrt::SpectrumField::getSpan(), toDouble64(), and toFloat64().
float vrt::VRTMath::toFloat16 (int32_t radixPoint, int16_t bits) [inline]
Converts a 16-bit fixed point number to a float.
Parameters:
radixPoint The radix point of the number (1..15).
bits The bits representing the fixed-point number.
Returns:
The floating-point value of the fixed point number.
References toDouble16(), and toFloat16().
Referenced by vrt::IndicatorFieldProvider::get3DPointingVectorAzimuth(), vrt::IndicatorFieldProvider::get3DPointingVectorElevation(), vrt::IndicatorFieldProvider::getAirTemperature(), vrt::IndicatorFieldProvider::getAuxGain1(), vrt::IndicatorFieldProvider::getAuxGain2(), vrt::IndicatorFieldProvider::getBitErrorRate(), vrt::IndicatorFieldProvider::getEbN0(), vrt::IndicatorFieldProvider::getGain1(), vrt::IndicatorFieldProvider::getGain2(), vrt::IndicatorFieldProvider::getNoiseFigure(), vrt::IndicatorFieldProvider::getOneDecibelCompressionPoint(), vrt::IndicatorFieldProvider::getPhaseOffset(), vrt::IndicatorFieldProvider::getPolarizationEllipticityAngle(), vrt::IndicatorFieldProvider::getPolarizationTiltAngle(), vrt::IndicatorFieldProvider::getReferenceLevel(), vrt::IndicatorFieldProvider::getSeaGroundTemperature(), vrt::IndicatorFieldProvider::getSecondOrderInputInterceptPoint(), vrt::IndicatorFieldProvider::getSNR(), vrt::IndicatorFieldProvider::getTemperature(), vrt::IndicatorFieldProvider::getThirdOrderInputInterceptPoint(), vrt::IndicatorFieldProvider::getThreshold1(), vrt::IndicatorFieldProvider::getThreshold2(), and toFloat16().
float vrt::VRTMath::toFloat32 (int32_t radixPoint, int32_t bits) [inline]
Converts a 32-bit fixed point number to a float.
Parameters:
radixPoint The radix point of the number (1..31).
bits The bits representing the fixed-point number.
Returns:
The floating-point value of the fixed point number.
References toDouble32(), and toFloat32().
Referenced by vrt::IndicatorFieldProvider::getHorizontalBeamwidth(), vrt::IndicatorFieldProvider::getVerticalBeamwidth(), and toFloat32().
float vrt::VRTMath::toFloat64 (int32_t radixPoint, int64_t bits) [inline]
Converts a 64-bit fixed point number to a float.
Parameters:
radixPoint The radix point of the number (1..63).
bits The bits representing the fixed-point number.
Returns:
The floating-point value of the fixed point number.
References toDouble64(), and toFloat64().
Referenced by toFloat64().
int16_t vrt::VRTMath::toHalf (float val) [inline]
Converts an IEEE 754 single-precision floating-point value to the bits equating to an IEEE 754-2008 half-precision (storage only) value.
    References:
      [1] IEEE 754-2008.
      [2] Jeroen van der Zijp. "Fast Half Float Conversions." November
          2008 (Revised September 2010).
          ftp://ftp.fox-toolkit.org/pub/fasthalffloatconversion.pdf
      [3] Free Software Foundation, Inc. "Using the GNU Compiler Collection
          (GCC)." 2013. [Section 6.12 "Half-Precision Floating Point."]
          http://gcc.gnu.org/onlinedocs/gcc/Half_002dPrecision.html
          [Last Accessed 5 Aug 2013]
      [4] Intel. "Intel C++ Compiler XE 13.1 User and Reference Guides."
          Document Number 323273-131US. 2013. ["Intrinsics for Converting
          Half Floats."]
          http://software.intel.com/sites/products/documentation/doclib/iss/2013/compiler/cpp-lin/GUID-23C8FF6D-3D66-4961-A3A0-E2A7DC874304.htm
          [Last Accessed 5 Aug 2013]
Parameters:
val The single-precision value.
Returns:
The bits representing the half-precision value.
References _toHalfInternal(), and toHalf().
Referenced by toHalf().
int32_t vrt::VRTMath::toInt16 (int32_t radixPoint, int16_t bits) [inline]
Converts a 16-bit fixed point number to an int.
Parameters:
radixPoint The radix point of the number (1..15).
bits The bits representing the fixed-point number.
Returns:
The integer value of the fixed point number.
References toInt16().
Referenced by toInt16(), and toLong16().
int32_t vrt::VRTMath::toInt32 (int32_t radixPoint, int32_t bits) [inline]
Converts a 32-bit fixed point number to an int.
Parameters:
radixPoint The radix point of the number (1..31).
bits The bits representing the fixed-point number.
Returns:
The integer value of the fixed point number.
References toInt32().
Referenced by toInt32(), and toLong32().
int32_t vrt::VRTMath::toInt64 (int32_t radixPoint, int64_t bits) [inline]
Converts a 64-bit fixed point number to an int.
Parameters:
radixPoint The radix point of the number (1..63).
bits The bits representing the fixed-point number.
Returns:
The integer value of the fixed point number.
References toInt64(), and toLong64().
Referenced by toInt64().
int64_t vrt::VRTMath::toLong16 (int32_t radixPoint, int16_t bits) [inline]
Converts a 16-bit fixed point number to a long.
Parameters:
radixPoint The radix point of the number (1..15).
bits The bits representing the fixed-point number.
Returns:
The integer value of the fixed point number.
References toInt16(), and toLong16().
Referenced by toLong16().
int64_t vrt::VRTMath::toLong32 (int32_t radixPoint, int32_t bits) [inline]
Converts a 32-bit fixed point number to a long.
Parameters:
radixPoint The radix point of the number (1..31).
bits The bits representing the fixed-point number.
Returns:
The integer value of the fixed point number.
References toInt32(), and toLong32().
Referenced by toLong32().
int64_t vrt::VRTMath::toLong64 (int32_t radixPoint, int64_t bits) [inline]
Converts a 64-bit fixed point number to a long.
Parameters:
radixPoint The radix point of the number (1..63).
bits The bits representing the fixed-point number.
Returns:
The integer value of the fixed point number.
References toLong64().
Referenced by toInt64(), and toLong64().
int64_t vrt::VRTMath::toVRTFloat (DataItemFormat form, int32_t dSize, double val)
Converts from an IEEE-754 double-precision floating-point value to the packed bits for a VRT floating-point.
Although VRT floating-point values can express many values in multiple ways within the binary form (e.g. 1/4 or 2/8) this function outputs the values in a "normalized form" where the output value will have a 1 in the most-significant-(non-sign-)bit of the mantissa, excepting for small values close to zero where the exponent is zero. This mirrors the behavior of IEEE-754 floating-point values, excepting that the highest bit is always present (not just for "denormal" values).
Since the range of VRT floating-point numbers is [0,1) (signed) or [-1,1) (unsigned) any values below/above that range will be converted to the smallest/largest value possible in that range. Any NaN values passed in will be converted to zero.
    References:
      [1] ANSI/VITA 49.0, Appendix D
      [2] IEEE-754
Parameters:
form The data item format. This must be one of the VRT floating-point formats.
dSize The data size in bits (2..63).
val The value to convert.
Returns:
The packed bits for the VRT floating-point number.
int32_t vrt::VRTMath::toVRTFloat32 (bool sign, int32_t eSize, int32_t dSize, double val)
Internal Use Only: Converts from an IEEE-754 double-precision floating-point value to the packed bits for a VRT floating-point without normal safety checks.
Parameters:
sign Is output signed?
eSize The number of exponent bits (1 to 6).
dSize The data size in bits (2..63).
val The value to convert.
int64_t vrt::VRTMath::toVRTFloat64 (bool sign, int32_t eSize, int32_t dSize, double val)
Internal Use Only: Converts from an IEEE-754 double-precision floating-point value to the packed bits for a VRT floating-point without normal safety checks.
Parameters:
sign Is output signed?
eSize The number of exponent bits (1 to 6).
dSize The data size in bits (2..63).
val The value to convert.
string vrt::VRTMath::unpackAscii (const vector< char > & buf, int32_t off, int32_t len) [inline]
Unpack a ASCII string from a buffer.
The string is assumed to be null-terminated in the event that the string is shorter than the allowable length.
Parameters:
buf byte array of data
off Offset into array
len length of the string in the buffer
Returns:
The unpacked value
References unpackAscii().
string vrt::VRTMath::unpackAscii (const void * ptr, int32_t off, int32_t len)
Unpack a ASCII string from a buffer.
The string is assumed to be null-terminated in the event that the string is shorter than the allowable length.
Parameters:
ptr pointer to byte array of data
off Offset into array
len length of the string in the buffer
Returns:
The unpacked value
Referenced by unpackAscii(), and vrt::BasicVRTPacket::unpackPayloadAscii().
int32_t vrt::VRTMath::unpackBits32 (const void * ptr, int32_t bitOffset, int32_t bitCount)
Internal Use Only: Reads bits from a buffer without safety checks.
int64_t vrt::VRTMath::unpackBits64 (const void * ptr, int32_t bitOffset, int32_t bitCount)
Internal Use Only: Reads bits from a buffer without safety checks.
bool vrt::VRTMath::unpackBoolean (const vector< char > & buf, int32_t off) [inline]
Unpack a boolean from a buffer.
Parameters:
buf byte array of data
off Offset into array
Returns:
The unpacked value
Exceptions:
VRTException If VRTConfig#getStrict() is true and the stored value is something other than -1, 0 or 1.
References unpackBoolean().
bool vrt::VRTMath::unpackBoolean (const void * ptr, int32_t off)
Unpack a boolean from a buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
Returns:
The unpacked value
Exceptions:
VRTException If VRTConfig#getStrict() is true and the stored value is something other than -1, 0 or 1.
Referenced by unpackBoolean(), and vrt::BasicVRTPacket::unpackPayloadBoolean().
boolNull vrt::VRTMath::unpackBoolNull (const vector< char > & buf, int32_t off) [inline]
Unpack a boolean from a buffer.
Parameters:
buf byte array of data
off Offset into array
Returns:
The unpacked value
Exceptions:
VRTException If VRTConfig#getStrict() is true and the stored value is something other than -1, 0 or 1.
References unpackBoolNull().
boolNull vrt::VRTMath::unpackBoolNull (const void * ptr, int32_t off)
Unpack a boolean from a buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
Returns:
The unpacked value
Exceptions:
VRTException If VRTConfig#getStrict() is true and the stored value is something other than -1, 0 or 1.
Referenced by unpackBoolNull(), and vrt::BasicVRTPacket::unpackPayloadBoolNull().
char vrt::VRTMath::unpackByte (const vector< char > & buf, int32_t off) [inline]
Unpack byte data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
Returns:
short value
References unpackByte().
char vrt::VRTMath::unpackByte (const void * ptr, int32_t off) [inline]
Unpack byte data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
Returns:
short value
References unpackByte().
Referenced by unpackByte(), and vrt::BasicVRTPacket::unpackPayloadByte().
void* vrt::VRTMath::unpackBytes (const vector< char > & buf, int32_t off, void * buffer, int32_t len) [inline]
Unpack an array of bytes from a buffer.
Parameters:
buf byte array of data [INPUT]
off Offset into array
buffer the output buffer [OUTPUT]
len length of the array in the buffer
Returns:
The output buffer.
References unpackBytes().
vector<char> vrt::VRTMath::unpackBytes (const vector< char > & buf, int32_t off, int32_t len) [inline]
Unpack an array of bytes from a buffer.
Parameters:
buf byte array of data
off Offset into array
len length of the array in the buffer
Returns:
The unpacked value
References unpackBytes().
Referenced by unpackBytes(), and vrt::BasicVRTPacket::unpackPayloadBytes().
double vrt::VRTMath::unpackDouble (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack double data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
double value
References unpackDouble().
double vrt::VRTMath::unpackDouble (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack double data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
double value
References unpackDouble().
Referenced by unpackDouble(), and vrt::BasicVRTPacket::unpackPayloadDouble().
float vrt::VRTMath::unpackFloat (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack float data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
float value
References unpackFloat().
float vrt::VRTMath::unpackFloat (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack float data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
float value
References unpackFloat().
Referenced by unpackFloat(), and vrt::BasicVRTPacket::unpackPayloadFloat().
InetAddress vrt::VRTMath::unpackInetAddr (const vector< char > & buf, int32_t off) [inline]
Unpack a 16-byte IPv6 address from a buffer.
Parameters:
buf byte array of data
off Offset into array
Returns:
The unpacked value
InetAddress vrt::VRTMath::unpackInetAddr (const void * ptr, int32_t off) [inline]
Unpack a 16-byte IPv6 address from a buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
Returns:
The unpacked value
Referenced by vrt::BasicVRTPacket::unpackPayloadInetAddr().
int32_t vrt::VRTMath::unpackInt (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack int data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
int value
References unpackInt().
int32_t vrt::VRTMath::unpackInt (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack int data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
int value
References unpackInt().
Referenced by vrt::BasicContextPacket::getContextIndicatorField0(), vrt::BasicVRLFrame::getFrameLength(), unpackInt(), vrt::BasicVRTPacket::unpackPayloadInt(), and unpackUInt().
int32_t vrt::VRTMath::unpackInt24 (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Internal Use Only: Unpack a 24-bit integer value as an int data from a byte buffer
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
int value
References unpackInt24().
int32_t vrt::VRTMath::unpackInt24 (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Internal Use Only: Unpack a 24-bit integer value as an int data from a byte buffer
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
int value
References unpackInt24().
Referenced by unpackInt24(), and unpackUInt24().
int64_t vrt::VRTMath::unpackLong (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack long data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
long value
References unpackLong().
int64_t vrt::VRTMath::unpackLong (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack long data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
long value
References unpackLong().
Referenced by unpackLong(), and vrt::BasicVRTPacket::unpackPayloadLong().
MetadataBlock vrt::VRTMath::unpackMetadata (const vector< char > & buf, int32_t off, int32_t len)
Unpack a metadata block into a buffer.
Parameters:
buf byte array of data
off Offset into array
len The length of the block
Referenced by vrt::BasicVRTPacket::unpackPayloadMetadata().
void vrt::VRTMath::unpackRecord (const vector< char > & buf, int32_t off, Record & val)
Pack a record into a buffer.
Parameters:
buf byte array of data
off Offset into array
val The record to pack
Referenced by vrt::BasicVRTPacket::unpackPayloadRecord().
int16_t vrt::VRTMath::unpackShort (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack short data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
short value
References unpackShort().
int16_t vrt::VRTMath::unpackShort (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack short data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
short value
References unpackShort().
Referenced by vrt::BasicVRTPacket::unpackPayloadShort(), unpackShort(), and unpackUShort().
TimeStamp vrt::VRTMath::unpackTimeStamp (const vector< char > & buf, int32_t off, IntegerMode epoch, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack an VITA 49.0 time stamp from a buffer.
Parameters:
buf byte array of data
off Offset into array
epoch The epoch to use (must be either IntegerMode_UTC or IntegerMode_GPS).
rep The byte representation to use
Returns:
The unpacked value
References unpackTimeStamp().
TimeStamp vrt::VRTMath::unpackTimeStamp (const void * ptr, int32_t off, IntegerMode epoch, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack an VITA 49.0 time stamp from a buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
epoch The epoch to use (must be either IntegerMode_UTC or IntegerMode_GPS).
rep The byte representation to use
Returns:
The unpacked value
References unpackUInt(), and unpackULong().
Referenced by vrt::BasicVRTPacket::unpackPayloadTimeStamp(), and unpackTimeStamp().
unsigned char vrt::VRTMath::unpackUByte (const vector< char > & buf, int32_t off) [inline]
Unpack unsigned byte data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
Returns:
short value
References unpackUByte().
unsigned char vrt::VRTMath::unpackUByte (const void * ptr, int32_t off) [inline]
Unpack unsigned byte data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
Returns:
short value
References unpackUByte().
Referenced by unpackUByte().
uint32_t vrt::VRTMath::unpackUInt (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack unsigned int data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
int value
References unpackInt(), and unpackUInt().
uint32_t vrt::VRTMath::unpackUInt (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack unsigned int data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
int value
References unpackUInt().
Referenced by unpackTimeStamp(), and unpackUInt().
uint32_t vrt::VRTMath::unpackUInt24 (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Internal Use Only: Unpack an unsigned 24-bit integer value as an int data from a byte buffer
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
int value
References unpackUInt24().
uint32_t vrt::VRTMath::unpackUInt24 (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Internal Use Only: Unpack an unsigned 24-bit integer value as an int data from a byte buffer
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
int value
References unpackInt24(), and unpackUInt24().
Referenced by unpackUInt24().
uint64_t vrt::VRTMath::unpackULong (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack unsigned long data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
long value
References unpackULong().
uint64_t vrt::VRTMath::unpackULong (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack unsigned long data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
long value
References unpackULong().
Referenced by unpackTimeStamp(), and unpackULong().
uint16_t vrt::VRTMath::unpackUShort (const vector< char > & buf, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack unsigned short data from a byte buffer.
Parameters:
buf byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
short value
References unpackShort(), and unpackUShort().
uint16_t vrt::VRTMath::unpackUShort (const void * ptr, int32_t off, ByteOrder rep = BIG_ENDIAN) [inline]
Unpack unsigned short data from a byte buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
rep The byte representation to use (BIG_ENDIAN or LITTLE_ENDIAN)
Returns:
short value
References unpackUShort().
Referenced by unpackUShort().
wstring vrt::VRTMath::unpackUTF8 (const vector< char > & buf, int32_t off, int32_t len, wchar_t replacement = '?') [inline]
Unpack a modified UTF-8 string from a buffer.
See the version of this method that takes in a void* for more details.
Parameters:
buf Byte array of data
off Offset into array
len Length of the string in the buffer
replacement The replacement character to use whenever a non UTF-8 character is encountered (typically '?'), if null an exception is thrown rather than replacing erroneous characters.
Returns:
The unpacked value.
Exceptions:
VRTException If the string found is not proper UTF-8 and replacement is null.
References unpackUTF8().
wstring vrt::VRTMath::unpackUTF8 (const void * ptr, int32_t off, int32_t len, wchar_t replacement = '?')
Unpack a modified UTF-8 string from a buffer.
The string is assumed to be null-terminated in the event that the string is shorter than the allowable length.
The modified UTF-8 format is identical to "normal" UTF-8 except that any embedded NUL values within the string are encoded as two-byte values (similar to what is done in the Java VM). Note that unlike the Java VM and some other 16-bit UTF representations in C++ this does NOT rely on "surrogate pairs" and supports the 1-/2-/3-/4-octet forms of UTF-8:
    Values in the 0x0001 to 0x007F range (ASCII, except NUL):
      Octet 1: [ 0 x x x x x x x ]
    Values in the 0x0080 to 0x07FF range and 0x0000 (ASCII NUL):
      Octet 1: [ 1 1 0 x x x x x ]
      Octet 2: [ 1 0 x x x x x x ]
    Values in the 0x0800 to 0xFFFF range:
      Octet 1: [ 1 1 1 0 x x x x ]
      Octet 2: [ 1 0 x x x x x x ]
      Octet 3: [ 1 0 x x x x x x ]
    Values in the 0x10000 to 0x10FFFF range:
      Octet 1: [ 1 1 1 1 0 x x x ]
      Octet 2: [ 1 0 x x x x x x ]
      Octet 3: [ 1 0 x x x x x x ]
      Octet 4: [ 1 0 x x x x x x ]
Parameters:
ptr Pointer to byte array of data
off Offset into array
len Length of the string in the buffer
replacement The replacement character to use whenever a non UTF-8 character is encountered (typically '?'), if null an exception is thrown rather than replacing erroneous characters.
Returns:
The unpacked value.
Exceptions:
VRTException If the string found is not proper UTF-8 and replacement is null.
Referenced by vrt::BasicVRTPacket::unpackPayloadUTF8(), and unpackUTF8().
UUID vrt::VRTMath::unpackUUID (const vector< char > & buf, int32_t off) [inline]
Unpack a 16-byte UUID from a buffer.
Parameters:
buf byte array of data
off Offset into array
Returns:
The unpacked value
References vrt::UUID::setValue().
UUID vrt::VRTMath::unpackUUID (const void * ptr, int32_t off) [inline]
Unpack a 16-byte UUID from a buffer.
Parameters:
ptr pointer to byte array of data
off Offset into array
Returns:
The unpacked value
References vrt::UUID::setValue().
Referenced by vrt::BasicVRTPacket::unpackPayloadUUID().