VRT: vrt::Utilities Namespace Reference
vrt::Utilities Namespace Reference
Various utility methods.
Functions
template<const VRTObject & >
void append (ostream &s, const char *prefix, const VRTObject &val, const char *suffix="")
Appends a value, assuming it is not null.
template<const string & >
void append (ostream &s, const char *prefix, const string &val, const char *suffix="")
Appends a value, assuming it is not null.
template<typename T >
void append (ostream &s, const char *prefix, const T val, const char *suffix="")
Appends a value, assuming it is not null.
template<const VRTObject & >
void append (ostream &s, const string &prefix, const VRTObject &val, const string &suffix=string(""))
Appends a value, assuming it is not null.
template<const string & >
void append (ostream &s, const string &prefix, const string &val, const string &suffix=string(""))
Appends a value, assuming it is not null.
template<typename T >
void append (ostream &s, const string &prefix, const T val, const string &suffix=string(""))
Appends a value, assuming it is not null.
template<typename T >
int32_t binarySearch (const vector< T > &vec, T val)
Searches a vector for a specified element.
int64_t currentTimeMillis ()
Gets the current time in milliseconds.
void dumpBytes (const void *ptr, int32_t len)
Dumps hex representation of bytes.
string format (const char *fmt,...)
Creates a string based on a format specifier and values.
int64_t fromStringClassID (string id)
Converts the string form of a VRT class identifier to a numeric.
int64_t fromStringDeviceID (string id)
Converts the string form of a device identifier to a numeric.
int32_t fromStringOUI (string oui)
Converts the string form of an IEEE Organizationally Unique Identifier (OUI) to a numeric.
string fromUTF8 (const wstring utf8, char replacement='?')
Converts a UTF8 string to an ASCII string.
void getCurrentSystemTime (int64_t &sec, int64_t &ps)
Internal Use Only: Gets the current time at maximum resolution (up to picoseconds).
double normalizeAngle180 (double deg)
Normalizes an angle such that it is on the range of [-180,+180).
double normalizeAngle360 (double deg)
Normalizes an angle such that it is on the range of [0,360).
void sleep (int64_t ms)
Sleeps for the given period and ignores any interrupted exceptions (EINTR).
void sleepUntil (int64_t ms)
Sleeps until the given system time and ignores any interrupted exceptions (EINTR).
void sleepUntil (TimeStamp ts)
Sleeps until the given system time and ignores any interrupted exceptions (EINTR).
boolNull toBoolean (const string &obj)
Converts a "boolean" string to a boolean value.
bool toBooleanValue (const string &obj)
Converts a "boolean" string to a boolean value.
string toHexString (int64_t val, int32_t bytes=8)
Quick conversion to hex string.
string toHexString (int32_t val, int32_t bytes=4)
Quick conversion to hex string.
string toLowerCase (const string &str)
Converts a string to lower-case.
string toStringClassID (int32_t oui, int16_t icc, int16_t pcc)
Converts the numeric form of a VRT class identifier to a string.
string toStringClassID (int64_t id)
Converts the numeric form of a VRT class identifier to a string.
string toStringDeviceID (int32_t oui, int16_t dev)
Converts the numeric form of a device identifier to a string.
string toStringDeviceID (int64_t id)
Converts the numeric form of a device identifier to a string.
string toStringOUI (int32_t oui)
Converts the numeric form of an IEEE Organizationally Unique Identifier (OUI) to a string.
string toUpperCase (const string &str)
Converts a string to upper-case.
string trim (const string &str)
Trims excess whitespace off the front and end of a string.
string trimNA (const string &str)
Trims excess whitespace off the front and end of a string and then returns "" if the result is "NA" or "N/A" (case insensitive).
Detailed Description
Various utility methods.
Function Documentation
template<const VRTObject & > void vrt::Utilities::append (ostream & s, const char * prefix, const VRTObject & val, const char * suffix = "") [inline]
Appends a value, assuming it is not null.
Parameters:
s (OUT) The output stream.
prefix (IN) The prefix to include ("" if n/a).
val (IN) The value.
suffix (IN) The suffix to include ("" if n/a).
template<const string & > void vrt::Utilities::append (ostream & s, const char * prefix, const string & val, const char * suffix = "") [inline]
Appends a value, assuming it is not null.
Parameters:
s (OUT) The output stream.
prefix (IN) The prefix to include ("" if n/a).
val (IN) The value.
suffix (IN) The suffix to include ("" if n/a).
template<typename T > void vrt::Utilities::append (ostream & s, const char * prefix, const T val, const char * suffix = "") [inline]
Appends a value, assuming it is not null.
Parameters:
s (OUT) The output stream.
prefix (IN) The prefix to include ("" if n/a).
val (IN) The value.
suffix (IN) The suffix to include ("" if n/a).
template<const VRTObject & > void vrt::Utilities::append (ostream & s, const string & prefix, const VRTObject & val, const string & suffix = string("")) [inline]
Appends a value, assuming it is not null.
Parameters:
s (OUT) The output stream.
prefix (IN) The prefix to include ("" if n/a).
val (IN) The value.
suffix (IN) The suffix to include ("" if n/a).
template<const string & > void vrt::Utilities::append (ostream & s, const string & prefix, const string & val, const string & suffix = string("")) [inline]
Appends a value, assuming it is not null.
Parameters:
s (OUT) The output stream.
prefix (IN) The prefix to include ("" if n/a).
val (IN) The value.
suffix (IN) The suffix to include ("" if n/a).
template<typename T > void vrt::Utilities::append (ostream & s, const string & prefix, const T val, const string & suffix = string("")) [inline]
Appends a value, assuming it is not null.
Parameters:
s (OUT) The output stream.
prefix (IN) The prefix to include ("" if n/a).
val (IN) The value.
suffix (IN) The suffix to include ("" if n/a).
template<typename T > int32_t vrt::Utilities::binarySearch (const vector< T > & vec, T val) [inline]
Searches a vector for a specified element.
The name of this function is patterned after the Java function (as this provides some consistency between the Java and C++ version), but the implementation is entirely different.
Parameters:
vec The vector to search.
val The value to look for.
Returns:
Non-negative value indicating the index if found or a negative value indicating one less than the insertion point times -1.
int64_t vrt::Utilities::currentTimeMillis ()
Gets the current time in milliseconds.
This function provides an interface that is fairly easy to use regardless of the platform and is similar to System.currentTimeMillis() in Java.
void vrt::Utilities::dumpBytes (const void * ptr, int32_t len) [inline]
Dumps hex representation of bytes.
Parameters:
ptr Pointer to start of memory (i.e. buffer) to be dumped
len Number of bytes to dump
string vrt::Utilities::format (const char * fmt, ...)
Creates a string based on a format specifier and values.
This is essentially a variant of snprintf(..) that returns a new string rather than setting a char* buffer.
Parameters:
fmt The format specifier.
... The remaining format values.
Referenced by vrt::IndicatorFieldProvider::getChildrenSIDString(), vrt::IndicatorFieldProvider::getCitedSIDString(), vrt::IndicatorFieldProvider::getParentsSIDString(), and vrt::IndicatorFieldProvider::getSiblingsSIDString().
int64_t vrt::Utilities::fromStringClassID (string id)
Converts the string form of a VRT class identifier to a numeric.
Parameters:
id The string form of the class identifier.
Returns:
The 56-bit class ID.
int64_t vrt::Utilities::fromStringDeviceID (string id)
Converts the string form of a device identifier to a numeric.
Parameters:
id The string form of the device identifier.
Returns:
The numeric form of the device identifier.
Referenced by vrt::IndicatorFieldProvider::setDeviceID().
int32_t vrt::Utilities::fromStringOUI (string oui)
Converts the string form of an IEEE Organizationally Unique Identifier (OUI) to a numeric.
Parameters:
oui The string form of the OUI (IEEE standard format).
Returns:
The 24-bit OUI.
Referenced by vrt::AbstractGeolocation::setManufacturerID().
string vrt::Utilities::fromUTF8 (const wstring utf8, char replacement = '?')
Converts a UTF8 string to an ASCII string.
Parameters:
utf8 The UFT8 sequence to convert.
replacement The replacement character to use if a non-ASCII character is encountered (typically '?').
Returns:
An applicable string.
Exceptions:
VRTException If replacement is null and a non-ASCII character is encountered.
void vrt::Utilities::getCurrentSystemTime (int64_t & sec, int64_t & ps)
Internal Use Only: Gets the current time at maximum resolution (up to picoseconds).
This function uses gettimeofday(..) *or* clock_gettime(..) *or* another other similar function to get the current system time in the "most optimal" manner.
General users should NOT use this function since it is subject to change without notice. The currentTimeMillis() is provided for more general use.
double vrt::Utilities::normalizeAngle180 (double deg)
Normalizes an angle such that it is on the range of [-180,+180).
Parameters:
deg The input angle in degrees.
Returns:
The corresponding angle in the range [-180,+180).
double vrt::Utilities::normalizeAngle360 (double deg)
Normalizes an angle such that it is on the range of [0,360).
Parameters:
deg The input angle in degrees.
Returns:
The corresponding angle in the range [0,360).
void vrt::Utilities::sleep (int64_t ms)
Sleeps for the given period and ignores any interrupted exceptions (EINTR).
Parameters:
ms The time to sleep in ms.
void vrt::Utilities::sleepUntil (int64_t ms)
Sleeps until the given system time and ignores any interrupted exceptions (EINTR).
Parameters:
ms The system time in ms.
void vrt::Utilities::sleepUntil (TimeStamp ts)
Sleeps until the given system time and ignores any interrupted exceptions (EINTR).
Parameters:
ts The time stamp to wait until.
boolNull vrt::Utilities::toBoolean (const string & obj)
Converts a "boolean" string to a boolean value.
The following (case-insensitive) conversions are used:
    _NULL:       ""
    _TRUE:       "true",  "t", "1", "yes", "y", "on"
    _FALSE:      "false", "f", "0", "no",  "n", "off"
Parameters:
obj The object to convert.
Returns:
_NULL, _TRUE, or _FALSE as appropriate.
Referenced by toBooleanValue().
bool vrt::Utilities::toBooleanValue (const string & obj) [inline]
Converts a "boolean" string to a boolean value.
The is identical to toBoolean except that it returns false in place of null.
Parameters:
obj The object to convert.
Returns:
true or false as appropriate.
References toBoolean().
Referenced by vrt::NetUtilities::getSocketOptionBool().
string vrt::Utilities::toHexString (int64_t val, int32_t bytes = 8)
Quick conversion to hex string.
Parameters:
val The value to convert.
bytes The number of bytes to consider.
string vrt::Utilities::toHexString (int32_t val, int32_t bytes = 4)
Quick conversion to hex string.
Parameters:
val The value to convert.
bytes The number of bytes to consider.
Referenced by toStringClassID(), and toStringDeviceID().
string vrt::Utilities::toLowerCase (const string & str)
Converts a string to lower-case.
Parameters:
str The input string.
Returns:
The lower-case version of the given string.
string vrt::Utilities::toStringClassID (int32_t oui, int16_t icc, int16_t pcc) [inline]
Converts the numeric form of a VRT class identifier to a string.
Parameters:
oui The 24-bit OUI (top 8 bits of the int must be 0x00).
icc The 16-bit (unsigned) information class code (ICC).
pcc The 16-bit (unsigned) packet class code (PCC).
Returns:
The string form of the class identifier.
References toHexString(), and toStringOUI().
string vrt::Utilities::toStringClassID (int64_t id)
Converts the numeric form of a VRT class identifier to a string.
Parameters:
id The 56-bit class ID (top 8 bits of the long must be 0x00).
Returns:
The string form of the class identifier.
string vrt::Utilities::toStringDeviceID (int32_t oui, int16_t dev) [inline]
Converts the numeric form of a device identifier to a string.
Parameters:
oui The 24-bit manufacturer OUI (top 8 bits of the int must be 0x00).
dev The 16-bit (unsigned) device identifier.
Returns:
The string form of the device identifier.
References toHexString(), and toStringOUI().
string vrt::Utilities::toStringDeviceID (int64_t id)
Converts the numeric form of a device identifier to a string.
Parameters:
id The 40-bit manufacturer OUI stored in a 64-bit space as: 0x00xxxxxx0000yyyy where xxxxxx is the 24-bit manufacturer OUI and yyyy is the 16-bit device ID.
Returns:
The string form of the device identifier.
Referenced by vrt::IndicatorFieldProvider::getDeviceID().
string vrt::Utilities::toStringOUI (int32_t oui)
Converts the numeric form of an IEEE Organizationally Unique Identifier (OUI) to a string.
Parameters:
oui The 24-bit OUI (top 8 bits of the int must be 0x00).
Returns:
The string form of the OUI (IEEE standard format).
Referenced by vrt::AbstractGeolocation::getManufacturerID(), toStringClassID(), and toStringDeviceID().
string vrt::Utilities::toUpperCase (const string & str)
Converts a string to upper-case.
Parameters:
str The input string.
Returns:
The upper-case version of the given string.
string vrt::Utilities::trim (const string & str)
Trims excess whitespace off the front and end of a string.
This is modeled after java.lang.String.trim() and is used within the auto-generated packet code.
Parameters:
str The input string.
Returns:
The trimmed output or str if no trimming is required.
string vrt::Utilities::trimNA (const string & str)
Trims excess whitespace off the front and end of a string and then returns "" if the result is "NA" or "N/A" (case insensitive).
Parameters:
str The input string.
Returns:
The trimmed output or str if no trimming is required.