VRT: vrt::IndicatorFields Namespace Reference
vrt::IndicatorFields Namespace Reference
Context/Control Indicator Fields and functions to retrieve CIF number and field bitmask from the enumerated value, as well as the reverse.
Namespaces
namespace protected_CIF0
Internal Use Only: Bitmasks for CIF0 fields (Legacy Fields and CIF Enables).
namespace protected_CIF1
Internal Use Only: Bitmasks for CIF1 fields (Spatial, Signal, Spectral, I/O, and Control fields)
namespace protected_CIF2
Internal Use Only: Bitmasks for CIF2 fields (Identifiers (tags)).
namespace protected_CIF3
Internal Use Only: Bitmasks for CIF3 fields (Temporal and Environmental fields).
namespace protected_CIF7
Internal Use Only: Bitmasks for CIF7 fields (Attributes).
Typedefs
typedef IndicatorFieldEnum IndicatorFieldEnum_t
Typedef of enumeration of all Context/Control Indicator Fields.
Enumerations
enum IndicatorFieldEnum {
CIF_NULL = -1, CIF0_RESERVED_0 = 0, CIF1_ENABLE, CIF2_ENABLE,
CIF3_ENABLE, CIF0_RESERVED_4, CIF0_RESERVED_5, CIF0_RESERVED_6,
CIF7_ENABLE, CONTEXT_ASOC, GPS_ASCII, EPHEM_REF,
REL_EPHEM, ECEF_EPHEM, INS_EPHEM, GPS_EPHEM,
DATA_FORMAT, STATE_EVENT, DEVICE_ID, TEMPERATURE,
TIME_CALIB, TIME_ADJUST, SAMPLE_RATE, OVER_RANGE,
GAIN, REF_LEVEL, IF_OFFSET, RF_OFFSET,
RF_FREQ, IF_FREQ, BANDWIDTH, REF_POINT,
CHANGE_IND, CIF1_RESERVED_0 = 32, BUFFER_SZ, VER_BLD_CODE,
V49_COMPL, HEALTH_STATUS, DISCRETE_IO64, DISCRETE_IO32,
INDEX_LIST, CIF1_RESERVED_8, SECTOR_SCN_STP, SPECTRUM,
CIFS_ARRAY, CIF1_RESERVED_12, AUX_BANDWIDTH, AUX_GAIN,
AUX_FREQUENCY, SNR_NOISE, ICPT_PTS_2_3, COMPRESS_PT,
THRESHOLD, EB_NO_BER, CIF1_RESERVED_21, CIF1_RESERVED_22,
CIF1_RESERVED_23, RANGE, BEAMWIDTH, SPATIAL_REF_TYPE,
SPATIAL_SCAN_TYPE, PNT_VECT_3D_ST, PNT_VECT_3D_SI, POLARIZATION,
PHASE, CIF2_RESERVED_0 = 64, CIF2_RESERVED_1, CIF2_RESERVED_2,
RF_FOOTPRINT_RANGE, RF_FOOTPRINT, COMM_PRIORITY_ID, FUNCT_PRIORITY_ID,
EVENT_ID, MODE_ID, FUNCTION_ID, MODULATION_TYPE,
MODULATION_CLASS, EMS_DEVICE_INSTANCE, EMS_DEVICE_TYPE, EMS_DEVICE_CLASS,
PLATFORM_DISPLAY, PLATFORM_INSTANCE, PLATFORM_CLASS, OPERATOR,
COUNTRY_CODE, TRACK_ID, INFORMATION_SOURCE, CONTROLLER_UUID,
CONTROLLER_ID, CONTROLLEE_UUID, CONTROLLEE_ID, CITED_MESSAGE_ID,
CHILDREN_SID, PARENTS_SID, SIBLINGS_SID, CITED_SID,
BIND, CIF3_RESERVED_0 = 96, NETWORK_ID, TROPOSPHERIC_STATE,
SEA_AND_SWELL_STATE, BAROMETRIC_PRESSURE, HUMIDITY, SEA_GROUND_TEMP,
AIR_TEMP, CIF3_RESERVED_8, CIF3_RESERVED_9, CIF3_RESERVED_10,
CIF3_RESERVED_11, CIF3_RESERVED_12, CIF3_RESERVED_13, CIF3_RESERVED_14,
CIF3_RESERVED_15, SHELF_LIFE, AGE, CIF3_RESERVED_18,
CIF3_RESERVED_19, JITTER, DWELL, DURATION,
PERIOD, PULSE_WIDTH, OFFSET_TIME, FALL_TIME,
RISE_TIME, CIF3_RESERVED_28, CIF3_RESERVED_29, TIMESTAMP_SKEW,
TIMESTAMP_DETAILS, CIF4_RESERVED_0 = 128, CIF5_RESERVED_0 = 160, CIF6_RESERVED_0 = 192,
CIF7_RESERVED_0 = 224, CIF7_RESERVED_1, CIF7_RESERVED_2, CIF7_RESERVED_3,
CIF7_RESERVED_4, CIF7_RESERVED_5, CIF7_RESERVED_6, CIF7_RESERVED_7,
CIF7_RESERVED_8, CIF7_RESERVED_9, CIF7_RESERVED_10, CIF7_RESERVED_11,
CIF7_RESERVED_12, CIF7_RESERVED_13, CIF7_RESERVED_14, CIF7_RESERVED_15,
CIF7_RESERVED_16, CIF7_RESERVED_17, CIF7_RESERVED_18, BELIEF,
PROBABILITY, THIRD_DERIVATIVE, SECOND_DERIVATIVE, FIRST_DERIVATIVE,
ACCURACY, PRECISION, MIN_VALUE, MAX_VALUE,
STANDARD_DEVIATION, MEDIAN_VALUE, AVERAGE_VALUE, CURRENT_VALUE
}
Enumeration of all Context/Control Indicator Fields.
Functions
int32_t getCIFBitMask (IndicatorFieldEnum_t f)
Get the 1-hot bit mask from IndicatorFieldEnum_t The top three (most-significant) bits of each 8-bit IndicatorFieldEnum_t are the CIF number The bottom five (least-significant) bits of each 8-bit IndicatorFieldEnum_t are the bit number CIF#: 0b11100000 = 0xE0 | Right-shift by 5, i.e.
int8_t getCIFBitNumber (IndicatorFieldEnum_t f)
Get the CIF bit number from the IndicatorFieldEnum_t The top three (most-significant) bits of each 8-bit IndicatorFieldEnum_t are the CIF number The bottom five (least-significant) bits of each 8-bit IndicatorFieldEnum_t are the bit number CIF#: 0b11100000 = 0xE0 | Right-shift by 5, i.e.
IndicatorFieldEnum_t getCIFEnum (int8_t cif, int8_t bit)
Get the IndicatorFieldEnum from the CIF number and CIF bit number The top three (most-significant) bits of each 8-bit IndicatorFieldEnum_t are the CIF number The bottom five (least-significant) bits of each 8-bit IndicatorFieldEnum_t are the bit number CIF#: 0b11100000 = 0xE0 | Left-shift by 5, i.e.
int8_t getCIFNumber (IndicatorFieldEnum_t f)
Get the CIF number from the IndicatorFieldEnum_t The top three (most-significant) bits of each 8-bit IndicatorFieldEnum_t are the CIF number The bottom five (least-significant) bits of each 8-bit IndicatorFieldEnum_t are the bit number CIF#: 0b11100000 = 0xE0 | Right-shift by 5, i.e.
Detailed Description
Context/Control Indicator Fields and functions to retrieve CIF number and field bitmask from the enumerated value, as well as the reverse.
Typedef Documentation
typedef IndicatorFieldEnum vrt::IndicatorFields::IndicatorFieldEnum_t
Typedef of enumeration of all Context/Control Indicator Fields.
Enumeration Type Documentation
enum vrt::IndicatorFields::IndicatorFieldEnum
Enumeration of all Context/Control Indicator Fields.
The enumerated value can be programatically converted to the CIF# and bitmask. The most significant 3 bits (left-most) are the CIF#, and the least significant 5 bits are the number of left shifts to apply to 0x1 to get the one-hot bitmask for the field. As such, a right-shift of the enumerated value (which is mathematically equivalent to a divide by 32) provides the CIF#, and a bitwise AND of the enumerated value with 0x1F (which is mathematically equivalent to a modulo 32) provides the number of bit shifts needed to produce the bitmask. The comments for each enumeration present this information as well in the following form:
<Field Key> <Bit #> <Description of field> (<CIF#>,<Bitmask>) <==> <CIF# bits> <Shift# bits> = <Enumerated Value>
Note that there are gaps in the enumrated values that are reserved for potential future CIFs 4, 5, and 6.
Enumerator:
CIF_NULL
NULL.
CIF0_RESERVED_0
Bit 0 Reserved (0,0x00000001) <==> 000 00000 = 0.
CIF1_ENABLE
Bit 1 CIF1 Enable (0,0x00000002) <==> 000 00001 = 1.
CIF2_ENABLE
Bit 2 CIF2 Enable (0,0x00000004) <==> 000 00010 = 2.
CIF3_ENABLE
Bit 3 CIF3 Enable (0,0x00000008) <==> 000 00011 = 3.
CIF0_RESERVED_4
Bit 4 Reserved (0,0x00000010) <==> 000 00100 = 4.
CIF0_RESERVED_5
Bit 5 Reserved (0,0x00000020) <==> 000 00101 = 5.
CIF0_RESERVED_6
Bit 6 Reserved (0,0x00000040) <==> 000 00110 = 6.
CIF7_ENABLE
Bit 7 Field Attributes Enable (0,0x00000080) <==> 000 00111 = 7.
CONTEXT_ASOC
Bit 8 Context Association Lists (0,0x00000100) <==> 000 01000 = 8.
GPS_ASCII
Bit 9 GPS ASCII (0,0x00000200) <==> 000 01001 = 9.
EPHEM_REF
Bit 10 Ephemeris Ref ID (0,0x00000400) <==> 000 01010 = 10.
REL_EPHEM
Bit 11 Relative Ephemeris (0,0x00000800) <==> 000 01011 = 11.
ECEF_EPHEM
Bit 12 ECEF Ephemeris (0,0x00001000) <==> 000 01100 = 12.
INS_EPHEM
Bit 13 Formatted INS (0,0x00002000) <==> 000 01101 = 13.
GPS_EPHEM
Bit 14 Formatted GPS (0,0x00004000) <==> 000 01110 = 14.
DATA_FORMAT
Bit 15 Signal Data Packet Payload Format (0,0x00008000) <==> 000 01111 = 15.
STATE_EVENT
Bit 16 State/Event Indicators (0,0x00010000) <==> 000 10000 = 16.
DEVICE_ID
Bit 17 Device Identifier (0,0x00020000) <==> 000 10001 = 17.
TEMPERATURE
Bit 18 Temperature (0,0x00040000) <==> 000 10010 = 18.
TIME_CALIB
Bit 19 Timestamp Calibration Time (0,0x00080000) <==> 000 10011 = 19.
TIME_ADJUST
Bit 20 Timestamp Adjustment (0,0x00100000) <==> 000 10100 = 20.
SAMPLE_RATE
Bit 21 Sample Rate (0,0x00200000) <==> 000 10101 = 21.
OVER_RANGE
Bit 22 Over-range Count (0,0x00400000) <==> 000 10110 = 22.
GAIN
Bit 23 Gain (0,0x00800000) <==> 000 10111 = 23.
REF_LEVEL
Bit 24 Reference Level (0,0x01000000) <==> 000 11000 = 24.
IF_OFFSET
Bit 25 IF Band Offset (0,0x02000000) <==> 000 11001 = 25.
RF_OFFSET
Bit 26 RF Reference Frequency Offset (0,0x04000000) <==> 000 11010 = 26.
RF_FREQ
Bit 27 RF Reference Frequency (0,0x08000000) <==> 000 11011 = 27.
IF_FREQ
Bit 28 IF Reference Frequency (0,0x10000000) <==> 000 11100 = 28.
BANDWIDTH
Bit 29 Bandwidth (0,0x20000000) <==> 000 11101 = 29.
REF_POINT
Bit 30 Reference Point Indentifier (0,0x40000000) <==> 000 11110 = 30.
CHANGE_IND
Bit 31 Context Field Change Indicator (0,0x80000000) <==> 000 11111 = 31.
CIF1_RESERVED_0
Bit 0 Reserved (1,0x00000001) <==> 001 00000 = 32.
BUFFER_SZ
Bit 1 Buffer Size (1,0x00000002) <==> 001 00001 = 33.
VER_BLD_CODE
Bit 2 Version and Build Code (1,0x00000004) <==> ...
V49_COMPL
Bit 3 V49 Spec Compliance (1,0x00000008).
HEALTH_STATUS
Bit 4 Health Status (1,0x00000010).
DISCRETE_IO64
Bit 5 Distrete I/O (64-bit) (1,0x00000020).
DISCRETE_IO32
Bit 6 Discrete I/O (32-bit) (1,0x00000040).
INDEX_LIST
Bit 7 Index List (1,0x00000080).
CIF1_RESERVED_8
Bit 8 Reserved (1,0x00000100).
SECTOR_SCN_STP
Bit 9 Sector Scan/Step (1,0x00000200).
SPECTRUM
Bit 10 Spectrum (1,0x00000400).
CIFS_ARRAY
Bit 11 Array of CIFS (1,0x00000800).
CIF1_RESERVED_12
Bit 12 Reserved (1,0x00001000).
AUX_BANDWIDTH
Bit 13 Aux Bandwidth (1,0x00002000).
AUX_GAIN
Bit 14 Aux Gain (1,0x00004000).
AUX_FREQUENCY
Bit 15 Aux Frequency (1,0x00008000).
SNR_NOISE
Bit 16 SNR/Noise Figure (1,0x00010000).
ICPT_PTS_2_3
Bit 17 2nd and 3rd-Order Intercept Points (1,0x00020000).
COMPRESS_PT
Bit 18 Compression Point (1,0x00040000).
THRESHOLD
Bit 19 Threshold (1,0x00080000).
EB_NO_BER
Bit 20 Eb/No BER (1,0x00100000).
CIF1_RESERVED_21
Bit 21 Reserved (1,0x00200000).
CIF1_RESERVED_22
Bit 22 Reserved (1,0x00400000).
CIF1_RESERVED_23
Bit 23 Reserved (1,0x00800000).
RANGE
Bit 24 Range (Distance) (1,0x01000000).
BEAMWIDTH
Bit 25 Beamwidth (1,0x02000000).
SPATIAL_REF_TYPE
Bit 26 Spatial Reference Type (1,0x04000000).
SPATIAL_SCAN_TYPE
Bit 27 Spatial Scan Type (1,0x08000000).
PNT_VECT_3D_ST
Bit 28 2-D Pointing Angle (structured) (1,0x10000000).
PNT_VECT_3D_SI
Bit 29 2-D Pointing Angle (simple) (1,0x20000000).
POLARIZATION
Bit 30 Polarization (1,0x40000000).
PHASE
Bit 31 Phase (1,0x80000000).
CIF2_RESERVED_0
Bit 0 Reserved (2,0x00000001) <==> 010 00000 = 64.
CIF2_RESERVED_1
Bit 1 Reserved (2,0x00000002).
CIF2_RESERVED_2
Bit 2 Reserved (2,0x00000004).
RF_FOOTPRINT_RANGE
Bit 3 RF Footprint Range (2,0x00000008).
RF_FOOTPRINT
Bit 4 RF Footprint (2,0x00000010).
COMM_PRIORITY_ID
Bit 5 Communication Priority ID (2,0x00000020).
FUNCT_PRIORITY_ID
Bit 6 Function Priority ID (2,0x00000040).
EVENT_ID
Bit 7 Event ID (2,0x00000080).
MODE_ID
Bit 8 Mode ID (2,0x00000100) <==> 010 01000 = 72.
FUNCTION_ID
Bit 9 Function ID (2,0x00000200).
MODULATION_TYPE
Bit 10 Modulation Type (2,0x00000400).
MODULATION_CLASS
Bit 11 Modulation Class (2,0x00000800).
EMS_DEVICE_INSTANCE
Bit 12 EMS Device Instance (2,0x00001000).
EMS_DEVICE_TYPE
Bit 13 EMS Device Type (2,0x00002000).
EMS_DEVICE_CLASS
Bit 14 EMS Device Class (2,0x00004000).
PLATFORM_DISPLAY
Bit 15 Platform Display (2,0x00008000).
PLATFORM_INSTANCE
Bit 16 Platform Instance (2,0x00010000).
PLATFORM_CLASS
Bit 17 Platform Class (2,0x00020000).
OPERATOR
Bit 18 Operator (2,0x00040000).
COUNTRY_CODE
Bit 19 Country Code (2,0x00080000).
TRACK_ID
Bit 20 Track ID (2,0x00100000).
INFORMATION_SOURCE
Bit 21 Information Source (2,0x00200000).
CONTROLLER_UUID
Bit 22 Controller UUID (2,0x00400000).
CONTROLLER_ID
Bit 23 Controller ID (2,0x00800000).
CONTROLLEE_UUID
Bit 24 Controllee UUID (2,0x01000000).
CONTROLLEE_ID
Bit 25 Controllee ID (2,0x02000000).
CITED_MESSAGE_ID
Bit 26 Cited Message ID (2,0x04000000).
CHILDREN_SID
Bit 27 Child(ren) SID (2,0x08000000).
PARENTS_SID
Bit 28 Parent(s) SID (2,0x10000000).
SIBLINGS_SID
Bit 29 Sibling(s) SID (2,0x20000000).
CITED_SID
Bit 30 Cited SID (2,0x40000000).
BIND
Bit 31 Bind (2,0x80000000).
CIF3_RESERVED_0
Bit 0 Reserved (3,0x00000001) <==> 011 00000 = 96.
NETWORK_ID
Bit 1 Network ID (3,0x00000002).
TROPOSPHERIC_STATE
Bit 2 Tropospheric State (3,0x00000004).
SEA_AND_SWELL_STATE
Bit 3 Sea and Swell State (3,0x00000008).
BAROMETRIC_PRESSURE
Bit 4 Barometric Pressure (3,0x00000010).
HUMIDITY
Bit 5 Humidity (3,0x00000020).
SEA_GROUND_TEMP
Bit 6 Sea/Ground Temperature (3,0x00000040).
AIR_TEMP
Bit 7 Air Temperature (3,0x00000080).
CIF3_RESERVED_8
Bit 8 Reserved (3,0x00000100).
CIF3_RESERVED_9
Bit 9 Reserved (3,0x00000200).
CIF3_RESERVED_10
Bit 10 Reserved (3,0x00000400).
CIF3_RESERVED_11
Bit 11 Reserved (3,0x00000800).
CIF3_RESERVED_12
Bit 12 Reserved (3,0x00001000).
CIF3_RESERVED_13
Bit 13 Reserved (3,0x00002000).
CIF3_RESERVED_14
Bit 14 Reserved (3,0x00004000).
CIF3_RESERVED_15
Bit 15 Reserved (3,0x00008000).
SHELF_LIFE
Bit 16 Shelf Life (3,0x00010000).
AGE
Bit 17 Age (3,0x00020000).
CIF3_RESERVED_18
Bit 18 Reserved (3,0x00040000).
CIF3_RESERVED_19
Bit 19 Reserved (3,0x00080000).
JITTER
Bit 20 Jitter (3,0x00100000).
DWELL
Bit 21 Dwell (3,0x00200000).
DURATION
Bit 22 Duration (3,0x00400000).
PERIOD
Bit 23 Period (3,0x00800000).
PULSE_WIDTH
Bit 24 Pulse Width (3,0x01000000).
OFFSET_TIME
Bit 25 Offset Time (3,0x02000000).
FALL_TIME
Bit 26 Fall Time (3,0x04000000).
RISE_TIME
Bit 27 Rise Time (3,0x08000000).
CIF3_RESERVED_28
Bit 28 Reserved (3,0x10000000).
CIF3_RESERVED_29
Bit 29 Reserved (3,0x20000000).
TIMESTAMP_SKEW
Bit 30 Timestamp Skew (3,0x40000000).
TIMESTAMP_DETAILS
Bit 31 Timestamp Details (3,0x80000000) <==> 011 11111 = 127.
CIF4_RESERVED_0
Bit 0 Reserved (4,0x00000001) <==> 100 00000 = 128.
CIF5_RESERVED_0
Bit 0 Reserved (5,0x00000001) <==> 101 00000 = 160.
CIF6_RESERVED_0
Bit 0 Reserved (6,0x00000001) <==> 110 00000 = 192.
CIF7_RESERVED_0
Bit 0 Reserved (7,0x00000001) <==> 111 00000 = 224.
CIF7_RESERVED_1
Bit 1 Reserved (7,0x00000002).
CIF7_RESERVED_2
Bit 2 Reserved (7,0x00000004).
CIF7_RESERVED_3
Bit 3 Reserved (7,0x00000008).
CIF7_RESERVED_4
Bit 4 Reserved (7,0x00000010).
CIF7_RESERVED_5
Bit 5 Reserved (7,0x00000020).
CIF7_RESERVED_6
Bit 6 Reserved (7,0x00000040).
CIF7_RESERVED_7
Bit 7 Reserved (7,0x00000080).
CIF7_RESERVED_8
Bit 8 Reserved (7,0x00000100).
CIF7_RESERVED_9
Bit 9 Reserved (7,0x00000200).
CIF7_RESERVED_10
Bit 10 Reserved (7,0x00000400).
CIF7_RESERVED_11
Bit 11 Reserved (7,0x00000800).
CIF7_RESERVED_12
Bit 12 Reserved (7,0x00001000).
CIF7_RESERVED_13
Bit 13 Reserved (7,0x00002000).
CIF7_RESERVED_14
Bit 14 Reserved (7,0x00004000).
CIF7_RESERVED_15
Bit 15 Reserved (7,0x00008000).
CIF7_RESERVED_16
Bit 16 Reserved (7,0x00010000).
CIF7_RESERVED_17
Bit 17 Reserved (7,0x00020000).
CIF7_RESERVED_18
Bit 18 Reserved (7,0x00040000).
BELIEF
Bit 19 Belief (7,0x00080000).
PROBABILITY
Bit 20 Probability (7,0x00100000).
THIRD_DERIVATIVE
Bit 21 3rd Derivative (7,0x00200000).
SECOND_DERIVATIVE
Bit 22 2nd Derivative (Accelleration) (7,0x00400000).
FIRST_DERIVATIVE
Bit 23 1st Derivative (Velocity) (7,0x00800000).
ACCURACY
Bit 24 Accuracy (7,0x01000000).
PRECISION
Bit 25 Precision (7,0x02000000).
MIN_VALUE
Bit 26 Min Value (7,0x04000000).
MAX_VALUE
Bit 27 Max Value (7,0x08000000).
STANDARD_DEVIATION
Bit 28 Standard Deviation (7,0x10000000).
MEDIAN_VALUE
Bit 29 Median Value (7,0x20000000).
AVERAGE_VALUE
Bit 30 Average Value (7,0x40000000).
CURRENT_VALUE
Bit 31 Current Value (7,0x80000000) <==> 111 11111 = 255.
Function Documentation
int32_t vrt::IndicatorFields::getCIFBitMask (IndicatorFieldEnum_t f) [inline]
Get the 1-hot bit mask from IndicatorFieldEnum_t The top three (most-significant) bits of each 8-bit IndicatorFieldEnum_t are the CIF number The bottom five (least-significant) bits of each 8-bit IndicatorFieldEnum_t are the bit number CIF#: 0b11100000 = 0xE0 | Right-shift by 5, i.e.
divide by 32 Bit#: 0b00011111 = 0x1F | Bitwise AND this bit-mask, i.e. modulo 32
Parameters:
f Field of interest
Returns:
1-hot CIF bit-mask
References getCIFBitNumber().
Referenced by vrt::BasicAcknowledgePacket::addError(), vrt::BasicAcknowledgePacket::addWarning(), vrt::BasicContextPacket::get3DPointingVectorStructured(), vrt::BasicContextPacket::getCIFsArray(), vrt::BasicContextPacket::getContextAssocLists(), vrt::IndicatorFieldProvider::getContextIndicatorFieldBit(), vrt::BasicContextPacket::getDataPayloadFormat(), vrt::IndicatorFieldProvider::getEphemerisECEF(), vrt::IndicatorFieldProvider::getEphemerisRelative(), vrt::BasicAcknowledgePacket::getError(), vrt::IndicatorFieldProvider::getGeolocationGPS(), vrt::IndicatorFieldProvider::getGeolocationINS(), vrt::BasicContextPacket::getGeoSentences(), vrt::BasicContextPacket::getIndexList(), vrt::BasicContextPacket::getSectorScanStep(), vrt::BasicContextPacket::getSpectrumField(), vrt::BasicAcknowledgePacket::getWarning(), vrt::IndicatorFieldProvider::isAutomaticGainControl(), vrt::IndicatorFieldProvider::isCalibratedTimeStamp(), vrt::IndicatorFieldProvider::isDataValid(), vrt::IndicatorFieldProvider::isDiscontinuous(), vrt::IndicatorFieldProvider::isInvertedSpectrum(), vrt::IndicatorFieldProvider::isOverRange(), vrt::IndicatorFieldProvider::isReferenceLocked(), vrt::IndicatorFieldProvider::isSignalDetected(), vrt::BasicAcknowledgePacket::removeError(), vrt::BasicAcknowledgePacket::removeWarning(), vrt::IndicatorFieldProvider::setAutomaticGainControl(), vrt::IndicatorFieldProvider::setCalibratedTimeStamp(), vrt::IndicatorFieldProvider::setContextIndicatorFieldBit(), vrt::IndicatorFieldProvider::setDataValid(), vrt::IndicatorFieldProvider::setDiscontinuous(), vrt::BasicAcknowledgePacket::setError(), vrt::IndicatorFieldProvider::setInvertedSpectrum(), vrt::IndicatorFieldProvider::setOverRange(), vrt::IndicatorFieldProvider::setReferenceLocked(), vrt::IndicatorFieldProvider::setSignalDetected(), and vrt::BasicAcknowledgePacket::setWarning().
int8_t vrt::IndicatorFields::getCIFBitNumber (IndicatorFieldEnum_t f) [inline]
Get the CIF bit number from the IndicatorFieldEnum_t The top three (most-significant) bits of each 8-bit IndicatorFieldEnum_t are the CIF number The bottom five (least-significant) bits of each 8-bit IndicatorFieldEnum_t are the bit number CIF#: 0b11100000 = 0xE0 | Right-shift by 5, i.e.
divide by 32 Bit#: 0b00011111 = 0x1F | Bitwise AND this bit-mask, i.e. modulo 32
Parameters:
f Field of interest
Returns:
CIF bit number
Referenced by getCIFBitMask().
IndicatorFieldEnum_t vrt::IndicatorFields::getCIFEnum (int8_t cif, int8_t bit) [inline]
Get the IndicatorFieldEnum from the CIF number and CIF bit number The top three (most-significant) bits of each 8-bit IndicatorFieldEnum_t are the CIF number The bottom five (least-significant) bits of each 8-bit IndicatorFieldEnum_t are the bit number CIF#: 0b11100000 = 0xE0 | Left-shift by 5, i.e.
multiply by 32 Bit#: 0b00011111 = 0x1F | Bitwise AND this bit-mask, i.e. modulo 32 Add the shifted CIF number to the bit number for the IndicatorFieldEnum value.
Parameters:
cif CIF number
bit Bit number
Returns:
IndicatorFieldEnum value corresponding with cif and bit.
int8_t vrt::IndicatorFields::getCIFNumber (IndicatorFieldEnum_t f) [inline]
Get the CIF number from the IndicatorFieldEnum_t The top three (most-significant) bits of each 8-bit IndicatorFieldEnum_t are the CIF number The bottom five (least-significant) bits of each 8-bit IndicatorFieldEnum_t are the bit number CIF#: 0b11100000 = 0xE0 | Right-shift by 5, i.e.
divide by 32 Bit#: 0b00011111 = 0x1F | Bitwise AND this bit-mask, i.e. modulo 32
Parameters:
f Field of interest
Returns:
CIF number
Referenced by vrt::BasicAcknowledgePacket::addError(), vrt::BasicAcknowledgePacket::addWarning(), vrt::BasicContextPacket::get3DPointingVectorStructured(), vrt::BasicContextPacket::getCIFsArray(), vrt::BasicContextPacket::getContextAssocLists(), vrt::IndicatorFieldProvider::getContextIndicatorFieldBit(), vrt::BasicContextPacket::getDataPayloadFormat(), vrt::IndicatorFieldProvider::getEphemerisECEF(), vrt::IndicatorFieldProvider::getEphemerisRelative(), vrt::BasicAcknowledgePacket::getError(), vrt::IndicatorFieldProvider::getGeolocationGPS(), vrt::IndicatorFieldProvider::getGeolocationINS(), vrt::BasicContextPacket::getGeoSentences(), vrt::BasicContextPacket::getIndexList(), vrt::BasicContextPacket::getSectorScanStep(), vrt::BasicContextPacket::getSpectrumField(), vrt::BasicAcknowledgePacket::getWarning(), vrt::IndicatorFieldProvider::isAutomaticGainControl(), vrt::IndicatorFieldProvider::isCalibratedTimeStamp(), vrt::IndicatorFieldProvider::isDataValid(), vrt::IndicatorFieldProvider::isDiscontinuous(), vrt::IndicatorFieldProvider::isInvertedSpectrum(), vrt::IndicatorFieldProvider::isOverRange(), vrt::IndicatorFieldProvider::isReferenceLocked(), vrt::IndicatorFieldProvider::isSignalDetected(), vrt::BasicAcknowledgePacket::removeError(), vrt::BasicAcknowledgePacket::removeWarning(), vrt::IndicatorFieldProvider::setAutomaticGainControl(), vrt::IndicatorFieldProvider::setCalibratedTimeStamp(), vrt::IndicatorFieldProvider::setContextIndicatorFieldBit(), vrt::IndicatorFieldProvider::setDataValid(), vrt::IndicatorFieldProvider::setDiscontinuous(), vrt::BasicAcknowledgePacket::setError(), vrt::IndicatorFieldProvider::setInvertedSpectrum(), vrt::IndicatorFieldProvider::setOverRange(), vrt::IndicatorFieldProvider::setReferenceLocked(), vrt::IndicatorFieldProvider::setSignalDetected(), and vrt::BasicAcknowledgePacket::setWarning().