VRT: vrt::PackUnpack Namespace Reference
vrt::PackUnpack Namespace Reference
Internal Use Only: Pack/unpack methods used by BasicDataPacket.
Functions
void packAsByte (PayloadFormat pf, void *ptr, int32_t off, const int8_t *array, const int32_t *chan, const int32_t *evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of int8_t.
void packAsDouble (PayloadFormat pf, void *ptr, int32_t off, const double *array, const int32_t *chan, const int32_t *evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of double.
void packAsFloat (PayloadFormat pf, void *ptr, int32_t off, const float *array, const int32_t *chan, const int32_t *evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of float.
void packAsInt (PayloadFormat pf, void *ptr, int32_t off, const int32_t *array, const int32_t *chan, const int32_t *evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of int32_t.
void packAsLong (PayloadFormat pf, void *ptr, int32_t off, const int64_t *array, const int32_t *chan, const int32_t *evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of int64_t.
void packAsShort (PayloadFormat pf, void *ptr, int32_t off, const int16_t *array, const int32_t *chan, const int32_t *evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of int16_t.
int8_t * unpackAsByte (PayloadFormat pf, const void *ptr, int32_t off, int8_t *array, int32_t *chan, int32_t *evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of int8_t.
double * unpackAsDouble (PayloadFormat pf, const void *ptr, int32_t off, double *array, int32_t *chan, int32_t *evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of double.
float * unpackAsFloat (PayloadFormat pf, const void *ptr, int32_t off, float *array, int32_t *chan, int32_t *evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of float.
int32_t * unpackAsInt (PayloadFormat pf, const void *ptr, int32_t off, int32_t *array, int32_t *chan, int32_t *evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of int32_t.
int64_t * unpackAsLong (PayloadFormat pf, const void *ptr, int32_t off, int64_t *array, int32_t *chan, int32_t *evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of int64_t.
int16_t * unpackAsShort (PayloadFormat pf, const void *ptr, int32_t off, int16_t *array, int32_t *chan, int32_t *evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of int16_t.
Detailed Description
Internal Use Only: Pack/unpack methods used by BasicDataPacket.
Usage Notes
If the data type of the array given does not match the PayloadFormat, the handling of any values outside of the mutual range limits is undefined. (For example inserting the value 1024 from an Int32 array into a PayloadFormat of Int8.)
If the data type of the array given does not match the PayloadFormat, the handling of any values outside of the mutual precision limits will result in a loss of precision. (For example inserting the value 3.14 from an Float32 array into a PayloadFormat of Int8 will result in the value 3 being set.)
The handling of NaN, +Inf, and -Inf when converting from a floating-point type to an integer type is undefined.
All floating-point NaN values are considered equal any NaN may be converted to any other NaN (i.e. "signaling NaN values" are not preserved).
All floating-point 0.0 values (i.e. -0.0 and +0.0) are considered equal and any 0.0 may be converted to any other 0.0 (i.e. the sign bit on a 0.0 is not preserved).
Performance Characteristics
Great effort has been made to optimize the most commonly used pack/unpack conversions. The table below shows the relative speed at which a given PayloadFormat can be packed/unpacked from a buffer.
       Speed   | Item Packing | Data Item |  Event   | Channel  | Efficient | Notes |
        [0]    |  Field Size  | Size [1]  | Tag Size | Tag Size |   Mode    |       |
    -----------+--------------+-----------+----------+----------+-----------+-------+
         A+    |       8      |     8     |    0     |     0    | Link/Proc |       |
     (Fastest) |              |           |          |          |           |       |
    -----------+--------------+-----------+----------+----------+-----------+-------+
         A     |       1      |     1     |    0     |     0    | Link/Proc |  [2]  |
               |       4      |     4     |    0     |     0    | Link/Proc |  [2]  |
               |      12      |    12     |    0     |     0    | Link/Proc |  [2]  |
               |      16      |    16     |    0     |     0    | Link/Proc |       |
               |      24      |    24     |    0     |     0    | Link/Proc |       |
               |      32      |    32     |    0     |     0    | Link/Proc |       |
               |      64      |    64     |    0     |     0    | Link/Proc |       |
               |      32      |   float   |    0     |     0    | Link/Proc |       |
               |      64      |   double  |    0     |     0    | Link/Proc |       |
    -----------+--------------+-----------+----------+----------+-----------+-------+
         A-    |       8      |  1 to  7  |    -     |     -    | Link/Proc |  [3]  |
               |      16      |  1 to 15  |    -     |     -    | Link/Proc |  [3]  |
               |      24      |  1 to 23  |    -     |     -    | Link/Proc |  [3]  |
               |      32      |  1 to 31  |    -     |     -    | Link/Proc |  [3]  |
               |      64      |  1 to 63  |    -     |     -    | Link/Proc |  [3]  |
               |   17 to 63   |  1 to 63  |    -     |     -    |    Proc   |       |
    -----------+--------------+-----------+----------+----------+-----------+-------+
         B     |      32      |  1 to 31  |  0 to 7  |  0 to 15 | Link/Proc |       |
               |      64      |  1 to 63  |  0 to 7  |  0 to 15 | Link/Proc |       |
               |      64      |   float   |  0 to 7  |  0 to 15 | Link/Proc |       |
               |   17 to 63   |  1 to 63  |  0 to 7  |  0 to 15 |    Proc   |       |
               |   33 to 63   |   float   |  0 to 7  |  0 to 15 |    Proc   |       |
    -----------+--------------+-----------+----------+----------+-----------+-------+
         D+    |    1 to 15   |  1 to 15  |    -     |     -    | Link/Proc | [3,4] |
               |   17 to 63   |  1 to 63  |    -     |     -    |    Link   |  [3]  |
               |   33 to 63   |   float   |    -     |     -    |    Link   |  [3]  |
    -----------+--------------+-----------+----------+----------+-----------+-------+
         D     |    1 to 15   |  1 to 15  |  0 to 7  |  0 to 15 | Link/Proc |  [4]  |
     (Slowest) |   17 to 63   |  1 to 63  |  0 to 7  |  0 to 15 |    Link   |       |
               |   33 to 63   |   float   |  0 to 7  |  0 to 15 |    Link   |       |
    -----------+--------------+-----------+----------+----------+-----------+-------+
    Notes:
      [0] The "speed" rating is an arbitrary "grade" indicating how fast the accessing
          of a given Payload Format is relative to other Payload Formats, where an
          "A+" equates to a simple memcpy in C++ and a "D" equates to a complex
          processing algorithm with nested loops and heavy use of bit manipulation.
          In practice the speed difference in speed between a "B" and an "A" is
          small whereas the difference between a "B" and a "D" is many orders of
          magnitude slower. (For example, on one test of ~2 million iterations using
          both link efficient ("D") and processing efficient ("B") and with Packing
          Field Sizes between 33 and 63 bits it took 38.2 sec for link efficient vs
          <0.1 sec for processing efficient.)
      [1] All Data items are signed/unsigned integers with the bit count as shown,
          except for "float" and "double" which represent IEEE-754 floating-point
          values.
      [2] Fast handling of Int1 and Int4/Int12 data by unpacking eight/two elements
          at a time. Total length must be a multiple of 8/2 to use this mode.
      [3] Event/Channel tags (if present) are not read and set to zero on write.
      [4] Future versions may provide a faster implementation for 1 to 15 bit
          field sizes when in Processing Efficient mode.
Currently all of the VRT floating-point formats are using algorithms that are similar to the "D+" and "D" ones used for IEEE-754 float data. Future versions may provide a faster implementation for situations where the data item size is 8/16/32/64 bits and/or processing-efficient mode is used.
Regardless of the algorithm used herein, the accessing of IEEE-754 floating-point values will always be faster than the accessing of VRT floating-point values since the former benefit from hardware acceleration.
Function Documentation
void vrt::PackUnpack::packAsByte (PayloadFormat pf, void * ptr, int32_t off, const int8_t * array, const int32_t * chan, const int32_t * evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of int8_t.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be set to zero. In most cases this results in a performance improvement over passing in an array of zeros.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will be ignored.
Parameters:
pf (IN) The data format
ptr (I/O) The buffer pointer
off (IN) The buffer offset
array (IN) The values to pack
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Referenced by vrt::BasicDataPacket::setDataByte().
void vrt::PackUnpack::packAsDouble (PayloadFormat pf, void * ptr, int32_t off, const double * array, const int32_t * chan, const int32_t * evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of double.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be set to zero. In most cases this results in a performance improvement over passing in an array of zeros.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will be ignored.
Parameters:
pf (IN) The data format
ptr (I/O) The buffer pointer
off (IN) The buffer offset
array (IN) The values to pack
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Referenced by vrt::BasicDataPacket::setDataDouble().
void vrt::PackUnpack::packAsFloat (PayloadFormat pf, void * ptr, int32_t off, const float * array, const int32_t * chan, const int32_t * evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of float.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be set to zero. In most cases this results in a performance improvement over passing in an array of zeros.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will be ignored.
Parameters:
pf (IN) The data format
ptr (I/O) The buffer pointer
off (IN) The buffer offset
array (IN) The values to pack
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Referenced by vrt::BasicDataPacket::setDataFloat().
void vrt::PackUnpack::packAsInt (PayloadFormat pf, void * ptr, int32_t off, const int32_t * array, const int32_t * chan, const int32_t * evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of int32_t.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be set to zero. In most cases this results in a performance improvement over passing in an array of zeros.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will be ignored.
Parameters:
pf (IN) The data format
ptr (I/O) The buffer pointer
off (IN) The buffer offset
array (IN) The values to pack
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Referenced by vrt::BasicDataPacket::setDataInt().
void vrt::PackUnpack::packAsLong (PayloadFormat pf, void * ptr, int32_t off, const int64_t * array, const int32_t * chan, const int32_t * evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of int64_t.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be set to zero. In most cases this results in a performance improvement over passing in an array of zeros.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will be ignored.
Parameters:
pf (IN) The data format
ptr (I/O) The buffer pointer
off (IN) The buffer offset
array (IN) The values to pack
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Referenced by vrt::BasicDataPacket::setDataLong().
void vrt::PackUnpack::packAsShort (PayloadFormat pf, void * ptr, int32_t off, const int16_t * array, const int32_t * chan, const int32_t * evt, int32_t length)
Internal Use Only: Packs values with the given format specifier from an array of int16_t.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be set to zero. In most cases this results in a performance improvement over passing in an array of zeros.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will be ignored.
Parameters:
pf (IN) The data format
ptr (I/O) The buffer pointer
off (IN) The buffer offset
array (IN) The values to pack
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Referenced by vrt::BasicDataPacket::setDataShort().
int8_t* vrt::PackUnpack::unpackAsByte (PayloadFormat pf, const void * ptr, int32_t off, int8_t * array, int32_t * chan, int32_t * evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of int8_t.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be ignored. In most cases this results in a performance improvement.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will not be modified.
Parameters:
pf (IN) The data format
ptr (IN) The buffer pointer
off (IN) The buffer offset
array (OUT) The output array for the values
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Returns:
The output array (same as array).
Referenced by vrt::BasicDataPacket::getDataByte().
double* vrt::PackUnpack::unpackAsDouble (PayloadFormat pf, const void * ptr, int32_t off, double * array, int32_t * chan, int32_t * evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of double.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be ignored. In most cases this results in a performance improvement.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will not be modified.
Parameters:
pf (IN) The data format
ptr (IN) The buffer pointer
off (IN) The buffer offset
array (OUT) The output array for the values
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Returns:
The output array (same as array).
Referenced by vrt::BasicDataPacket::getDataDouble().
float* vrt::PackUnpack::unpackAsFloat (PayloadFormat pf, const void * ptr, int32_t off, float * array, int32_t * chan, int32_t * evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of float.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be ignored. In most cases this results in a performance improvement.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will not be modified.
Parameters:
pf (IN) The data format
ptr (IN) The buffer pointer
off (IN) The buffer offset
array (OUT) The output array for the values
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Returns:
The output array (same as array).
Referenced by vrt::BasicDataPacket::getDataFloat().
int32_t* vrt::PackUnpack::unpackAsInt (PayloadFormat pf, const void * ptr, int32_t off, int32_t * array, int32_t * chan, int32_t * evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of int32_t.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be ignored. In most cases this results in a performance improvement.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will not be modified.
Parameters:
pf (IN) The data format
ptr (IN) The buffer pointer
off (IN) The buffer offset
array (OUT) The output array for the values
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Returns:
The output array (same as array).
Referenced by vrt::BasicDataPacket::getDataInt().
int64_t* vrt::PackUnpack::unpackAsLong (PayloadFormat pf, const void * ptr, int32_t off, int64_t * array, int32_t * chan, int32_t * evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of int64_t.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be ignored. In most cases this results in a performance improvement.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will not be modified.
Parameters:
pf (IN) The data format
ptr (IN) The buffer pointer
off (IN) The buffer offset
array (OUT) The output array for the values
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Returns:
The output array (same as array).
Referenced by vrt::BasicDataPacket::getDataLong().
int16_t* vrt::PackUnpack::unpackAsShort (PayloadFormat pf, const void * ptr, int32_t off, int16_t * array, int32_t * chan, int32_t * evt, int32_t length)
Internal Use Only: Unpacks values with the given format specifier as an array of int16_t.
Setting the channel tags (chan) and/or event tags (evt) arrays to null will cause any channel or event tags present to be ignored. In most cases this results in a performance improvement.
If the channel tags (chan) and/or event tags (evt) arrays are non-null when there are no channel or event tags present, the values in the arrays will not be modified.
Parameters:
pf (IN) The data format
ptr (IN) The buffer pointer
off (IN) The buffer offset
array (OUT) The output array for the values
chan (OUT) The output array for the channel tags (null if n/a)
evt (OUT) The output array for the event tags (null if n/a)
length (IN) Number of elements to convert
Returns:
The output array (same as array).
Referenced by vrt::BasicDataPacket::getDataShort().