VRT: vrt::NetUtilities Namespace Reference
vrt::NetUtilities Namespace Reference
Various utilities methods.
Functions
void doHttpGet (const string &url, map< string, string > &header, string &data)
Internal Use Only: Gets the response from an HTTP GET call.
map< string, string > getDefaultSocketOptions (bool optimize, TransportProtocol transport)
Gets a set of default socket options that can be added to.
string getHost (const string &hostPort)
Gets the host name from a host:port.
InetAddress getHostAddress (const string &hostPort)
Gets the host name from a host:port.
string getNetworkDeviceName (const string &nic, int32_t vlan)
Gets the device name applicable when given a NIC and VLAN.
int16_t getPort (const string &hostPort)
Gets the port number from a host:port.
int getSocketOptionBool (map< string, string > &opts, const string &key, bool def=false)
Internal Use Only: Gets a socket option as a boolean (0/1).
int getSocketOptionInt (map< string, string > &opts, const string &key, int32_t def=INT32_NULL)
Internal Use Only: Gets a socket option as an int.
bool hasOpt (map< string, string > &opts, const string &key)
Internal Use Only: Is a socket option present?
ifreq toInterface (int sockfd, const string &device, bool isMCast=false)
Internal Use Only: Converts device name to a device object.
Variables
const int32_t EXTRA_BUFFER_SIZE = 80
Internal Use Only: Fudge factor to use when sizing buffers that work with UDP datagrams to account for size of datagram header, plus the IP header, etc.
const int32_t MAX_IPv4_UDP_LEN = 65475
Maximum length of a UDP packet (including the UDP header) in octets when transmitted over IPv4 (65,471).
const int32_t MAX_UDP_LEN = 65535
Maximum length of a UDP packet (including the UDP header) in octets (65,535).
const int32_t UDP_HEADER_LENGTH = 8
The length of a UPD packet header in octets (8).
Detailed Description
Various utilities methods.
Socket Creation Options
The socket creation methods take in a map of options used for initializing a socket. If the map is null, or if a given entry is null, the default value will be used. The map may include any of the basic SO_* socket options for example:
    string bufSize = ...;
    options["SO_SNDBUF"] = bufSize;
It may also include the following options:
    CONNECT_TIMEOUT - The connection timeout for a TCP Socket in ms.
    LOCAL_PORT      - The local port to use for a TCP client connection (this
                      overrides the default which is to use any available
                      ephemeral port).
    RCVBUF_EAGER    - Override the normal o/s behavior and force the receive
                      buffer to be eagerly initialized when a UDP socket
                      (unicast/multicast) is opened. The default o/s behavior
                      on some systems (particularly Linux) is to do a lazy
                      initialization of the receive buffer for a UDP socket.
                      When an lazy initialization is done, the receive buffer
                      might not be initialized until (or possibly after) the
                      first receive call is made, resulting in packet loss
                      during the period between the open and the actual buffer
                      initialization. Setting this to true attempts to force
                      the o/s to initialize the receive buffer as part of the
                      open (or at least the open within this class); however,
                      there is no guarantee that the o/s will allocate it at
                      that time. Setting this to false will use the default
                      o/s behavior, which is generally faster. (Note that
                      there is no SNDBUF_EAGER since there is no reason to
                      buffer output packets until the first one is sent.)
    SERVER_BACKLOG  - The backlog value for a TCP server socket.
Any options not applicable for the given socket type will be ignored. Note that IP_MULTICAST_IF is also ignored since this is explicitly set via the "device" input parameter. Additionally SO_SNDBUF, SO_RCVBUF, SO_REUSEADDR, and SO_TIMEOUT may be given defaults that differ from the O/S defaults where applicable (however these defaults can be overridden via the socket options provided).
Function Documentation
void vrt::NetUtilities::doHttpGet (const string & url, map< string, string > & header, string & data)
Internal Use Only: Gets the response from an HTTP GET call.
map<string,string> vrt::NetUtilities::getDefaultSocketOptions (bool optimize, TransportProtocol transport)
Gets a set of default socket options that can be added to.
This allows a easy way of getting "default" options that may be slightly more optimal than the ones provided by the o/s.
WARNING: The "default" options provided by this function may change between releases and may vary from platform to platform within the same release.
Parameters:
optimize Select more aggressive optimizations that assume high-rate VITA-49 traffic (true) or defer to o/s defaults where the benefit to "general" traffic is unclear (false). Setting this to true may enable options that optimize performance for streaming-data at the expense of slower connect/open times and/or may be inappropriate for non-packetized data.
transport Specific transport to use for any transport-specific optimizations (can be null). (This value is only considered with respect to optimizations that require differentiation between transport options.)
Returns:
The set of options to use (never null).
string vrt::NetUtilities::getHost (const string & hostPort)
Gets the host name from a host:port.
Parameters:
hostPort The host:port in "host:port", "host" or ":port" syntax.
Returns:
The applicable host name or null if not specified.
InetAddress vrt::NetUtilities::getHostAddress (const string & hostPort)
Gets the host name from a host:port.
Parameters:
hostPort The host:port in "host:port", "host" or ":port" syntax.
Returns:
The applicable host name or null if not specified.
string vrt::NetUtilities::getNetworkDeviceName (const string & nic, int32_t vlan)
Gets the device name applicable when given a NIC and VLAN.
Parameters:
nic The NIC to use ("" if n/a).
vlan The VLAN to use (-1 if n/a).
Returns:
The applicable device identifier (e.g. "eth1", "eth0.123").
Exceptions:
VRTException if a VLAN is specified without a NIC
int16_t vrt::NetUtilities::getPort (const string & hostPort)
Gets the port number from a host:port.
Parameters:
hostPort The host:port in "host:port", "host" or ":port" syntax.
Returns:
The applicable port number or null if not specified.
int vrt::NetUtilities::getSocketOptionBool (map< string, string > & opts, const string & key, bool def = false) [inline]
Internal Use Only: Gets a socket option as a boolean (0/1).
References hasOpt(), and vrt::Utilities::toBooleanValue().
int vrt::NetUtilities::getSocketOptionInt (map< string, string > & opts, const string & key, int32_t def = INT32_NULL) [inline]
Internal Use Only: Gets a socket option as an int.
References hasOpt().
bool vrt::NetUtilities::hasOpt (map< string, string > & opts, const string & key) [inline]
Internal Use Only: Is a socket option present?
Referenced by getSocketOptionBool(), and getSocketOptionInt().
ifreq vrt::NetUtilities::toInterface (int sockfd, const string & device, bool isMCast = false)
Internal Use Only: Converts device name to a device object.
Variable Documentation
const int32_t vrt::NetUtilities::EXTRA_BUFFER_SIZE = 80
Internal Use Only: Fudge factor to use when sizing buffers that work with UDP datagrams to account for size of datagram header, plus the IP header, etc.
const int32_t vrt::NetUtilities::MAX_IPv4_UDP_LEN = 65475
Maximum length of a UDP packet (including the UDP header) in octets when transmitted over IPv4 (65,471).
Although the max packet length for UDP is 65,635 bytes, IPv4 imposes a lower limit:
    Maximum IPv4 Length:        65,535 octets
    Maximum IPv4 Header:      -     60 octets  (20 octets is minimum)
    -----------------------------------------
    Maximim UDP in IPv4:        65,475 octets
Accordingly this value should be thought of as the maximum for transmission size and MAX_UDP_LEN should be used as the maximum receive size.
See also:
MAX_UDP_LEN
const int32_t vrt::NetUtilities::MAX_UDP_LEN = 65535
Maximum length of a UDP packet (including the UDP header) in octets (65,535).
See also:
MAX_IPv4_UDP_LEN
const int32_t vrt::NetUtilities::UDP_HEADER_LENGTH = 8
The length of a UPD packet header in octets (8).